### ISSUE TITLE
EasySearch & Typeahead

### ISSUE THREAD

**Issue by viktorperez** [matteodem/meteor-easy-search#102]
Is possible use the Typeahead with EasySearch? I'm trying to integrate this package (https://github.com/sergeyt/meteor-typeahead) but unfortunately EasySearch stops working. I know that EasySearch integrate an Autosuggest functionality but I would like know if there are any possibility to integrate Typeahead.

**Comment by matteodem** [comment]
I didn't have a closer look at this but please reference the docs for more detailed explanations http://matteodem.github.io/meteor-easy-search/docs/javascript-api/. I might do an "Integrating with other Services" part if it is wished. 

Need to have a look at typeahead though before.

**Comment by matteodem** [comment]
Could somebody of you provide me with a repo that uses this package with type ahead? Examples are always a good way of showing how it can be used in a modular fashion.

**Comment by matteodem** [comment]
Since it doesn't look like any of you is interested in providing it, I'll close it.

**Comment by vishim** [comment]
Here is a repo which shows that easy search does not work with typeahead by doing something like this 
    {{> esInput index="teams" class="form-control typeahead" placeholder="NBA teams" autocomplete="off" spellcheck="off" data-source="teams"}}


https://github.com/vishim/meteor-typeahead-easy-search.git

**Comment by matteodem** [comment]
Yes, because `autocomplete` `spellcheck` and `data-source` are not supported by EasySearch. Please see the proposal for a working solution up there.

**Comment by Rahbaran** [comment]
I don't know if this is still current or if autosuggest does the same. If not, I'd also be interested for an example to see how easysearch and typeahead work.

**Comment by matteodem** [comment]
Please try out the autosuggest component to find out if it gives you the needed functionality. By the way the new `Cursor` that is returned when searching also allows to fetch the documents, so it is still possible.
