### ISSUE TITLE
Performance tuning

### ISSUE THREAD

**Issue by ChihChengLiang** [matteodem/meteor-easy-search#111]
I tried to implement a dictionary with 800K entries, using easy-search package with mongodb. The app deployed at [here](http://naerterms.meteor.com/), source code repo [here](https://bitbucket.org/SatoshiLiang/terms_naer/src/084f9aa60cc79237e38117310204078dbaf4db3b?at=master). The main issue is the webpage takes forever to render results for just one query, happening on both local and remote hosts. I am certain that mongodb is not the bottleneck, since the same query complete instantly in mongo shell when tested locally. How can I improve the performance? Thanks!

**Comment by matteodem** [comment]
I am pretty sure that 800K entries might take longer, but that long is weird and unexpected. Can I see the query you ran in the meteor shell to test it?

**Comment by matteodem** [comment]
Here for example it takes about 2 to 3 secs and has 100k docs: http://easy-search-leaderboard.meteor.com/

**Comment by ChihChengLiang** [comment]
Run in meteor shell

```
$ meteor shell

Welcome to the server-side interactive shell!

Tab completion is enabled for global variables.

Type .reload to restart the server and the shell.
Type .exit to disconnect from the server and leave the shell.
Type .help for additional help.

> Dict.find({"en":{"$regex":".*sla.*","$options":"i"}}).count()
1736
> Dict.find({"en":{"$regex":".*sla.*","$options":"i"}}).fetch()
(results print out without hesitate)
```


```
$ mongo
MongoDB shell version: 2.4.9
connecting to: test
> use dict-database
switched to db dict-database
> db.dict.find({"en":{$regex:".*app.*",$options:"i"}}).count()
3563
> db.dict.find({"en":{$regex:".*app.*",$options:"i"}})
{ "_id" : ObjectId("54b12ba5dd066875a19881cb"), "category" : "兩岸對照名詞-植物名詞", "updated" : "2013-06-21", "ch" : "採脂", "cn" : "采脂", "en" : "(resin/ wood) tapping", "sid" : 1867679 }
(other results not pasted here....)
```

Also for your information:
```
> db.dict.getIndexes()
[
	{
		"v" : 1,
		"key" : {
			"_id" : 1
		},
		"ns" : "dict-database.dict",
		"name" : "_id_"
	},
	{
		"v" : 1,
		"key" : {
			"en" : 1
		},
		"ns" : "dict-database.dict",
		"name" : "en_1"
	}
]

```

**Comment by ChihChengLiang** [comment]
Find some clues now. I used meteor debug and found out that the 'search' function in mongo.js was called multiple time when typing. For example, when queried "science",  the strings "sc", "scie","scien", and  "science" are also queried.

**Comment by ChihChengLiang** [comment]
Here's a theory. The default 200 ms keydown event time up is too fast for a slow search. It takes me 2030ms to type science in a casual pace. Might be some break in between exceeds 200ms and fires the events several times.

```
a= function(){
start= Date.now();
prompt('Type science as fast as possible!');
console.log(Date.now()-start)}
```

**Comment by matteodem** [comment]
You're right, there might be some ways in which we can enhance the performance of the search. You could change the event to __enter__, see here http://matteodem.github.io/meteor-easy-search/docs/blaze-components/.

I'm not sure about how to stop the query if you started typing again, since that's hard to capture, but it should be possible to cache certain things, for example when paginating. Also I hope we can use text indexes now with the MongoDB shipped with Meteor.

**Comment by ChihChengLiang** [comment]
My workaround is simply add an timeout='1000' attribute at esInput template and it works nicely. It would be helpful to arrange a section that collects such workarounds in doc.

I'll keep digging into the source code and see if any chance to contribute.

**Comment by matteodem** [comment]
Okay, I think having real solutions instead workarounds in the docs are more precious. Thanks though for showing it, I'll keep an eye on solutions to improve performance.

**Comment by micahalcorn** [comment]
I am having this issue also. Otherwise this package is incredible, thanks.

**Comment by matteodem** [comment]
Can you please update your app? The new version uses text indexes to speed up the search.

**Comment by matteodem** [comment]
Does not look like I can do a lot more than setting up text indexes for fast search, feel free to write here if you're still having performance issues.

**Comment by Roshdy** [comment]
@ChihChengLiang can you please show a demo on how u did that?
