### ISSUE TITLE
Searching through Component API

### ISSUE THREAD

**Issue by mfcollier** [matteodem/meteor-easy-search#112]
Hi, first off i would like to thank you for this great package, it makes searching so much easier for everyone.

I would however like to know how I can use the result set from EasySearch.search using the Blaze components i.e. on the client I would like to set-up a default search and then show the result set.

EasySearch.search('cars',  "Toyo", function (err, data) {
  // use data.results and data.total <<< This is my problem, how can I use them please :)
});

I can get a result set back on the client that has all the documents I expect, however 

how can I then pass these results to the Blaze components so that I can show the results using a template with #esEach etc

I have been trying to do this for some time and have come to the conclusion that I am sure I am missing something simple here, and help much appreciated.

Thanks in advance

**Comment by matteodem** [comment]
Hey there

When using the blaze components you can easily use them with the esInput, which is a simple text input used for searching: http://matteodem.github.io/meteor-easy-search/. Is there any reason why you want to set the values with javascript?

**Comment by mfcollier** [comment]
Hi, thanks for quick reply.

- I am building a sports website, so the idea is when you click on a team name from the landing page, for example, it routes to a new dynamic page for each team. Here I would like to just show the news stories pre-filtered just for the selected team, hence I would like to control this from Javascript either via iron-router data: or via a template helper ( or indeed any way!)


-  I will then add faceted search within those pre-built results to drilldown further

I have a generic 'news search' route using esInput already so you can search the entire stories database. This works perfectly :)

**Comment by matteodem** [comment]
okay, great. I think this is an understandable use case and I'll implement when I got time.

**Comment by mfcollier** [comment]
Thanks again, this would be great.

**Comment by matteodem** [comment]
Added a search on component level for 1.4.7

```javascript
Template.sportsBox.helpers({
  'click .image' : function () {
    EasySearch
      .getComponentInstance({ index: 'someIndex', id: 'someOptionalId' })
      .search('hello')
    ;
  }
});
```

This will trigger the search with the same functionality you have when you do it via the esInput.

**Comment by matteodem** [comment]
Please update and test this functionality.

**Comment by mfcollier** [comment]
Hi, i have tested this and it works perfectly - thank you very much for this, it is most appreciated.
