### ISSUE TITLE
Query string combined fields: Mongo-DB

### ISSUE THREAD

**Issue by warsamebashir** [matteodem/meteor-easy-search#113]
Hello,

Is there a way to use the `query` function on `createSearchIndex` to filter against two document fields. For example on a document `Users`, if i have a `firstName` and `lastName` field and when the user searches using the `esInput` field `firstName <space> lastName`, how would I find users with `fullName`.

```` Javascript

'query': function (searchString) {
        var query = EasySearch.getSearcher('mongo-db').defaultQuery(this, searchString);
         // any way to filter with provided searchString ??
        return query;
    }

````

**Comment by matteodem** [comment]
You can specify multiple fields in the field parameter. I am not exactly sure what the question is here. Can I see the whole configuration and the expected search behaviour?

**Comment by warsamebashir** [comment]
Sorry for the confusing question. I mean't to ask about queries combining two separate document fields like `firstName` and `lastName`. The search behavior is that if someone searches for `John Doe`, they would receive all results where `firstName: 'John'` and `lastName: 'Doe'`. I am not sure if that is possible through `mongoDB` queries or through the existing `field` option.

**Comment by matteodem** [comment]
You can split the string by whitespace and then construct the query like that. This approach is extremely hacky though and I wouldn't do it.

Another thing is to just create a new field called "fullName", then you specify that field for searching. That is the approach when using search indexes like Elastic Search.

**Comment by warsamebashir** [comment]
Are you proposing the field `fullName` as a database field or one on the `createSearchIndex` configuration ? I know that with `ES` you can do `fuzzyLikeThis` queries among other things but not sure of similar filtering for mongo.

**Comment by matteodem** [comment]
I would propose it in the database itself. But since we got an Elastic Search Index, it could be possible to add a "transform" function for the elastic search docs themselves, since you don't always want to have the elastic search docs be the same as the mongo docs.

Temporarily you could just add it to the mongodb docs though.

**Comment by warsamebashir** [comment]
We ended up using mongoDB queries and the provided the `query` function

**Comment by matteodem** [comment]
fyi, in the new version 1.4.7 you will be able to add a transform function that lets you combine fields with Elastic Search like following


```javascript
EasySearch.createSearchIndex('name', {
  ...
  field: 'fullName',
  transform: function (doc) {
    doc.fullName = doc.firstName + ' ' + doc.lastName;
  } 
  ...
});
```

**Comment by warsamebashir** [comment]
@matteodem Thanks for the updates. I am assuming this is only going to be possible with `elastic-search` as the search engine: i.e

`"use" : "elastic-search",`

**Comment by matteodem** [comment]
yes, since having "non visible" fields on mongo-db docs is not possible and it shouldn't be.
