### ISSUE TITLE
Search in array Mongo-DB

### ISSUE THREAD

**Issue by babnik63** [matteodem/meteor-easy-search#114]
Hi,
Is there any solution for searching in arrays in mongo-db documents?  city:[NY,Paris,..]

**Comment by matteodem** [comment]
You would have to override the "query" option to add a "$in" operator or anything else that works with arrays. see:

http://docs.mongodb.org/manual/reference/operator/query/in/
http://matteodem.github.io/meteor-easy-search/docs/javascript-api/

**Comment by babnik63** [comment]
Thanks ;-)
