### ISSUE TITLE
Exclude documents from search

### ISSUE THREAD

**Issue by fardeemmunir** [matteodem/meteor-easy-search#118]
I am doing a search on the users collection on the `profile.name` field. I want to exclude the current user form the search. How can I do that? I couldn't figure something from the docs.

Also can I set the limit to infinity?

**Comment by erasaur** [comment]
Looks like this question was covered in another issue. You can edit the query to exclude the current user from the results like this, assuming you're using mongo-db search:

```
query: function (searchString) {
    var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);
    var user = Meteor.users.findOne(this.publishScope.userId);

    query['profile.name'] = { $ne: user.profile.name };
    return query;
}
```

**Comment by matteodem** [comment]
Currently you cannot set the limit to infinity, any use case why you would want to do that?

**Comment by matteodem** [comment]
Closing this since there's no answer. Feel free to answer though at a later time.

**Comment by fardeemmunir** [comment]
Sorry, I totally forgot to comment.

Anyways I want the search to show all matching documents so therefore without any limit.

**Comment by matteodem** [comment]
That is not a use case of why you would like to have infinite search, http://en.wikipedia.org/wiki/Use_case
