### ISSUE TITLE
Running complex queries using mongo selectors 

### ISSUE THREAD

**Issue by almogdesign** [matteodem/meteor-easy-search#120]
I understand I can do the following 

query.categories = { $in : this.props.filteredCategories }

but can this be done for a number of mongo selectors or just one complex one like so 

var topics = Topics.find({$and:[{permalinkUser: permalinkUser},{permalink: permalink}, {public:true}]}).fetch();

**Comment by matteodem** [comment]
Please refer to the to see how you can construct selectors: http://docs.meteor.com/#/full/selectors. Also see the find method explained here: http://docs.meteor.com/#/full/find.

The query object is essentially a selector object, so you have full possibility to change it however you want.

**Comment by almogdesign** [comment]
Yes I understand that is it possible to due the following 
```javascript
query = {formName: this.props.formName, producerId: this.props.producerId};
```
I have noticed in tall the examples that query requires the selector name like so 
```javascript
 query.categories = { $in : this.props.filteredCategories };
```
Meaning I can only run a query on the categories field

**Comment by matteodem** [comment]
no, you could additional do this:

```javascript
 query.formName = this.props.formName;
 query.producerId = this.props.producerId;
 query.categories = { $in : this.props.filteredCategories };
```

This is standard Javascript.

**Comment by almogdesign** [comment]
Yea thanks ended up doing that, just wanted to see if you had an API for this. Its working great
