### ISSUE TITLE
triggerSearch() not working 

### ISSUE THREAD

**Issue by almogdesign** [matteodem/meteor-easy-search#121]
I'm triggering the triggerSearch() method however noting is happing  

My Template: 
```javascript
{{#esEach index="forms"}}
     <h2>Test</h2>
 {{/esEach}}
```
Template JS:
```javascript
 var instance = EasySearch.getComponentInstance(
            { index : 'forms' }
        );
 instance.triggerSearch();
```
And EasySearch Setup 
```javascript
// Search for reports
EasySearch.createSearchIndex('forms', {
    'collection': Forms,
    'field': ['formName', 'producerIdNumber'],
    'limit': 15,
    'use' : 'mongo-db',
    'sort': function() {
        return { 'created': -1, 'name': -1 };
    },
    'query': function(searchString, opts) {
        // Default query that will be used for the mongo-db selector
        var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);
        console.log('Running query');
        query.formName = 'Preaviso Biológico';
        return query;
    }
});
```

**Comment by almogdesign** [comment]
I also tried the following but noting 

 EasySearch.getComponentInstance({ index: 'forms' }).search(form);

**Comment by almogdesign** [comment]
So you must have the esInput component in the template for this to work 
```javascript
 {{> esInput index="forms"  placeholder="Search..." class="form-control" }}
```

If you don't want to show this you can then hid the input component, will also try to test this out with the filter option. But it would be nice to require the esInput component.

**Comment by matteodem** [comment]
If you really have to include the esInput then that's a bug.

**Comment by almogdesign** [comment]
I did, currently I'm just hiding it

**Comment by matteodem** [comment]
You're right, it's because of following line: https://github.com/matteodem/meteor-easy-search/blob/master/lib/components/easy-search-components.js#L210. I need a way to see which index is being used with components. 

I'll have a look in the next days.

**Comment by matteodem** [comment]
This works in the latest version __1.4.10__

**Comment by matteodem** [comment]
Feel free to re-open if it doesn't.
