### ISSUE TITLE
Reactive publish with EasySearch.search() on server

### ISSUE THREAD

**Issue by vuhpham** [matteodem/meteor-easy-search#123]
First of all, thanks so much for this awesome package.

I'm using it along with publishComposite (https://github.com/englue/meteor-publish-composite) to write a search publisher. 

However, since EasySearch.search returns results instead of cursor then I'm stuck on making it reactive. Does anyone know anything wrong in my code or what is the better approach for my problem?
Here is my code:
```
Meteor.publishComposite('docs', function(options) {
	check(options, {
		sort: Object,
		limit: Number,
		filter: Object,
		searchString: String
	});
	var docs = EasySearch.search('docs', options.searchString, {
		limit: options.limit,
		sort: function() {
			return options.sort;
		},
		query: function(searchString) {
			var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);
			return _.extend(query, options.filter);
		}
	}).results;

	var objIds = _.map(docs, function(doc) {
		return doc._id;
	});

	return {
		find: function() {
			return Docs.find({
				_id: {
					$in: objIds
				}
			}, {
				sort: options.sort
			});
		},
		children: [{
			find: function(doc) {
				return Images.find({
					_id: doc.image
				});
			}
		}]
	};
});
```

**Comment by matteodem** [comment]
Thank you. This package does the reactive search by subscribing itself to a reactive data source, as seen here: https://github.com/matteodem/meteor-easy-search/blob/master/lib/components/easy-search-components.js#L127.

I guess the way you're using it right now is fine. Would it help you if there was a way to only return the cursor?

**Comment by vuhpham** [comment]
Hi @matteodem, thank for your response. Please correct me if I'm wrong, my understanding is the triggerSearch method will trigger a new search whenever a new condition is raised. However, my problem is reproduced by these steps:
1. User A subscribe "searchDocs" publisher and get the search result set is [R1, R2, R3]
2. In the same time, user B insert a new doc R4 and it matches the condition that user A search.
3. User A should see R4 in result set reactively along with [R1, R2, R3]. So I'm thinking about if EasySearch.search() return a cursor and publisher will return that cursor, result set of search will be reactive in this case.

**Comment by matteodem** [comment]
As of now it's also for UX reasons not showing that new document, since it'd confuse the user when the search results just "suddenly" change. This is really bad for example if you got pagination in your search.

I'm not sure if that's a thing we want to have added to the search, but I'm open for suggestions why this should be implemented.

**Comment by vuhpham** [comment]
My idea was just to wrap every publisher in server by Easysearch, so it can serve user either search or normal cases without loosing reactive. In the normal cases, subscriber just need to pass the searchString parameter as empty. But since it was an intended structure, so I think I will go the other way.

Many thanks, @matteodem
