### ISSUE TITLE
returnFields is not working for reactive search

### ISSUE THREAD

**Issue by mquandalle** [matteodem/meteor-easy-search#126]
It seems that all the field of a collection are published even if we use the `returnFields` option. Maybe because of https://github.com/matteodem/meteor-easy-search/blob/master/lib/easy-search-common.js#L79?

**Comment by matteodem** [comment]
This is right. I will have a look at it later this evening.

**Comment by matteodem** [comment]
Fixed in latest version with commit cb2726c056e6996a79e73a3060b2e94c4c8d9fea. I really am wary of new functionality. I'll be sure to add a little amount of new features and then just write a decent amount of tests to cover this.

**Comment by mquandalle** [comment]
Thanks!

**Comment by mquandalle** [comment]
After a test, it seems to not be fixed. Do you need a reproduction?

**Comment by matteodem** [comment]
I just tested it locally again with __1.4.9__ with following code (loaded on client and server):
```javascript
// On Client and Server
Players = new Meteor.Collection('players');
// name is the field of the documents to search over
Players.initEasySearch('name', {
  'returnFields' : ['name']
});
```

Please give me a reproduction repo if this doesn't work for you.

**Comment by mquandalle** [comment]
Hum, I was using a mongo field selector, like

```js
{
  name: 1
}
```

I'll try again with the array syntax.

**Comment by matteodem** [comment]
Yes. the thing is with the array like syntax it'd be hard to rewrite it for elastic search. I'll otherwise add it to also accept field selectors.

**Comment by matteodem** [comment]
Please feel free if it doesn't work with the array syntax.

**Comment by mquandalle** [comment]
Tested, and it works, thank you very much :-)
(I guess it just needs some tests :p)

**Comment by matteodem** [comment]
Of course it does, as anything else :smile:. I'll be sure to just focus on tests after I resolved the other 2 bugs in the issues.
