### ISSUE TITLE
Searching non-string data types

### ISSUE THREAD

**Issue by clarkritchie** [matteodem/meteor-easy-search#136]
This is a great package.  Thanks for contributing.

Question:  I'm not able to search on non-string fields, or I'm just missing something obvious.  In the example below, ```up``` is an Int32 -- shouldn't I be able to just do something like transform?

```
EasySearch.createSearchIndex('productsIndex', {
    'field': ['name','up','down'],
    'collection': Products,
    'use': 'mongo-db',
    'transform': function (doc) {
        doc.up = doc.up.toString();
    }
});
```

Thanks.

**Comment by matteodem** [comment]
You would need to add the query parameter: http://matteodem.github.io/meteor-easy-search/docs/javascript-api/

**Comment by clarkritchie** [comment]
Makes sense, thanks!

**Comment by clarkritchie** [comment]
I totally missed ```convertNumbers: true``` in the docs, which worked for Int32.  Not sure it's working for Double, but not super concerned about that right now.  Thanks again.
