### ISSUE TITLE
Search on subdocument (Users)?

### ISSUE THREAD

**Issue by clarkritchie** [matteodem/meteor-easy-search#137]
Am I just missing how to search on, for example, a user's email?  Refs #79?

```
    EasySearch.createSearchIndex('usersIndex', {
        'field': ['username','emails[0].address'],
        'collection': Meteor.users,
        'use': 'mongo-db',
    });
```

**Comment by matteodem** [comment]
I'll add an example how to search over the Meteor.users collection soonish.

**Comment by matteodem** [comment]
Just for your knowledge, the custom query method does the work.

**Comment by connor-baer** [comment]
Awesome, thanks!

**Comment by clarkritchie** [comment]
I ended up doing this:

```
    EasySearch.createSearchIndex('usersIndex', {
        'field': ['username','emails.0.address'],
        'collection': Meteor.users,
        'use': 'mongo-db'
    });
```

**Comment by matteodem** [comment]
there is a way to search in arrays, I'll add it soon. I'm very busy right now, sorry.

**Comment by matteodem** [comment]
Added it to the doc recipes, hope this helps! http://matteodem.github.io/meteor-easy-search/docs/recipes/

**Comment by notarypublic** [comment]
There is still not a simple example for searching through Meteor.users collection. I am getting an error trying to use a query like @clarkritchie submitted -- is it possible to provide the most basic example of an index for Meteor.users? For example, searching on just the [username] field?

**Comment by matteodem** [comment]
How about the recipe called "Searching user mails" ? http://matteodem.github.io/meteor-easy-search/docs/recipes/
