### ISSUE TITLE
Option to return all items if no text is entered in esInput

### ISSUE THREAD

**Issue by reinzor** [matteodem/meteor-easy-search#138]
Currently, there is no possibility to list all items when there is no filter active in the esInput.

#ifEsInputIsEmpty can be used to list all items but this implies that the user has to re-implement all the paging logic.

It would be nice if this was an option when you register the easy search on a collection.

**Comment by Urigo** [comment]
+1

**Comment by junecoder** [comment]
:+1:

**Comment by matteodem** [comment]
Please update to the latest version of Easy-Search and test this feature with the new property ```allDocsOnEmpty``` on the esInput
