### ISSUE TITLE
autosuggest remove default onselect action

### ISSUE THREAD

**Issue by krishnakanth123** [matteodem/meteor-easy-search#139]
I'm using autosuggest
```
{{> esAutosuggest index="userSuggestions" id="autosuggest" renderSuggestion=suggestionTpl }}
```
I've defined search index here

```
EasySearch.createSearchIndex('userSuggestions', {
  'collection': User, 
  'use' : 'mongo-db',
  'limit':5,
  'field': ['name','job_title']
});
```
to get the selected value i'm using tracker in rendered function
```
Tracker.autorun(function () {
    var instance = EasySearch.getComponentInstance(
        {id : 'autosuggest', index : 'userSuggestions' }
    );

    instance.on('autosuggestSelected', function (values) {
      console.log(values);
    });
  });
```
but when I select (press enter on particular autosuggest value) item, it is displaying like a label with x mark, I suppose this is a default behaviour, How to get rid of the default behaviour.

You can see that in the below image

http://i.stack.imgur.com/Td4Uk.png

**Comment by matteodem** [comment]
What is the exact feature request of this issue?

**Comment by matteodem** [comment]
You can use the ```renderValue``` options for this functionality: http://matteodem.github.io/meteor-easy-search/docs/blaze-components/
