### ISSUE TITLE
Filtering based on numbers

### ISSUE THREAD

**Issue by nicolascarey** [matteodem/meteor-easy-search#140]
I have a working filter set up - its a dropdown selecting integers.

I'm trying to change the query part, where the search index is created so that it will show greater than / less than using Mongo commands.

However things don't seem to be working.

This code works, which would be fine if the dropdown was only to show exact prices...
<pre>
   if (this.props.filteredCategory !== '0') {
      query.price = this.props.filteredCategory ;
    }

</pre>

But I'm trying to get something like this working, where it will return everything under that price:

if (this.props.filteredCategory !== '0') {
      query.price = { $lt : this.props.filteredCategory} ;
    }

However it just stays stuck on ifEsIsSearching

**Comment by matteodem** [comment]
Please provide me with a reproduction repo.

**Comment by matteodem** [comment]
Please post your reproduction when you got it.
