### ISSUE TITLE
Search works the first time, but if I navigate away and back using iron-router, it doesn't function

### ISSUE THREAD

**Issue by slickdev** [matteodem/meteor-easy-search#142]
I haven't been able to determine the reason for this yet... has anyone else had similar issues?

Search functionality works the first time, or on a fresh reload, but once I navigate to another page and come back, search no longer works.

**Comment by matteodem** [comment]
Can you reproduce it please?

**Comment by SeabookChen** [comment]
Same issue here.

**Comment by SeabookChen** [comment]
Seems there are some caching issue in the code.

I hacked the code by doing the following, but leave it to author to fix the code.
```
function clear(index, componentId) {
    var conf,
      id = generateId(index, componentId);

    SearchVars.set(id, {
      'searching' : false,
      'searchingDone' : false,
      'total' : 0,
      'currentValue' : '',
      'searchResults' : [],
      'skip' : 0
    });

    if (EasySearch._usesSubscriptions(index)) {
      conf = EasySearch.getIndex(index);
      conf.subscriptionHandle && conf.subscriptionHandle.stop();
    }

    inputCache = '';

   //  This is the place i changed code to make sure the code `createSearchDependency(index, data.id)` run every time
    var startPos = initializedComponents.indexOf(index);
    if (startPos != -1) {
      initializedComponents.splice(startPos, 1);
    }

  }
```

**Comment by slickdev** [comment]
Thanks for posting the reproduction, @SeabookChen

**Comment by matteodem** [comment]
Perfect, @SeabookChen fix is the right way to do it. I'm happy to have PR's for it or I'll implement it when I get to it.

**Comment by matteodem** [comment]
This should be fixed in the latest version __1.4.12__, please test it and write into this ticket if the bug is still there.

**Comment by slickdev** [comment]
Great, thanks Matteo. Tested it on my end and it works.
