### ISSUE TITLE
Don't index the whole document into elastic-search

### ISSUE THREAD

**Issue by MaazAli** [matteodem/meteor-easy-search#144]
I'm trying to switch over to elastic search but it seems like the whole document is being indexed instead of the fields you specify. If this is done to ensure that if the searchable fields ever change, a re-index isn't required then I get it but then I suggest we have a indexFields property where we can give an array of field names that should be indexed by elastic search per document. There are fields in my document that will never be searched, they are usually never available to the client either and they should not be indexed by elastic search.

If there is a way to let elastic search know you only want to index a subset of the document, please point me in the right direction, thanks!

@matteodem thanks for the awesome plugin by the way.

EDIT:
There seems to be the transform function that does this, however, I'm just using deletes at the moment. You can close this issue or suggest a better way to handle this case :)

**Comment by matteodem** [comment]
Hello there, thanks for the kind words. Transform has been explicitly added to provide this functionality. See the recipe example for it: http://matteodem.github.io/meteor-easy-search/docs/recipes/ (Enhancing document fields)
