### ISSUE TITLE
Search Displays All Results After Deleting Characters

### ISSUE THREAD

**Issue by frank1340** [matteodem/meteor-easy-search#145]
Hello, 

I noticed that if I delete characters from a search, sometimes the entire result set shows up for the first character entered even if no characters are present.  For example, if I type in "head c", and then delete all characters, the results with an 'h' will display.  This seems to happen when a whitespace is used at some point in the search.

**Comment by matteodem** [comment]
I do not really understand your explanation, can you provide another example with steps on how to reproduce?

**Comment by frank1340** [comment]
Simply put, after deleting all characters in esInput, results still show for the first character of the deleted string.  Is that clear?

**Comment by frank1340** [comment]
This still happens.  Could this be my fault?  I have a ifEsInputIsEmpty check, but the results for the first character are still shown, with the first character not being present.

**Comment by matteodem** [comment]
I need a reproduction repository for this, since I cannot reproduce it locally with the leaderboard example.
