### ISSUE TITLE
ES features questions

### ISSUE THREAD

**Issue by kk4sh** [matteodem/meteor-easy-search#146]
Hi, 

First of all, thanks for your awesome package. 

i use it using elactic search as searchengine. 

i have both questions: 

- How/when es docs is synchronized with mongodb items?

- more a elastic question than a real package question but how to combine match and fuzzylike inside a bool query.

sql equivalent of 

`select * from items where a = 'b' and b like '%plop%'`

 And finally , you talk about a 'body' parameter in your es documentation. Aim of this parameter ? 

Thanks

**Comment by matteodem** [comment]
MongoDB docs are synchronized when they are inserted, removed or updated. See the code here: https://github.com/matteodem/meteor-easy-search/blob/master/lib/searchers/elastic-search.js#L74. For elastic search questions, please refer to their docs  http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
