### ISSUE TITLE
Match error: Expected string, got object in field value

### ISSUE THREAD

**Issue by almogdesign** [matteodem/meteor-easy-search#147]
The first time I run a search I'm getting the following error. Then if I try another search I'm stuck in an endless search without results. 

I just updated to the latest package two days ago and now I'm getting the following error 

Expected string, got object in field value at checkSubtree (packages/check/match.js:159:1)
packages/check/match.js:296:1
Function._.each._.forEach (packages/underscore/underscore.js:113:1)
checkSubtree (packages/check/match.js:290:1)
check (packages/check/match.js:32:1)
 [object Object].<anonymous> (packages/matteodem:easy-search/lib/easy-search-common.js:63:1)
packages/matb33:collection-hooks/collection-hooks.js:214:1
[object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) [object Object]._handler (packages/matb33:collection-hooks/collection-hooks.js:213:1)
packages/check/match.js:109:1
I20150219-18:19:31.938(2)? Sanitized and reported to the client as: Match failed [400]

Here is my code 

On the client 
```javascript            
// Calls the search
EasySearch.changeProperty('forms', 'formName', form);
EasySearch.changeProperty('forms', 'producerId', producerId);
EasySearch.changeProperty('forms', 'blockId', blockId);
EasySearch.changeProperty('forms', 'created', created);
EasySearch.getComponentInstance({ index: 'forms' }).search(created);
```

Example values 
Preaviso Biológico
RJk8yFPoKx5wJqmHh
2015-02-13
2015-02-19
["2015-02-13", "2015-02-19"]

my search code 
```javascript           
// Search for reports
EasySearch.createSearchIndex('forms', {
    'collection': Forms,
    'props' : {
        'formName' : '',
        'producerId' : '',
        'blockId': '',
        'created': []
    },
    'field': ['formName', 'producerId', 'blockId', 'created'],
    'limit': 15,
    'use' : 'mongo-db',
    'sort': function() {
        return { 'created': -1, 'formName': -1 };
    },
    'query': function(searchString, opts) {
        // Default query that will be used for the mongo-db selector
        var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);
        if (this.props.formName != '') {
            query.formName = this.props.formName;
        }
        if (this.props.producerId != '') {
            query.producerId = this.props.producerId;
        }
        if (this.props.blockId != '') {
            query.blockId = this.props.blockId;
        }
        if (this.props.created.length != 0) {
            query.created = {$gte:new Date(this.props.created[0]), $lt:new Date(this.props.created[1])};
        }
        return query;
    }
});
```

**Comment by matteodem** [comment]
This is happening because you search with an array instead of a string.

**Comment by almogdesign** [comment]
Great but it worked before and it stopped with the recent update? Was there a changelog covering breaking changes?

**Comment by matteodem** [comment]
No there wasn't, since it was intended to be only searchable with strings. I will add that to the docs.

**Comment by almogdesign** [comment]
So it was a bug and with the update it was fixed?

**Comment by matteodem** [comment]
exactly, sorry for not mentioning it in the docs.

**Comment by almogdesign** [comment]
No worries know I know how to fix it.
