### ISSUE TITLE
Why is EasySearch using objects in the search query 

### ISSUE THREAD

**Issue by almogdesign** [matteodem/meteor-easy-search#148]
When I look out the query output being used I'm seeing objects is there are a reason for this 

{ '$or': 
[ { formName: [Object] },
{ producerId: [Object] },
{ blockId: [Object] },
{ created: [Object] } ],
producerId: 'RJk8yFPoKx5wJqmHh',
blockId: 'HxeudF5c5KWh4EAwa' }

**Comment by matteodem** [comment]
Yes, it is a $or guery being executed, what is the question here?

**Comment by almogdesign** [comment]
I'm not creating the objects I'm just passing strings and the query has the same search object twice why is that? 

I'm passing this - producerId: 'RJk8yFPoKx5wJqmHh'
so is there this - producerId: [Object] 

And why is it twice

**Comment by matteodem** [comment]
because you probably specified it as a field when using "createSearchIndex", right? The reason why search works by just specifing fields is since EasySearch sets up a mongo query that works with it.

**Comment by matteodem** [comment]
Feel free to write the answer into the bug if it something different.
