### ISSUE TITLE
Reactive document search

### ISSUE THREAD

**Issue by kk4sh** [matteodem/meteor-easy-search#151]
The question has been already discussed but keep reactivity on deletion/addition document may be a great feature. 
I agree with you . It may be an UX problem in the case of instant searching...it has to be managed.
But today the search engines are no more use only for this case, and may be used for instance to browse  though documents by applying filtering ( typically a ecommerce website)...or visualize a filtered tasklist..and so..
I think a lot of people may be interested for this enhancements
Thank you

**Comment by matteodem** [comment]
see description in #230

**Comment by matteodem** [comment]
This is fixed as of v2, where the default behavior has changed.
