### ISSUE TITLE
Search between two date range issue

### ISSUE THREAD

**Issue by almogdesign** [matteodem/meteor-easy-search#152]
Hi, 
So everything was working fine until the latest update. Now when I run a query search between two dates I'm not getting anything back. 

I tried both new date as meteor suggest and sending ISO dates to the query. 

The way only I got it working was to change out the way I run the query as you can see in the code. 

Pervious version 
```javascript
'query': function(searchString, opts) {
        // Default query that will be used for the mongo-db selector
        var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);

        if (this.props.formName != '') {
            query.formName = this.props.formName;
        }
   
        if (this.props.producerId != '') {
            query.producerId = this.props.producerId;
        }

        if (this.props.blockId != '') {
            query.blockId = this.props.blockId;
        }

        if (this.props.endDate != '') {
            query.created = {$gte:'2015-02-28T11:21:53.501Z', $lt:'2015-01-22T11:21:53.501Z'}; 
           // Also tried the following format 
            // new Date('2015-01-01')
            //new Date('2015-02-28')
        }
        return query;
    }
```

What I'm currently working that works 
```javascript
query =  {$and:[{formName: 'Preaviso Biológico'}, {created:{$gte:new Date('2015-01-01'), $lt:new Date('2015-02-28')}}]};
```

I removed everything else

**Comment by matteodem** [comment]
Which version was the latest working one?

**Comment by almogdesign** [comment]
matteodem:easy-search 1.4.13

**Comment by matteodem** [comment]
the changes from 1.4.14 to 1.4.13 only are these https://github.com/matteodem/meteor-easy-search/commit/cac7da61a534cb7d7d64ffdc0e8264d683e3a861, please hand in a reproduction repository if this problem still exists.

**Comment by kalubunda** [comment]
hey is it possible to display data between two dates in mongodb like in sql?. i mean display all the content between the start date and end date in mongodb

**Comment by matteodem** [comment]
Please refer to the mongodb docs for this. It is possible with Easy Search to rewrite the mongodb selector by providing a `selector` method to the engine configuration.
