### ISSUE TITLE
ElasticSearch index: how to specify field properties?  I need not_analyzed

### ISSUE THREAD

**Issue by dpdonohue** [matteodem/meteor-easy-search#153]
Thanks for meteor-easy-search!  I love it.

I have a field that contains ID values with hyphens (-).
ElasticSearch tokenizes myField, when I do not want it to.
See here
http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_finding_exact_values.html

I need to specify my field to be not_analyzed, like this.
"properties" : {
                myField : {
                    "type" : "string",
                    "index" : "not_analyzed" 
                }
            }

Can I specify this using EasySearch?

**Comment by matteodem** [comment]
related to #79

**Comment by matteodem** [comment]
I will close this as it is related to the referenced story.

**Comment by niranjans** [comment]
@matteodem So this is not possible with easy search? I need to have geospatial search but when I try the distance filter, I get the following error:

`nested: QueryParsingException[[cars] field [locationCoordinates] is not a geo_point field];`

Are there any alternatives?

**Comment by rico** [comment]
You can do it using the ElasticSearch API

- Create (or recreate) your index: `curl -X PUT http://localhost:9200/your-index`

- Set the desired mappings: 

```
curl -X PUT  -d '{
  "default": {
    "properties": {
      "your_field": {
        "type": "string",
        "index": "not_analyzed"
      }
    }
  }
}' http://localhost:9200/your-index/_mapping/default
```

**Comment by matteodem** [comment]
Yes it is not possible right now with `Easy-Search` itself.
