### ISSUE TITLE
Apply filters on search results

### ISSUE THREAD

**Issue by chinna789** [matteodem/meteor-easy-search#154]
My search index 
```
EasySearch.createSearchIndex('userSuggestions', {
  'collection': User, 
  'use' : 'mongo-db',
  'limit':5,
  'field': ['name','sex','profile.location','company'],
  query: function (searchString) {
    var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);
        query['deleteReque'] = { $ne: true };
        return query;
    }
});
```

I'm using ```esInput`` and getting results

```
{{> esInput index=indexes class="side-search" id="dbsearch"}}
```

After getting the results, I'm giving the user option to filter, like `sex` M/F

what is the best way to perform these filters on results

**Comment by matteodem** [comment]
Have a look at the leaderboard for filtering examples https://github.com/matteodem/easy-search-leaderboard

**Comment by chinna789** [comment]
I've implemented using my own input and `search` function in server side.
Thankyou for the reference
