### ISSUE TITLE
make EasySearch.search return subscription(like) object

### ISSUE THREAD

**Issue by smeijer** [matteodem/meteor-easy-search#157]
Should be great if the javascript api, ```EasySearch.search``` returned a subscription (like) object. Mostly because I need to be able to determine if the search query is completed, or still running (ready);

Based on the [Meteor Pattern: Template-Level Subscriptions](https://www.discovermeteor.com/blog/template-level-subscriptions), I would like to implement search like:

```js
Template.userSearch.created = function() {
  // 1. Initialization
  var instance = this;

  instance.ready = new ReactiveVar(false);
  instance.query = new ReactiveVar('');
  instance.results = new ReactiveVar([]);

  // 2. Autorun
  instance.autorun(function() {
    var query = instance.query.get();

    var subscription = EasySearch.search('users', query, function (error, data) {
      instance.results.set(data.results);
    });

    if(subscription.ready()) {
      instance.ready.set(true);
    }
    else {
      instance.ready.set(false);
    }
  }

  // 3. Cursor
  instance.users = function() {
    return instance.results.get();
  }
}
```

So, for this basic pattern, which works really nice in my opinion, there even isn't a real subscription required. All ```EasySearch.search``` has to return is a object with a reactive method called ```ready```.

**Comment by matteodem** [comment]
You can get states by using the Components with the Component API: http://matteodem.github.io/meteor-easy-search/docs/component-api/

**Comment by smeijer** [comment]
I was aware of the Components part. But what If i'm not using components, but writing my own interface / templates?

Combined with the methods above:

```js
Template.userSearch.helpers({
  'users': function() {
    var instance = Template.instance();
    var users = instance.users();

    return users;
  }
});

Template.userSearch.events({
  'submit form': function(event, instance) {
    var input = $(instance.find('input'));
    var query = input.val();
    instance.query.set(query);
  }
});
```

```html
<!-- simplified for clarity -->
<template name="userSearch">
  <form>
    <input type="text" name="search" />
  </form>

  <ul>
    {{#each users}}
      <li>{{name}}</li>
    {{/each}}
  </ul>
</template>

**Comment by matteodem** [comment]
I already considered doing this, but from an backwards compatibility it would break a lot of stuff. I might consider adding a ```reactiveSearch``` method though, or something similiar like that (which returns a subscription handle). wdyt?

**Comment by smeijer** [comment]
I didn't really study the code, so I can be incorrect. But I'm not entirely sure why such a return would break backwards compatibility. Because as it looks to me, the current ```EasySearch.search``` method isn't returning a thing. So it would just be some extra functionality. Or am I really missing something here?

Nevertheless, a separate method like ```reactiveSearch``` could most definitely work. 

Just a quick mock to clarify my thoughts, don't pin it on me. What I meant was something like:

```js
var Handle = function() {
   this._ready = new ReactiveVar(false);
};

_.extend(Handle.prototype, {
  ready: function() {
     return this._ready.get();
  }
});

// adapted ./master/lib/easy-search-client.js#L34
EasySearch.search = function (name, searchString, callback) {
  var results, searcher,
    index = EasySearch.getIndex(name),
    indexOptions = filterFunctions(index),
    handle = new Handle();

  if (!index) {
    throw new Meteor.Error(500, "Couldnt find index: '" + name + "'");
  }

  searchString = searchString || '';
  searcher = EasySearch.getSearcher(index.use);

  if (searcher) {
    results = searcher.search(name, searchString, indexOptions);
    handle._ready.set(true);
    callback(null, index.changeResults(results));
  } else {
    Meteor.call('easySearch', name, searchString, indexOptions, function(err, res) {
       handle._ready.set(true);
       callback(err, res);
    });
  }

  return handle;
};
```

**Comment by matteodem** [comment]
okay I understand now. I thought you wanted to get the subscription handle, since we're subscribing to data for the reactive search. This seems like a cool idea, I'll let it here as an enhancement.
