### ISSUE TITLE
Page loads 'breaking' search

### ISSUE THREAD

**Issue by quoid** [matteodem/meteor-easy-search#158]
It seems like the search breaks in between pages loads; the search api continues to function but it is the esInput that 'breaks.' By breaks I mean it no longer provides me with search results and doesn't reset the search query on click of a result. The weird thing is that if I move the search element from the layout to a view (template section), it works properly.

I made a quick screencast showing this behavior where you can see that the search in the top right (in the app's layout) fails to function properly after a page load (search results clicked), but the search bar inside a view/template functions properly after a page reload. ~~[Here is the video link]~~

Optimally, I'd like to keep the esSearch in the app layout. Any help on this would be greatly appreciated.

**Comment by matteodem** [comment]
you got a reproduction for it?

**Comment by matteodem** [comment]
This is not reproduceable here https://github.com/matteodem/easy-search-leaderboard

**Comment by jsilverMDX** [comment]
Just noting here that I was able to fix this by migrating away from esInput component. I programmed my own version of it using a dependency and the search API and was able to fix it.

**Comment by matteodem** [comment]
This is really weird. Can you list what configuration, so I can reproduce it? A repo would also be appreciated.

**Comment by jsilverMDX** [comment]
The app is rather complex, and a reproduction wouldn't be simple. Also I am not sure what parts of the app was breaking it, beyond that the component wasn't working. What do you mean by configuration? I can provide specific details.

**Comment by matteodem** [comment]
what you provided as the argument for ```createSearchIndex```.

**Comment by jsilverMDX** [comment]
I didn't call ```createSearchIndex``` I used the following ```People.initEasySearch(['name'])``` Sometimes I put another field like "notes."

**Comment by matteodem** [comment]
I cannot reproduce it locally with the same configuration (Switching between two sites and the search still works)

**Comment by jsilverMDX** [comment]
It's some bug with our site. We were able to fix it by replacing esInput component with a custom version that called the API directly and it works the exact same. I have no idea what it was.

**Comment by matteodem** [comment]
okay, if you are able to track it down to Easy-Search feel free to re-open or create a new issue.
