### ISSUE TITLE
Elastic and Date format

### ISSUE THREAD

**Issue by kk4sh** [matteodem/meteor-easy-search#159]
Hello, 

I have a problem with the Date format and the use in ES. 

In Mongo, i have the following storage 

    "At" : ISODate("2014-10-30T23:16:59.841Z"),
where "At" is typed as Date.  

The automatic mappings seems ok with the default ES configuration, 

    {"At":{"type":"date","format":"dateOptionalTime"}

The obtained result by ES querying is formatted as a string 

    "At":["\"2014-10-30T23:16:59.841Z\"

=> as a consequence, obtained result value for sorting and filtering is false. For ie, the "sort" value on this field gives the following results : 

    {"At":["\"2014-10-30T23:16:59.841Z\""],"ItemId":["Item10046"]},"sort":["59.841z"]}

Any clue to solve it ? 

I have noticed, the date option is enriched with underscore in the ES doc, may just the cause
"date_optional_time"
http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html

Edit: 

Spot in getESFields(doc) where JSON.stringify method doubles the quotes, test on Date format should be added

 newDoc[key] = _.isObject(value) && !_.isArray(value) && !_isDate(value) ? JSON.stringify(value) : value;

**Comment by matteodem** [comment]
Please update to latest version of EasySearch ```1.5.1``` and try if it works now.
