### ISSUE TITLE
esPagination - class option / styling?

### ISSUE THREAD

**Issue by ganySA** [matteodem/meteor-easy-search#160]
Hi

I see that in the documentation esPagination does not have a 'class' option. I am using bootstrap i was wondering if there is a way to assign bootstrap pagination classes?

Apologies if i missed something in the documentation.

Thanks

**Comment by matteodem** [comment]
yeah you are right, that's missing. I probably will add a new parameter called ```renderPagination```.

**Comment by matteodem** [comment]
This is now resolved as of v2, with the `customRenderPagination` option, see http://matteodem.github.io/meteor-easy-search/docs/components/
