### ISSUE TITLE
Pagination is not functioning correctly. 

### ISSUE THREAD

**Issue by stephenfairchild** [matteodem/meteor-easy-search#163]
I've asked a question on StackOverflow, but I started thinking this is perhaps a better avenue? It's unlikely this is a bug, but more likely a lack of my understanding of this package and meteor as well. 

http://stackoverflow.com/questions/29188220/meteor-easy-search-pagination-integration

I'm happy to close this issue in lieu of SO or vice versa. 

Thanks

**Comment by matteodem** [comment]
Can you give me a reproduction-repository please?

**Comment by stephenfairchild** [comment]
Sure. Here you go: https://github.com/stephenfairchild/MeteorDemo
1.) Create an account
2.) Go to homepage and submit a bunch of items. 
3.) Go to the history tab and view the pagination issues.

**Comment by matteodem** [comment]
The reproduction repository is not functional, a package called pages is missing.

**Comment by matteodem** [comment]
Feel free to add the pages package and update the repo accordingly.

**Comment by soniya90** [comment]
I have more than 50000 of records. and pagination is working properly. But this tool displaying all the pages instead of showing starting few pages from the searched page.

**Comment by soniya90** [comment]
page limit is 20.. what m i missing?

**Comment by matteodem** [comment]
Are you missing the feature to only show the first 10 sites, if the pagination has more than 10 available sites? I'll open a new ticket for that.

**Comment by soniya90** [comment]
Hello Micheli,

Thank you for your response. 
Please refer attached screenshot to identify the problem.  I just want show few pages link with prev next option.  

Thank you in advance....

----------------------------------------

**Comment by soniya90** [comment]
Yes i m missing this features to show 10 or 20 sites. It will be a greatful if you add this feature as soon as possible..
Thank you

----------------------------------------
