### ISSUE TITLE
Multiple collection search question

### ISSUE THREAD

**Issue by centinel3** [matteodem/meteor-easy-search#164]
Good afternoon,

This is an awesome search package, thank you very much! I have a question about leveraging this for multiple collection searches.

In my scenario, on a list page, I have modules that reference multiple collections to bring back the full view (projects, colors, etc.). I'm using iron router waitOn to pass the _id in order to get all the data from multiple collections before I render the view (currently), and would ideally like to accomplish the same with search. Is there a way to perhaps do a search on one collection, grab the _id of each result, then use a Meteor.find() or the like to get the rest of the data pertaining to that specific search result (I hope that makes sense).

The long and short of it is if I search projects, I get some of the data and would like to (in conjunction with) return not only that project data but the data pertaining to that project form other collection documents that share a project ._id.

Thanks in advance and look forward to hearing form you.
Sincerely,
Chris

**Comment by matteodem** [comment]
Hello @centinel3, do you want to use EasySearch to create relations? Do I understand that correctly? Please make a step by step list which shows the use case you are asking me about.

**Comment by centinel3** [comment]
Hey Matt,
I have pasted my code below. Id like to allow the user to search through multiple collections, and have the search bing back the project item that has the search term they are looking for. My project list page references both the project collection as well as the colors collection (as I'm displaying data from both collections on the project list page). 

As I can see it now, I can have the search look at different collections, though need to have separate blocks of code to display the results from the different collections. Some of my code is below. 

In the picture, the color bar is what I would also like to display when the search results are returned. This is specific to the colorsCollection and usually pass the project _id to get the colors per project item.

![screen shot 2015-03-24 at 7 08 35 pm](https://cloud.githubusercontent.com/assets/199507/6814864/480bc840-d259-11e4-8971-fae892d27dc4.png)


Router:
// Project List
  this.route('projects-list', {
    name: 'projectsListTpl',
    path: '/projects-list',
    onBeforeAction: function () {
      if (!Roles.userIsInRole(Meteor.user(), 'owner') && !Roles.userIsInRole(Meteor.user(), 'admin')) {
        this.render('accessDeniedTpl');
        this.stop();
        return;
      } else {
        this.next();
      }
    },
    waitOn: function() {
      if (Meteor.user()) {
        return [Meteor.subscribe('projects', Meteor.user().profile.companyId), Meteor.subscribe('colors-used-list')];
      }
    }
  });

// HTML Search Template:
<template name="searchFormTpl">
    {{> esInput index=indexes placeholder="Search..." }}

    <ul>
        {{#esEach index="projects"}}
        {{> _projectListItem}}
        {{/esEach}}
    </ul>
  
    <ul>
        {{#esEach index="colors"}}
        {{> _projectListItem}}
        <li>colorName: {{colorName}}</li>
        {{/esEach}}
    </ul>

    {{> esLoadMoreButton index="projects"}}

    {{#ifEsHasNoResults index=indexes}}
    <div class="no-results">No results found!</div>
    {{/ifEsHasNoResults}}

    {{#ifEsIsSearching index=indexes}}
    <div>Loading...</div>
    {{/ifEsIsSearching}}
</template>

Template.searchFormTpl.helpers({
  indexes: function() {
      return ['projects', 'colors'];
  }
});

// Project list item template
<template name="_projectListItem">
  <div class="project-list-item">
  <a href="{{pathFor 'projectPageTpl'}}">
    <div class="company-project-name">{{clientProjectName}}</div>
    <div class="company-project-description">{{projectDescription}}</div>
  </a>

    <div class="totals group">
      <img src="{{companyImageUrl}}"/>
      
      <div class="top-row group">
        <div class="colors-total">color{{colorsTotal}}</div>
        <div class="typography-total">type-{{typographyTotal}}</div>
      </div>

      <div class="bottom-row group">
        <div class="components-total">comp-{{componentsTotal}}</div>
        <div class="files-total">file-{{filesTotal}}</div>
      </div>
      
    </div>

    {{> _colorsUsedListItemsTpl}}

    <div class="project-info group">
      <div class="company-name">{{clientName}}</div>
      <div class="page-views"><i class="fa fa-eye"></i>{{pageViewsTotal}}</div>
      <div class="favorites"><i class="fa fa-heart"></i>{{favoritesTotal}}</div>
    </div>

  </div>
</template>

<template name="_colorsUsedListItemsTpl">
  <div class="colors-used-list-items">
    {{#each colorsUsedListItems}}
      <div class="color" style="width:{{colorWidth}}%; background-color:#{{colorHexValue}};"></div>
    {{/each}}
  </div>
</template>

Template._colorsUsedListItemsTpl.helpers({
  colorsUsedListItems: function() {
    return ColorsCollection.find({projectId: this._id}, {sort: {colorRank: 1}});
  },

  colorWidth: function() {
    var totalColors = Template.parentData(1).colorsTotal;
    var colorWidth = 100 / totalColors;
    return colorWidth;
  }
});

**Comment by matteodem** [comment]
If you want to search through multiple collections with the blaze components you can use an array of indexes as the parameter. Please try to have a concise question that states what you want to achieve and what is taking you back. 

http://matteodem.github.io/meteor-easy-search/docs/blaze-components/ (see multiple section)

**Comment by centinel3** [comment]
Good morning,

I apologize for not being clear. 

**To simplify things:**
If I want to allow the user to search for colors from a ColorsCollection, I can search the colors collection and bring back a cursor with the results (I have done this already per your documentation). 

**ColorsCollection Schema:**
* projectId: Number,
* colorName: String,

(searching through colors allows me to display search results with colorName and projectId.)

How do I also display the projectName within the same ColorsCollection search results? Is there a way I can use the projectId (from the ColorsCollection) to do a Meteor.Find on a separate ProjectCollection that holds the projectName data?

**ProjectCollection Schema:**
* projectId: Number,
* projectName: String

**The end result I'm looking to achieve:**
* User searches ColorsCollection for a specific colorName.
* Search results brings back colorName and projectName

**Comment by matteodem** [comment]
Relationships are not handled within Easy-Search right now. You can use one of these packages though to get this functionality: https://atmospherejs.com/?q=relation
