### ISSUE TITLE
Fix sorting by date

### ISSUE THREAD

**Issue by ganySA** [matteodem/meteor-easy-search#165]
I am trying to sort by dateCreated field having read the documentation i am struggling a bit to understand how i would go about doing this. 

In the docs it mentions using sort specifiers i am just not sure how i would go from the below to applying the sort specifier?

     'sort': function (searchString) {
		var sort = EasySearch.getSearcher(this.use).defaultSort();

      // return [dateCreated,-1] ??
      }

**Comment by matteodem** [comment]
you should be able to return a sort specifier as defined here: http://docs.meteor.com/#/full/sortspecifiers

**Comment by ganySA** [comment]
Hi

I have tried that as per the documentation as follows:


	'sort': function (searchString) {
		var sort = EasySearch.getSearcher(this.use).defaultSort();


		return [["dateCreated", "desc"]];
	}

This does not seem to work. throws no errors etc.

**Comment by matteodem** [comment]
Do you have a reproduction repository for it?

**Comment by ganySA** [comment]
i do not have one. will need to set something up.

**Comment by matteodem** [comment]
Have a look at https://github.com/matteodem/easy-search-leaderboard/blob/master/leaderboard.js#L189 to see a working example.

**Comment by ganySA** [comment]
Hi matt

Thanks for taking the time on this. I see you re-opened this, just want to check with you does that mean it is a bug? or i am doing something wrong.

Thanks a lot.

**Comment by matteodem** [comment]
It means that I probably would've closed it if it works over there. I'll let it open as long as I don't have a repro for it.

**Comment by ganySA** [comment]
Hi matt

I have managed to isolate the problem down to mongodb date fields.

The sort functions as per the above works 100% for fields that are not date/time fields. The minute you try sort by a mongo date field, things go wrong.

Thanks

**Comment by matteodem** [comment]
okay, does updating help? You are using Elastic-Search then right?

**Comment by ganySA** [comment]
No i am not using elastic search.... my init code is as follows:

    EasySearch.createSearchIndex('listings', {
	field: ['orgName', 'title', 'category', 'subcategory', 'dateCreated'],
	collection: Listings,
	transform: function (doc) {
		doc.image = doc.images[0].path;
	},
	sort: function()
	{
		return { 'dateCreated': -1 };
	},
	query: function (searchString) {
		// Default query that will be used for searching
		var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);

		return query;
	}
});

**Comment by matteodem** [comment]
I have added logic which doesn't stringify date objects anymore, please test this again.

**Comment by ganySA** [comment]
looking good so far thanks a lot for the fix :+1:
