### ISSUE TITLE
Collection helpers does not work

### ISSUE THREAD

**Issue by meteorjs3000** [matteodem/meteor-easy-search#166]
I've been using `dburles:collection-helpers` package so that my meteor collection can have something like

	Books = new Mongo.Collection('books');
	Authors = new Mongo.Collection('authors');

	Books.helpers({
	  author: function() {
	    return Authors.findOne(this.authorId);
	  }
	});

However after I switch to using `easy-search` the helpers dont seem to return anything.

    {{#each books}}
        {{name}} by {{author.name}}
    {{/each}}

will only return the book's name but not the author's. How can we get collection helpers working again?

**Comment by matteodem** [comment]
Please give me a reproduction repo for it

**Comment by dannychua** [comment]
@matteodem I am experiencing a similar issue and took the liberty to create [a repo here](https://github.com/dannychua/easysearch-collectionhelpers)

**Comment by meteorjs3000** [comment]
Hey @dannychua,

Thank you so much, thats exactly what we need!

**Comment by matteodem** [comment]
Please update to the latest version and test the feature
