### ISSUE TITLE
The new mongodb text indexes - support finds only results for complete words

### ISSUE THREAD

**Issue by DanielDornhardt** [matteodem/meteor-easy-search#167]
Hi, from the Mongodb reference (http://docs.mongodb.org/manual/reference/operator/query/text/#match-operation):

> The $text operator matches on the complete stemmed word. So if a document field contains the word blueberry, a search on the term blue will not match. However, blueberry or blueberries will match.

The defaultSearch of the mongodb search engine was just changed to use this:

https://github.com/matteodem/meteor-easy-search/commit/de97d3017b7b7d29203980ef5e24f4a12336605f

- Which is nice I guess, but it changes the results returned for incompletely entered words in the search (namely to "nothing found" until the entire word, if there are matches at all, is entered).

So that's a big change in "perceived" reactivity, in that the users don't immediately see results as soon as they start typing. Also the "autosuggest" - field doesn't really live up to its name anymore, I think.

So I think it might be a good alternative query (actually, are there some alternative search strategies for simply pluggin into initEasySearch in EasySearch already?), but not a great replacement out of the box.

Also, the addition of the full text index to the users' database without prior notice doesn't seem to be optimal either.

Anyways, great package, thank you all a lot, but I just wanted to let you know what I just found out.

**Comment by DanielDornhardt** [comment]
I created a quick gist of  the query: search callback from the old version:

https://gist.github.com/DanielDornhardt/c3f4195bed9afacc2ddf

Which should work as the default search did, I think - It doesn't supply the "regexCallback" - functionality, but it works for me as a quick fix.

**Comment by matteodem** [comment]
I will change it back to be default without any text indexes and have a property called, ```useTextIndexes``` when creating the search index to enable it.

**Comment by DanielDornhardt** [comment]
Thanks for all the effort with EasySearch. It's working well for me, even though there have been some points where I had to adapt it for my use. Great work.

**Comment by Miggz** [comment]
Thanks so much for this guys.  Daniel, I'm using your temp fix for now and looking forward to having useTextIndexes.  

Love this package.

**Comment by matteodem** [comment]
Please update to the latest version of Easy-Search.
