### ISSUE TITLE
Searching bug

### ISSUE THREAD

**Issue by ganySA** [matteodem/meteor-easy-search#168]
Hi Matt

Quick question / test scenario for a potential bug. 

I am encountering a small bug, which i seem to have isolated to the following test case.

If you have an esInput and you enter a search into it, then clear the search and re-enter the exact same search the ifEsIsSearching shows permanently and the esEach never displays.

e.g. enter hello
then clear hello (highlight with mouse then backspace)
then re-enter hello

It seems that if the search is the same as the previous esEach/ifEsIsSearching doesnt actually populate. The ifEsIsSearching just spins forever.

Thanks
~g

**Comment by ganySA** [comment]
looking good so far thanks a lot for the fix :+1:

**Comment by matteodem** [comment]
Can you also reproduce it with the leaderboard example https://github.com/matteodem/easy-search-leaderboard?
