### ISSUE TITLE
Allow nested strings as fields for autosuggest

### ISSUE THREAD

**Issue by yanndebelgique** [matteodem/meteor-easy-search#169]
Hi my collection has the following form :
```
{
 foo : {
   bar : 'hello world'
  }
} 
```
How can I search for foo.bar ? I want autosuggest to return the value of foo.bar 
Is this possible with your package?

**Comment by matteodem** [comment]
"foo.bar" should work, but as of now it'll only work with minimongo. If you want to have it with mongo-db you need to use the code snippet that is provided in #167

**Comment by yanndebelgique** [comment]
thanks for the pointer but does not help :-(
I used the query function given in the code snippet.

I think the problem is here :
  'field': ['view.message','view.subheader','ruleId'],
If I ask for 'view.message' I get the error. If I put ruleId in front like so 

  'field': ['ruleId','view.message','view.subheader']

Then I don't get the error 
but then I get the following result which is not what I want : 

https://www.dropbox.com/s/36tlnkkhv7qg84a/Screenshot%202015-03-30%2011.43.41.png?dl=0

It returns the ruleId but this is not what I want. I want to show the value of 'view.header' in the suggestion box. Also the data context of the suggestion template does not allow me to access the suggested documents. 

Here is my code : 

## my search index

```
EasySearch.createSearchIndex('insightsAutosuggest', {
  'collection': Insights,
  use : 'mongo-db',
  'field': ['view.message','view.subheader','ruleId'],
  transform: function (doc) {
    doc.message = doc.view.message;
  },
  'convertNumbers': true,
    query: function(searchString) {
    var field, selector, stringSelector;
    selector = {};
    field = this.field;
    stringSelector = {
      '$regex': '.*' + searchString + '.*',
      '$options': 'i'
    };
    if (_.isString(field)) {
      selector[field] = stringSelector;
      return selector;
    }
    if (this.convertNumbers && parseInt(searchString, 10) === searchString) {
      searchString = parseInt(searchString, 10);
    }
    selector['$or'] = [];
    _.each(field, function(fieldString) {
      var orSelector;
      orSelector = {};
      if (_.isString(searchString)) {
        orSelector[fieldString] = stringSelector;
      } else if (_.isNumber(searchString)) {
        orSelector[fieldString] = searchString;
      }
      return selector['$or'].push(orSelector);
    });
    return selector;
  }
});
```


##my templates

```
<template name="InsightSearch">
  <div class="row">
    <div class="col s12 m6 offset-m3 l4 offset-l4">
      <div class="card">
        <div class="card-content">

            {{> esAutosuggest index="insightsAutosuggest" id="autosuggest"  renderSuggestion="suggestion" renderValue="autosuggestValues" }}

        </div>
      </div>
    </div>
  </div>
</template>

<!--<template name="suggestionTpl">-->
  <!--&lt;!&ndash; Default way of ES rendering the suggestions &ndash;&gt;-->
    <!--{{pre}}<span class="found">{{found}}</span>{{post}}-->
  <!--&lt;!&ndash; "doc" gives access to the suggested document &ndash;&gt;-->
    <!--{{doc.view.header}}-->
<!--</template>-->



<template name="autosuggestValues">
    <span class="value">
        <a href="#" class="remove">X</a>
        {{value}}
    </span>
</template>

<template name="suggestion">
    {{this}} {{pre}}<span class="found">{{found}}</span>
</template>

```

**Comment by matteodem** [comment]
As a temporary solution I'd propose you have a special field for the autosuggest field, which is not nested.

**Comment by matteodem** [comment]
This is now fixed as of v2, it uses lodashes `get` method to retrieve nested string values, see https://github.com/matteodem/meteor-easy-search/tree/master/packages/easysearch:autosuggest
