### ISSUE TITLE
Nested fields

### ISSUE THREAD

**Issue by mads397** [matteodem/meteor-easy-search#17]
It seems like it's not possible to use nested fields (e.g. profile.name) when creating an index with EasySearch.createSearchIndex(). Can anybody confirm this?

**Comment by elGusto** [comment]
I believe there's still an issue about this ? The snippets helper of the esAutosuggest template uses 

     this[firstField]

This causes an exception when declaring the nested index fields (I only tested using minimongo) using the dot notation.
