### ISSUE TITLE
componentInstance.get('total') - receiving results from searches in other windows?

### ISSUE THREAD

**Issue by DanielDornhardt** [matteodem/meteor-easy-search#170]
Hi, i'm probably doing something wrong, but I don't know what exactly.

I'd like to display the count of a search from my db. Whenever I try to fetch the count in one template helper, it is current at first, but when i do another search from a different window, the value gets updated to the same number of results in both windows.

I'd like to have individual numbers of results for each window.

I created a MeteorPad from the Leaderboard Example here: http://meteorpad.com/pad/mbpQaYPMG2ZZSEP9n/Leaderboard

And added a "X results found" - display beneath the table of found players.

See from line 56 of main.html:

        {{#if numResults}}
          <div>{{numResults}} results found.</div>
        {{else}}
          <div>No results found</div>
        {{/if}}

And from line 58 of common.js:

    numResults: function() {
      return EasySearch.getComponentInstance({id: 'search', index: 'players'}).get('total');

- what am I missing? Do I have to add another key / index to getComponentInstance? Or is getComponentInstance the wrong way to go anyways?

Thanks and best wishes

Daniel

**Comment by matteodem** [comment]
Hello Daniel

I'm not sure if this behaviour has anything to do with Easy-Search, since it only uses collections to count documents. I'll have a closer look at this though in the next days.

**Comment by matteodem** [comment]
This is related to #245
