### ISSUE TITLE
Limit count of pages shown in pagination

### ISSUE THREAD

**Issue by soniya90** [matteodem/meteor-easy-search#171]
I have more than 50000 of records. and pagination is working properly. But this tool displaying all the pages instead of showing starting few pages from the searched page. Page limit is set to 20.
so Pagination shows like 'Prev 1 2 3 4 5 6 7 8 upto 2500 Next '. 
What m i missing?

**Comment by niranjans** [comment]
+1

**Comment by centinel3** [comment]
+1

**Comment by matteodem** [comment]
This is now resolved as of v2, see the `maxPages` attribute for the `EasySearch.Pagination` component http://matteodem.github.io/meteor-easy-search/docs/components/.
