### ISSUE TITLE
Using Meteor.user() in query function

### ISSUE THREAD

**Issue by stephenfairchild** [matteodem/meteor-easy-search#172]
I've seen your example where query accept an options argument, but I still can't this to work. Where do I pass in the options at? I want to use query like this: 

           EasySearch.createSearchIndex('items', {
            'collection': Items,
            'field': ["details","createdAt"],
            'limit': 25,
            'use' : 'mongo-db',
            'sort': function() {
                return {createdAt: -1};
            },
            'query': function () {
              return {username: Meteor.user().username };
            }

          });

**Comment by fermuch** [comment]
You have to use [EasySearch.changeProperty](http://matteodem.github.io/meteor-easy-search/docs/javascript-api/)

So you set it like this:
(client)
```javascript
EasySearch.changeProperty('item', 'userId', Meteor.userId())
```

And, when you create the index:
```javascript
EasySearch.createSearchIndex('items', {
        'collection': Items,
        'field': ["details","createdAt"],
        'limit': 25,
        'use' : 'mongo-db',
        'sort': function() {
            return {createdAt: -1};
        },
        'query': function () {
          return {username: Meteor.users.find(opts.props.userId).username };
        }
      });
```

**Comment by stephenfairchild** [comment]
Thanks for your help. I've implemented your example and `opts` is undefined.

**Comment by fermuch** [comment]
the thirst argument to changeProperty should be the same as the search index name.
Also, the query function has two arguments: searchString and opts. Forgot to add that.

I'm fixing the example.

**Comment by matteodem** [comment]
I also changed the example to be ```this.props``` instead of ```opts.props```

**Comment by stephenfairchild** [comment]
No errors, but it's still not returning any records. I can hardcode a username in the query function and get results. I've implemented your example exactly as you have it. 

        // in client and server
        Items = new Mongo.Collection("items");

        EasySearch.createSearchIndex('items', {
          'collection': Items,
          'field': ["details","createdAt"],
          'limit': 25,
          'use' : 'mongo-db',
          'sort': function() {
            return {createdAt: -1};
          },
          'query': function (searchString, opts) {
            return {username: Meteor.users.find(this.props.userId).username };
          }
        });

        //in client
        Template.history.created = function () {
          EasySearch.changeProperty('items', 'userId', Meteor.userId());
        };

**Comment by matteodem** [comment]
okay, so there's a publishScope property on the opts, please use that to access the current user:

```javascript
'query': function (searchString, opts) {
  return {username: Meteor.users.find(opts.publishScope.userId).username };
}
```

**Comment by stephenfairchild** [comment]
Well, that doesn't work either. Same results....

**Comment by fermuch** [comment]
Silly question, but, are you checking if the user is logged in? ```Meteor.userId()``` returns null if not.

**Comment by stephenfairchild** [comment]
Yes of course. I can log `Meteor.userId()` to the console and it prints out the user id, that matches the username of the user in the database with records

        Template.history.rendered = function () {
          EasySearch.changeProperty('items', 'userId', Meteor.userId());
          console.log(Meteor.userId());
        };

**Comment by fermuch** [comment]
I created a [Pad](http://meteorpad.com/pad/Y8wmNBj65ZRNSRn9d/easy-search%20with%20Meteor.userId()) to help you debug the problem. It is very basic and doesn't do anything actually, but it shows the correct behavior of chageProperty.

Register and filter the users with some string. You'll see in the shell something like:
```UserID:  aofdH9kTqBxPr6Y42```


Hope this helps!

**Comment by stephenfairchild** [comment]
Thanks for all of your help. I finally got it working. To be honest, I still have no clue what the issue was. The code looked the same as mine, so I updated Meteor along with all of my packages and then just wrote the code over again (creating the index and template helpers, etc.) So I guess it could have been an outdated package issue or typo somewhere. Thanks again!

**Comment by matteodem** [comment]
Thanks for the help on this one @fermuch
