### ISSUE TITLE
ElasticSearch search not the same sort on the server and on the client

### ISSUE THREAD

**Issue by fermuch** [matteodem/meteor-easy-search#173]
If I write a query like this:

```json
{"query":{"filtered":{"query":{"fuzzy_like_this":{"fields":["name","description"],"like_text":"foo"}}}},"sort":["_score","name"]}
```

On the project, I'm using the same structure with ```query``` and ```sort```.

ElasticSearch returns me in this order:

```javascript
"foobar" (score: 1.0493062)
"barFoo" (score: 0.8695872)
"lorem ipsum foobar" (score: 0.15528342)
```
It is also well sorted when I run the query manually on the server and even in the client, but when I display the results with {{>esEach}}, the order is:

```javascript
"barFoo"
"lorem ipsum foobar"
"foobar"
```

This not only breaks the _score given by ElasticSearch, but also makes a mess when using pagination.

**Comment by fermuch** [comment]
I see the problem is in [easy-search-components.js](https://github.com/matteodem/meteor-easy-search/blob/master/lib/components/easy-search-components.js), since it's trying to sort by mini-mongo's or mongodb's registered sorter (which is the "sort" property).

Maybe a custom client-side sort function for minimongo should be added when using elasticsearch, since elasticsearch sorts are not compatible with the client db?

**Comment by ganySA** [comment]
@fermuch great suggestion this would be fantastic and would also resolve the date sort problem i have.

**Comment by fermuch** [comment]
@ganySA as a temporal fix, if you disable reactivity (reactive: false) it is displayed just as the server gets it.

**Comment by ganySA** [comment]
Great, thanks for the workaround!

**Comment by matteodem** [comment]
You should be able to set ```reactiveSort``` to handle client side sorting. I still have to document it though

**Comment by matteodem** [comment]
Please tell me if that works

**Comment by fermuch** [comment]
It doesn't, since I need elasticsearch's _score in the client to do the same sort. Some way to disable client sorting and display it just as the server sends it would be the proper solution IMO.

Or check if reactiveSort is set to false, to disable client side sorting?

**Comment by fermuch** [comment]
I'm happy to say it is now working as expected, and I'm not using ```reactive: false``` anymore. :+1:

**Comment by matteodem** [comment]
This is a really weird error, since observeChanges shouldn't change the order of the documents that are observed. Anyways, thanks for finding that one

**Comment by talalav** [comment]
I have the same problem. My elasticsearch query is: 
{
  "query": { "match": { "title": "xxxx yyyy } },
  "sort": { "_score": { "order": "asc" } }
}
The sort is not the same.
I'm using the 2.0.9 version of your package.
