### ISSUE TITLE
Autosuggest typo

### ISSUE THREAD

**Issue by 2016rshah** [matteodem/meteor-easy-search#175]
If I'm not mistaken, there is an extra closing parentheses in the auto-suggest docs:

<pre>
// Only client
Template.playersOverview.created = function () {
  // set up reactive computation
  this.autorun(function () {
    var instance = EasySearch.getComponentInstance(
        { index : 'players' }
    );

    instance.on('autosuggestSelected', function (values) {
      // run every time the autosuggest selection changes
    });
  });
});
</pre>

should be 

<pre>
// Only client
Template.playersOverview.created = function () {
  // set up reactive computation
  this.autorun(function () {
    var instance = EasySearch.getComponentInstance(
        { index : 'players' }
    );

    instance.on('autosuggestSelected', function (values) {
      // run every time the autosuggest selection changes
    });
  });
};
</pre>

**Comment by matteodem** [comment]
Changed it to be onCreated, thanks! http://matteodem.github.io/meteor-easy-search/docs/autosuggest-field/
