### ISSUE TITLE
Search Array

### ISSUE THREAD

**Issue by sangyoo91** [matteodem/meteor-easy-search#177]
Sorry for the newbie question..

I have a collection that stores data as the following.
```
Title: (string)
Content: (string)
Tags: (Array)
    [0] (string)
    [1] (string)
    [2] (string)
    ..So on
Author: (string)
```

I want my search to return the tags as well but I'm so lost.

I tried to write my query but I think I'm very very wrong...

Please guide me in the right direction!

```
'query' : function(searchString) {
	var  query = { "content": searchString, "title": searchString, "user": searchString, "title": {$inc[searchString]},	};            	
	return query;                                                                                                            
},
```

**Comment by matteodem** [comment]
What do you mean by "return the tags as well"? By default, Easy-Search returns all fields of the documents.

**Comment by sangyoo91** [comment]
@matteodem My tags are stored in an array as strings. Idk why but it won't return my tags. Let's say for example, I have a document as follow
```
title : javascript
content: blablabla
tags :
  [0] : meteor
  [1] : jquery
```

It won't return the above if I search for meteor or jquery. It will only return if I search javascript or blablabla

**Comment by sangyoo91** [comment]
@matteodem Actually I just tried and it won't return the content as well. It will only be searchable by title and author. this is my settings for easy search.

```
//search
EasySearch.createSearchIndex('posts', {
	'use' : 'mongo-db',
	'reactive': true,
	'field' : ['tags', 'title', 'author', 'content'],  // required, searchable field(s)
	'collection' : Posts,      // required, Mongo Collection
	'limit' : 10,    // not required, default is 10
	'sort': function() {
		return {'votes': -1, 'submitted': -1};
	}
});
```

**Comment by sangyoo91** [comment]
@matteodem 

https://gist.github.com/DanielDornhardt/c3f4195bed9afacc2ddf

I added this to my query to figure this problem. But I have no idea why this fixed this.

**Comment by matteodem** [comment]
Please update to the latest version, this should fix it.
