### ISSUE TITLE
'?q=' Query in router

### ISSUE THREAD

**Issue by sangyoo91** [matteodem/meteor-easy-search#178]
Is it possible to use easy-search to show queries in the router?

I have a search rendered in an overlay template and I'd like to show the query to the route like in atmosphere js

**Comment by matteodem** [comment]
This could be possible with the component search method: http://matteodem.github.io/meteor-easy-search/docs/component-api/

**Comment by adriamooney** [comment]
@sangyoo91 did you get this to work?  I'm trying to do the same thing.  If you can provide an example that would be great!
