### ISSUE TITLE
Searching multiple strings

### ISSUE THREAD

**Issue by sangyoo91** [matteodem/meteor-easy-search#180]
Hello. I am trying to search for multiple strings at the same time.

In my document for example, I have the following
```
Post1
  Tags:
    [0]: "meteor"
    [1]: "javascript"
```

```
Post2
  Tags:
    [0]: "meteor"
    [1]: "jquery"
```

I want my search to return both post1 and post2 if I type `meteor javascript`. But as of now, both posts will not return. It will return correspondingly if I type each items seperately. E.g., If I type meteor, I will get both post1 and 2. If I type javascript, it will return post1. If I type jquery, it will return post 2.

**Comment by matteodem** [comment]
You can now use text indexes with the ```mongo-db``` engine, see: http://matteodem.github.io/meteor-easy-search/docs/javascript-api/. That should work, since it uses text analysis for querying the fields.
