### ISSUE TITLE
Question: on how searchingDone works and "on" events

### ISSUE THREAD

**Issue by ganySA** [matteodem/meteor-easy-search#181]
Hi

I am trying to understand how events work for easy search. 

Firstly i would like to know if searchingDone fires per record or once?

Secondly, I would like to set the search completed function differently on different templates. so i have placed this code within the **rendered** template function however this simply keeps adding more and more events. e.g
    
    Template.rendered = function() {
           console.log('fired');
           instance = EasySearch.getComponentInstance({ id: 'searchquery', index: 'listings' });
           instance.on('searchingDone',function(){ //my code}}
     }

Is there any ways to clear the on events so i can re-init them on a per template basis e.g

Thanks

**Comment by matteodem** [comment]
searchingDone fires when the search process is finished, so once for all the records being returned.

What does "adding more and more events" mean? What is the actual problem of using one of the Blaze Components?

**Comment by ganySA** [comment]
I want to run some code when a search is completed. If you place the below code to the on rendered then for every time you go back to the template it will add another searchDone event. Keeps attaching events, its not a problem with easy search but is there a way to "clear" all the events from EasySearch?

instance.on('searchingDone',function(){ //my code}}

**Comment by matteodem** [comment]
yes, so there's actually a way to attach the autorun of the template instance to the getComponentInstance method, like this: 

```javascript
Template.rendered = function() {
  var instance = EasySearch
    .getComponentInstance(
      { id: 'searchquery', index: 'listings', autorun: this.autorun }
    )
    .on('searchingDone',function(){ //my code}}
 }
```

I'll add this to the docs. Feel free to comment if there are any other questions
