### ISSUE TITLE
Ability to change the `type` of esInput

### ISSUE THREAD

**Issue by AlexFrazer** [matteodem/meteor-easy-search#182]
I am using [Ionic Framework, which has a specific type for "phone number"](http://ionicframework.com/html5-input-types/#tel). Is it possible to change the `type` attribute of the esInput?

Would also be nice to add data attributes if possible

**Comment by matteodem** [comment]
You can now add a custom ```type``` property to esInput: http://matteodem.github.io/meteor-easy-search/docs/blaze-components/. Please create a new ticket for data attributes, with a use case for them.
