### ISSUE TITLE
Support for textScore with mongodb index

### ISSUE THREAD

**Issue by lowi** [matteodem/meteor-easy-search#183]
Are you planing to add support for textScore with the mongodb text index?

At the moment, the results are not sorted by score relevancy, and it would be necessary to add the textScore to the projection as described here:
http://docs.mongodb.org/manual/reference/operator/projection/meta/

db.articles.find(
   { status: "A", $text: { $search: "coffee cake" } },
   { score: { $meta: "textScore" } }
).sort( { date: 1, score: { $meta: "textScore" } } )

**Comment by matteodem** [comment]
It's not implemented yet, PR's are welcome.

**Comment by matteodem** [comment]
I'll close this as score is not yet listed as a valid option for the ```find``` method: http://docs.meteor.com/#/full/find.

**Comment by matteodem** [comment]
related to #187, might be interesting to have a look at it.

**Comment by kyooriouskoala** [comment]
+1

**Comment by vuhpham** [comment]
+`

**Comment by latitudehopper** [comment]
+1

**Comment by matteodem** [comment]
This is supported in the last version __1.6.0__, see docs http://matteodem.github.io/meteor-easy-search/docs/recipes/

**Comment by Neftedollar** [comment]
is $meta is supported at 2.0 version?

**Comment by matteodem** [comment]
yes, just use the several configurations together with what's stated in the mongodb docs to accomplish it https://docs.mongodb.org/v3.0/reference/operator/projection/meta/

**Comment by Neftedollar** [comment]
can you provide example with it? I've tryed to add score field, but i've catch couple of errors
