### ISSUE TITLE
Is it possible to change number of results in pagination?

### ISSUE THREAD

**Issue by AlexFrazer** [matteodem/meteor-easy-search#184]
Here's some code I have:
```
Template.orderList.onRendered(function() {
  var itemHeight = $(this.find('.order-list > a.item')).outerHeight();
  var containerHeight = $(this.find('.order-list')).innerHeight();
  var perPage = Math.round(containerHeight / itemHeight);
});
```

`perPage` on my laptop is 16. I want to say, each page is 16 items. Does there exist a way to change the number of results shown, even when there is nothing in the search bar?

**Comment by AlexFrazer** [comment]
I think I found a solution, but it seems a little sleight of hand.

```
var instance = EasySearch.getComponentInstance({ index: "orders" });
EasySearch.changeLimit('orders', perPage);
instance.triggerSearch();
```
Seems the "trigger search" is necessary afterwards.

**Comment by matteodem** [comment]
feel free to create a new issues for other questions!
