### ISSUE TITLE
Problem with MongoDB search

### ISSUE THREAD

**Issue by smoiz** [matteodem/meteor-easy-search#186]
Great product, however since updating to the latest Meteor from 1.0 I have encountered a problem.

My config:
```javascript
Cards.initEasySearch('name', {
    'limit' : 15,
    'use': 'mongo-db' // speeds up since client doesn't need entire db.
});
```

Error log:
```
(/meteor/containers/59356dbe-49ba-2e8a-d92a-9b4bc060f5dc/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
at [object Object].emit (events.js:95:17)
[Tue Apr 07 2015 19:45:19 GMT+0000 (UTC)] INFO Exception from sub cards/easySearch id z8Kf46DgKfqJWzaYw MongoError: invalid
operator: $search
at Object.Future.wait (/meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:398:15)
at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:929:1)
at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:963:1)
at [object Object]._.extend.map (packages/mongo/mongo_driver.js:973:1)
at [object Object]._.extend.fetch (packages/mongo/mongo_driver.js:997:1)
at [object Object].Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:812:1)
at Object.methods.search (packages/matteodem:easy-search/lib/searchers/mongo.js:66:1)
at [object Object]._handler (packages/matteodem:easy-search/lib/easy-search-common.js:73:1)
at packages/check/match.js:109:1
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```

The program runs on Meteors own servers. It seems that the operator $search is invalid according to log.
Before the update to the latest Meteor & Mongo I had no such problems.

**Comment by phinmpofu** [comment]
Seconding this as I am experiencing the exact same error. 

@smoiz are you using an external mongoDB by any chance? I am using a Sandbox from Compose.io and thought it may have to do with that.

**Comment by matteodem** [comment]
Looks like the $search operator is not supported. I also upgrade the leaderboard to the latest version and it works.

Can you please give me the Meteor version + MongoDB and what your configuration looks like with an example document off the collection.

**Comment by phinmpofu** [comment]
In my case:
Meteor Version: 1.1.0.2
MongoDB: v2.4.10 (Sandbox from Compose.io)

using the Sandbox mongoDB when publishing       MONGO_URL='mongodb://USERNAME:PW@kahana.mongohq.com:10048/DBNAME' meteor 

Config:
    /collections

    Properties = new Mongo.Collection('propertyDetails');
    EasySearch.createSearchIndex('propertyDetails', {
    'collection': Properties,
    'field': 'Postcode', //field to search through
    'use':  'mongo-db'
    'limit': 10,
    'query': function (searchString, opts) {
    var query = EasySearch.getSearcher(this.use).defaultQuery(this, '^'+searchString);
    return query;
      }
    });

I also have a publication file in my Server folder to limit the number of collections sent to the client on load. The collection has 100,000 docs. 

    Meteor.publish('propertyDetails', function() {
    Counts.publish(this, 'propertyDetailsCount', Properties.find(), {nonReactive: true});
    return Properties.find({}, {limit: 10});
    });

Document example:
    {
     "id": ObjectId("xxxxxxxxxxxx"),
     "postcodeDistrict": "BR1",
     "postcode": "BR1 1AB",
     "city": "Bromley",
     "streetName": "East Street",
     "addressLine1": "Apartment 1",
     "addressLine2": "The Old Post Office",
     "propertyID": "NumberLong(52405291)",
     "mainImage": "../img/no-interior-images.jpg",
    }

**Comment by smoiz** [comment]
@phinmpofu: I am using the Meteor free servers (using deploy command). As far as I know they don't use external MongoDB.

@matteodem: Meteor version: 1.1.0.2, Mongo: 2.6.7.

Example document:
```json
{ "name" : "Admonitions, The", "text" : "Unique master.\nPut this card in play. Tap to discard one card if you control a ready Sabbat vampire. Tap to draw two cards if you control a ready Black Hand vampire. During your discard phase, control of The Admonitions passes counter-clockwise until it is controlled by a Methuselah who controls a ready Sabbat vampire (or is burned if there are none).",
 "requirement" : "",
 "clan" : "",
 "discipline" : "",
 "bloodCost" : "", 
"poolCost" : "", 
"set" : "BH:U, Third:U",
 "banned" : "", 
"type" : "Master", 
"cardId" : "20",
 "cardType" : "lib",
 "_id" : "KbYDZLbp6mbwqHW4c" 
}
```
I use easy-search to search by name.

**Comment by matteodem** [comment]
Please update to the latest version.

**Comment by smoiz** [comment]
Updated to the latest version and tested. Everything seems to be working fine. Great job!
