### ISSUE TITLE
Question about mongodb fulltext search ranking

### ISSUE THREAD

**Issue by vuhpham** [matteodem/meteor-easy-search#187]
![screen shot 2015-04-13 at 15 05 23](https://cloud.githubusercontent.com/assets/6336436/7126524/b3d669aa-e1ee-11e4-85c2-ab3e17ed4cfb.png)

Hi all, I wanted to implement ranking for search. As you can see in the picture, Stephen Lovelance should be the first result since it has 2 keywords are matched. Any idea?

**Comment by niranjans** [comment]
+1. Would like to know the solution to this too.

**Comment by niranjans** [comment]
@vuhpham Could you manage to solve this? I'm just curious to know how to go about this.

**Comment by vuhpham** [comment]
@niranjans I'm still investigating. If you have any idea, feel free to raise :)

**Comment by niranjans** [comment]
Sure. I actually posted this on the forum too but didn't get a reply. From what I've read, I think this can be done by the [`$text`] (http://docs.mongodb.org/manual/reference/operator/query/text/) search feature of MongoDB which returns a relevance score (which can be used for sorting).

However, do make sure to look at the behavior section before going that route. I think it will suite you in your situation. 
I actually need to have a little more complex search with `$near` Geospatial filters and other goodies so I will probably have to go with ElasticSearch.

**Comment by vuhpham** [comment]
Thanks @niranjans I might also go with ElasticSearch as well since my app is growing with big content.

**Comment by matteodem** [comment]
Sorry for not responding. I'm pretty sure we could solve that by using textScore http://docs.mongodb.org/manual/reference/operator/projection/meta/. I'll try it out in the next days.

**Comment by matteodem** [comment]
See referenced issue
