### ISSUE TITLE
Add SearchBlox support

### ISSUE THREAD

**Issue by searchblox** [matteodem/meteor-easy-search#188]
We would like to get support added for SearchBlox which is based on Elasticsearch 
You can find the request/response parameters in the SearchBlox Wiki https://searchblox.atlassian.net/wiki/display/SD/Search+Parameters+and+Response

**Comment by matteodem** [comment]
Please feel free to add an integration whenever you have time. The elasticsearch integration will give you an idea of how it's achievable.
