### ISSUE TITLE
remove empty array from top during sort

### ISSUE THREAD

**Issue by thomasspiesser** [matteodem/meteor-easy-search#189]
hey @matteodem,
first of all, thanks for the great search package. I really like using it!

I have a question, I have something like an events collection including a dates array like so

    {
    _id: 123,
    dates: [
    date1, date2
    ]
    }

I would like to sort the events according to the next occurring date, which is no problem with 

    'sort': function () {
      return { 'dates': 1 };
    }

However, like that and thanks to mongos comparing function, the top most events are those with no date at all, cause apparently an empty array is smaller than smallest date. Do you have any idea how to work around this? Can I post-process the results I get back from your search? Where would I do that? Any hint in the right direction would be ever so much appreciated. Thanks!

**Comment by matteodem** [comment]
I think the best solution would be to extend your selector with the ```query``` option:
http://matteodem.github.io/meteor-easy-search/docs/javascript-api/. You want to use the ```$size``` mongodb selector: http://docs.mongodb.org/manual/reference/operator/query/size/.

**Comment by thomasspiesser** [comment]
thanks for the answer @matteodem! i could of course as you suggest `query` for events with a `$size` of `dates` array greater 0 or something. the problem is though, i need all events, even if they don't have a date at the moment. they should just sort below the ones with date. or do you mean, i should query twice, like a pre-selection?

**Comment by matteodem** [comment]
Oh, I totally missunderstood it. Do you want to append the documents without a date?

**Comment by thomasspiesser** [comment]
sorry for being unclear. 
i want the user to be able to browse all events (so the indexed collection is `events` and the query is on that collection, e.g. return all `events` that have a tag `party`). so far so good. 

Now, I would like for the user to see the event with the date closest to today on top, staying with the `parties` example, he/she should see the next occurring party first, not the one in, i don't know, 8 weeks. Hence my attempt to `sort` them according to `date`. 

Problem is though: events that are not scheduled for any reason (e.g. event exists in collection but owner did not fix a date yet) show up first, since the `dates` array is empty. I want them to show up last.

what i want:

    {_id: 1, tag: "party", dates: [30.4.2015, 2.5.2015], ..., }
    {_id: 2, tag: "party", dates: [1.1.2016], ..., }
    {_id: 3, tag: "party", dates: [], ..., }

what i get when i `sort` with `dates: 1`:

    {_id: 3, tag: "party", dates: [], ..., }
    {_id: 1, tag: "party", dates: [30.4.2015, 2.5.2015], ..., }
    {_id: 1, tag: "party", dates: [1.1.2016], ..., }

And i can't figure out how to fix this...
Hope I was clearer this time.

**Comment by matteodem** [comment]
Then I would:

1. add a __hasDate__ field to your documents, that is a boolean value (true if dates array is not empty)
2. Set the hasDate value on inserts and updates based on the dates array

**Comment by matteodem** [comment]
Feel free to comment if there are any further questions.

**Comment by thomasspiesser** [comment]
that seems easy enough, thanks a million!
