### ISSUE TITLE
Set elasticsearch analyzers

### ISSUE THREAD

**Issue by fermuch** [matteodem/meteor-easy-search#190]
Is there an easy way to set up elasticsearch analyzers for fields? I can't find any in the docs, and I'm doing it manually with a shell script for now.

For example, I'd like to add the filter ```html_strip``` and the analyzer ```snowball``` with a defined language to a field. Is it possible with the current API?

**Comment by matteodem** [comment]
Not yet, that's a good thing that could be possible to extend. Maybe make the Node Elastic Search wrapper accessible.

**Comment by fermuch** [comment]
Ah, I can fix some workarounds if I get access to EasySearch elastic's instance! :+1:

**Comment by matteodem** [comment]
the Elasticsearch API should be reachable through ```EasySearch.ElasticSearch```. Please try it out

**Comment by matteodem** [comment]
@fermuch do you have any example on how you use the ES Node API right now? I'll consider it when implementing it for v2.

**Comment by matteodem** [comment]
As of v2 ElasticSearch is in a separate package called `easysearch:elasticsearch`. You can specify analyzers through the direct access to the elasticsearch node client, see https://github.com/matteodem/meteor-easy-search/tree/master/packages/easysearch:elasticsearch
