### ISSUE TITLE
Elasticsearch only working via JS API

### ISSUE THREAD

**Issue by nov1n** [matteodem/meteor-easy-search#191]
When using the js below after running:

EasySearch.search('testIndex',  "term", function (err, data) {
  console.log(data)
});

I get ~2500 results. However if I use the blaze components as defined [here](http://matteodem.github.io/meteor-easy-search/docs/blaze-components/) I get none. Anyone able to help? Thanks in advance!

```javascript
EasySearch.config({
    'host': 'localhost:9200'
});

TestCollection = new Meteor.Collection("test");

EasySearch.createSearchIndex('testIndex', {
  'collection': TestCollection, // instanceof Meteor.Collection
  'field': ['name', 'message'], // array of fields to be searchable
  'limit': 10,
  'use' : 'elastic-search',
  'convertNumbers': true,
  'props': {
    'filteredCategory': 'All',
    'sortBy': 'score'
  },
  'sort': function() {
    return ['_score'];
  }
});
```

**Comment by matteodem** [comment]
Please show me your HTML

**Comment by nov1n** [comment]
<div class="card card-input" id="search-card">
    <i class="fa fa-search"></i> {{> esInput index="fbcomments" class="search-bar" placeholder="Search..." }}
</div>

<h4>Results</h4>
<hr>

<div>
    <div class="col-xs-12 search-results">
        {{#esEach index="fbcomments"}}
            {{> commentRow}}
        {{/esEach}}
    </div>
</div>

{{#ifEsHasNoResults index="fbcomments"}}
    <div class="no-results">
        No results
    </div>
{{/ifEsHasNoResults}} 

{{#ifEsIsSearching index="fbcomments"}}
    <div>
        Loading...
    </div>
{{/ifEsIsSearching}}

<div class="more-wrapper">
    {{> esLoadMoreButton index="fbcomments" class="btn btn-default" content="More..."}}
</div>

**Comment by nov1n** [comment]
Here it is
```
<div class="card card-input" id="search-card">
    <i class="fa fa-search"></i> {{> esInput index="testIndex" class="search-bar" placeholder="Search..." }}
</div>

<div>
    <div class="col-xs-12 search-results">
        {{#esEach index="testIndex"}}
            {{> commentRow}}
        {{/esEach}}
    </div>
</div>

{{#ifEsHasNoResults index="testIndex"}}
    <div class="no-results">
        No results
    </div>
{{/ifEsHasNoResults}} 

{{#ifEsIsSearching index="testIndex"}}
    <div>
        Loading...
    </div>
{{/ifEsIsSearching}}

<div class="more-wrapper">
    {{> esLoadMoreButton index="testIndex" class="btn btn-default" content="More..."}}
</div>
```

**Comment by matteodem** [comment]
Try instead of calling ```{{> otherTemplate}}```, adding the content directly inside the __esEach__:

```html
{{#esEach index="testIndex"}}
    <div class="message">{{name}}: {{message}}</div>
{{/esEach}}
```

If that doesn't help, please provide a reproduction repository.

**Comment by nov1n** [comment]
I tried that, along with many other alternatives. I am unsure on how to create a repro since this involves elasticsearch aswell as meteor.

**Comment by matteodem** [comment]
Run ```meteor update``` and if that doesn't help either, please provide a reproduction since it works with the leaderboard example found here: https://github.com/matteodem/easy-search-leaderboard

**Comment by nov1n** [comment]
Hey Matteo,

I made a repro [here](https://github.com/nov1n/easy-search-leaderboard)

Try making an elasticsearch index called players and add 1 document {"name": "foo"}.
Next launch the meteor app and try to type "foo" in the search bar. As you can see the pagination will correctly show 1 page. But no results are shown.

If you run the following in the console it works and 1 document is returned.

```
EasySearch.search('players',  "ro", function (err, data) {
  console.log(data);
});
```

**Comment by matteodem** [comment]
Finally had a look at it. Did you add an ElasticSearch document or MongoDB document? The ElasticSearch index synchronizes mongo-db docs, thus you shouldn't manually insert any ES docs, if that's what you did.

**Comment by nov1n** [comment]
I inserted documents via the regular Meteor Collection API calls.

**Comment by matteodem** [comment]
I tested your repository and it worked. see http://screencast.com/t/pvlRx7o0ac

**Comment by nov1n** [comment]
I have no idea what is causing mine to bug then. I'm using elasticsearch 1.4.2 on windows.

**Comment by matteodem** [comment]
No error in the meteor console and / or browser? You can also see how I inserted the document in the screenshot, if you want to reproduce it.

**Comment by matteodem** [comment]
might have a relation to windows maybe?

**Comment by nov1n** [comment]
Maybe someone on windows could try to reproduce to see if it is just me.. I
don't have time in the near future to investigate and used the JS API
instead of the blaze components for now

**Comment by matteodem** [comment]
Does this problem still exist?
