### ISSUE TITLE
Is it possible to give different weights / sorting preference to specific fields

### ISSUE THREAD

**Issue by niranjans** [matteodem/meteor-easy-search#192]
For the `mongo-db` searcher, if I want a search which gives different weightage to different matched fields, is that possible with this package?  
Like if a text is present in 2 different fields, and based on the weightage, the search result of that text would be more relevant than the other and so would order accordingly. 

For example - I search for the text 'book'. If that word is present in both the `title` field and `description` field, I would like to have the `title` record a higher rating than the other one. Is this possible? 

I know this can be done with ElasticSearch but I am looking for this in MongoDB.

**Comment by matteodem** [comment]
Yes, actually there's a weight property http://docs.mongodb.org/manual/tutorial/control-results-of-text-search/. I'll create a new ticket and close this one.

**Comment by matteodem** [comment]
see #197
