### ISSUE TITLE
EasySearch not working property, but it worked before

### ISSUE THREAD

**Issue by i25959341** [matteodem/meteor-easy-search#193]
I am currently implementing the EasySearch solution for my site and for some reason it s not working anymore, it worked before.

https://github.com/matteodem/meteor-easy-search

During those time, I works mainly on implementing Collectionsfs, changed the field setting for data.

Template code:

   <div class="container">
        {{> esInput index="posts" id="search" placeholder="Search Listing..." convertnumber=true }}
    </div>

     {{#ifEsIsSearching index="posts" id="search" logic="OR" }}
        <div>Searching...</div>
    {{/ifEsIsSearching}}

    {{#ifEsInputIsEmpty index="posts" id="search"}}
          <div class="posts">
            {{#each posts}}
              {{> postItem}}
            {{/each}}
          </div>

          {{else}}

          <div class="posts">
            {{#esEach index="posts" id="search"}}
                {{> postItem}}
            {{/esEach}}
          </div>
    {{/ifEsInputIsEmpty}}

    {{#ifEsHasNoResults index="posts" id="search" logic="OR" }}
        <div class="no-results">No results found!</div>
    {{/ifEsHasNoResults}}

</template>

Mongodb code:

Posts = new Mongo.Collection('posts');

Posts.initEasySearch(['firstName', 'lastName', 'university'], {
    'limit' : 20,
    'use' : 'mongo-db'
});

Posts.allow({
  update: function(userId, post) { return ownsDocument(userId, post); },
  remove: function(userId, post) { return ownsDocument(userId, post); },
});

Meteor.methods({
  postInsert2: function(postAttributes) {
    check(Meteor.userId(), String);
    check(postAttributes, {
      firstName: String,
      lastName: String,
      address: String,
      phone: String,
      university: String,
      loanPeriod: String,
      loanRate: String,
      loanAmount: String,
      job: String
    });
...........

**Comment by matteodem** [comment]
Please update to the latest version and if it still doesn't work hand in a reproduction repository.

**Comment by i25959341** [comment]
thank, the update make it works now .
