### ISSUE TITLE
Does this package also handle data sync between MongoDB and ElasticSearch? 

### ISSUE THREAD

**Issue by niranjans** [matteodem/meteor-easy-search#195]
I looked in the docs but this part was not clear to me (and I am new to ElasticSearch). If going with the ElasticSearch option, does this package also take care of data sync between MongoDB and ES (By Rivers or something else?).

Or does it assume that an ES environment is already setup with data already in the indexes? I think this is more likely but I just wanted to confirm.

**Comment by MaazAli** [comment]
You need to have ES running but the addon will take care of keeping the indexes up to date in ES.

**Comment by niranjans** [comment]
I'm a little confused with how this indexes the documents in ES.
I have an ES cluster on compose.io and have provided the url in the config:
```
EasySearch.config({
    'host' : 'https://<user>:<password>@aws-us-east-1-portal3.dblayer.com:9999/',
});
```

Now, when I use ElasticSearch, I am getting the proper results back but when I check document with that id on the ES cluster itself using curl, it cannot not find it: 
`https://<user>:<password>@aws-us-east-1-portal3.dblayer.com:9999/<index name>/<type name>/<document id>`

```
// The following works in the app. But cannot find the documents on the ES cluster
EasySearch.createSearchIndex('cars', {
	'field' : ['title', 'description'],
	'collection' : Cars,
	'limit' : 30,
	'use' : 'elastic-search',
	'query': function (searchString) {
		return { "term" : { "title" : searchString} };	
	},
	'sort': function () {
	    return ['_score'];
	  }
});
```

**Comment by niranjans** [comment]
I realized I was looking under the wrong index name and hence was not finding it on the cluster.

But I still am curious to know how this package handles data syncing between Mongo and ES internally? 
From my research, there are a few options - [Rivers] (https://github.com/richardwilly98/elasticsearch-river-mongodb), Collection-hooks, etc. What technique does this use?

**Comment by matteodem** [comment]
It does by using observeChanges: https://github.com/matteodem/meteor-easy-search/blob/master/lib/searchers/elastic-search.js#L74

**Comment by niranjans** [comment]
Got it. Thanks for linking to it. And thanks for this awesome package.
