### ISSUE TITLE
ElasticSearch 'Total' Session variable not being set, Pagination not working

### ISSUE THREAD

**Issue by niranjans** [matteodem/meteor-easy-search#198]
Hi, 

I am using the Js / Components API of this package with `ElasticSearch` searcher to run my search. I am getting back proper results and everything runs fine except I cannot get the pagination to work. 

When I added `{{> esPagination index="cars"}}`, nothing showed up. Since I am directly searching using Components API, I do not have a particular `id` to pass with this. 

I then tried to paginate next / prev using:
```
EasySearch.getComponentInstance({ index: 'cars'}).paginate(EasySearch.PAGINATION_NEXT);
``` 
and re-triggering the search and this worked well. 

Now, if I need to show the page number links, I will need the total hits returned. For this, I tried using `Session.get('esVariables_cars_total')` but that always returns 0. All the other Session variables have the correct values ( Like`Session.get('esVariables_cars_currentLimit')`, etc ). It is just the total that is not being set.

I tried going through the package source and the ElasticSearch searcher code but could not figure this out. I think the default total is being set as 0 and later this [line] (https://github.com/matteodem/meteor-easy-search/blob/8f52e99c888e530042f4682cf4c2ce81e82c502c/lib/searchers/elastic-search.js#L117) should set the total count but for some reason, that is not happening.

**Comment by niranjans** [comment]
After studying the source some more, I found out that we need to be subscribed to the `index + '/easySearchCount'` publication for the Pagination to work. And since I am not esInput at all, [this] (https://github.com/matteodem/meteor-easy-search/blob/fad4b56e08289b0d9ee488c61b6a648da8e4fa21/lib/components/easy-search-components.js#L248) function is not being called and this is not being subscribed.

So for now, I am thinking of just adding a subscription manually by:
```
// In my search template
Meteor.subscribe('cars/easySearchCount');
```

But I'm not sure if this is the best way to go about this.

**Comment by matteodem** [comment]
I'll have a look at this, good stuff on researching the actual bug!

**Comment by matteodem** [comment]
Feel free to write into this ticket if the bug is not resolved.
