### ISSUE TITLE
Add an Option in JS API createSearchIndex to show all result if searchString is empty

### ISSUE THREAD

**Issue by ransanjeev** [matteodem/meteor-easy-search#200]
I am using the EasySearch JS API to create and query the index. If the searchString is of zero length, I get the first page from the collection else I use the EasySearch Search API to get the result. It will be nice if defaultResult option could be added during index creation. 
It could be a function block or what ever makes sense.

**Comment by matteodem** [comment]
Why not have an else block as shown in https://github.com/matteodem/meteor-easy-search/issues/82?

**Comment by matteodem** [comment]
You could change the limit with the JS API and then search for '' and get back all documents.

**Comment by joaobarcia** [comment]
Hi Matt, this would be extremely useful. In our case we have "filter" and "sort by" options associated with easysearch. Do we have to create a new template with the same filter/sort buttons, helpers, events and methods but now associating them with the full collection display?
