### ISSUE TITLE
Issue using ElasticSearch on Server side

### ISSUE THREAD

**Issue by newterminator** [matteodem/meteor-easy-search#202]
I put the following code in the createSearchIndex function: 

```javascript
EasySearch.createSearchIndex('person', {
    'collection': Person,
    'field': ['name', 'age', 'gender', 'education' ], 
    'limit': 10,
    'use' : 'elastic-search',
    'body': {
        "_source": false,
        'highlight': {"fields": {"gender":{}, "education": {} }}
    },
    'reactive': false,
    'query': function(searchString) {
        query = { "match": {"_all": searchString} };
        return query;
    }
```

And then in the server side the code below: 
```javascript
Meteor.methods({
    checkInput: function (input) {
        var highlight;
        EasySearch.search('person', input, {'limit' : 1}, function (err, data) {
             highlight = data.hits.hits[0]['highlight'];
        });
        return highlight;
    }
});

```

I am trying to get the highlight section of the data(The fields [highlighted by ElasticSearch](http://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html)). But when I check it, it holds no value even if there was a positive match for the 'input' in the search function.

**Comment by newterminator** [comment]
The image below shows the query run in the console directly with elasticsearch and giving the highlight section:

![highlight_elasticsearch](https://cloud.githubusercontent.com/assets/5087437/7424678/3fae5920-ef72-11e4-85b9-cefb927d8557.jpg)

**Comment by matteodem** [comment]
Can you please give a reproduction repo or a clear description of what your problem is?

**Comment by newterminator** [comment]
That issue was probably resolved long time back ... I should have closed this topic/discussion ...
