### ISSUE TITLE
mongo-db search only working for "words" not characters

### ISSUE THREAD

**Issue by chinna789** [matteodem/meteor-easy-search#206]
I've updated latest version of this package

I'm using mongodb 2.6v in my local and staging too(meteor too)

previously when I was working with 2.4version it used to work for character search too

for Ex: to search for "jon snow", if I type 'j' I got the results

now, I need to type a word either 'jon' or 'snow' to get the result.

Is this my problem or latest version issue? 

How to fix this? any links?

my  code
```
EasySearch.createSearchIndex('boxSuggestions', {
  'collection': User,
  'use' : 'mongo-db',
  'field': ['name'],
  query: function (searchString) {
    var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);
        query['user_id'] = {$ne: this.userId};
        return query;
    }
});
```

and on keyup event I'm calling the search index

```
EasySearch.getComponentInstance({ index: 'boxSuggestions', id: 'searchBox' }).search(text);
```

```
{{#esEach index="boxSuggestions" id="searchBox"}}

{{/each}}
```

**Comment by vuhpham** [comment]
Check out this closed issue:  
https://github.com/matteodem/meteor-easy-search/issues/167

**Comment by chinna789** [comment]
I was using 
```
'useTextIndexes': true
```

I changed it to `false` and it worked fine.
