### ISSUE TITLE
Example of Using Nodejs ElasticSearch API in Easy Search

### ISSUE THREAD

**Issue by newterminator** [matteodem/meteor-easy-search#208]
Can someone please give an example of using the Node.js Elastic Search api which is exposed in Easy Search as marked [here] (https://github.com/matteodem/meteor-easy-search/commit/38277cec88b850225e4a46aea610ef3d197ac0d1) by @matteodem. 

I tried the following, which is taken from the api docs in [Quick Start with ElasticSearch.js API] (http://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/quick-start.html) but got no documents returned (input is the variable that holds the search string): 

```javascript
var client = new EasySearch.ElasticSearch.Client({
   host: 'localhost:9200'
});
var hits;

client.search({
   index: 'person',
   type: '_all',
   body: {
      query: {
          match: {
              name: input
          }
       }
    }
}).then(function (resp) {
   hits = resp.hits.hits;
}, function (err) {
   console.trace(err.message);
});
```
At end of this, the variable 'hits' holds nothing even though when I run the same query in the console directly with elasticsearch I get the document(s) retrieved.

**Comment by stivaugoin** [comment]
+1
I am looking to do the same . If you find an example , can you share it please ?

**Comment by brylie** [comment]
We also need an example of how to implement this search pattern, particularly for an existing search index on the Elastic server.

**Comment by matteodem** [comment]
This is documented here now http://matteodem.github.io/meteor-easy-search/docs/elastic-search/ (see __Using the ElasticSearch Client directly__)

**Comment by matteodem** [comment]
Feel free to write into this ticket if there are still examples missing.
