### ISSUE TITLE
Custom changeResults() function is not called?

### ISSUE THREAD

**Issue by Bandit** [matteodem/meteor-easy-search#212]
By using

```
EasySearch.createSearchIndex('bookings', {
    'field' : ['customer', 'notes'],
    'collection' : Bookings,
    'limit' : 20,
    'use' : 'mongo-db',
    'changeResults' : function (results) {
      console.info("test", results);
      return results;
    }
});
```

I never get any console output... is this because this function is called by the server rather than the client?

How do I determine what's inside the `results` object so I know what to change? There's no documentation on this function on the website.

**Comment by lsunsi** [comment]
Same here.
The annoying thing is that I really need this callback to denormalize some data being searched, because the integration with publish-composite is poor.

**Comment by matteodem** [comment]
Soon, maybe this weekend. I am having finals the next 2 weeks and I am really busy with that right now.

**Comment by lsunsi** [comment]
Great, thanks!
This weekend would be nice, because I am currently using a much more complex login to avoid this bug and I'm going to release the new meteor website this week! I would be cool if I could get it fixed.
Anyway, finals... damn finals.

**Comment by matteodem** [comment]
What speaks against using transform? http://docs.meteor.com/#/full/mongo_collection It's rather hard to fix this, since I cannot call changeResults on all docs, I'd need to introduce `changeResult` that acts on every document and deprecate `changeResults`.

**Comment by Bandit** [comment]
I think `transform` will work fine for me; I actually didn't know it existed.

I guess a scenario where someone only wants to transform search results (rather than every time it's pulled from the database) might be a reason why this couldn't be used?

**Comment by matteodem** [comment]
I'll create a new issue for creating a transform method and close this one.

**Comment by aguegu** [comment]
Same problem. Is there any update yet?

In the doc, there are both `transform` and `changeResults` documented. But neither of them works on current release, v1.6.3.

```
transform: Optional function(document) which can be used to transform documents before indexing (does not work with mongo based search)
changeResults: Optional function(reults) to make custom changes before using them
```

According to the doc above, there are total two different properties. Is `transform` going to replace `changeResults`? It does not make much sense to me.

**Comment by matteodem** [comment]
Yes, I'll be sure to explain the functionality of those sufficiently in the next version.
