### ISSUE TITLE
Pagination 'Previous' link not active until page 3

### ISSUE THREAD

**Issue by centinel3** [matteodem/meteor-easy-search#214]
Good morning,

I want to thank you for this awesome package! It works awesome. I implemented simple pagination and it's working as it should, though I noticed that the 'previous' button doesn't become active until page 3. for my test I have a limit of 1 on the collection init (see below). Is there something I'm missing? Thank you for your time. -Chris

ProjectsCollection.initEasySearch(['clientProjectName', 'clientName', 'projectDescription'], {
    'limit' : 1,
    'use' : 'mongo-db'
});

![screen shot 2015-05-14 at 9 14 58 am](https://cloud.githubusercontent.com/assets/199507/7632343/24379b9a-fa1a-11e4-9a8b-a04657d65560.png)
![screen shot 2015-05-14 at 9 14 47 am](https://cloud.githubusercontent.com/assets/199507/7632344/2439693e-fa1a-11e4-8fb6-d59589adde23.png)

**Comment by centinel3** [comment]
Update: I adjusted the page limit to 2 and previous now enables after the first page. Seems that this is a bug if you are only returning 1 result (which I'm not in production).

Thanks again for this awesome package! -Chris

**Comment by matteodem** [comment]
What are the exact reproduction steps?

**Comment by centinel3** [comment]
This is all set per my last post above. IT seems this is a bug if the user is limiting the page results to only 1. -Chris

**Comment by matteodem** [comment]
Feel free to write into this ticket if the bug is not resolved with the latest version __1.6.0__.
