### ISSUE TITLE
PAGINATION_NEXT - I can't get this to work

### ISSUE THREAD

**Issue by centinel3** [matteodem/meteor-easy-search#215]
I know that limiting pagination page values is on the enhancement list, so in the meantime I want to move forward with allowing the user to just click a 'next' or 'previous' button. I see there is a javascript method to move to the next page, though can't seem to get it to work. Also, is there a method for previous (ie: EasySearch.PAGINATION_PREV)?

Any help would be appreciate. Sincerely, Chris

JS:
Template.searchFormTpl.events({
	'click #next-page': function() {
		EasySearch.pagination('projects', EasySearch.PAGINATION_NEXT);
	}
});

HTML:
<template name="searchFormTpl">
  {{> esInput index="projects" placeholder="Search: Company Name, Project, Description" }}

  <div id="project-list" class="group">
    {{#esEach index="projects"}}
      {{> searchProjectItemTpl}}
    {{/esEach}}
  </div>

  <div class="search-controls">
    {{> esPagination index="projects"}}

    <div id="next-page">NEXT PAGE</div>
  </div>

  {{#ifEsHasNoResults index="projects"}}
    <div class="no-results">No results found!</div>
  {{/ifEsHasNoResults}}

  {{#ifEsIsSearching index="projects"}}
    <div>Loading...</div>
  {{/ifEsIsSearching}}

  {{#ifEsInputIsEmpty index="projects"}}
        <div>Search for projects</div>
    {{/ifEsInputIsEmpty}}
</template>

**Comment by matteodem** [comment]
Please create a reproduction repo with a description of what doesn't work as expected.
