### ISSUE TITLE
Using Query on user search

### ISSUE THREAD

**Issue by Pushplaybang** [matteodem/meteor-easy-search#219]
Is there any documentation, or can anyone explain how to use the query a little more when using the createSearchIndex.

Is this sort of thing only necessary for nested documents?  

````js
	query: function (searchString, opts) {
	    // Default query that is used for searching
	    var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);

	    // Make the emails searchable
	    query.$or.push({
	      emails: {
	        $elemMatch: {
	          address: { '$regex' : '.*' + searchString + '.*', '$options' : 'i' }
	        }
	      }
	    });

	    return query;
	  }

````

**Comment by matteodem** [comment]
what you return here is a standard MongoDB selector, see http://docs.mongodb.org/manual/reference/operator/query/elemMatch/

**Comment by matteodem** [comment]
Feel free to write into this ticket if there are any open questions.
