### ISSUE TITLE
Limit access to index

### ISSUE THREAD

**Issue by mads397** [matteodem/meteor-easy-search#22]
This is not a bug report but rather a question:

What would be the best way to limit who has access to searching a given index? I tried to only define my search index on the server, but it seems that the index is still searchable on the client. Perhaps I can solve it by checking permissions in the publish method(s) for the collection(s) used for the index, but that just seems a little cumbersome.

Any ideas?

**Comment by WayneUong** [comment]
@matteodem The reference link expired. Where can I find the latest url? Thanks

**Comment by matteodem** [comment]
here's the example http://matteodem.github.io/meteor-easy-search/docs/core/ and API reference is here http://matteodem.github.io/meteor-easy-search/docs/api-reference/
