### ISSUE TITLE
What wrong with me?

### ISSUE THREAD

**Issue by jmlv** [matteodem/meteor-easy-search#220]
Hi! I am trying to search in multiple colletion, but something wrong.

    Template.searchBox.helpers({
      indexes: function() {
        return ["collection1", "collection2"];
      }
    });

    Collection1= new Mongo.Collection("collection1");
    EasySearch.createSearchIndex("collection1", {
      "field": ["some1", "some2", "some3"],
      "collection": Collection1,
      "limit": 10,
      "use": "mongo-db"
    });

    Collection2= new Mongo.Collection("collection2");
    EasySearch.createSearchIndex("collection2", {
      "field": "some",
      "collection": Collection2,
      "limit": 10,
      "use": "mongo-db"
    });

And template
    
    {{> esInput index=indexes placeholder="Search..." class="form-control"}}

And Router

    Router.configure({
      loadingTemplate: "loading",
      layoutTemplate: "mainLayout",
      notFoundTemplate: "notFound",
      waitOn: function() {
        return [
            Meteor.subscribe("collection1"),
            Meteor.subscribe("collection2")
            ];
        }
      });

First search runs fine, but when I click a link on a different path and try to search, nothing happens.
When i typing in input Session(esVariables_vacancies_currentValue) changes, but Session(esVariables_vacancies_searchResults: "[]") not. Please help.

PS: searchbox template include on all pages
PSS: when i dont use indexes, all worked fine

**Comment by jmlv** [comment]
Hello again.
I am trying like this:

    {{> esInput index="collection1" placeholder="Search..." class="form-control"}}
    {{> esInput index="collection2" placeholder="Search..." class="form-control"}}

Yes, without indexes all worked good, but double inputs....

**Comment by jmlv** [comment]
Sooo, when i add 3 inputs

    {{> esInput index="collection1" placeholder="Search..." class="form-control"}}
    {{> esInput index="collection2" placeholder="Search..." class="form-control"}}
    {{> esInput index=indexes placeholder="Search..." class="form-control"}}

All work fine! But when only indexes, after going to other route, search dont work.
Oh God.

**Comment by jmlv** [comment]
Matteo, i find the problem. If include {{> searchBox}} (my template for search box and results)  before {{> yield}}

    Template.esInput.destroyed = function () {
    var data = Template.currentData();
    EasySearch.eachIndex(data.index, function (index, opts) {
      opts.countSubscriptionHandle && opts.countSubscriptionHandle.stop();
      opts.subscriptionHandle && opts.subscriptionHandle.stop();
      clear(index, data.id);
      initializedComponents.splice(initializedComponents.indexOf(index), 1);
      });
    };

not working. That explains it.

**Comment by matteodem** [comment]
So does the problem work now?

**Comment by jmlv** [comment]
Only include Template.esInput in yield

**Comment by matteodem** [comment]
I'll close it, please create a bug if you find another problem.
