### ISSUE TITLE
Set isSearching to true when loading caused by allDocsOnEmpty=true

### ISSUE THREAD

**Issue by rico** [matteodem/meteor-easy-search#222]
I have the following situation. I set the values for the `props` (filters) from the `Session` on load. This works fine. Combined with `allDocsOnEmpty=true` it works exactly how expected. However, it doesn't seem, that `isSearching ` is set to `true`. 

Since the initial search can take some time as well, it would be great, if `isSearching` would be `true` during initial load so that the loading view is shown.

P.S: your package is really fun to work with (and fell a bit in love with Elasticsearch too ;-) - thanks.

**Comment by matteodem** [comment]
Great to hear that you got to like Elastic-Search! I'll report this as a bug and will have a look at it soon.

**Comment by matteodem** [comment]
Feel free to write into this ticket if the bug is not resolved with the latest version __1.6.0__.
