### ISSUE TITLE
Set esInput to search a specific field of an index.

### ISSUE THREAD

**Issue by geritol** [matteodem/meteor-easy-search#224]
Is it possible to somehow do with the simple setup (like mentioned in the demo):

Players.initEasySearch(['name', 'score'], {
    'limit' : 20,
    'use' : 'mongo-db'
});

To add two search fields:
{{> esInput index="players" placeholder="Search..." }}
{{> esInput index="players" placeholder="Search..." }}

And somehow set that the first field should search only in 'name', and the second only for 'score'. Thanks a lot for the help and the awesome package.

**Comment by matteodem** [comment]
The most simple way to do that is by creating two indexes for the same collection, with `createSearchIndex`, see http://matteodem.github.io/meteor-easy-search/docs/javascript-api/

**Comment by matteodem** [comment]
Related to #223

**Comment by matteodem** [comment]
This is now possible as of v2, see #223 for further information.
