### ISSUE TITLE
How to turn off reactivity?

### ISSUE THREAD

**Issue by artitw** [matteodem/meteor-easy-search#226]
I thought there used to be a way to turn off reactivity like
````
EasySearch.createSearchIndex('users', {
...
'reactive': false,
...
});
````
However, I no longer see it in the documentation. Any ideas?

**Comment by matteodem** [comment]
What is your use case for having non-reactive search results?

**Comment by artitw** [comment]
I just wanted to reduce CPU usage on the server by turning off reactivity. Meteor's merge box is quite computationally intensive.  

If the option is no longer available, can you confirm? Also please let me know if you have other ideas for improving performance. Thanks!

**Comment by matteodem** [comment]
It is no longer officially supported, but there is still code that relies on `reactive` being true. A good thing to improve performance is to define `returnFields` and use mongo text indexes / Elastic Search for searching.

**Comment by artitw** [comment]
Thanks very much for your advice. In that case, how do I define `returnFields`?

**Comment by matteodem** [comment]
It is an array of document fields to return, so if you have the document:

```json
{
  "name": "woop",
  "description": "woop woop"
}
```

And you only display __name__ in your search results, you can define your index like this:

```javascript
EasySearch.createSearchIndex({
  ...
  returnFields: ['name'],
  ...
});
```

I hope that makes sense.

**Comment by artitw** [comment]
Thanks, I added the `returnFields` to my index, and it seems to work (at least not throwing errors). I just took a look at the docs and see that we can turn off reactivity on `esInput`. Is that outdated?

http://matteodem.github.io/meteor-easy-search/docs/blaze-components/

**Comment by matteodem** [comment]
Yes, I will remove it from the docs, thanks!
