### ISSUE TITLE
esDropdown Component?

### ISSUE THREAD

**Issue by iamkevingreen** [matteodem/meteor-easy-search#227]
esInput is great, and maybe there is another way to do this but I think it could be a beneficial addition. 

Currently the filters only fire after a search is made, I am having trouble getting a dropdown to fire the search since it is waiting for the original esInput. An esDropdown, could like the input grab the value of that option and fire that as a searchString. Unless there is an abstract way to fire the search without esInput? I basically want to search without using the esInput field first and not really sure how to go about doing that.

**Comment by matteodem** [comment]
You can use the Component `search` method. See http://matteodem.github.io/meteor-easy-search/docs/component-api/ or https://github.com/matteodem/easy-search-leaderboard/blob/master/leaderboard.js#L83 as an example.
