### ISSUE TITLE
autoform integration

### ISSUE THREAD

**Issue by pajooh** [matteodem/meteor-easy-search#228]
hi @matteodem , and thank you for this great package.
i want to have an auto suggest select input (title as label, _id as value) with server side search.
generally speaking, many autoform select options come from other collection's items. there is no problem when the collection items count is low, which can be showed via a normal select (and publishing all items of that related collection), but it is not possible to do this for a big one. in my opinion, just an auto suggest search box can help.
is it possible to use easy-search to create an autoform widget for this?
any help would be highly appreciated.

**Comment by matteodem** [comment]
have a look at ```esAutosuggest```, http://matteodem.github.io/meteor-easy-search/docs/blaze-components/

**Comment by pajooh** [comment]
@matteodem i'm aware of ```esAutosuggest```, i wan't it to use as a select input (with separate label and value). also i want it to integrate it with autoform,  to show something like [this](https://github.com/aldeed/meteor-autoform#calculate-options-in-the-schema)

**Comment by matteodem** [comment]
can you show me an example of your autoform definition, enhanced with easy-search? Just to see what you're trying to achieve.

**Comment by matteodem** [comment]
Feel free to write into this issue and I'll re-open it
