### ISSUE TITLE
Full Text Search on Emails

### ISSUE THREAD

**Issue by patrickml** [matteodem/meteor-easy-search#229]
For some reason I cannot do a fullText search on users and have it search their email address?

this is the field name I am using `emails.address`

**Comment by matteodem** [comment]
Please give me reproduction steps with a clear description of you problem.

**Comment by AlexFrazer** [comment]
I think you must use `$elemMatch` for that query if you're looking through the `Meteor.users` collection.

```
function searchEmails(email) {
  Meteor.users.find({
    "emails": {
      $elemMatch: {
        "address": email
      }
    }
  })
}
```

**Comment by matteodem** [comment]
Thanks for answering :+1:

**Comment by patrickml** [comment]
Here is an example: 

Lets say i'm creating a search field for the users collection

~~~
 {{> esInput index="users" placeholder="Enter User Info" }}
~~~

to create my search index il do the following

~~~
EasySearch.createSearchIndex('users', {
  'collection': Meteor.users,
  'field': [
    'profile.firstname',
    'profile.lastname',
    'profile.mobile',
    'emails.address'
  ],
  'limit': 10,
  'use': 'mongo-db',
  'convertNumbers': false,
  'useTextIndexes' : true,
  'query': function (searchString) {
    var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);

    //remove ourselves from the result
    query['_id'] = { $ne: this.userId };
    return query;
  }
});
~~~

If you notice I have `emails.address` as a field but if I type in a users email they do not show up

https://www.dropbox.com/s/h2bpb6518f7htl8/Screenshot%202015-07-06%2016.51.15.png?dl=0

Now if I type in their first & last name they will

https://www.dropbox.com/s/kodw0ggsgdm56xf/Screenshot%202015-07-06%2016.52.01.png?dl=0

**Comment by matteodem** [comment]
You need to change the `query` method to include the $elemMatch selector that @AlexFrazer included.

**Comment by matteodem** [comment]
see here http://matteodem.github.io/meteor-easy-search/docs/recipes/
