### ISSUE TITLE
Support for accented characters

### ISSUE THREAD

**Issue by gatosaurio** [matteodem/meteor-easy-search#232]
I´m searching over the 'name' field of a collection.
Suppose that field on Mongo has been set up as "León".
When the user types "Leon" (without the accented o) on the search field of course nothing shows up. 

How can I make this to work so that "León" shows up when the user types "Leon"?
Is there a way to do it without adding extra fields into the collection?

**Comment by matteodem** [comment]
You can try to use text indexes by settings ```useTextIndexes``` to ```true```: http://matteodem.github.io/meteor-easy-search/docs/javascript-api/

**Comment by gatosaurio** [comment]
Sadly that didn´t work.

Customers.initEasySearch(['name'], {
    'limit' : 20,
    //'use' : 'mongo-db',
    'useTextIndexes': true,
    'reactive': false
});

Commenting out the 'use' key works the same as commenting out the 'useTextIndexes' key, both display results but without the feature I need.
Using all keys without commenting any doesn't display any results.

It will be nice to have this support for accented characters implemented :)

**Comment by matteodem** [comment]
It's already possible by providing a custom query method that removes the accents on the characters, see http://matteodem.github.io/meteor-easy-search/docs/javascript-api/ (searchString is the parameter to be adjusted)

**Comment by gatosaurio** [comment]
I guess I see where you're heading now. 

I'll try it later and comment on the results.

Thanks for the quick reply!
