### ISSUE TITLE
Searching Over a Local Collection

### ISSUE THREAD

**Issue by dylanmcgowan** [matteodem/meteor-easy-search#233]
Hey, 

Is there a workaround for searching over a local collection like the one below? I'm building a cordova app that pulls the local contacts from the user's phone and need to search over them.  

localContacts = new Meteor.Collection(null);

and then I assume to call it in the helper like so.
{{#ifEsIsSearching index="null"}}

each localContact looks like this

{
    "name": "Alan",
    "phoneNumbers":[{
      "value":"4103021863",
      "pref":false,
      "id":0,
      "type":"mobile"
    }],
    "emails":null
  }

But I'm getting errors in the console ~~ "Error: Match error: Expected number, got undefined"

Any help would be much appreciated!!!

**Comment by matteodem** [comment]
Please show me your Easy-Search configuration (either ```createSearchIndex``` or ```initEasySearch```)

**Comment by dylanmcgowan** [comment]
Hey man sorry, the problem was on my end.  I was declaring the local collection on the client, but moving it to the lib folder and setting the index to 'null' for the helpers solved my problem.  Cheers!
