### ISSUE TITLE
Need to know when document has been inserted into Elasticsearch

### ISSUE THREAD

**Issue by rico** [matteodem/meteor-easy-search#234]
In my application, once the document is added to the Collection (Form -> Meteor method), the user is redirected back to the page listing the objects (using easy search). However, the newly created object is not shown in the listing.

I noticed, that when i delay the redirect by around 200ms, the new object is shown as well. 

So I guess the insertion of the document into elasticsearch, is done asynchronously and that just takes some time.

Is there any way to know, when the elasticsearch operation has completed (callback, event)?

**Comment by matteodem** [comment]
This is another problem, which is related to #230

**Comment by matteodem** [comment]
This is fixed as of v2, where the default behavior has changed.
