### ISSUE TITLE
Nested Field query

### ISSUE THREAD

**Issue by OminStyle** [matteodem/meteor-easy-search#239]
Thanks for offering such a great package. I got everything to work except for a simple query for a nested field. I'm trying to search for a ```location.country``` field but I'm unable to get this to work. I've tried
```query.location = { country: this.props.country }``` and
```
query.location = {};
query.location.country = this.props.country;
```
after verifying that ```this.props.country``` returns the country (eg. 'USA') but no luck.

**Comment by OminStyle** [comment]
My fault. I just learned that ```query.location.country``` is not same as either of them. http://stackoverflow.com/questions/16002659/mongodb-how-to-query-nested-objects. I used ```_.extend(query, {"location.country": this.props.country});``` instead and it works perfectly.

**Comment by latitudehopper** [comment]
I don't seem to be able to get that to work. I have done this, have I done it wrong?
```javascript
     'limit' : 20,
    'use' : 'mongo-db',
    'props' : {
        'year' : null // demo purpose configuration, can be used in query
    },
    'query' : function (searchString, opts) {
        var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);

        if (this.props.year != null) {
            _.extend(query, {"date.year": this.props.year});
        }

        return query;
    }
```

**Comment by matteodem** [comment]
try to have a look at what `query` contains and show me the output here

**Comment by latitudehopper** [comment]
I think I may have an idea, the year is not a string....

 { '$or': [ { title: [Object] }, { text: [Object] } ], 'date.year': '1987' }

**Comment by latitudehopper** [comment]
Yes, that was the problem. Good thoughts on checking query. A little parseInt action helped.
