### ISSUE TITLE
ElasticSearch - adding filter to the query

### ISSUE THREAD

**Issue by kyooriouskoala** [matteodem/meteor-easy-search#241]
Hi, I'm trying to use the filter feature on my project but it doesn't seem to work when using elastic-search.

I've also downloaded the [leaderboard example] (https://github.com/matteodem/easy-search-leaderboard) using the original elastic-search (commented out) code chunk but can't get it to work either. 

Thought I found the solution from the [Javascript API ] (http://matteodem.github.io/meteor-easy-search/docs/javascript-api/) doc section and so I tried this code below until I noticed the comment that says "Default query that will be used for the mongo-db selector" >.<

````javascript
EasySearch.createSearchIndex('players', {
    'collection': Players, // instanceof Meteor.Collection
    'field': ['name'], // array of fields to be searchable
    'limit': 10,
    'use' : 'elastic-search',
    'convertNumbers': true,
    'props': {
        'filteredCategory': 'All'
    },
    'query': function(searchString, opts) {
        // Default query that will be used for the mongo-db selector
        var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);

        console.log(opts);

        // filter for categories if set
        if (this.props.filteredCategory.toLowerCase() !== 'all') {
            query.category = this.props.filteredCategory;
        }

        return query;
    },
    'sort': function() {
        return ['_score'];
    }
});
````

Now, I'm not so sure if the filter feature works for elastic-search. If it is supposed to work, could you provide the doc on how to use it, please? Thank you.

**Comment by matteodem** [comment]
The `query` will not work, since it's not structured like ElasticSearch Queries. Have a look at the [Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/query-dsl-queries.html) and don't forget to run a separate ES process when using Elastic-Search (see docs).

**Comment by kyooriouskoala** [comment]
Checked out the [Query DSL] (https://www.elastic.co/guide/en/elasticsearch/reference/1.4/query-dsl-queries.html) and I think I'm almost there. I'm not sure what you mean by running a separate ES process though. Could you elaborate more, please? Thanks.

**Comment by matteodem** [comment]
http://matteodem.github.io/meteor-easy-search/docs/elastic-search/ (How to install)

**Comment by kyooriouskoala** [comment]
Hi @matteodem, 

I'm getting really close to making it work here. 

```` javascript
if (this.props.prefLocation.toLowerCase() !== 'all') {
            var query = {
                "filtered": { 
                    "query": {
                        "fuzzy_like_this": {
                            "fields": ["productTitle"],
                            "like_text": searchString
                        }
                    },
                    "filter": {
                        "term": { "currentDealInfo.location": this.props.prefLocation.toLowerCase() }
                    }
                }

            };
        }
````

Currently stuck at making the filter term to work since it has to be an exact match (and with space). For example: 

Filter term: `new`
Expected result: `new`
Current results: `new`, `new south`, `new south wales`

Filter term: `new south`
Expected result: `new south`
Current result: null

Happen to know how to solve this issue?

**Comment by kyooriouskoala** [comment]
From what I understand so far, it seems that elasticsearch mapping would be the solution for the above issue but then it's not yet supported in the current version of this package. 

If that's not the case, please enlighten me. Otherwise, this issue can be closed. Thanks!

**Comment by matteodem** [comment]
You can access the raw Elastic-Search client and set the mapping there for now: http://matteodem.github.io/meteor-easy-search/docs/elastic-search/
