### ISSUE TITLE
How to replace text in esInput and trigger results?

### ISSUE THREAD

**Issue by artitw** [matteodem/meteor-easy-search#242]
I defined a class for the `esInput` called `search-box` and tried to use jQuery to replace the text as shown below, but it doesn't seem to trigger the search results expected.

    $(".search-box").val("Hello World");
    $(".search-box").trigger('keyup');

**Comment by artitw** [comment]
UPDATE: It works only when I first manually type in something before the event triggers. Starting from scratch, it shows the "Searching..." text but no results.

**Comment by matteodem** [comment]
The solution to this problem is answered in #237
