### ISSUE TITLE
Server hangs when '|' (pipe) character is used in the search

### ISSUE THREAD

**Issue by OminStyle** [matteodem/meteor-easy-search#243]

**Comment by matteodem** [comment]
Works with the easy-search-leaderboard example https://github.com/matteodem/easy-search-leaderboard

**Comment by OminStyle** [comment]
I'm getting a weird behaviour on the leaderboard too. It's probably something minor but I noticed that it's not treated as a normal string character. Can you try searching for some random string followed by "|"? It might be more noticeable on an app with less data. Here's what I'm currently working on http://orosim.meteor.com/courses. The app currently has 10000 data points. Try searching for "charles| abc" and delete the string and wait for the search to reset

I was actually trying to see if meteor-easy-search can search by keywords. The behaviour I'm seeing right now is more like a phase search ([wiki](https://en.wikipedia.org/wiki/Full_text_search#Improved_querying_tools)). For example, I would like to be able to search for a person named "Charles Han" but also be able to search by "Han Charles".

**Comment by matteodem** [comment]
You should use either mongo db text indexes or Elastic-Search (which is a more mature approach to search).

**Comment by OminStyle** [comment]
I was afraid you might say that... thanks for the reply though!

**Comment by matteodem** [comment]
I don't think that this problem has anything to do with Easy-Search itself, feel free to write into the ticket if you think otherwise.

**Comment by OminStyle** [comment]
Have you tried reproducing my steps?

**Comment by matteodem** [comment]
I did and it weirdly enough takes longer to recover to all results after writing the pipe sign. There is no actual transformation of the searchString going on, so I assume it doesn't have anything to do with it.

If you want you can provide a custom `query` property that changes the searchString to remove such non-word characters.
