### ISSUE TITLE
Count of results is shared between sessions

### ISSUE THREAD

**Issue by matteodem** [matteodem/meteor-easy-search#245]
* Open two browser tabs
* Search for some string
* Count of results changes for both open apps

It should be able to have different counts for each tab.

**Comment by darrenangle** [comment]
This is affecting the 'load more' button, which seems to be tied to the count stored in the db.

If multiple users are searching at the same time, and one has loaded 30 more dogs, while another has a smaller query, the first user will lose their load more button.

**Comment by darrenangle** [comment]
I noticed there is an esCounts collection containing the ES indexes and a count. That value appears to be shared among all connected users no matter their differences in state - seems like this count could be stored on the client, to maintain their individual query states... I'm using ES in a large production app with many simultaneous users searching. Any advice? (Thanks for the amazing work!)

**Comment by matteodem** [comment]
so is the load more button being affected for different users?

**Comment by micant** [comment]
I'm having the same problem, in our app we have a counter variable holding instance.get('total') that updates the number of docs returned in search. If you open multiple tabs and search, or another user logs in and searches, the variable changes across all the search instances. Pagination is also affected in the same way.

**Comment by micant** [comment]
@darrenangle Did you come up with a solution for this on your project?

**Comment by darrenangle** [comment]
Unfortunately no - we redesigned to avoid pagination and capped the results.

**Comment by matteodem** [comment]
I'm about to release v2 very soon, this and other bugs are resolved in the next version.

**Comment by darrenangle** [comment]
Sweet! Thanks Matteo.

**Comment by micant** [comment]
Awesome thanks very much.

**Comment by dburles** [comment]
Hey @matteodem just wondering if you have an ETA on the v2 release?

**Comment by matteodem** [comment]
By the end of the week.

**Comment by matteodem** [comment]
This bug is fixed as of v2, see the [UPGRADE.md](https://github.com/matteodem/meteor-easy-search/blob/master/UPGRADE-2.0.md) or [docs](http://matteodem.github.io/meteor-easy-search/getting-started/) for information about the changes.
