### ISSUE TITLE
How to filter search and get result in context?

### ISSUE THREAD

**Issue by diegodesouza** [matteodem/meteor-easy-search#246]
I have the following, my issue or question is to how to be able to search through my ```customers``` collection and filter out by the customerName but maintain the structure i already have for the customer(full document with all the fields displayed), where as with what I have so far, I get only the name of customer outside context(nor in the nav nor in the structured customers display)

    Customers.initEasySearch(['customerName'], {
      'limit': 5,
     });

    <template name="searchCustomers">
        {{> esInput index="customers" placeholder="Search..." }}
        <ul>
            {{#esEach index="customers"}}
                <li>{{customerName}}</li>
            {{/esEach}}
        </ul>
    </template>

    <div class="search">{{> searchCustomers}}</div>

![question](https://cloud.githubusercontent.com/assets/7575914/8664868/4e49d0c2-29ab-11e5-83b8-73e747cd889a.jpeg)

in this case it would have to filter out with that query(sport) and have returned only 2 documents, but instead I got the names only. does this makes sense? Thanks for your patience

**Comment by matteodem** [comment]
That does not make a lot of sense to me. Are you missing data? Please give a clear description of your problem.

**Comment by diegodesouza** [comment]
I was able to work around without the package. Thanks for the attention.
