### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by matteodem** [matteodem/meteor-easy-search#248]
2.0 will have major bc breaks with a MIGRATING.md to make the switch as less painful as possible.

Changes:
- Use ES6 with https://atmospherejs.com/meteor/ecmascript
- Use a component package for Blaze Components (maybe http://components.meteor.com/)
- Split it into separate `core`, `components` and `autosuggest` package (+ `easy-search` with core and components)
- Rewrite `createSearcher` to be a class called `EasySearch.Engine`
- Rewrite `createSearchIndex` to be a class called `EasySearch.Index`
- Make certain index configuration dependent on the Engine and Component and not everything by the Index
- Also allow search objects (instead of search strings)
- Rename `initEasySearch` to `createSearchIndex`
- Change github repository to include all packages

Features:
#247, #244, #190, #171, #151, #79, #70, #282

Include bugfixes for open bugs.

**Comment by dfischer** [comment]
I would recommend not using a component package as that would add a lot of bloat to people who *don't* want that.

**Comment by matteodem** [comment]
I think this project has taken a size where **not** having a component library is not feasible anymore. Since the new core package has a lot more functionality built in, you could also just use that if the components package adds to much bloat* to your project.

**Comment by dfischer** [comment]
Why would you *need* a 3rd party component library over vanilla blaze?

**Comment by matteodem** [comment]
Extensibility, please refer to the code itself if you're curious what that component package brings you.

**Comment by dfischer** [comment]
Having to use http://components.meteor.com/ for `components` seems a bit bloated. You should be able to get away with vanilla blaze, maybe not as elegant but you should be able to.

Using http://components.meteor.com/ forces an entire abstraction into others people's projects that they may not want. Not to mention Blaze 2.0 will be handling these issues.

**Comment by matteodem** [comment]
Then I'll wait for Blaze 2.0 or happily accept a PR that resolves this. Please create a new issue if you feel like the __bloat__ really makes a noticable difference on the client-side, with a clear description of what the problem is.

**Comment by methodbox** [comment]
Are you going to make ```autosuggest``` a working component this time. #299 from me clearly shows that it is not working at this time.

I've also seen multiple closed issues with the same fundamental issue I have reported again with no actual resolution.

Maybe if this feature had better documentation it would help.

**Comment by matteodem** [comment]
Yes, but it'll use a library like `selectize` that takes over the autosuggest logic itself.

**Comment by matteodem** [comment]
v2 is now released!

**Comment by rico** [comment]
Nice! Will check it out out asap. Thanks!

**Comment by sferoze** [comment]
@matteodem Hey, I am still using Easy Search 1.0 

Everything is working and I am happy with 1.0. I don't seem to need any new features from 2.0 at the moment. 

Just wondering if there is any major reason for me to upgrade to 2.0 then? Is it a drastic improvement in performance or something other than features and using ES6? At this point I just don't see any point of upgrading but wanted to check with you too see what are the major reasons for upgrading...

Thanks Easy Search is really important in my app :)

**Comment by matteodem** [comment]
If you want to be up to date with the latest meteor releases + make use of the new features (e.g import / export) then it'd be advisable to upgrade. Also bugs in v1.* won't be fixed unless through a PR.
