### ISSUE TITLE
How to custom pagination like bootstrap 3?

### ISSUE THREAD

**Issue by thearabbit** [matteodem/meteor-easy-search#254]
I want to custom pagination like bootstrap 3 (Datatable).
Because it is not good when may records.

**Comment by matteodem** [comment]
What is the exact problem you're having?

**Comment by thearabbit** [comment]
When I search with many result, so it view along pagination (1, 2, 3.....100000).

**Comment by thearabbit** [comment]
It mean that I want to show it like `first - pre - 1 2.......1000-1001 - next - last`, if have many result a.

**Comment by matteodem** [comment]
Please have a look at existing issues before creating new ones (#171).
