### ISSUE TITLE
Is it possible to override one query parameter from the server?

### ISSUE THREAD

**Issue by OminStyle** [matteodem/meteor-easy-search#256]
I'm able to override the limit from the server using the example in the documentation.
```
EasySearch.search('cars',  "Toyo", {
  'limit' : 50 // override the 20, defined in createSearchIndex
}[, callback]);
```
I was wondering if it's possible to override just one query parameter (eg. ```query.categories```) from the server.

I have tried the following but didn't work.
```
EasySearch.search('cars',  "Toyo", {
  'limit' : 50, // override the 20, defined in createSearchIndex
  'query.categories': "xyz"
}[, callback]);
```

**Comment by OminStyle** [comment]
```
EasySearch.search('cars',  "Toyo", {
  'limit' : 50, // override the 20, defined in createSearchIndex
  'skipCategoriesUpdate': true
}[, callback]);
```
and adding additional check inside ```EasySearch.createSearchIndex``` worked for me.

**Comment by matteodem** [comment]
Good stuff, I'm in the process of creating a "simpler" API for version 2, hopefully it'll be much clearer how to do things like that then
