### ISSUE TITLE
manageAutosuggestValues match check throw error when using keyboard

### ISSUE THREAD

**Issue by allanlundhansen** [matteodem/meteor-easy-search#257]
Expected behaviour on manageAutosuggestValues(callback) [Line# 739](https://github.com/matteodem/meteor-easy-search/blob/bd93fef106de5933b5c663188f1f3c7e8ac97ea4/lib/components/easy-search-components.js#L739):

Same behaviour as when selecting from list with mouse click.

Observed behaviour:

Uncaught Error: Match error: Unknown key in field [1].pos

[Line# 752](https://github.com/matteodem/meteor-easy-search/blob/bd93fef106de5933b5c663188f1f3c7e8ac97ea4/lib/components/easy-search-components.js#L752)

Check throws error as of difference on objects created from mouse selection and keyboard selection

Object set from keyevent
[Line# 672](https://github.com/matteodem/meteor-easy-search/blob/bd93fef106de5933b5c663188f1f3c7e8ac97ea4/lib/components/easy-search-components.js#L672)

Object set from click event
[Line# 600](https://github.com/matteodem/meteor-easy-search/blob/bd93fef106de5933b5c663188f1f3c7e8ac97ea4/lib/components/easy-search-components.js#L600)

**Comment by matteodem** [comment]
This is fixed in the latest release 1.6.2, feel free to re-open if you think not.
