### ISSUE TITLE
How to get selected result back in search field?

### ISSUE THREAD

**Issue by bdebb** [matteodem/meteor-easy-search#259]
Hi, i'm a meteor-newbie and i really like this package.
One question: how can i get the selected result back in my search field?
Instead of in a separate template?
I'm using the autosuggest-example.

Thanks!

Barry

**Comment by matteodem** [comment]
Hello Barry

What do you mean with "get result back"? Do you want to get the value? See the docs http://matteodem.github.io/meteor-easy-search/docs/autosuggest-field/

**Comment by bdebb** [comment]
Hi Matteodem,

Yes, i would like to get the selected row from the combobox back in my searchfield (where i began typing/searching).
I looked at the docs, but the only thing i can find is to use the 'renderValue=', but then i get the result back in other field/template.

**Comment by matteodem** [comment]
How about `on.('autosuggestSelected', function () ...)` ?

**Comment by allanlundhansen** [comment]
Hi Matte, thank you for a good package! 
This method works for me only if I put a small timeout on the value assign when using .val('something') works when using .attr('value', 'something') , however if I don't put a timeout on the input field update, the keyup event listener will trigger a new search resulting in another result only containing value in input field which is not the best user experience.

**Comment by bdebb** [comment]
Thanks Matte! I've got it working now, however when i send a 'return' (event 13) to/after the input search field value, Meteor gets into an infinite loop. (i'm updating salesorder totals after this emulated 'enter', and after that the script apparently comes back in the this.autorun(function (), and all is starting over again!).
A whole different challenge!
Do you perhaps know an alternative for the autorun function, but still able to get the result value  :-)

Just one little other thing, i noticed that when i retrieve the 'values' value in the instance.on('autosuggestSelected'..... function, the 'values' are accumulated after each result selection (f.e. 1st selection returns: [object], 2nd: [object],[object], 3rd: [object],[object],[object] and so on.
Not really a problem, i worked around that.

Thanks again!

**Comment by bdebb** [comment]
Hi Matt,

One little question more: when i'm updating a collection from an event, the Easy Search Autosuggest Component is no longer working. (not searching for values anymore).
Do you have any idea?
I've been trying all day to make this working..

Thanks!
Barry

**Comment by bdebb** [comment]
Hi Matt, could you please respond to the following: (i think i found something)
The problem above is solved when i give my component an id, like:
{{> esAutosuggest index="products" id="search" renderSuggestion="suggestionTpl" renderValue=this }}

However, then the 'instance.on('autosuggestSelected' ...' is not triggered.

Am i doing something wrong here?

**Comment by matteodem** [comment]
I'll have a look at this soonish, please create new issues for other problems than the original one.

**Comment by matteodem** [comment]
Please have a look at "Retrieve component values" and "Available values" on here: http://matteodem.github.io/meteor-easy-search/docs/component-api/.

**Comment by bdebb** [comment]
Thanks! I'll have a look at that

**Comment by matteodem** [comment]
Feel free to create new issues for your other problems.
