### ISSUE TITLE
Scroll up when load more

### ISSUE THREAD

**Issue by cesarve77** [matteodem/meteor-easy-search#261]
When click in load more button the page go to top. This is the normal behavior ?

How can I changed?

Thanks

sorry for my english

**Comment by matteodem** [comment]
Probably the site reloads, because you're not capturing the event.

**Comment by kyooriouskoala** [comment]
Hi @matteodem,

I'm having the same issue where clicking on load more button causes the page to scroll back to the top. 

Package version: v1.6.4
Load more button: `{{> esLoadMoreButton index="es-products" id="search" }}`
Engine: ElasticSearch

Could you kindly explain what do you mean by "not capturing the event"? 

Thank you.

**Comment by Roylib** [comment]
+1

**Comment by matteodem** [comment]
It's related to the subscription stopping before the new one is coming in.

**Comment by Roylib** [comment]
Do you have an idea how to solve it?
