### ISSUE TITLE
Search index query() is not called when index uses mongo-db

### ISSUE THREAD

**Issue by Pathemeous** [matteodem/meteor-easy-search#263]
I have made a search bar with the blaze component esInput.

To provide some context: the goal is to search over the titles of this collection, while filtering out results in a different language than the current language of the site.

I have defined the following search index, as taken from the recipes section of the documentation:
```
EasySearch.createSearchIndex('pages', {
  'field' : 'title',
  'use' : 'mongo-db',
  'collection' : Pages,
  'query' : function (searchString) {
  	console.log('query is entered');
    // Default query that will be used for searching
    var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);

    query.language = Session.get('lang');
    return query;
  }
  });
```

Using a console.log, I checked to see if the query function was entered.
With the above situation, this was not the case.

However, when I remove the 'use' property, the query function is entered.

Do you know what is going wrong here?

**Comment by matteodem** [comment]
Where are you running that code? `mongo-db` only call's "search" on the server and syncs data over the wire.

**Comment by Pathemeous** [comment]
The above code is in the `lib` folder. The search bar (and it's automatic functionality) is put in a template with blaze components that is in the `client` folder.

The search bar searches multiple collections, and the other two indices do work. Their indices are made directly in the respective collections (also in `lib`).

Trying to define the index in its collection instead, like the other two, does not make a difference:

```
Pages.initEasySearch(['title', 'language'], {
  // 'use' : 'mongo-db',
  'query' : function (searchString) {
    console.log('query is ran');
    // Default query that will be used for searching
    var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);
    console.log(query);

    query.language = Session.get('lang');
    return query;
  }
  });
```
The console log is only output when mongo-db is not used.

**Comment by matteodem** [comment]
The problem is that you're ussing Session in the server environment, which does not exist there. Use `props`: 

http://matteodem.github.io/meteor-easy-search/docs/javascript-api/ (search for __changeProperty__ and __props__)

**Comment by Pathemeous** [comment]
Thanks, not using changeProperty and props was indeed the problem.
