### ISSUE TITLE
autosuggest for just one value

### ISSUE THREAD

**Issue by Alino** [matteodem/meteor-easy-search#265]
Is it possible to set autosuggest to receive only just one value? I dont want the suggestions list to open the second time after I choose my first value.

**Comment by matteodem** [comment]
Please give a detailed description with either reproduction steps or repository.

**Comment by Alino** [comment]
hi, thanks for fast reply.
I have an autosuggest field

```html
<template name="categorySearchInput">
  {{> esAutosuggest index="masterCategories" id=param  renderSuggestion="suggestion" renderValue="autosuggestValues" }}
</template>

<template name="autosuggestValues">
    <span class="value">
        <a href="#" class="remove">X close</a>
      {{value}}
    </span>
</template>

<template name="suggestion">
  {{pre}}<span class="found">{{found}}</span>{{post}} ({{doc.score}})
</template>
```

javascript

```coffeescript
Template.categorySearchInput.onCreated ->
  self = @
  id = self.data.param
  instance = undefined
  instance = EasySearch.getComponentInstance(
    id: id
    index: 'masterCategories'
  )
  instance.on 'autosuggestSelected', (val) ->
    if val? and val.length > 0
      input = $('#' + id)
      $(input).hide()
      $(input).closest('form').children('button').removeAttr('disabled')
      $(input).closest('form').find('.suggestions').hide()
    if val? and val.length is 0
      input = $('#' + id)
      $(input).show()
      $(input).closest('form').children('button').attr('disabled', true)
      $(input).closest('form').find('.suggestions').show()
```

I would like to be able to choose only one value after I perform a search, so suggestions will not open after entering that first value. But my code is only trying to hide .suggestions class and it works only like 50% of time. Is there better approach?

**Comment by Alino** [comment]
the problem for me here is that if I press enter to choose value, that value is chosen (ok) but the suggestions list is opened again to choose another value (which I dont want to choose, so it should be closed)

**Comment by Alino** [comment]
seems I kind of solved this with this line
```coffeescript
$('.suggestions').removeClass('show').hide()
```
