### ISSUE TITLE
#ifHasNoResults incorrectly returns false when a filter is applied and the currentValue is an empty string

### ISSUE THREAD

**Issue by rchrdschfr** [matteodem/meteor-easy-search#266]
Apply a filter as described in the Recipes section of the docs (http://matteodem.github.io/meteor-easy-search/docs/recipes/).

Then select a filter which returns an empty result. If currentValue is an empty string, #ifHasNoResults returns false even though searchResults is an empty array.

**Comment by matteodem** [comment]
Can you list up the steps to easily reproduce this?

**Comment by rchrdschfr** [comment]
1. Make a normal search using #esInput
2. Add an #ifHasNoResultsBlock
3. Create a custom filter, perhaps exactly the same one under "Filters / Faceted Search" here: http://matteodem.github.io/meteor-easy-search/docs/recipes/
4. Apply a filter to the search which you know should return an empty query. Do so while your search string is also empty.

The search query will officially be empty, but the #ifHasNoResultsBlock helper method returns false because the search string is empty (see https://github.com/matteodem/meteor-easy-search/blob/master/lib/components/easy-search-components.js#L393).

To work around this I added my own helper which checks the value of the current search result.

~~~
reallyHasResults: function() {
    var instance = EasySearch.getComponentInstance(
      {index : 'dreams', id: 'search-my-dreams'}
    );
    var results = instance.get('searchResults');
    if (typeof results !== 'undefined') {
      if (results.length > 0) {
        return true;
      }
    }
    
    return false;
  }
~~~

**Comment by matteodem** [comment]
Please test this behaviour with v2, it now only checks the count of documents recieved and not the input string itself.
