### ISSUE TITLE
Search over a FS Collection?

### ISSUE THREAD

**Issue by tdhz77** [matteodem/meteor-easy-search#267]
I can't figure out how to search over an FS collection? Anybody have any ideas on how to do this?
I have created a Mongo Collection with the same name as a FS Collection but still get initEasySearch no method defined error. If I use a standard Mongo Collection everything works fine.

**Comment by matteodem** [comment]
Try to use `createSearchIndex`

**Comment by tdhz77** [comment]
Could you give me an example? I don't understand the documentation.

**Comment by matteodem** [comment]
Does FS.Collection extend the normal Meteor Collection? Also try defining the Uploads collection before calling `createSearchIndex`.

Do you use the Blaze Components?

**Comment by tdhz77** [comment]
Yes, I believe that FS Collection extends the normal Meteor Collection. 
cfs.uploads.filerecord
Uploads collection is defined before createSearchIndex and I'm not using Blaze Components.

**Comment by matteodem** [comment]
I don't see a field name in your collection and the associated search call that return no results. Please provide a reproduction repo.

**Comment by tdhz77** [comment]
Thank you issue is resolved. Perhaps an issue with FS Collection. You are right that the field name had issues. Added metadata.name to my db and called the results and everything is good.

Thank you for your time matteodem!
