### ISSUE TITLE
Using esAutosuggest with multiple indexes 

### ISSUE THREAD

**Issue by tdmoneybanks** [matteodem/meteor-easy-search#268]
I wanna use multiple indexes in one search bar. I see that you have to split up the esEach's with the indexes you have defined on the esSearch. Is it possible to have the esAutosuggest suggest values from both indexes? 
Thanks!

**Comment by matteodem** [comment]
No that is not possible yet, what's the use case for that? Why not simply have it in the same collection?

**Comment by tdmoneybanks** [comment]
So I have a global search bar that is going to search over every collection similar to amazon. I had two ideas for how to render all of them. Either render an overlay that has a space for each collection I'm going over (3) with infinite scroll or to use a select 2 style. I suppose my question is what would be best practice to search multiple indexes from a global search bar.

**Comment by matteodem** [comment]
I don't know what your app looks like, but mixing up data from several indexes in an esEach is bad, as every `index` might have different fields.

**Comment by matteodem** [comment]
Please update to v2 and use an `EasySearch.Input` with several `EasySearch.Each` components to achieve this behaviour, see http://matteodem.github.io/meteor-easy-search/docs/components/
