### ISSUE TITLE
{{#esEach }} not returning results even though they are subed. 

### ISSUE THREAD

**Issue by tdmoneybanks** [matteodem/meteor-easy-search#270]
Here is my code which uses the index "xbdgames". 
```
<template name="searchOverlayApp">
	<div class="overlay">
		<a class="js-overlay-close overlay-close">close X</a>
		{{> esInput index="xbdgames" id="search-input" placeholder="search"}}
		<div class="xbdgames-container">
			{{#esEach index="xbdgames"}}
				<p> here they are: {{this}} </p>
			{{/esEach}}
		</div>
	</div>
</template>
```
When I type into the search bar, I can see (using mongol) documents being subbed to under "esSearchResults" but nothing appears under the {{#esEach}}. I also see no errors in the client or server console. Any ideas?

**Comment by matteodem** [comment]
You need to use the same `id` on esInput and eEach, see docs: http://matteodem.github.io/meteor-easy-search/docs/blaze-components/

**Comment by tdmoneybanks** [comment]
ahhh thanks so much
