### ISSUE TITLE
Adding Unicode to esInput Placeholder

### ISSUE THREAD

**Issue by mayvn10** [matteodem/meteor-easy-search#273]
Hi @matteodem 

I'm using esInput in a project I'm building with your easy-search and was wondering if there's a way to add Unicode to the placeholder.

Currently when I do the following

```javascript
{{> esInput index=search class="search-input" placeholder="&#xf002; search"}}
```

.search-input calls the "FontAwesome" font family, but it renders exactly what's there:
```javascript
&#xf002; search
```

When I use normal HTML, the unicode renders as the FontAwesome search glass.

Is there a way to render the unicode using esInput?

**Comment by matteodem** [comment]
How does your normal HTML look like?

**Comment by mayvn10** [comment]
The HTML looks like:

```html
<input autofocus="autofocus" type="search" class="search-input" value="" placeholder="&#xf002; search" />
```

.search-input calls the font family FontAwesome and the unicode renders the search glass inside the placeholder.

**Comment by matteodem** [comment]
Please update to v2 and see if the problem still exists, docs are here: http://matteodem.github.io/meteor-easy-search/docs/core/

**Comment by matteodem** [comment]
Write into this issue if this is still a problem with v2
