### ISSUE TITLE
Preventing flashing

### ISSUE THREAD

**Issue by ChrisCinelli** [matteodem/meteor-easy-search#277]
When user types in esInput and it triggers a search, all the "es" templates flash blank for a few milliseconds before the results of the search are rendered. It would be a better user experience if the content could stay the same until the data is ready. 

I think that this behavior is to better support `ifEsIsSearching`. If that is the reason, ideally it would be good to have a `ifEsIsNotSearching` or `ifEsIsDone` that people can chose to use and prevent the flashing.

**Comment by rwatts3** [comment]
Any solution on this ?

**Comment by matteodem** [comment]
Please update to v2 and provide steps of what the current and expected behaviour is.
