### ISSUE TITLE
Causes a depency conflict on meteor 1.2 RCs

### ISSUE THREAD

**Issue by mquandalle** [matteodem/meteor-easy-search#278]
I tested an application that uses the latest version of `matteodem:easy-search` with the upcoming release of meteor (v1.2). Due to a new compiler API, meteor incremented the major version number of most of the build plugins package. This causes a dependency conflict with less, even if I believe your Less files should work fine with the new `less` package.

Here is the error:

```
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: Conflict: Constraint less@1.0.13 is not satisfied by less
   2.5.0-rc.1_1.
   Constraints on package "less":
   * less@=2.5.0-rc.1_1 <- top level
   * less@1.0.13 <- matteodem:easy-search 1.5.6
```

A reasonable fix could be to explicitly accept both major version of less in `package.js`:

```js
api.use('less@1.0.0||2.0.0')
```

**Comment by matteodem** [comment]
thanks for providing the fix with the issue itself!

**Comment by mquandalle** [comment]
Any ETA? Sorry to ask, but that's the only package preventing me to test the next release of meteor.

**Comment by matteodem** [comment]
Please try out the latest release __1.6.3__ which has your proposed solution in it.

**Comment by mquandalle** [comment]
Thanks, it works :)
