### ISSUE TITLE
semantic-ui Search

### ISSUE THREAD

**Issue by navi8602** [matteodem/meteor-easy-search#279]
Hi all, I use semantic-ui Search but I do not understand how to make it work with the item. Help me please. What am not the body. How to use this search with Easy Search

div class="ui search">
        <div class="ui icon input">
            {{> esInput index="review" id="main" placeholder="Что будем искать?" class="prompt" }}
            <i class="search icon"></i>
        </div>

        <div class="results">
        {{#esEach index="review"}}
            <a class="result"><div class="content"><div class="title">{{name}}</div></div></a>
        {{/esEach}}
        </div>
    </div>

Template.searchBox.rendered = function () {
        $('.ui.search')
            .search({
                source: content
            })
        ;
    };

**Comment by matteodem** [comment]
Please create a more specific issue
