### ISSUE TITLE
Easy search with two lists of the same collection on the same page

### ISSUE THREAD

**Issue by jasonmash** [matteodem/meteor-easy-search#280]
I am trying to use easy search twice on two lists of the same collection on the same page - each list has its own id and search index. I am using mongo-db to do the searching. The problem I am having is that each entity within the collection is shown only on one of the two lists – never both. The search indices are setup as shown below:

```javascript
EasySearch.createSearchIndex('list1', {
  field: 'name',
  collection: Entities,
  use: 'mongo-db',
  query: function(searchString, opts) {
    return EasySearch.getSearcher(this.use).defaultQuery(this, searchString);
  }
});

EasySearch.createSearchIndex('list2', {
  field: 'name',
  collection: Entities,
  use: 'mongo-db',
  query: function(searchString, opts) {
    return EasySearch.getSearcher(this.use).defaultQuery(this, searchString);
  }
});

```
I suspect this issue is caused by each entity within esSearchResults being associated with one _index value only. I’m not sure if this issue is to do with my code or an issue in the package – would you be able to confirm?

**Comment by matteodem** [comment]
Can you elaborate on what the problem is? Go through single steps and what the supposed outcome is and what actually is happening.

**Comment by jasonmash** [comment]
I have two lists shown on the same screen:
-	one shown when a user searches from the navigation bar (in a separate template)
-	another shown within the main page content

See below for an example of what I mean:

![screen shot 2015-09-10 at 13 57 50](https://cloud.githubusercontent.com/assets/2655627/9788787/f32c07a4-57c3-11e5-8b8c-55c62b9e8cf3.png)

Both of these lists are using easy search, and the easy search blaze components for displaying the input field and each of the results.

The blaze components point to different search indices – in the below example companies1 and companies2. The configuration is shown below.

My configuration has the companies1 list shown on screen at all times within the navigation bar. It is limited to 50 records by default with a button to show more. Searching it using the associated input box works perfectly. The correct results are filtered as you’d expect.

The other list (companies2) has the same configuration, but with no limit, and is not shown by default. To see it you have to navigate to a specific page. When on that page, and the first list (companies1) is not being used, searching works fine.

However, when I go to the page with the companies2 list, and start searching in the other list (companies1), it does not show entities that match the search if they are currently displayed in the other list. 

It appears as if the esSearchResults collection only associates results with one search index – when in this instance the same results could be shared across multiple indices.

List 1 setup:
Blaze template:
```javascript
<div class="search-input">
   {{> esInput index="companies1" id="easy-search-global" placeholder="Search..." allDocsOnEmpty=false}}
</div>
<div class="list-group">
    {{#esEach index="companies1" id="easy-search-global"}}
        {{name}}
    {{/esEach}}
</div>
```

Search index:
```javascript
EasySearch.createSearchIndex('companies1', {
  field: ['name','tags'],
  collection: Companies,
  use: 'mongo-db',
  limit: 50,
  sort: function() {
    return {
      'name': 1
    };
  },
  query: function(searchString, opts) {
    return EasySearch.getSearcher(this.use).defaultQuery(this, searchString);
  }
});
```

List 2 setup:
Blaze template:
```javascript
{{> esInput index="companies2" placeholder="search..." allDocsOnEmpty=true reactive=false class="form-control"}}
{{#ifEsIsSearching index="companies2"}} 
     {{> spinner}} 
{{else}} 
     {{#esEach index="companies2"}} 
          <li>{{name}}</li>
     {{/esEach}} 
     {{> esLoadMoreButton index="companies" class="btn btn-default"}} 
{{/ifEsIsSearching}}
```

Search index: 
```javascript
EasySearch.createSearchIndex('companies2', {
  field: 'name',
  collection: Companies,
  use: 'mongo-db',
  query: function(searchString, opts) {
    return EasySearch.getSearcher(this.use).defaultQuery(this, searchString);
  }
});
```

I'm happy to answer any other questions! :)

**Comment by matteodem** [comment]
After quite some time I was finally able to have a look at it, I'll try this use case with v2 and fix it in there.

**Comment by matteodem** [comment]
Please try this again with v2. There is now logic in place that separates the documents published to the client so that both indexes can work independently from one another.

**Comment by jamiecollinson** [comment]
Just upgraded and works for me (I'm working on the same project as @jasonmash). Thanks so much - easysearch is proving invaluable for our project.

Quick question for my understanding - was this only an issue if the engine is minimongo rather than mongodb / elasticsearch? I'm presuming it was to do with how the results were returned to the client via a collection, but wanted to double check.

**Comment by matteodem** [comment]
Yeah so the problem was that the `_id` field was the same when being published to the client but the order / index could've been a different one. So it would match the first index but the next would be ignored as the publication would've readded the same document.

The solution right now is to change the _id to be a combination of the search definiton and the real id and have an additional field called `__originalId` as described here: http://matteodem.github.io/meteor-easy-search/docs/recipes/.

Not really happy with this solution but besides the fact that `_id` is something different it is working fine.
