### ISSUE TITLE
Can't get events working

### ISSUE THREAD

**Issue by kop** [matteodem/meteor-easy-search#281]
Hi and thank you for this great package.

I have a problem with event handlers. Please point me what I'm doing wrong if possible.
According to the [docs](http://matteodem.github.io/meteor-easy-search/docs/component-api/), I'm doing:

```js
/**
 * Template "NotepadIndex" hooks.
 */
Template.NotepadIndex.onCreated(function () {

    var self = this,
        searchInstance = EasySearch.getComponentInstance({
            id: 'notepadSearch',
            index: 'myProspects',
            autorun: self.autorun
        });
    searchInstance.on('searchingDone', function (searchingIsDone) {

        if(searchingIsDone){

            // Align blocks with packery
            var prospectsContainer = self.$('.prospects-container');
            prospectsContainer.packery({
                itemSelector: '.single-prospect',
                gutter: 0
            });

            // Shorten bio texts
            self.$('.prospect-description').dotdotdot({
                height: 70
            });
        }
    });
});
```

And ofcourse I the view I have all es-related componenets declared with id `notepadSearch`.
However, as a result I have:

```
Exception from Tracker recompute function: undefined
debug.js:43 TypeError: Cannot read property 'autorun' of undefined
    at Blaze.TemplateInstance.autorun (http://my-site.com/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3361:19)
    at Object.EasySearch.getComponentInstance.on (http://my-site.com/packages/matteodem_easy-search.js?74d87f9aff1f9210a65da6a48bf9533236ee854b:1866:16)
    at null.<anonymous> (http://my-site.com/client/views/notepad/index.js?cca27b27dc329c428065d6d5d3c23db039762c89:13:20)
    at http://my-site.com/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3155:22
    at Function.Template._withTemplateInstanceFunc (http://my-site.com/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12)
    at fireCallbacks (http://my-site.com/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3151:12)
    at null.<anonymous> (http://my-site.com/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3231:5)
    at fireCallbacks (http://my-site.com/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1941:16)
    at Object.Tracker.nonreactive (http://my-site.com/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:593:12)
    at http://my-site.com/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1938:13 undefined
```

**Comment by matteodem** [comment]
What does `console.log(self.autorun)` print out?

**Comment by kop** [comment]
@matteodem,

`console.log(self.autorun)`:

```
function (f) {
  return this.view.autorun(f);
};
```

From what I understood from my investigations is that `this.view` is undefined.
Problems occurs not when I'm trying to get a search component instance, but when I'm trying to:

```
searchInstance.on('searchingDone', function (searchingIsDone) {});
```

It resolves to this autorun function and to the missing view variable.

**Comment by methodbox** [comment]
I am currently experiencing the same issue with a massive number of errors, but the original issue was this error:

```Exception from Tracker recompute function: undefined```

When I run ```console.log(self.autorun)``` I get ```undefined```.

This is using your default example for Autosuggest field from here:

http://matteodem.github.io/meteor-easy-search/docs/autosuggest-field/

**Comment by matteodem** [comment]
Remove the `autorun` property from there for now

**Comment by methodbox** [comment]
This is still not working, you're suggestion of doing so without autorun also does nothing. Not clear why this is closed.
Opening a separate issue to document my experience.

**Comment by matteodem** [comment]
Do you still get an error without the autorun specified?

**Comment by matteodem** [comment]
I'll close this issue again as it has been inactive for more than a week now.
