### ISSUE TITLE
How to customize markup of load more button? 

### ISSUE THREAD

**Issue by sizovilya** [matteodem/meteor-easy-search#282]
Hi!
Can I customize text and markup of esLoadMoreButton ?

**Comment by aguegu** [comment]
I had exactly the same issue. I use meteroric for the frontend, so I can add iconic class to the class property to change the look. The text can be modified by 'content' property. It may not be as customizable as you need. But it is better than nothing.

    {{>esLoadMoreButton index="products" content="Load more products ..." class="button button-full button-clear button-stable"}}

**Comment by matteodem** [comment]
I'll make this more configurable in the next version.

**Comment by matteodem** [comment]
This is resolved as of v2, you can now give it an `attributes` parameter that is an object, specifying the object attributes (class, id and so on), see http://matteodem.github.io/meteor-easy-search/docs/components/.
