### ISSUE TITLE
Use props in permission method

### ISSUE THREAD

**Issue by sferoze** [matteodem/meteor-easy-search#284]
I am using changeProperty function to pass parameters to Easy Search from the client. 

`EasySearch.changeProperty('notes', 'notepadId', [notepad._id])`

But the permissions key does not pickup on the new props to check if the user has permission. 

the props key still stays at the original value it was set. 

How can I pass properties to the permission function, like I do to the query function?

**Comment by matteodem** [comment]
You need to call `triggerSearch`, see http://matteodem.github.io/meteor-easy-search/docs/component-api/ and the leaderboard as an example https://github.com/matteodem/orion-cli

**Comment by sferoze** [comment]
aw so this means I cant use the built in event detection? I have to add code to detect input change and then call the triggerSearch? How can I have it so I keep the code as is, but the permissions is based  off of the current properties.

**Comment by matteodem** [comment]
You only need to call `triggerSearch` when you want __custom__ behaviour (for example select elements, other input fields) and so on.

**Comment by sferoze** [comment]
hi @matteodem 

but how can I access the properties in the permission function? If I use the API to change the properties, the permission function does not pickup on this change

**Comment by matteodem** [comment]
I wouldn't do the permission handling over Easy-Search, but rather have documents or rules in your 'query' method that define which documents are searchable

**Comment by sferoze** [comment]
@matteodem This is what I am doing and it is currently working. In the query function I use the properties to define which documents are searchable for that user. 

But my worry is that anyone can go into the console, use the changeProp API and pass in the notepadID for a notepad they don't have access too. Then they would be allowed to search it I believe. So that is why I was thinking that permission function would be run before each query and would use the latest properties.

**Comment by matteodem** [comment]
Can you show me part of your query code? The notpadID will only be in the `props` object, and that should be ignored by your query method. Or not have crucial code that defines the documents that are searchable.

`permission` is only thought for yes, no answers to if the user can search the index, not which documents can be searched.

**Comment by sferoze** [comment]
Hi @matteodem 

Here is my code that defines the searching notes within a notepad

```coffee
EasySearch.createSearchIndex 'notes',
  field: ['text', 'title']
  'limit': 10
  'props':
    'notepadId': []
    'archived': false
  collection: Notes
  use: 'mongo-db'
  'useTextIndexes': true
  query: (searchString, opts) ->
    # Default query that is used for searching
    query = EasySearch.getSearcher(this.use).defaultQuery(@, searchString)
    if @props.notepadId.length > 0
      query.notepadId = {$in: @props.notepadId}
    query.archived = @props.archived
    query
  permission: ->
    true
    #@userId?
    # if @props.notepadId.length > 0
    #   notepad = Notepads.find({_id: {$in: @props.notepadId}, $or: [{userId: @userId}, {'collaborators.userId': @userId}], archived: false})
    #   notepad.count() > 0
  sort: ->
    ob =
      score:
        $meta: 'textScore'
```

As you can see I am searching the notes collection for notes within the users notepad. 

So on the client I use 

```coffee
EasySearch.changeProperty('notes', 'notepadId', [notepad._id])
EasySearch.changeProperty('notes', 'archived', false)
```

to change the parameters for the query search. 

But the permissions does not pickup on these new parameters. If you look at the commented out code in the permission function, that is what I tried which did not work. 

Does it make sense to you my issue? Any suggestions?

**Comment by matteodem** [comment]
I would rather do the $or search query with the userId in the query method, so that you don't need to check the properties / notepads themselves in the permission method.

The `query` returns a MongoDB selector, so that should be no problem.

**Comment by sferoze** [comment]
ah yah that makes sense! I dono why I didn't think of that. The query itself can handle the permission

**Comment by sferoze** [comment]
@matteodem actually there is an issue.

The query is on the Notes collection. The notes collection itself does not know which subset of notes a specific user is allowed to access. The notepad collection know which notes the user is allowed to access. But the query is running on the notes collection. 

This is why I wanted to use the permission function to query the notepad collection based on the current properties and return true or false. 

Any suggestions? I can't check permission by altering the query function for notes. I need to check the notepad collection. 

This would not be an issue if the permission function would recognize `this.props.notepadId`

**Comment by matteodem** [comment]
I think it makes more sense to think more about your data structure and try to have it work there. Since it doesn't look like me that it's a general permission to search the index, that we're talking about here. right?

**Comment by sferoze** [comment]
Basically you need to have access to a document in the 'Notepad' collection to see if you can search the 'Notes' collection. 

So before searching the Notes collection. I need the permission function to check if the user has access to a document in the Notepad collection. 

Here is my publish function which might give more info

```coffee
Meteor.publishComposite 'myNotepad', (notepadId, noteLimit) ->
  {
    find: () ->
      Notepads.find({_id: notepadId, $or: [{userId: @userId}, {'collaborators.userId': @userId}], archived: false})
    children: [
      {
        find: (notepad) ->
          Notes.find
            notepadId: notepad._id
            archived: false
          ,
            limit: noteLimit
            sort: 
              rank: 1
      }
    ]
  }
```

As you can see if first finds notepads the user is allowed to access. Then based on that is returns notes.

I want to setup something similar for Easy Search. 

The solution is to use the permissions function but it does not pickup on the properties set with EasySearch.changeProperty

What do you recommend. I can't really change the data structure. Each note should not need to have access information. The notepad stores that info. And if you can access the notepad, then you can access any note with that notepadID.

**Comment by matteodem** [comment]
It should be possible to construct that notepad selector together with the `props` in the `query` method. (try to do a Notepad.find() in there).

**Comment by sferoze** [comment]
Hmm I tried but it looks like @userId or Meteor.userId() is not available in the query method? Did you know this? I can't trust the client to pass in their own userID because they could pass in anything. How do I get the userId in the query function?

**Comment by sferoze** [comment]
@matteodem I want to follow up on this issue.

Currently in the query, and the permissions function I do not have access to the userId of the person searching.

In the permission function I log out `this.userId` and its undefined, even though im logged in

same issue in the query function, no `this.userId`

`Meteor.userId()` does not work either. Even worse it throws an error saying to only use `this.userId`

How are you supposed to use the permissions if you cannot access this.userId? I would like access to `this.userId` in the query function as well.

**Comment by matteodem** [comment]
read the manual: http://matteodem.github.io/meteor-easy-search/docs/javascript-api/  (`this.publicationScope`)

**Comment by sferoze** [comment]
@matteodem ah sorry I missed that, thanks! 

Actually I might point out though that the documentation is incorrect. 

I console.logged out `this` and there is no this.publicationScope. 

It has been renamed this.publishScope.

And to get the userId you need.

`userId = this.publishScope.userId`

**Comment by matteodem** [comment]
thanks, I'll fix that.
