### ISSUE TITLE
Option to show all elements if there is no text input

### ISSUE THREAD

**Issue by joaobarcia** [matteodem/meteor-easy-search#285]
As https://github.com/matteodem/meteor-easy-search/issues/82#issuecomment-138102765 and https://github.com/matteodem/meteor-easy-search/issues/200 I think it would be extremely useful to have the option to display all results if there is no text input.

Although it is possible to display any information through the blaze tag {{#ifEsInputIsEmpty}}, it is not possible to associate the elements inside this tag with the current query and sort options.

Maybe easier explained with the following image:
![easy search github issue](https://cloud.githubusercontent.com/assets/6717014/9720860/79ee308c-558a-11e5-8530-7487f5f9a2f6.png)

By having a "display all elements" option in easy search it would be possible to keep the selected queries/sorters even when displaying all the elements. Thus having a cleaner code and structure

**Comment by matteodem** [comment]
It is possible to return a selector that matches "all" documents, when the searchString is empty. See http://matteodem.github.io/meteor-easy-search/docs/javascript-api/.

**Comment by joaobarcia** [comment]
Thanks for the feedback and the great lib. I'm running into some difficulties on where to place the code. Would it be possible to create a recipe?

I've tried placing code in the 'query': function(searchString, opts) {} but it seems that it is only called when the searchString is not empty.

I've also tried placing the code as an event. The code as mentioned in http://matteodem.github.io/meteor-easy-search/docs/component-api/ (Handling Events section) seems that it makes my page unable to render.

**Comment by matteodem** [comment]
I'll add that with v2

**Comment by joaobarcia** [comment]
Hi matt, that would be great! 

Could you give us some pointers on how to achieve it in the meanwhile?

**Comment by matteodem** [comment]
How about `allDocsOnEmpty` http://matteodem.github.io/meteor-easy-search/docs/blaze-components/?

**Comment by joaobarcia** [comment]
Oh... my bad... It was extremely straightforward.

**Comment by brewhk-dev** [comment]
For those who are reading this in 2016, `allDocsOnEmpty` is now [`noDocumentsOnEmpty`](http://matteodem.github.io/meteor-easy-search/docs/components/)

    {{> EasySearch.Input index=myIndex noDocumentsOnEmpty=false}}
