### ISSUE TITLE
Tika integration

### ISSUE THREAD

**Issue by dropfen** [matteodem/meteor-easy-search#286]
Hi matteo,
what do you think, how hard it would be add the elastic attachments plugin, and expose it in the api for file searching?

Thank you

**Comment by matteodem** [comment]
Hey there

Right now it's useful for syncing MongoDB documents to indexes and make them searchable over ES. It's not really fit for using existing indexes. How would you like to use Easy-Search together with an existing index? Any usecase?

**Comment by dropfen** [comment]
Look we are at the point where we are evaluating different strategies for the search solution. So, I find your ES integration very good.

The file search scenario, which I have in mind, is, that we will have a "filesCollection" with the path, name, and some meta-info.. Store the file somewhere in the file system.. and then we provide the fileId and content of the file as base64 string to ES. The docs says, that you just have to map it as 

`myFile: {type: "attachment"}`
see the docs [elasticsearch-mapper-attachments](https://github.com/elastic/elasticsearch-mapper-attachments)
And I was thinking, that this should be not a problem to do.

**Comment by dropfen** [comment]
Of course you have to install the attachments plugin to use it, like you have to do with ES itself.

**Comment by matteodem** [comment]
I'll have this open for now.

**Comment by dropfen** [comment]
I am studying your code, and I think, the best way would be to create an easy-search-files package and extend it to use like in this pseudo code:

  `EasySearch.createFilesIndex({'myFiles', { collection, 'filePathKey' })`

And this should return only the fileIds, nothing more..

Because we need a special observer which will encode the files to base64, and it's not good to add this condition into the existing code, this will add extra complexity, which nobody wants ;)

**Comment by matteodem** [comment]
I don't think this is something that needs to be in core, but you could create a `searcher` which handles file indexes.

**Comment by dropfen** [comment]
yeah, exactly
