### ISSUE TITLE
changeResults not called when using mongo-db?

### ISSUE THREAD

**Issue by mbreuer23** [matteodem/meteor-easy-search#287]
Awesome package; immensely helpful.

It appears that changeResults() is not called when using "mongo-db", but is called when using "minimongo".  Is this accurate, and if so, is there a reason for that?  

I was hoping to be able to changeResults on the server (by adding fields from other collections) without having to worry about having all the necessary data published to the client, but I'm having trouble getting that working.

When I use "minimongo" it works as expected, however.

**Comment by matteodem** [comment]
Yes, this is not possible right now with `mongo-db`, this will change though with v2.

**Comment by matteodem** [comment]
see #247

**Comment by againer** [comment]
+1 for this please.

If you are impatient, you can use `.searchMultiple` instead of `.search`.  This seems to force `.changeResults` to be called.  Doing it this way however, takes away your ability to use `#esEach`, `EsHasNoResults` in your template.  Instead you can set some reactive vars (dicts or whatever) in the callback. It might look something like this:

```
...searcher.searchMultiple(['index1, ...,  'indexN'], someQuery, (error, results) => {
  //set reactive template vars here
  //results is altered based on your index's changeResults function.
  console.log(results);
]);
```

**Comment by matteodem** [comment]
v2 will have a more consistent approach to this. Won't take too long anymore until it's out.

**Comment by againer** [comment]
I have a forked version of easy-search using reywood:publish-composite.  Do you have plans to hook it up for v2?  Are you interested in seeing a PR for it?

**Comment by matteodem** [comment]
I'd like to have a general way of changing the publishing of documents, but feel free to create a PR, definitely interested in seeing how you solved that problem.

**Comment by matteodem** [comment]
As of v2 there is `beforePublish` (only for engines that search on the server, `MongoDB`, `MongoTextIndex` and so on, not `Minimongo`) and `transform`, see http://matteodem.github.io/meteor-easy-search/docs/recipes/.

Please try it out and write into this issue or a new one if there are any other problems.
