### ISSUE TITLE
 has no method 'aggregate'

### ISSUE THREAD

**Issue by tdhz77** [matteodem/meteor-easy-search#288]
EasySearch.createSearchIndex('uploads', {
collection: Uploads,
field: 'original.name',
limit: 4
});

I20150918-11:31:25.760(-5)? Exception from sub uploads/easySearch id MBN4wwyTBLKcqRAkm TypeError: Object #<EventEmitter> has no method 'aggregate'
I20150918-11:31:25.760(-5)?     at Object.methods.search (packages/matteodem:easy-search/lib/searchers/mongo.js:93:1)
I20150918-11:31:25.761(-5)?     at [object Object]._handler (packages/matteodem:easy-search/lib/easy-search-common.js:85:1)
I20150918-11:31:25.761(-5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150918-11:31:25.761(-5)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
I20150918-11:31:25.761(-5)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150918-11:31:25.761(-5)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150918-11:31:25.761(-5)?     at packages/ddp/livedata_server.js:546:1

**Comment by matteodem** [comment]
Which version of Meteor are you using?

**Comment by PauliBuccini** [comment]
@matteodem, well actually I encountered same error on server. I am having in on `METEOR@1.2.0.1`.
As well it only happens, at least in my case, searching Meteor.users collection

**Comment by matteodem** [comment]
Can you show me your index config?

**Comment by PauliBuccini** [comment]
EasySearch.createSearchIndex('users', {
  'collection': Meteor.users,
  'field': ['fullName', 'company', 'emails.0.address', 'position'],
  'limit': 10,
  'use' : 'mongo-db',
  'convertNumbers': false,
  'sort': function() {
    return { 'fullName': -1};
  },
  'query': function(searchString, options) {
    var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);
    if (this.props.notInApp) {
      query.purchasedApps = {}
      query.purchasedApps['$ne'] = this.props.notInApp;
    }
    if (this.props.notInCompany) {
      query.addedCompany = {}
      query.addedCompany['$ne'] = this.props.notInCompany;
    }
    query.isDeleted = false;
  }
});

**Comment by PauliBuccini** [comment]
@tdhz77 @matteodem, well eventually issue was caused by matb33:collection-hooks, which were added  earlier then easy-search, simple solution is to have easy-search package added earlier then other packages which are interfering with collections.

**Comment by matteodem** [comment]
oh okay, that's weird that collection-hooks overwrite those methods
