### ISSUE TITLE
Easy search with string and mongo find on query 

### ISSUE THREAD

**Issue by almogdesign** [matteodem/meteor-easy-search#289]
I'm trying to setup an easy search with use mongo find and the search query string, the mongo find is working and always returning posts that belong to a user even if the search string does not match it shouldn't show any post is the search does not match 

What am I doing wrong? 

```javascript
EasySearch.createSearchIndex('myPosts', {
    'collection': Posts,
    'field': ['category', 'subCategory', 'quantity', 'quality'],
    'limit': 8,
    'use' : 'mongo-db',
    'sort': function() {
        return { 'createdAt': -1};
    },
     'query': function(searchString, opts) {
     var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);
     query =  {posterId:this.publishScope.userId, isClaimed:0}
     return query;
     }
});
```

**Comment by matteodem** [comment]
Have a look at the contents of `query` and modify it to your needs. Default behaviour is to either match the search string in one of your specifield `field`s.

**Comment by matteodem** [comment]
Also, don't overwrite the query. You need to obviously write your code as:


```javascript
query.posterId = { ... };

// instead of:
// query = { posterId: ... }, which sets a new query variable
```

Please take a closer look at your code before opening an issue.

**Comment by almogdesign** [comment]
I have this 
var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString); 

Which I understand matches the searchString 

but then I have  

query =  {posterId:this.publishScope.userId, isClaimed:0}

which I guess overrides it how can add the two
