### ISSUE TITLE
Clear search results

### ISSUE THREAD

**Issue by wbashir** [matteodem/meteor-easy-search#29]
I am not sure but is there an underlying function within the source code to explicitly reset the search input `esInput` and the search results. Users of my application have found the search results stale when they browse away from a route and I would like to reset it back or I should say run a clear, if that is possible ?

**Comment by Shelagh-Lewins** [comment]
I can't get this working, EasySearch.Components doesn't seem to exist and I don't know what "index" or "id" should be? It's really important to automatically close the results list and clear the box when the user selects a result. I can't find any reference to 'clear' in the docs.

**Comment by dylanmcgowan** [comment]
I'm also wondering how to do this.  Looking at the EasySearch object there is a EasySearch.Cursor.emptyCursor object but that is the closest thing i can find.  How do you 'clear' the results with the new version?? thanks.

**Comment by matteodem** [comment]
I think this got forgotten with v2, it might make most sense to always reset "search results" as soon as the user navigates away. I'll implement it that way for now.

**Comment by matteodem** [comment]
Should have that behaviour now in latest version, please check it out.

**Comment by dylanmcgowan** [comment]
How do you do it? 
like 
```
EasySearch.Components.clear(index, id);
```

or 
```
EasySearch.Cursor.emptyCursor 
```
?

**Comment by matteodem** [comment]
Do you want an explicit clear method? I did not add it but one way would be to use component methods to search for an empty string.

**Comment by dylanmcgowan** [comment]
Oh thats kind of genius haha, a dedicated method would be nice, but the empty string does the trick for now.

**Comment by Shelagh-Lewins** [comment]
I tried patternsIndex.search("");, but the search results stayed on screen. What am I dooing wrong?

**Comment by Shelagh-Lewins** [comment]
Note: I want to hide the list if the user presses 'Esc' or clicks outside the list, so they don't have to go into the input and delete the search term to hide the search list. So that's a use case for manually clearing the list. I haven't tried it yet but I expect that your suggestion of searching for empty string will work for this.

**Comment by meecect** [comment]
I can't get this to work.

I tried:

```
    ContentSearchIndex.getComponentMethods().reset();
```
and

```
    ContentSearchIndex.getComponentMethods().search("");
```
when I clear the search this way I just get all results, even though my search input component has noDocumentsOnEmpty=true:

```
    {{> EasySearch.Input indexes=searchIndexes charLimit=2 noDocumentsOnEmpty=true attributes=searchBoxAttributes}}
```
