### ISSUE TITLE
Upgrade less version for meteor 1.2

### ISSUE THREAD

**Issue by Neobii** [matteodem/meteor-easy-search#290]
The new meteor version has a less dependency of 2.5.0_1.
error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0_1.
Constraints on package "less":
* less@1.0.0||2.0.0 <- matteodem:easy-search 1.6.3

**Comment by dfischer** [comment]
Yeah this is pretty critical. @matteodem possible to get an update today with this?

**Comment by matteodem** [comment]
This is fixed in the latest version.

**Comment by sferoze** [comment]
Hmm I just upgraded to meteor 1.2. It did not upgrade completely. got some text saying which packages were not updates. But now when I try and start my server I get

```
While selecting package versions:
   error: Potentially incompatible change required to top-level dependency: matteodem:easy-search 1.6.3,
   was 1.6.4.
   Constraints on package "matteodem:easy-search":
   
   To allow potentially incompatible changes to top-level dependencies, you must pass
   --allow-incompatible-update on the command line.
```

**Comment by sferoze** [comment]
I figured it out. Meteor upgraded Easy Search to 1.6.4 but Meteor itself did not upgrade to 1.2 because of other incompatible packages. So I downgraded easy search and it worked again.

**Comment by matteodem** [comment]
:+1:
