### ISSUE TITLE
Why does this depend on less?

### ISSUE THREAD

**Issue by dfischer** [matteodem/meteor-easy-search#291]
Why does this depend on less?

**Comment by matteodem** [comment]
Because of the autosuggest component

**Comment by dfischer** [comment]
Forcing people to use less isn't cool. Instead it should be pure CSS or an optional less add-on. It's causing bloat, especially when people use SCSS.

**Comment by dfischer** [comment]
The code in https://github.com/matteodem/meteor-easy-search/blob/master/lib/components/easy-search-components.less is not enough to justify requiring less. It would be really awesome to have that as an optional add-on, or just part of the readme as CSS to copy+paste.

**Comment by matteodem** [comment]
Will change with the next version, give me another 2 weeks and it's out.

**Comment by dfischer** [comment]
Awesome, you rock.

**Comment by matteodem** [comment]
Removed the less dependency as of the latest version
