### ISSUE TITLE
Update to Meteor 1.2 

### ISSUE THREAD

**Issue by almogdesign** [matteodem/meteor-easy-search#292]
I'm getting the following message / error when trying to update to meteor 1.2 

Potentially incompatible change required to top-level dependency: matteodem:easy-search 1.6.3, was 1.6.4.
Constraints on package "matteodem:easy-search":

**Comment by Neruell** [comment]
same here

**Comment by matteodem** [comment]
I need more information on this, show me the list of packages you're using or a reproduction repo.

**Comment by Neruell** [comment]
I tried to remove the package and also others which were displaying the same error with "less" incompatibility. Afterwards I added this package easy-search and it seemed to work fine and didn't report the same issue. So I guess the issue is not really with this package.
