### ISSUE TITLE
Search works oddly, some text/number searches dont yield the desired results. 

### ISSUE THREAD

**Issue by mervynteo** [matteodem/meteor-easy-search#294]
When I search for say a specific item, seems like more results appear than required. 
Not sure if I need to add any custom rules or theres a bug. 

For example when you type: 
title one --> all results appear (wrong) 
4            --> only title 4 appears (correct) 
title 4      --> again all results (wrong)

I have an example here
http://meteorpad.com/pad/ee4AraCZxPLWaGd7k/search%20(github)

**Comment by matteodem** [comment]
Please provide reproduction steps or a repository.
