### ISSUE TITLE
Error while search across multiple collections

### ISSUE THREAD

**Issue by mervynteo** [matteodem/meteor-easy-search#295]
So say each post has comments. Both have their respective collections. 
I implemented the below based on the examples on the website. 

I got the following error when I try to load the search page: 
>TypeError: Cannot read property 'limit' of undefined

On typing in the search field, I get the following error:
>Uncaught Error: Match error: Expected number, got undefined

--

### JS client
```javascript
//Posts = new Mongo.Collection('posts');
//Comments = new Mongo.Collection('comments');
// Comments are linked to Posts by postId

EasySearch.createSearchIndex('posts', {
   'field'        : ['title', 'body'], 
   'collection'   : Posts,
   'use'          : 'mongo-db',
   'limit'        : 20,
});
EasySearch.createSearchIndex('comments', {
   'field'        : ['body'],
   'collection'   : Comments,
   'use'          : 'mongo-db',
   'limit'        : 20,
});
Template.searchPosts.helpers({ 
   'indexes' : function () {
       return ['posts', 'comments'];
   }
});
```

### HTML
```html
{{> esInput index=indexes placeholder="Search..." convertnumber=true}}  
 {{#ifEsIsSearching index=indexes}}  <!-- removed the " " around indexes -->
      <div>Loading...</div>
      {else}}
           {{#esEach index="posts"}}
        	{{> postItem}}
            {{/esEach}}

             {{#esEach index="comments"}}
                 {{> postItem}}
             {{/esEach}}
       {{/ifEsIsSearching}}

    {{#ifEsHasNoResults index=indexes}}
          <div class="no-results">No results!</div>
    {{/ifEsHasNoResults}}
```

**Comment by matteodem** [comment]
Your HTML should be `{{> esInput index=indexes .. }}` without the `"` around it.

**Comment by mervynteo** [comment]
Thanks for the package and the quick reply. 
I used both and results are the same. Let me try test it again and confirm with you on the results.

**Comment by mervynteo** [comment]
Hi Matt, 
It got rid of the error message. Right now it just doesn't show any search results.. just says "Loading".
No other error messages on the server side.

**Comment by matteodem** [comment]
What did you change?

**Comment by mervynteo** [comment]
Have updated the lines, have only removed the " " around indexes. It shows loading message, probably stuck at {{#ifEsIsSearching index=indexes}}. Would you have any suggestions on how to troubleshoot or test? Thanks!

**Comment by matteodem** [comment]
Try to print out component values, see here http://matteodem.github.io/meteor-easy-search/docs/component-api/

**Comment by mervynteo** [comment]
Ok ill give it another shot. 
By the way do i need to edit this line ... Template.yourTemplate.indexes = ['players', 'cars'];?
It says this way of writing is deprecated in favor of Template.youTemplate.helper ({});

**Comment by matteodem** [comment]
yep, use helpers, I'll be sure to use the current Meteor API in the new docs.

**Comment by mervynteo** [comment]
Although this probably will not solve the original issue of no search results + loading message, wanted to confirm if the below helper is correctly written? 

```javascript
// From this  -- Template.searchPosts.indexes = ['posts', 'comments'];
// to 
// this 

Template.searchPosts.helpers = ({
   'indexes': function({                            //or simply 'index' =  ['posts', 'comments] 
      ['posts', 'comments] 
   })
});
```

**Comment by matteodem** [comment]
You can see that even github shows you your errors :).

```javascript
Template.searchPosts.helpers = ({
   'indexes': function({                            //or simply 'index' =  ['posts', 'comments] 
      return ['posts', 'comments'];
   })
});
```

**Comment by mervynteo** [comment]
@matteodem  Your right, attached the corrected lines. 
```javascript
Template.searchPosts.helpers({
   'indexes' : function () {                 
      return ['posts', 'comments'];
   }
});
```

**Comment by matteodem** [comment]
yep, are you using `collection-hooks`?

**Comment by mervynteo** [comment]
I dont have it in my packages.

**Comment by matteodem** [comment]
`index: "indexes` is wrong. You need to specify the name of an index, what you specified there doesn't make any sense. Please try to understand before copying code.

**Comment by mervynteo** [comment]
Apologies, I should mention that was a last ditch attempt. Im quite a newbie so please bear with me. 

Using just index: 'posts' would make the test input work but yield no search results. 
I had to fit 2 indexes within the code and tried the following due to errors shown: 

```javascript
{ id: 'main', index: 'posts', index: 'comments' }     //search test input fails
{ id: 'main', index: 'posts', 'comments' }
{ id: 'main', index: indexes }                                //says indexes is not defined
{ id: 'main', index: ['posts', 'comments'] }            //search test input fails 

// lastly
{ id: 'main', index: 'posts' },
{ id: 'main', index: 'comments' }        // passes test input, shows in console.log but no search results

**Comment by matteodem** [comment]
Why are your collections commented out in your first code example?

**Comment by matteodem** [comment]
Also please show me example docs.

**Comment by mervynteo** [comment]
@matteodem 
I included them to show I have them in my lines, they are commented out above as they are not the source of the problem. 

For the example docs, Im playing around with the Microscope project [here](https://github.com/DiscoverMeteor/Microscope/tree/master/client)

**Comment by matteodem** [comment]
Where did you put the javascript code?

**Comment by mervynteo** [comment]
Hi @matteodem , 
I placed the search.js and search.html within the client only side. The 2 files I have not added into the Github yet. The collection lines are at the collection folder within the library side (accessible by both client and server)
The lines for those files are provided above when I wrote the post. 

Let me know if you need me to post the lines to you?

Thanks!

**Comment by matteodem** [comment]
did you see in the tutorial that it states following?

```
// On Client and Server
```

:smile:

**Comment by matteodem** [comment]
Please have a look at the leaderboard example if there are anymore questions like this https://github.com/matteodem/easy-search-leaderboard

**Comment by mervynteo** [comment]
I did see the statement and comment, but thought it would be odd to repeat it twice, one in client and one on server? 

Just a quick clarification, in your example (which I have also been referring to), the createindex is only within the "if server" portion. So would a single copy within server files do the trick? 

Im asking because I did up a isolated but simple working version that works (albeit a little odd) in my other question posted on Github. The createindex was in the "common.js" file and not server.js, Not sure if you managed to see it?

**Comment by matteodem** [comment]
You can just simply create a .js file that loads on both environments, that's what Meteor and other frameworks call __isomorphic code__. Please have a look at the leaderboard example.

**Comment by mervynteo** [comment]
Isee, ok I get what you mean now. To put it on the common folder.
Ok will test it out and let you know the results. Thanks!

**Comment by matteodem** [comment]
Feel free to write into this issue if this still is an issue.

**Comment by mervynteo** [comment]
Just wondering if searching across multiple index is still supported in the new version 2.0 and if yes, any changes? Im still troubleshooting it and it may be due to a need for joins between 2 collections.

**Comment by matteodem** [comment]
See https://github.com/matteodem/meteor-easy-search/blob/master/UPGRADE-2.0.md, it's not needed anymore since you got your index instance now to search on.
