### ISSUE TITLE
changing placeholder text breaks search 

### ISSUE THREAD

**Issue by thomasspiesser** [matteodem/meteor-easy-search#296]
hey,
first of all: thanks for the great package!

I have an issue while implementing translation of my app. I use a template helper to set the placeholder text in esInput like so:

    {{ > esInput index="courses" placeholder=getPlaceholder class="form-control" allDocsOnEmpty=true value=query }}

and the helper

    getPlaceholder: function () {
      return i18n('search.short'); // this returns a string like "search.." (en) or "cherche..." (fr)
    }

this works great except for when i change the language while on the search template. it does not trigger a new search. on the client the value of `currentValue` still changes but the `query` function in `createSearchIndex` does not log anything anymore (i `console.log()` the `searchString` that is passed to the `query` function).

any ideas?

**Comment by matteodem** [comment]
Did you try to call `triggerSearch` with the components API?`http://matteodem.github.io/meteor-easy-search/docs/component-api/

**Comment by thomasspiesser** [comment]
calling `EasySearch.getComponentInstance({ index: 'courses' }).triggerSearch()` from the browser console works fine and triggers the search with the value from the `esInput` template. however, the `esInput` itself does not trigger the search anymore.

**Comment by matteodem** [comment]
What does "the esInput itself does not trigger the search anymore"? Once you change the language the input becomes not functional, as in nothing works anymore or it just doesn't searhc on the "language switch"?

**Comment by thomasspiesser** [comment]
meaning non-functional - nothing works anymore.

**Comment by thomasspiesser** [comment]
I used your code snippet from [here](http://matteodem.github.io/meteor-easy-search/docs/component-api/) to log what the user is searching for in the client like so

```javascript
Template.searchCourse.onCreated(function () {
  var self = this,
    instance;

  instance = EasySearch.getComponentInstance(
    { index: 'courses' }
  );

  instance.on('searchingDone', function (searchingIsDone) {
    searchingIsDone && console.log('I am done!');
  });

  instance.on('currentValue', function (val) {
    console.log('The user searches for ' + val);
  });
});
```

and logged also the searchstring like so:
```javascript
EasySearch.createSearchIndex('courses', {
  'field' : ['title', 'description'],
  'collection' : Courses,
  'use' : 'minimongo',
  'limit': 50, 
  'props': {
    'filteredCategory' : 'Alle',
    'onlyShowPublic' : true
  },
  'sort': function () {
    return { 'hasDate': -1, 'dates': 1 };
  },
  'query' : function (searchString, opts) {
    // Default query that is used for searching
    var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);

    // this contains all the configuration specified above
    if (this.props.onlyShowPublic) {
      query.isPublic = true;
    }
    // filter for category if set
    if (this.props.filteredCategory !== 'Alle') {
      query.categories = this.props.filteredCategory;
    }
    // or more than 1 category: props.filteredCategories must be [] then!
    // if (this.props.filteredCategories.length > 0) {
    //   query.categories = { $in : this.props.filteredCategories };
    // }
    console.log('logging searchString in createSearchIndex query function:');
    console.log(searchString);
    return query;
  }
});
```

to illustrate a bit more what happens. here is the console output before language switch, searching for word 'dark':

searchCourse.js:10: I am done!
searchCourse.js:14: The user searches for da
easySearch.js:31: logging searchString in createSearchIndex query function:
easySearch.js:32: da

searchCourse.js:10: I am done!
searchCourse.js:14: The user searches for dar
easySearch.js:31: logging searchString in createSearchIndex query function:
easySearch.js:32: dar

searchCourse.js:10: I am done!
searchCourse.js:14: The user searches for dark
easySearch.js:31: logging searchString in createSearchIndex query function:
easySearch.js:32: dark

then i switch the language and search again:

searchCourse.js:10: I am done!
searchCourse.js:14: The user searches for da

searchCourse.js:10: I am done!
searchCourse.js:14: The user searches for dar

searchCourse.js:10: I am done!
searchCourse.js:14: The user searches for dark

does that illustrate the issue a bit more?

**Comment by matteodem** [comment]
Please upgrade to v2 and try it out now. There is a `attributes` parameter on the input, see http://matteodem.github.io/meteor-easy-search/docs/components/

**Comment by thomasspiesser** [comment]
wow, you re-did the whole thing! I'll check it out, thanks.

**Comment by matteodem** [comment]
How did this go?

**Comment by matteodem** [comment]
Please feel free to write into this issue if this is still a problem.

**Comment by thomasspiesser** [comment]
Hey, I finally managed to update to v2. Issue is solved with this! Thanks a lot.
