### ISSUE TITLE
Results Flash When The Search is Complete

### ISSUE THREAD

**Issue by rwatts3** [matteodem/meteor-easy-search#297]
Have you found a solution to the flashing of the documents when elastic search loads? 
This is really an eye sore and any solution would be greatly appreciated.

**Comment by matteodem** [comment]
Do you have a video or any reproduction steps / repo?

**Comment by rwatts3** [comment]
I could prepare a video. The repo is not up just yet. I resolved the issue
on the page that contains the search. It appears I needed to add another
property to the esInput template. Don't have it in front of me but it's
similar to allow... However when I click on a link and it takes me to the
routed detail page the contents are empty then flash in after the route
instead of being their already.

**Comment by rwatts3** [comment]
Here is the video. 
Notice the last couple seconds. When I navigate to the route it flashes empty then the data loads in after. This was not happening before I added the package. I couldn't see any errors in the console. 

http://screencast.com/t/qn6c8XaIM0T

**Comment by matteodem** [comment]
Shouldn't the page change happen after the subscription is ready? I don't know how this is related to EasySearch

**Comment by rwatts3** [comment]
I assumed it's related because the only thing that has changed in my code
was adding EasySearch. I'll take a closer look and see if it's something
else but I doubt it.

**Comment by rwatts3** [comment]
Ah I found the issue, can't believe it was simple. You're correct it had nothing to do with ES. 
The issue with the flashing of the screen was due to the route of my detail page not having the correct template assignment. 
I put the template as "article"  instead of "homeArticle" which caused iron router to render the page then search for a corresponding template to match the data.
