### ISSUE TITLE
[question] easy-search in production

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [matteodem/meteor-easy-search#300]
Hi there,
I'd like to ask you whether the configuration of the host: localhost:9200 have to be changed if used in production environment such as compose.io and aws?
Thanks in advance,

**Comment by matteodem** [comment]
You need to know on which domain aws or compose.io hosts Elasticsearch, I don't think it runs on the same host.

**Comment by RanaivosonHerimanitra** [comment]
Does it mean I need to ulenable elasticsearch service both on my Paas and my daas?

**Comment by matteodem** [comment]
You just need an accessable elasticsearch host process somewhere.
