### ISSUE TITLE
keyup event on EsInput component does not work well

### ISSUE THREAD

**Issue by sferoze** [matteodem/meteor-easy-search#306]
I am using the keyup event on my esInput like so

```jade
+esInput(index="notes" placeholder="Search Notes" class="form-control header-search-input clearable" event="keyup")
```

What I notice is that the first time you try searching with the input it always shows loading template and never shows results until you press enter. Once you press enter loading goes away and it shows search results. 

But upon subsequent searches it shows results right after you finish typing the words. 

I think the keyup event is somewhat buggy? Has anyone else noticed this?

**Comment by matteodem** [comment]
I'll test and resolve this in v2

**Comment by matteodem** [comment]
This is resolved as of v2
