### ISSUE TITLE
Using the ElasticSearch Client directly. What is the host?

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [matteodem/meteor-easy-search#307]
Sorry for re-posting a slightly similar question like I asked before(easy-search in production mode )  but I'm still trying to figure out this package.
I have set up an elasticsearch service which runs perfectly on aws. I have also loaded some data and put them inside an index called ```test```. Now I'd like to you use your package to query them.
Following the doc you provide. Here is what I did:
//On both client and server define client
```
var client = new EasySearch.ElasticSearch.Client({
   host: 'my-aws-domain-here'
});
```
// then when a user clicks on a button, launch the search and output in the console:

```
'click #launch_search1'  : function (e,t)
          {
client.search({
                 index: 'test',
                   // EasySearch uses 'default' as the type, when creating the index
               type: 'default',
   body: {
      query: {
          match: {
              Name: $('#myquery1').val()
          }
       }
    }
}).then(function (response) {
   console.log(response.hits.hits);
}, function (err) {
   console.log(err.message);
});
}
```
However, I get the following error: ```TypeError: client is undefined```
Could you please indicate me what am I missing ?

**Comment by matteodem** [comment]
You use `var client` which does not expose the variable globally but inside the file. That has nothing to do with EasySearch, but with javascript variable scope. Read this: http://www.w3schools.com/js/js_scope.asp
