### ISSUE TITLE
Easy Search not working with ios emulator

### ISSUE THREAD

**Issue by em222iv** [matteodem/meteor-easy-search#308]
I am doing a search for a collection called lists with the easy search package. 
This works fine when running in the browser. However it does not work in the ios emulator.
Is this a common problem where I've missed out on something or is the fault with me?

My code looks like this:

Template:

            <div id="searchLists">
            {{#esEach index="lists" id="search"}}
                <div>
                    {{title}}<i>{{index}}</i>
                    <form>
                        <a href="/lists/{{_id}}">show</a>
                        <a class="remove-list-element">remove</a>
                        <input type="text" class="list-title-update" placeholder="{{title}}">
                        created by: {{author}}
                    </form>
                </div>
                {{else}}
                Notjign
            {{/esEach}}
        </div>

Server:

         EasySearch.createSearchIndex('lists', {
    'collection': Lists, // instanceof Meteor.Collection
    'field': ['title', 'index', 'author'], // array of fields to be searchable
    'limit': 20,
    'use' : 'mongo-db',
    'convertNumbers': true,
    'props': {
        'filteredCategory': 'All',
        'sortBy': 'title'
    },
    'sort': function() {
        if (this.props.sortBy === 'title') {
            return { 'title': 1 };
        }
        // default by highest score
        return { 'title': 1 };
    },
    'query': function(searchString, opts) {
     // Default query that will be used for the mongo-db selector
     var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);
     //console.log(opts);
     // filter for categories if set
     if (this.props.filteredCategory.toLowerCase() !== 'all') {
         query.category = this.props.filteredCategory;
     }

        return query;
    }
});

Included in collection:

     Lists.initEasySearch(['title', 'author', 'index'], {
       'limit' : 20,
       'use' : 'mongo-db'
    });

**Comment by matteodem** [comment]
Are there any errors in the cordova console?

**Comment by em222iv** [comment]
Yes, while clicking the esInput field, this message shows:
>
Oct 19 11:39:05 Eriks-iMac SpringBoard[6628]: [<_UIKeyboardArbiterHandle: 0x7fe0116c41a0; PID 6657: com.apple.accessibility.AccessibilityUIServer <(null)>; hosting PIDs {(
	)}; level 0.000000; active NO [wants NO]; suppression 0>] could not take process assertion

**Comment by em222iv** [comment]
The log shows this when the input field is clicked.
When i type in it, it says nothing.
>
Oct 19 11:56:14 Eriks-iMac assertiond[6632]: assertion failed: 15A284 13A340: assertiond + 12188 [93893311-6962-33A7-A734-E36F946D8EBA]: 0x1
Oct 19 11:56:15 Eriks-iMac SpringBoard[6628]: [<_UIKeyboardArbiterHandle: 0x7fe0116c41a0; PID 6657: com.apple.accessibility.AccessibilityUIServer <(null)>; hosting PIDs {(
	)}; level 0.000000; active NO [wants NO]; suppression 0>] could not take process assertion

**Comment by matteodem** [comment]
Not sure what that is supposed to mean/ if it has anything to do with EasySearch.

**Comment by matteodem** [comment]
Please update to v2 and if the problem still exists, provide a reproduction repository or steps.
