### ISSUE TITLE
setting 'index' field dynamically in esInput leads no search results

### ISSUE THREAD

**Issue by streamnsight** [matteodem/meteor-easy-search#310]
Just trying this out.
All worked well until I tried assigning the esInput index dynamically 
(I have a set of pages that look similar and display different type of data, so the search field and results look similar, only the content changes)

when setting the esEach index dynamically with esInput set statically, it works, but if i set both dynamically, I get no results.
both are set in helpers, and there may be a rendering order issue here (using iron router), but I'm not sure which way to check to troubleshoot.

thanks for help.

**Comment by matteodem** [comment]
What does dynamically mean? Please give me a small reproduction repository or steps with code to reproduce.

**Comment by streamnsight** [comment]
Hi...
thanks for the super quick answer.

dynamically means I use something like:

`{{> esInput index=index placeholder="Search..."}}`

and 

```
Template.searchbar.helpers({
    index: function () {
        var route    = Router.current().route.getName().split('.')[0];
        return route;
    }
});
```

I just added: 
`var instance = EasySearch.getComponentInstance({index: route}).triggerSearch();` 
in both the helper code and it seems to work actually.

**Comment by streamnsight** [comment]
EDIT: spoke too soon... it works 'sometimes' when adding 'triggerSearch' line, I do see the data is on the client now, but the display is not updated (nothing shows, yet sometimes it does)..

**Comment by streamnsight** [comment]
A hint probably: I notice when changing esInput the esSearchResults change, but the esCounts remains at 0.

**Comment by matteodem** [comment]
Can you please try it out with v2? Also what's the real use case for this? why not search in multiple indexes?

**Comment by matteodem** [comment]
Please write into this issue if this still remains.

**Comment by streamnsight** [comment]
I tried with v2. It does not work.
I believe it is simply because the index is registered in the onCreated function, and changing index dynamically after the Input is rendered once will not update the index. 

Why is it in onCreated and not onRendered? is there a reason for this?

**Comment by matteodem** [comment]
No, not really. Have you tried with a forked version to use onRendered? I'll create a new issue to investigate on that.

**Comment by streamnsight** [comment]
I'm trying to use the fork but I don't know how to implement the forked package in my project, especially with the : is the name. I can't create a new package with those names, and simply putting the package in packages does not work on its own. 
So how do I install my local fork in my project to test?
Thanks

**Comment by matteodem** [comment]
There are two steps:

* Add package contents to packages/* folder and rename it to something like `local-easy-search` (doesn't need a semicolon)
* Add package name to .meteor/packages list

How I do it is by cloning the repo and symlinking easy:search to the packages folder in the app that I test, see
