### ISSUE TITLE
search through a publication/subscription rather than a collection?

### ISSUE THREAD

**Issue by streamnsight** [matteodem/meteor-easy-search#311]
Just wondering if it is possible to search through a subscription rather than a collection (i.e. an already subset of the data)

I use `publishComposite` to publish subsets of data. Then I'd like to search within those.

For example I have *Devices*, and *Users*. A *Device* has *Users*. A *Device* also has a specific *User* who is the manager. 
If I want to list *Users* of a *Device* the logged-in User manages, I need to search *Devices* he manages, then *Users* of these *Devices*.
This is achieved by `publishComposite`.
Is there a way to then search through this publication/subscription? 
Or a way to do run this type of query directly with EasySearch?

Thanks

**Comment by matteodem** [comment]
So until now the actual search was rather inconsistent and this might be hard. I'll release v2 though in the next day and I feel like this could be a good use case for docs. How are you using publishComposite right now? And how would you like to structure it, assuming you get back a mongo cursor thats publishable

**Comment by streamnsight** [comment]
mmm... I have to say I am not sure if I understand the question:
It seems to me EasySearch creates its own publications. It also seems like if i want to be able to set a 'limit' on the number of records, the search needs to happen on the server side (a different issue but pretty critical one)

I use publishComposite as i explained: 
it's a cascade of queries in Mongo I guess, and publishComposite 'aggregates' the results, to form a publication. 
I have to say I don't know enough of the details of Meteor publish/subscribe to say how it works, but I do end up with a cursor on the Collection subscribed to, which I use as if it was the original Mongo Collection.

in ES, it seems like indexes (search results) are also 'publications', but to specifically named collections, not the original collection. (i.e. if I use `initEasySearch`, on my `Devices` collection, then `esEach` pulls data from something called `esSearchResults` it seems. )

I guess it makes sense since one needs the 'full' dataset to search within, and you can't 'replace' the subscription with the results. 

So to try to answer your question, I would need to be able to use `initEasySearch` on the subscription name somehow, not on the Collection.

The other option, as I mentioned earlier, is to do this multi-collection query within the search query, but that means handling multi-stage queries.

a typical publishComposite query looks like:

```
Meteor.publishComposite('application.users', function (aID) {
    return {
        find: function () {
            if (!this.userId) { return; }
            return Devices.find({$or: [{users: this.userId}, {owner: this.userId}], aID: aID}, {
                fields: device_fields,
                limit: 100
            });
        },
        children: [
            {
                find: function (device) {
                    return Meteor.users.find({_id: {$in: device.users}}, {fields: user_fields, limit: 100})
                }
            }
        ]
    };
});
```

here, it looks up Application Users: 1st look up Devices with a specific App ID, then outputs cursor of aggregated Users of these Devices.

Thanks

**Comment by matteodem** [comment]
v2 is now released and it allows you to access the mongo cursor, so you could create custom publications with it, see http://matteodem.github.io/meteor-easy-search/docs/core/ (Searching)

**Comment by matteodem** [comment]
Please write into this issue if there are further questions.

**Comment by streamnsight** [comment]
Hi, Thanks again for the quick response.
I will definitely try v2 asap.


Just trying to clarify here:

Do you mean: On the server side, create indexes on the base collections, then use the index.search().mongoCursor as the collections to use in publishComposite?

Then on the client side I should be getting only the proper data, but filtered on the server side already, in a publication, which populates the client side base collections.

Then do I need to create an index on the client side base collections for client side search?
Does that seems like the right way to do this?

Do I really need an index on the client side for this to work? (since filtering and limits are set on the server side, the base collection on the client is the results collection I can display in full, isn't it?
In all the previous doc examples, the index is set on both the client and server and that's confusing to me)

thanks

**Comment by matteodem** [comment]
Hi there

If you're only going to use the data that is published and none of the EasySearch Components and so on, it's not needed to have an index on the client. Also you can use `easysearch:core` to only get the javascript code if that's the case.

**Comment by frankapimenta** [comment]
Hi,

I have a webapp that has users and when I list the users I display a count of their posts.
After implementing easy search count of posts are not show because posts publication is not subscribed.
how could I tell easy search to subscribe associated collections?

**Comment by frankapimenta** [comment]
I use astronomy package (https://github.com/jagi/meteor-astronomy).
How can I combine easy search and astronomy for easy search to provide me with a astronomy class and not a mongo db object?

**Comment by matteodem** [comment]
Please create a new issue for this.
