### ISSUE TITLE
2.0 - searching docs associated with current user?

### ISSUE THREAD

**Issue by mbreuer23** [matteodem/meteor-easy-search#314]
I have a Plans collection.  Each plan has a title.  So the user can search all plans by title.  However, I want to restrict results only to where doc.creatorId === userId of currently logged in user. 

How can I achieve this?  I tried modifying the selector to use Meteor.userId(), but i get the "cannot use Meteor.userId() in publish functions, use this.userId" error, and this.userId is undefined.

In previous versions, I would have used something like this.publishScope.userId.

**Comment by matteodem** [comment]
Yes, I removed the this.publishScope and added the userId as the first parameter of the `permission` configuration, see http://matteodem.github.io/meteor-easy-search/docs/api-reference/.

**Comment by matteodem** [comment]
Feel free to write into this issue if there are any more questions regarding this topic.

**Comment by mbreuer23** [comment]
Thanks.  Correct me if I'm wrong, But it appears to me that permission just controls whether you can execute the query.   It has no bearing on which docs are returned. 

one thought I had was to add the userId as a prop and check the userId===props.userId in the permission function.   But I don't see a way to access props there

**Comment by matteodem** [comment]
Yes, permission controlls general access to the index. What's your usecase? Do you want to restrict the user from seeing a certain set of documents?

**Comment by mbreuer23** [comment]
Yes exactly.    I want the user to be able to search by title, but also have the collection automatically filtered to show only docs where the doc.creatorId equals userId of current user.     i tried defining my own selector, but I can't figure out how to reference the current user in the selector function.   Meteor.userId() does not work.

**Comment by matteodem** [comment]
that might be, I'll create a new ticket to have a look at that.
