### ISSUE TITLE
2.0 - How does the limit work with new Index

### ISSUE THREAD

**Issue by sferoze** [matteodem/meteor-easy-search#315]
Since the limit field is not part of the configuration of the Index anymore, how is the limit set when using the Blaze Component. 

For example

```
{{> EasySearch.Input index=myIndex}}

{{#EasySearch.Each index=myIndex}}
  <div class="result">{{someField}}</div>
{{/EasySearch.Each}}

And the Core index

let index = new EasySearch.Index({
  collection: someCollection,
  fields: ['name'],
  engine: new EasySearch.MongoTextIndex(),
  permission: (userId) => {
    return userHasAccess(userId); // always return true or false here
  }
});

```

As you see the core index does not have a limit.

So if you use the input blaze component what is the limit. And how do you change it?

**Comment by matteodem** [comment]
You can define the `defaultSearchOptions` on the index instance now, see http://matteodem.github.io/meteor-easy-search/docs/api-reference/. Those options are what is used by default when searching, and as the blaze components do not override them you can use them to configure the index:

```javascript
let index = new EasySearch.Index({
  collection: someCollection,
  fields: ['name'],
  engine: new EasySearch.MongoTextIndex(),
  permission: (userId) => {
    return userHasAccess(userId); // always return true or false here
  },
  defaultSearchOptions: {
    limit: 20 // could also have skip and props
  }
});
```

**Comment by matteodem** [comment]
Feel free to write into this issue if there are any more questions regarding this topic.
