### ISSUE TITLE
Define ES index name and type

### ISSUE THREAD

**Issue by streamnsight** [matteodem/meteor-easy-search#320]
the index seems to be hard coded to 'easysearch' in the Syncer

I would like to be able to search through my own indices in ES. How do I configure that?

**Comment by matteodem** [comment]
This is missing, what's the usecase for it?

**Comment by streamnsight** [comment]
the use case is pretty common: I have an ES cluster with many indices. I want to use Meteor and search to give it access to my front end.

I forked the repo and augmented the engine to allow for any indexName and indexType. 
Also fixed the must run in a fiber issue there.

How do I do a pull request on here?

**Comment by matteodem** [comment]
Please create a branch and do a PR into master, you should be able to do it over the Github UI: https://help.github.com/articles/creating-a-pull-request/. Thanks!

**Comment by streamnsight** [comment]
Do I understand right that easy-search searches within an ElasticSearch collection that's mapped from a MongoCollection, and then map _ids to the mongo collection to return the filtered collection? 
Basically using ES for the extended search/filtering capability, but not to get the docs from?

I'm confused here as I try to get documents back and I do get hits and ids, but no docs back, and looking at the code the searchCursor tries to find docs in the Mongo Collection that match that ids of the docs found in ES... but since my docs are not in mongo I get nothing... 

I guess I need to pull the docs from ES and put them in mongo first, is that right?

**Comment by matteodem** [comment]
Yes you're right with the mapping to the mongo collection. So Elasticsearch basically takes over the heavy lifting part and mongo is here to keep the reactivity. Yep, I'm not sure if it makes a lot of sense to directly search the ElasticSearch index (by returning the raw docs) as Meteor is built around the reactive awesomeness. 

It's still possible to convince me otherwise though.

**Comment by matteodem** [comment]
Index name and types are now configurable
