### ISSUE TITLE
Using selector causes no results to be displayed

### ISSUE THREAD

**Issue by ciwolsey** [matteodem/meteor-easy-search#321]
I'm having issues while updating my code from 1.x to 2.x.

Here is a gist that explains my problem:

https://gist.github.com/ciwolsey/bbc643ceb6be25fe12ef

All examples give results except example one, where the unaltered selector I'm returning causes no results to be shown.

**Comment by matteodem** [comment]
The problem is that the third parameter called `aggregation` is missing. Can you point me to the wrong docs so i can fix it?

**Comment by ciwolsey** [comment]
I just looked at the docs again and noticed the aggregation param. I'm 100% sure it wasn't there before but I can't figure out where I was looking before. The code was copy pasted from the example so there must be some incorrect or outdated docs somewhere but I'm afraid I no longer know where.

**Comment by matteodem** [comment]
Oh I actually wanted to write here that I updated the docs, sorry for the confusion!
