### ISSUE TITLE
error adding easy search

### ISSUE THREAD

**Issue by EddieLi** [matteodem/meteor-easy-search#324]
I simply typed in meteor add easy:search and received the following errors
 => Errors while adding packages:             
                                              
While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: easysearch:core 2.0.1
Required by: easysearch:components 2.0.1

unknown package: isobuild:compiler-plugin
Required by: ecmascript 0.1.3-plugins.1

**Comment by matteodem** [comment]
Which version of Meteor are you running? Got a reproduction repo or steps?

**Comment by poterealpopolo** [comment]
Hello I have the same errors, I'm using Meteor 1.1.0.3

**Comment by matteodem** [comment]
EasySearch is only supported from 1.2, as it's written with ES2015

**Comment by poterealpopolo** [comment]
Right now I have no time to go to the last version of meteor. There is no way of being able to operate with 1.1.0.3 ?

**Comment by matteodem** [comment]
I don't think there's a way to allow ES2015 code in 1.1.0.3, right?

**Comment by poterealpopolo** [comment]
Yes, you're right. Anyway I take the time to update meteor and now everything is ok. 

Thanks a lot.
