### ISSUE TITLE
Only use transform on client side

### ISSUE THREAD

**Issue by chompomonim** [matteodem/meteor-easy-search#326]
It seems, that transform doesn't for work properly in `engine: EasySearch.MongoDB()`

``` CoffeeScript
class @ClientBase
  name: -> "#{@first_name} #{@last_name}"

@ClientsIndex = new EasySearch.Index
  collection: Clients
  fields: ['first_name', 'last_name']
  engine: new EasySearch.MongoDB
    transform: (doc) -> _.extend new ClientBase, doc
```

In template I do

``` jade
+EasySearch.Each index=OrdersIndex
  li {{name}}, {{first_name}}, {{last_name}}
```

And there is no `name` at all while `first_name` and `last_name` shows correctly :(
Any ideas where is problem?

**Comment by matteodem** [comment]
What does transform return? The thing is that with MongoDB it runs the `transform` method on the server side, I don't think that you can create custom object instances there.

**Comment by chompomonim** [comment]
Ok, so what them would you suggest? Use `beforePublish` and set `doc.name` there or some other solution using transform?

**Comment by matteodem** [comment]
Trying to add information without using custom classes for now. Might make sense though to only apply transform on the client side so it mirrors the same behaviour as with normal collections.

**Comment by chompomonim** [comment]
Is it already possible to apply transform only on the client? How?

**Comment by matteodem** [comment]
No it isn't so that's what I'm thinking of. I'll create a ticket to have a look at that.

**Comment by dburles** [comment]
+1 for this. It might be nice to support existing transformations by applying it if one exists. [Here's a repro app with collection-helpers of the current problem](https://github.com/dburles/easy-search-bug/tree/transform) (with a workaround).

**Comment by mbreuer23** [comment]
+1 for this and for @dburles suggestion

**Comment by matteodem** [comment]
Fixed in latest version `2.0.5`.

**Comment by thomasspiesser** [comment]
still, collection-helpers do not work - only with the workaround @dburles suggested.

**Comment by mbreuer23** [comment]
Well, you still have to define a transform function in you engine config.  But you can just use regular collection_.transform and return that document to have access to your helpers (as functions, like you'd expect).

Previously you had to do the transform, and then apply your helpers individually.  


```javascript
transform: function(doc) {
  var transformedDoc = Invites._transform(doc);
  return transformedDoc;
  // previous workaround
  // var transform = Invites._transform(doc);
  // doc.helper1 = transform.helper1();
  // doc.helpers2 = transform.helper2();
  // return doc;
},
```

**Comment by matteodem** [comment]
Did not add that logic in `2.0.5`, I'll create a new issue for that.

**Comment by thomasspiesser** [comment]
@mbreuer23 thanks for the tip!
