### ISSUE TITLE
Does this package support Meteor 1.1?

### ISSUE THREAD

**Issue by derwaldgeist** [matteodem/meteor-easy-search#329]
I've tried to use it, but only got these errors:
```
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: unknown package: isobuild:compiler-plugin
   Required by: ecmascript 0.1.3-plugins.1
   
   unknown package: isobuild:isopack-2
   Required by: easysearch:core 2.0.1
   Required by: easysearch:components 2.0.1
```

I assume this is due to dependencies on Meteor 1.2. But I could not find out which package version is the last that can be used with Meteor 1.1?

**Comment by matteodem** [comment]
All packages require 1.2 because they use ES2015 syntax

**Comment by mitar** [comment]
You could maybe use mquandalle:harmony for Meteor 1.1?

**Comment by derwaldgeist** [comment]
@matteodem: Thanks for your quick reply. Is there any chance to use an older version until I've upgraded to 1.2?

**Comment by matteodem** [comment]
I actually used that, but thought that most of people would switch to 1.2 asap. You could use an older version but the API is quite different there so that doesn't make a lot of sense. I'll think about re-adding harmony to allow older meteor versions to use EasySearch.

**Comment by jay-depot** [comment]
In the meantime are the old API docs still hosted anywhere?

**Comment by matteodem** [comment]
They're here https://github.com/matteodem/meteor-easy-search/tree/gh-pages-gatsby/v1-docs. Wanted to add them to the gh-pages branch though. I'll create a story for that.

**Comment by matteodem** [comment]
They are here now https://github.com/matteodem/meteor-easy-search/tree/gh-pages/_v1docs.
