### ISSUE TITLE
Custom searchCollection name

### ISSUE THREAD

**Issue by veered** [matteodem/meteor-easy-search#330]
It previous versions of EasySearch it was possible to have multiple search indices over the same Mongo collection. This is no longer possible because the search collection's name is not configurable:      

    config.name = (config.collection._name  || '').toLowerCase();

So when multiple indices are declared on the same collection, the client gets errors like 

    Uncaught Error: There is already a collection named 'associates/easySearch'

I think that we might be able to fix this simply by changing the earlier line of code to:
 
    if (_.isUndefined(config.name))
      config.name = (config.collection._name  || '').toLowerCase();

**Comment by matteodem** [comment]
that's right, feel free to create a PR for this one (as it should be a minor change).

**Comment by dburles** [comment]
I've come across a scenario where I'd like to modify the query based on user permission, is there a way to handle that @matteodem? My workaround was to create another index with the modified query and pass that to the components based on the users permission (obviously not ideal if security was important).

**Comment by matteodem** [comment]
you could access the `userId` inside a custom `query` method, see first example here http://matteodem.github.io/meteor-easy-search/docs/recipes/

**Comment by dburles** [comment]
Oh that's exactly what I'm after, thanks!

**Comment by matteodem** [comment]
Should be fixed as of 2.0.3.
