### ISSUE TITLE
When you just change search options, not the query, the results are wrong

### ISSUE THREAD

**Issue by veered** [matteodem/meteor-easy-search#332]
In `search-engine.js` the JSON serializations of the search request only include `searchDefinition` not `options`. This means that if you only change something in options (like `skip` for example), then EasySearch will immediately report that the cursor is ready and give you the wrong results. To fix this we will probably need to include `options` in the JSON serializations.

**Comment by matteodem** [comment]
good spot, thanks! I think this whole JSON serialization is kind of a mess, but I'll have a look at this soonish.
