### ISSUE TITLE
Components should take the search cursor and not the index

### ISSUE THREAD

**Issue by dburles** [matteodem/meteor-easy-search#333]
Is there any reason why this isn't the case? It would mean that we can use the `search` method and also make use of the components, currently that doesn't appear to be possible.

The way I have things setup is the search method lives within an autorun on a template instance, Sessions are used for the search and for a bunch of props.

These session vars are set by an input field + select menus for props. The API is currently confusing as to when and where we should be using the search instance or referencing the index.

Edit: There's likely a valid reason why this is the case, if that's so it would be great if I could be pointed in the right direction

**Comment by matteodem** [comment]
The reason the index is being passed is because components like `LoadMore` and `Pagination` need to create new cursors with different options set on them (limit, skip and so on). Does that make sense to you?

**Comment by dburles** [comment]
Yeah, makes sense. I wonder is it possible to use the search method with the components?

**Comment by matteodem** [comment]
This got under apparently. Yes, you can use component methods to do `search` in javascript. See __Using component methods__ (http://matteodem.github.io/meteor-easy-search/docs/components/) or __Searching without an input__ (http://matteodem.github.io/meteor-easy-search/docs/recipes/).
