### ISSUE TITLE
2.0 components: Prevent searching with empty input field

### ISSUE THREAD

**Issue by rjsmith** [matteodem/meteor-easy-search#336]
I am using the new 2.0 packages, including the UI search components.
When I navigate to my search page in my application (see excerpt of search page template below), easysearch does an immediate search, even though the input field is blank.  I have looked through the code but cannot figure out where this initial search is getting triggered from.  If the input field is blank, I do not want it to trigger a search.  I am using an index with the MongoGB engine.

```html
                <div class="row">
                    <div class="col-xs-12">
                        {{> EasySearch.Input index=mySearchIndex attributes=getInputAttributes timeout=500}}
                    </div>
                 </div>
                <div class="row">
                    <div class="col-xs-12">
                      <h4>Search Results&nbsp;<small>Showing {{getResultCurrentCount}} of {{getResultCount}} results</small></h4>
                      <div class="list-group">
                        {{#EasySearch.Each index=mySearchIndex}}
                          {{> searchSpecificationResultItem resultItem=this}}
                        {{/EasySearch.Each}}
                      </div>
                      {{> EasySearch.LoadMore index=mySearchIndex attributes=getLoadMoreAttributes}}

                      {{#EasySearch.IfNoResults index=mySearchIndex}}
                        <div class="no-results">No results found!</div>
                      {{/EasySearch.IfNoResults}}
                    </div>
                </div>
```

**Comment by matteodem** [comment]
This is the actual code: https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/lib/input/input.js#L13.

What is your expected behaviour when doing an empty search through an input? It might make sense to allow a falsy value in a custom `selector` to return 0 documents.

**Comment by rjsmith** [comment]
Hi,

There are 2 separate, but related issues here I think:

1. Even if I commented out the EasySearch.Input component from my template, my search page still immediately issues a search with an empty search string (I am logging the `selector` function on the MongoDB engine on the server, so I can see this happening). It seems to be triggered somewhere inside the EasySearch.Each block helper code?

2. What is the expected behaviour for a search triggered with an empty ("") search string? Imho, I would expect any existing search results (from a previous non-blank search) to be cleared out. I have just implemented this behaviour by forcing the MongoDB engine to return an empty cursor from the server - see below (`source` is one of the collection fields). But would prefer some way to simulate the same result without sending a search request to the server and doing a real MongoDb query .. your suggestion is similar, I think ? :

```javascript
		selector: function (searchObject, options, aggregation) {
			if (searchObject && searchObject.source === "") {
				// Force empty string searches to return 0 results
				return {
					_id: 'non_existent'
				}
			} else {
				let selector = this.defaultConfiguration().selector(searchObject, options, aggregation);
				// Only search for specs in the user's own partition
				selector.partitionId = Plangy.Organisation.getPartitionIdByUserId(options.search.userId);
				// Restrict search to items in user's current project
				let _user = Meteor.users.findOne({_id: options.search.userId}, {fields: {currentProjectId: 1}});
				selector.projectId = _user.currentProjectId;
				// Only search for active, non-deleted documents
				selector.deleted = {$exists: false};
				console.log('selector:'+JSON.stringify(selector));
				return selector;
			}
```

By the way - thanks for creating this package .. I have been able to add a search feature to my application from scratch in less than a day.

**Comment by matteodem** [comment]
In the next version you should be able to just simply put the `Each` block into the else block of the `IfInputEmpty` so that it only searches when the input has some text. Would that be sufficient?

**Comment by rjsmith** [comment]
yes, that will probably work, look forward to trying it out.

**Comment by sizovilya** [comment]
@matteodem ,
Hi! When the release of new version with this feature?

**Comment by matteodem** [comment]
This should work now as of the latest version `2.0.4`, please check it out.

**Comment by rjsmith** [comment]
@matteodem I will wait until its published onto atmosphere, then test in my application, thanks!

**Comment by matteodem** [comment]
It is released now on atmosphere.

**Comment by rjsmith** [comment]
@matteodem.
Thanks. I just tried it in my application. When the search input is empty, the search still seems to be invoked, and it goes into an unending loop sending blank search queries to the server.  It only stops when I enter a non-blank search query.

```html
 {{> EasySearch.Input indexes=myIndex attributes=getInputAttributes timeout=500}}

                       {{#EasySearch.IfInputEmpty index=myIndex}}
                          <div class="no-results">Enter a search word</div>
                        {{else}}
                          <small>Showing {{getResultCurrentCount myIndex}} of {{getResultCount myIndex}} results</small>
                          <div class="list-group">
                            {{#EasySearch.Each index=myIndex}}
                              {{> searchSpecificationResultItem resultItem=this}}
                            {{/EasySearch.Each}}
                          </div>
                     {{/EasySearch.IfInputEmpty}}
```

Am I using it correctly?

**Comment by matteodem** [comment]
Yes, this should be fine. I remember testing this use case locally though, I'll create a new issue to investigate this.

**Comment by datalifter** [comment]
@matteodem - first off, you rock!

2nd - @rjsmith, great questions. I'm just getting into Meteor and working through all this great stuff, but having trouble getting the attributes for the EasySearch.Input component to take.

I have the following line in my Template: 
`{{> EasySearch.Input index=offendersIndex attributes=inputAttributes}}`

And in the JS file I have:
`inputAttributes: function () {
    return { class: 'easy-search-input', placeholder: 'First, Last, Street, City, County, Status...' };
  }`

**What am I missing?**

**Comment by matteodem** [comment]
I'm not sure what the problem is here, can you please provide the full template helpers configuration?

**Comment by datalifter** [comment]
Hi @matteodem !

Thanks for the quick reply.  As it turns out, for some reason, removing the inputAttributes function, compiling then putting it back triggered the results I was looking for.

All works great now!

But while I have your attention! ;-)

If I wanted to enter 2 strings in the EasySearch.Input box and search for those, how would you go about setting that up?

In this case I would be searching in 2 fields - name and county.  So the input would look something like "smith benton"  I'm indexing the "name" and "county" fields in my index.

Thanks in advance!

**Comment by matteodem** [comment]
What do you exactly want to achieve? Do you want to split up the input string into separate keywords?

**Comment by datalifter** [comment]
I would love to be able to filter the results. As an example, I enter in "smith" and get all records with this phrase found within the indexed fields.  In my case, first and last name, street name and county. I would like to be able to continue to type "smith benton" and filter the results with the added keyword.

I considered adding some additional selectors for "county" and once "changed" apply this filter to the results. I guess this would be one way to do that.

Any thoughts?

**Comment by matteodem** [comment]
the current default behaviour would just search for "smith benton" across all your fields? Is that not what you're expecting? Can you please create a new issue where we can have a closer look at this.

**Comment by datalifter** [comment]
No.  "smith" is in the name.last field, "benton" in the address.county field.  Both are included in the EasySearch fields list.

What would be the best solution?

**Comment by datalifter** [comment]
Hi @matteodem - I'm going to open up a new ticket for this thread.
