### ISSUE TITLE
Component else blocks not functioning correctly

### ISSUE THREAD

**Issue by dburles** [matteodem/meteor-easy-search#338]
Came across this issue which I've [reproduced here](https://github.com/dburles/easy-search-bug).

Notice how *No results* appears and then while searching it remains on *Loading...*.

Replace `searchA` with `searchB` and things function correctly. The particular pattern in `searchA` was one that was previously working prior to 2.0.

Thanks a lot, appreciate your work on this package @matteodem !

I think this reproduction app also demonstrates this bug too: https://github.com/matteodem/meteor-easy-search/issues/336

**Comment by matteodem** [comment]
Not sure if the pre v2 version is still supposed to be working. What do you think is wrong now or doesn't make any sense to you regarding the if components?

**Comment by dburles** [comment]
The content in the else blocks just never renders

**Comment by matteodem** [comment]
This is going to be fixed in the next version.

**Comment by matteodem** [comment]
Should be fixed in the latest version `2.0.4`.
