### ISSUE TITLE
Updated to latest version now getting TypeError: Object [object Object] has no method 'createSearchIndex' 

### ISSUE THREAD

**Issue by almogdesign** [matteodem/meteor-easy-search#339]
Just updated to latest version and now I'm getting the following error - TypeError: Object [object Object] has no method 'createSearchIndex'

**Comment by matteodem** [comment]
Yes, EasySearch v2 is a major version upgrade and contains a big refactoring around the old API, check out the docs here http://matteodem.github.io/meteor-easy-search/getting-started
