### ISSUE TITLE
Please exclude `services` field from search by default in Meteor.users collection.

### ISSUE THREAD

**Issue by AlexFrazer** [matteodem/meteor-easy-search#340]
Just noticed this, seems like it might be a security risk. To replicate:

```
PlayersIndex = new EasySearch.Index({
  fields: ['profile.name.full'],
  collection: Meteor.users,
  engine: new EasySearch.MongoDB()
});
```

Try finding and fetching from this index on the client.

**Comment by matteodem** [comment]
It's currently not possible for me to try this out, what's the problem with the services field inside Meteor.users?

**Comment by AlexFrazer** [comment]
It contains stuff like the hashed password and login services, Meteor usually doesn't publish these by default

**Comment by matteodem** [comment]
You can remove the fields by modifing the doc with `beforePublish`, see here http://matteodem.github.io/meteor-easy-search/docs/recipes/ (Adding additional data to your document)
