### ISSUE TITLE
Does this package need to use lodash?

### ISSUE THREAD

**Issue by rjsmith** [matteodem/meteor-easy-search#344]
Hi,
I spotted that easy:core and easy:components both declare a dependency on erasaur:meteor-lodash. This adds the lodash library to my application (250kb unzipped) .. I have not been using it previously, nor it seems has any of the other 50+ community packages I use in my application so far. I would prefer not to be forced to incorporate lodash into my app at this point .. but I do still want to use meteor-easy-search.

I experimented with a local fork to replace with the meteor-platform 'underscore' library in both `easy:core` and `easy:components` packages. The only issue I found was on this line which uses the `_.assign` lodash method .. I replaced it with _.extend:

https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:core/lib/core/index.js#L26

Replaced with:
```javascript
    this.config = _.extend({}, Index.defaultConfiguration, config);
```

Would you accept a PR that changes that breaking line above, and changes the dependency on lodash to be [`weak`](http://docs.meteor.com/#/full/pack_use) instead?

**Comment by rjsmith** [comment]
Hi @matteodem . I have a local commit ready that I could submit as a PR ... please let me know.

**Comment by matteodem** [comment]
I think the consistency of lodash is definitely a plus, but I do understand the concerns of keeping easy-search and it's dependencies slim. Please open the PR and I'll have a look.

One functionally lodash does provide that underscore doesn't have which is useful for the autosuggest component, which is [_.get](https://lodash.com/docs#get). So as long as this isn't replaced in your PR I'll happily have a look at it.

**Comment by matteodem** [comment]
Closed as it's a weak dependency now.
