### ISSUE TITLE
index.search().fetch() sometimes returns no results on client

### ISSUE THREAD

**Issue by jamiecollinson** [matteodem/meteor-easy-search#345]
I have an index which is reliably working with EasySearch components and with the server side JS API, but if I use it on the client side with `index.search(query).fetch()` it intermittently fails to return results.

Looking at the cursor returned by `index.search(query)` I can see that the no data results coincide with the cursor's `_isReady` property being false.

Should I be doing something to wait for `_isReady`? Alternatively is it recommended to do client side API calls via a method call to the server?

**Comment by matteodem** [comment]
This is the default _reactive_ nature of Meteor. You need to execute the code inside a `Tracker.autorun` function and then wait for isReady() is true. What is the use case? If you need instant access to data with only one method call then you should execute the search method on the server.

**Comment by jamiecollinson** [comment]
That makes complete sense. The use case is that I'm filling the options of a selectize input based on a search of what's been typed. Since my comment I've resolved by calling a server method which performs the search then updates the selectize options on a callback.

I suppose alternatively I could store the query term and options in `ReactiveVar`s on the template instance and use `Tracker.autorun` to update the options and push them into selectize. But I think calling a server method is cleaner for this case.

Do you think a built-in method on the index to perform a server side search would be a good idea? What I've done is add a generic helper method on the server, but this relies on my naming convention of attaching each index to it's collection:
```
Meteor.methods({
  'searchByCollection': (collectionName, query, options) => {
    return Collections[collectionName].index.search(
      query,
      options
  }.fetch();
});

**Comment by matteodem** [comment]
I think it's fine but I definitely wouldn't make it possible to specify the collection name or at least restrict the allowed strings there. Also do `check` calls for every argument there, otherwise you might get XSS attacks.

**Comment by matteodem** [comment]
Feel free to write into this issue if there are any other questions
