### ISSUE TITLE
customRenderPagination parameter Question

### ISSUE THREAD

**Issue by chadjguidry** [matteodem/meteor-easy-search#348]
I'm trying to utilize the customRenderPagination parameter for the Pagination component, but am unable to get the custom template rendered as expected.  Is my usage of the component incorrect, or is there something else going on?  I did not see the parameter used in the leaderboard example to compare against.  

The code below shows a basic program attempting to utilize the parameter.  Thanks for this awesome package.

JS
```javascript
People = new Mongo.Collection('people');
Factory.define('person', People, Fake.user({ fields: [ 'name', 'email',
               'surname']}));

PeopleIndex = new EasySearch.Index({
  collection: People,
  fields: ['name', 'email'],
  engine: new EasySearch.Minimongo()
});

if (Meteor.isClient) {
  Template.main.helpers({
    'peopleIndex': function() {
      return PeopleIndex;
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    var numPeople = People.find().fetch().length
    if(numPeople < 100) {
      for(numPeople; numPeople < 100; numPeople++) {
        Factory.create('person', Fake.user({ fields: [ 'name', 'email',
               'surname']})); 
      }
    }
  });
}
```

HTML
```html
<head>
  <title>learn_easy_search</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>
  {{> main}}
</body>

<template name="main">
  Search: {{> EasySearch.Input index=peopleIndex}}
  <h2>People</h2>
  <ul>
    {{#EasySearch.Each index=peopleIndex}}
      <li>{{name}}</li>
    {{/EasySearch.Each}}
  </ul>
  {{> EasySearch.Pagination index=peopleIndex maxPages=10 
  customRenderPagination=test}}
</template>

<template name="test">
  <h3>Testing Custom Pagination Template</h3>
</template>
```

**Comment by matteodem** [comment]
Try putting quotes around `test` like `customRenderPagination="test"`

**Comment by chadjguidry** [comment]
I added the quotes around `test` within my html file as suggested, but it did not have any effect on the template rendered.  The default template was still rendered.  Below is the code used in this change:  

```html
{{> EasySearch.Pagination index=peopleIndex maxPages=10 
  customRenderPagination="test"}}
```

**Comment by WayneUong** [comment]
+1 I'm getting the same problem

**Comment by jkishan** [comment]
Same problem here also. Not rendering the custom template.

**Comment by sabativi** [comment]
+1 I am getting the same problem

**Comment by matteodem** [comment]
This is fixed in the last version `2.0.9`

**Comment by WayneUong** [comment]
I there an example of how customRenderPagination works? It's displaying the template but I'm not sure how to get the template to work.

**Comment by matteodem** [comment]
No there's not right now, I'll create an issue to add an example to the docs.
