### ISSUE TITLE
Server-side search within publication

### ISSUE THREAD

**Issue by WayneUong** [matteodem/meteor-easy-search#352]
This is not an issue but more of a question/feature request.

I have a collection called "Contacts", where each document has an authorId. I want the user to server-side search the collection (for performance purpose, so I'm using the MongoDB engine), but only returns contacts that have the same authorId as the user. It seems like the permission just either allows or denies access to the entire collection. Is there a way to implement server-side filtering?

Thanks

**Comment by matteodem** [comment]
Yes there is, by specifying a custom `selector` method which specifies the mongodb selector, see http://matteodem.github.io/meteor-easy-search/docs/engines/
