### ISSUE TITLE
Selectize Implementation

### ISSUE THREAD

**Issue by petr24** [matteodem/meteor-easy-search#354]
Hey man, 
I just did an upgrade, some great stuff pumped out into the update. 

Quick question. I am using autosuggest and trying to do the email demo from selectize page. I attached a few screen shots, but basically in the search I want to show the name and email label like in the demo, and allow multiple users or tags if you will to be added. Is this possible?

![screen shot 2015-11-05 at 7 20 05 am](https://cloud.githubusercontent.com/assets/3904464/10968254/01798e6c-838e-11e5-9c6c-6cecf7583a42.png)

**Comment by mbreuer23** [comment]
You can configure the selectize component's behavior using the changeConfiguration options in the autosuggest component.  

So your markup might look like  
{{> EasySearch.Autosuggest index=userIndex changeConfiguration=config }}

And then you need to define a template helper for config.  It should return a **function** that returns your desired options:  

An example with the default config is shown below.   You can override and add options as desired 

```javascript
Template.blah.helpers({
   config: function() {
        return function() {
              return {
                   valueField,
                   labelField,
                   searchField,
                   create: false,
                   preload: true,
                   render: {
                         option: (item, escape) => Blaze.toHTMLWithData(suggestionTemplate, {
                        doc: item,
                        _id: item._id,
                          label: _.get(item, labelField)
                                })
                    },
                   load: (query, callback) => {
                        if (computation) {
                         computation.stop();
                        }

                      computation = Tracker.autorun(() => {
                       let cursor = index.search(query),
                             docs = cursor.fetch();

                       if (handle) {
                            clearTimeout(handle);
                         }

                        handle = setTimeout(() => {
                            callback(docs);
                         }, 100);
               });
         }
});
```

**Comment by matteodem** [comment]
Exactly, you get the existing configuration as a parameter though (to the function you're returning) if you want to only change certain parts.

**Comment by petr24** [comment]
Thanks guys, had time this weekend to go through it, got it working.
