### ISSUE TITLE
Backwards compatibility with previous versions

### ISSUE THREAD

**Issue by gatosaurio** [matteodem/meteor-easy-search#356]
Hi,

I'm currently using version 1.5.6 on a production app.
Will I be able to upgrade to the latest version without experiencing any breaking changes?
Are there any backwards compatibility issues we should be aware of?

Excuse if this question doesn't belong here, I didn't know where else to search.

Thank you

**Comment by matteodem** [comment]
see the UPGRADE-2.0.md https://github.com/matteodem/meteor-easy-search/blob/master/UPGRADE-2.0.md, there are many BC breaks that are either because of bad design decisions that I made in the previous versions or to be consistent around different "engines".
