### ISSUE TITLE
Is it possible to add multiple keywords to a filter?

### ISSUE THREAD

**Issue by gymed** [matteodem/meteor-easy-search#357]
Sorry for a bit of a newbie question.  I've looked at the example and docs and can't seem to work out if this is possible or not.

What I'm trying to do is filter a collection using a list keywords that are all entered in one input.  I tried this with bootstrap tags-input and I tried with autosuggest instead, but while something like bootstrap:tags-input can return an array, I can't seem to figure out a way to make an easysearch filter match items in that array (rather than treating it as a long string with commas).  Is there a recipe for this multiple tag/keyword use-case?

**Comment by matteodem** [comment]
There is an easy-search autosuggest component that might do what you want, but the logic for extracting the string needs to be done in a custom `selector` method.

**Comment by mbreuer23** [comment]
I'm not sure what your exact use case is, but the example below might help you get started. 

I'm making a few assumptions here, such as that your tag field is a string that contains a single tag, that you're passing a list of tags as a comma-separated string, and that you want to filter docs that have at least one of the tags entered in the search.

```javascript
var index= new EasySearch.Index({
	collection: TaggedCollection,
	fields: ['tag'],
	name: 'myName',
	engine: new EasySearch.MongoDB({
		selector: function(searchObject, options, aggregation) {
			var selector, tags;

			selector = {'$or': [] }; // initialzie selector 
			
			tags=searchObject.tags.split(","); // tags is now an Array

			// loop through tags array and add to selector
			_.each(tags, function(tag, index) {
				selector.$or.push({tag: tag});
				
			});
			
			return selector;
			
		}
	})
});
```
