### ISSUE TITLE
Search on a FS collection

### ISSUE THREAD

**Issue by essenlive** [matteodem/meteor-easy-search#358]
Not sure if it is a easy search or FS Collection problem but since the last update [this code](http://meteorpad.com/pad/tpd5dwvA4AeugBseo/Leaderboard) throws this error. I cant seem to get what changed with the last update.
### model/collection.js
```javascript
Items = new FS.Collection("items", {
    stores: [ new FS.Store.GridFS("items") ],
});

ItemsIndex = new EasySearch.Index({
    collection: Items,
    fields: ['metadata.name'],
    engine: new EasySearch.Minimongo()
});
```
### error
```bash
W20151111-11:27:25.512(1)? (STDERR) Error: Match error: Expected particular constructor
W20151111-11:27:25.512(1)? (STDERR)     at check (packages/check/match.js:33:1)
W20151111-11:27:25.512(1)? (STDERR)     at new Index (lib/core/index.js:17:5)
W20151111-11:27:25.513(1)? (STDERR)     at models/collections.js:95:14

**Comment by matteodem** [comment]
It has to do with this line https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:core/lib/core/index.js#L17, does FS.Collection not extend the original Meteor.Collection?

**Comment by essenlive** [comment]
Ok I don't know how I missed it. Just had to use `collection: Items.files`### model/collection.js
```javascript
Items = new FS.Collection("items", {
    stores: [ new FS.Store.GridFS("items") ],
});

ItemsIndex = new EasySearch.Index({
    collection: Items.files,
    fields: ['metadata.name'],
    engine: new EasySearch.Minimongo()
});
```
