### ISSUE TITLE
Print out users in role

### ISSUE THREAD

**Issue by Mistaken3lf** [matteodem/meteor-easy-search#360]
I print out all users in a specific role but meteor also prints out the currently logged in user even if they aren't in that role. I have a helper that prints out users in a role and not equal to the current user. Is there a way to do this with easy search using $ne to the current user ID?

**Comment by mbreuer23** [comment]
You can probably accomplish this as follows.  For sake of this example I'm assuming you're searching on the username field

```javascript
var index= new EasySearch.Index({
	collection: Meteor.users,
	fields: ['username'],
	name: 'usersInRole',
	engine: new EasySearch.MongoDB({
		selector: function(searchObject, options, aggregation) {
			var selector = this.defaultConfiguration().selector(searchObject, options, aggregation);

			var userId = options.search.userId;
			selector._id = {$ne : userId};

			// other code to filter by role

			return selector;
		}
	})
});
```

**Comment by Mistaken3lf** [comment]
Since I'm using minimongo as my engine can I still do it this way?

**Comment by mbreuer23** [comment]
You should be able to.

**Comment by Mistaken3lf** [comment]
Awesome. Thanks. I will try it out.

**Comment by matteodem** [comment]
Thanks for taking this over, feel free to write into this issue if there are other problems connected to this issue.
