### ISSUE TITLE
Is there a way to search by publication for current template/route of the same collection?

### ISSUE THREAD

**Issue by scribblegenius** [matteodem/meteor-easy-search#361]
Is there a way to search the entire database of the same collection based on which publication the current template subscribes to?

Usecase: I have several templates with different publications that pull different parts of the same collection of posts. Based on the user authorization, the user should be able to search the posts 
1) he owns
2) belong to a group that he is a member of 
3) if they have a flag = public

Minimongo engine partly solves the problem by showing only posts from the publication of the current template, but it only pulls the client side ones ( as it is supposed to do! ).

What would be nice is to be able to search the entire collection based on the publication the rendered template/route is subscribed to.

**Comment by matteodem** [comment]
It should be possible to search the whole collection, but with a subset by using custom props, see http://matteodem.github.io/meteor-easy-search/docs/core/
