### ISSUE TITLE
Is it possible to sort by an added field?

### ISSUE THREAD

**Issue by joaobarcia** [matteodem/meteor-easy-search#363]
Hi,

As described in "Adding additional data to your document" from http://matteodem.github.io/meteor-easy-search/docs/recipes/. 

Imagine we would add another field, let's say doc.userState from another collection. userState is a numeric value between 0 and 1.

Is it possible to sort by 'userState'? I am not being able to achieve this.

Thanks

**Comment by matteodem** [comment]
There is no way to sort on the client when using `beforePublish` on the server to add fields. What is the use case here?

**Comment by joaobarcia** [comment]
We are building an open education website. For this example, we have the following three collections:
Lessons (lesson content)
Users
UserStates (documents have userId, lessonId and userState. userState defines what is the probability that a user will be able to finish each lesson successfully).

We would like to sort lessons by their state in order to show the most accessible lessons first.

**Comment by matteodem** [comment]
so the sorting on the client is different for each user?

**Comment by matteodem** [comment]
Please refer to the [first recipe](http://matteodem.github.io/meteor-easy-search/docs/recipes/) in the docs
