### ISSUE TITLE
Is possible to my index to return a mongo db object?

### ISSUE THREAD

**Issue by AlexanderPD** [matteodem/meteor-easy-search#365]
Now in my view i do this simple thing:

```
{{#each machines}}
{{> singleMachine}}
{{/each}}
```

machines is a helper that filter my Meteor Collection named "Machines".
Its pretty easy and i can easily apply filter on both server or client. But i now need the "search" ability and i used EasySearch.

Now my view code is this:

```
{{> EasySearch.Input index=index }}
{{#EasySearch.Each index=index}}
{{> singleMachine}}
{{/EasySearch.Each}}
```

index helper just returns MachinesIndex

I declared my model like this:

```
MachinesIndex = new EasySearch.Index({
    engine: new EasySearch.MongoDB(),
    collection: Machines,
    fields: ['_id', 'name', 'stuff', 'foo', 'bar']
});
```

it works, but i cannot understand WHY its working. It correctly filter by name but what if i want to filter by "_id"?

And.. a bigger problem is that i cannot set other filter (well, i think i can but i don't know how to do it).
My goal is to filter by name all Machines with "foo" value = "test"

i tried this helper but its not working:

```
MachinesIndex.config.mongoCollection.find({ foo: 'test' });
```

i get this: "Error: Did not receive an index or an array of indexes: "[object Object]" [invalid-configuration]" 

So.. whats the best approach? I should set this foo filter in some way or is there any way to let MachinesIndex return a Meteor.Collection? I'd like this second way because i don't need to refactor anything, just hope its possible!

**Comment by matteodem** [comment]
You need to setup a selector configuration that changes the *raw* mongodb selector that is used for search.
