### ISSUE TITLE
addProps not accepting value other than string.

### ISSUE THREAD

**Issue by unceasingwaves** [matteodem/meteor-easy-search#367]
As stated in title addProps function is not not accepting value other than string object. It used to accept Boolean type in 1.*. 

After commenting the type check for value type in addProps function from 
     } else if (_.isString(args[0]) && _.isString(args[1])) {
to
     } else if (_.isString(args[0]) ~~&& _.isString(args[1])~~) {
Works. 

-Gowtham.

**Comment by thomasspiesser** [comment]
+1
i think it also used to accept arrays, otherwise how to add multiple filter keywords for example..

**Comment by matteodem** [comment]
Gonna add that in the next version, feel free to create a PR for it.

**Comment by matteodem** [comment]
Fixed in latest version `2.0.5`.

**Comment by unceasingwaves** [comment]
@matteodem great, thanks.
