### ISSUE TITLE
Using parametric subscriptions

### ISSUE THREAD

**Issue by streamnsight** [matteodem/meteor-easy-search#368]
Been reading through the code and fixing a couple things on my own fork, but I'm still confused about how to make it work for me:

as explained here #359 , one can 'subscribe' to a static subscription and search through it using MiniMongo on the client, but what about the case of parametric subscriptions?

Example: 
I have 10,000 users for a given 'business'. When I subscribe to this list, I use 2 parameters: a filter to only show the users of this business, and a limit. This is what gets to the client.
Now on the client, I also sort and filter those: the 10k users belong to various 'classes' and I need to show these in different pages.
So I end up having many types of Subscriptions for the same 'user' Collection.

Now I want to search through those: 
I can search through Collections, but not Subscriptions. As I understand it, what easy-search returns is a subscription.

If I want to use MiniMongo, I would have to subscribe to the full set (no limit to the client) to then sort through those on the client side. Otherwise I'm only searching through a subset that made it to the client.

So, to search the full set, I really need to do this search on the server side, using MongoDB engine. 
That means my subscription logic needs to be inside the easy-search subscription.

In the Core, you pointed me out to the subscription are:

```
Meteor.publish('carSearch', (searchString) {
  check(searchString, String);

  // index instanceof EasySearch.Index
  return index.search(searchString).mongoCursor;
})
```
If that lets me return a MongoCursor, that is doing the search BEFORE the business logic. 
I want to provide the Mongo Collection to the index AFTER I did my filtering logic (minus the limit)

How would I do this?
I'm coming to thinking I should generate a Collection that is filtered by my logic and then put the index on that... but then we'll probably run into many issues: duplicate dataset (space /storage issue), reactivity (what if the collection changes, does easy search update?) etc...

So, the other option I see is applying the business logic through added filters in ES.
That is a little scary to me there as it's relying on ES to do security, but ok...

So, the question really is: how would I apply a complex Mongo filter to the index?

**Comment by streamnsight** [comment]
re-reading the doc, it seems like all this should be possible using searchDefinition and options... 
it is just not clear how this is done.

**Comment by matteodem** [comment]
You can achieve filtering by adding custom props as your second parameter and having logic in your search index for that. see here http://matteodem.github.io/meteor-easy-search/docs/core/
