### ISSUE TITLE
More complete documentation examples please

### ISSUE THREAD

**Issue by sonicviz** [matteodem/meteor-easy-search#369]
Hi,

Great package, thanks.

However, despite the documentation so far @ http://matteodem.github.io/meteor-easy-search/docs/recipes/  (which is excellent to see!) I found it difficult to understand some things.

Why?

The docs consistently only partially explain things and then give vague references as to how to complete the setup required. This is really frustrating from a learning perspective as it ends up being a little like entering a maze, when all you want to do is implement a solution for a particular use case.

In my case something which I would think would be a very common one: searching on a collection filtered by logged in user. I eventually got it working by minimongo working off the client side.
But trying to get it working off MongoDB quickly became confusing.

eg: http://matteodem.github.io/meteor-easy-search/docs/recipes/ has a section on "Accessing user data" that just shows
// Client and Server
let index = new EasySearch.Index({
  ...
  engine: new MongoDB({
    selector(searchDefinition, options) {
      console.log(options.search.userId); // contains the userId
    }
  }),
  permission(options) {
    console.log(options.userId); // contains the userId
  }
});

Why no examples of how you set the searchDefinition or options?

There's other partial snippets throughout the docs but I also find them more confusing than helpful because they depend on the assumption the reader already knows something or where to find it.
Not really best practice in educational design.

I think the package is excellent, and the documentation site is a great first effort but needs another pass in explaining how all the components and API work in some different common use cases. The leader board is a simple one, but in reality most apps would be working with some kind of user account system - or at least it's the next most common use case. 

I think if you do that then it really will be Meteor Easy Search.

Thanks!

**Comment by matteodem** [comment]
I'm more than interested in how to make the docs better as it might be harder for me to find the unclear points. I'm assuming though that when reading the *recipes* the *Getting started* section is already read. 

_The docs consistently only partially explain things and then give vague references as to how to complete the setup required._

Could you please show me where you think that's happening? I feel like the recipes could indeed be a place where I assume a lot of knowledge, so it might already be of help to link to certain parts or explain certain things more carefully there.

**Comment by sonicviz** [comment]
Snipping from above

>>Why no examples of how you set the searchDefinition or options?

>>The leader board is a simple one, but in reality most apps would be working with some kind of user account system - or at least it's the next most common use case.

**Comment by matteodem** [comment]
The leaderboard example is intended to be simple, but feel free to create an issue there (in the repo) requesting to show an example of how to only let "logged in users" search or any other user related functionality.

I don't know what you mean with

>>Why no examples of how you set the searchDefinition or options?

The  `selector` configuration allows you to change the incoming searchDefinition + options that you provided while searching with `index.search(searchDefinition, options)`. As requested in this issue I'll add more explanation at places where I think it makes sense and feel free to add other parts in the documentation that you think could be better explained or don't make sense.

**Comment by sonicviz** [comment]
Great, look forward to it!

**Comment by matteodem** [comment]
Also something that came up in #381 is:

1) Use Minimongo in the basic example
2) Explain how MongoDB by default publishes all docs and docs should be restricted by using `selector`

**Comment by matteodem** [comment]
Also examples of how to use the `logic` component parameter with multiple indexes and multiple indexes on components in general, see #378 and #377

**Comment by Shelagh-Lewins** [comment]
I think one reason I couldn't find the answers in the documents is that they are organised by how the code is structured. But I don't know whether I want an API or a Component Method, and as I also don't know what the feature I need is called, I go from page to page not finding the right section.

Thanks to your help I'm beginning to understand how it all works and so I can start to explore and figure things out for myself.

Maybe an FAQ with code snippets would be useful for beginners? Questions might include:

- How to find the current search term (myIndex.getComponentDict().get('searchDefinition'))
- How to ensure only published documents are returned (use Minimongo or a selector)
- How to use logic with multiple indexes
- What's the difference between selector, query, filter and permissions
...etc

(I'm not asking you to answer those questions here, just showing them as possible examples)

**Comment by matteodem** [comment]
I've added more docs that hopefully have clearer descriptions. Feel free to read through http://matteodem.github.io/meteor-easy-search/getting-started/. Also there are now snippets in each of the main pages that remind people to read the Getting started page before reading those (Core, Components and Recipes).

Feel free to give feedback.
