### ISSUE TITLE
new Tracker dependency is added to componentDict every time seachTemplate is rendered

### ISSUE THREAD

**Issue by thomasspiesser** [matteodem/meteor-easy-search#375]
Hey, I have a question. I noticed that every time I go to my search page a new Tracker dependency is added to the component dict. Now, when I `console.log('hello from easy:search')` in the `selector()` function of the engine like so:

```javascript
myIndex = new EasySearch.Index({
  collection: MyCollection,
  fields: ['title'],
  engine: new EasySearch.MongoDB({
    selector( searchObject, options, aggregation ) {
      console.log('hello from easy:search');
      let selector = this.defaultConfiguration().selector( searchObject, options, aggregation );
      // custom filter etc...
      return selector;
    },
  }),
});
```

and go from home to search and back and forth a couple of times, I get the following in the browser console:

```
_.keys(myIndex.getComponentDict().keyDeps.searchOptions._dependentsById)
["70", "581", "1007", "1433", "1859", "2285", "2711", "3137", "3159"]
```

and on the server console on searching 'test' for example:

````
I20151124-21:05:01.500(1)? hello from easy:search
I20151124-21:05:01.505(1)? hello from easy:search
I20151124-21:05:01.508(1)? hello from easy:search
I20151124-21:05:01.511(1)? hello from easy:search
I20151124-21:05:01.513(1)? hello from easy:search
I20151124-21:05:01.527(1)? hello from easy:search
I20151124-21:05:01.531(1)? hello from easy:search
I20151124-21:05:01.535(1)? hello from easy:search
I20151124-21:05:01.541(1)? hello from easy:search
I20151124-21:05:01.545(1)? hello from easy:search
```

I was wondering if that is the default/desired behavior? Why are all these dependencies kept? My hunch would be to `stop()` them, when the template is destroyed, but maybe I'm overlooking something?.

**Comment by matteodem** [comment]
I don't think this is the intended behaviour. I'll investigate this further soon, but it looks like it's just a tracker dependency that is not getting stopped.

**Comment by thomasspiesser** [comment]
if you point me into the right direction i could try to provide a fix?!

**Comment by matteodem** [comment]
Sure, so there's a components package that implements the blaze components. You can see here that handles are being created whenever searched with an input https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/lib/input/input.js#L18. 

To me it feels like there's simply a `onDestroyed` method missing in that component that also calls stop on `cursorHandle`. The handle needs to be on the component scope though for that to work.

**Comment by matteodem** [comment]
Fixed in latest version `2.0.5`.

**Comment by thomasspiesser** [comment]
that was fast. Thanks!

**Comment by matteodem** [comment]
I just had time today :stuck_out_tongue_closed_eyes:
