### ISSUE TITLE
Link v1 docs in current documentation

### ISSUE THREAD

**Issue by CWLye** [matteodem/meteor-easy-search#376]
Hello,

Thanks for the awesome package. Works really well and is easy to integrate. This isn't really an issue but is there anyway we can get the documentations for the older version of Easy Search? 

This is a bad time for me to upgrade to Meteor 1.2 but I have plans to upgrade in the next few weeks to make use of the new Easy Search. In the meantime, it would be good if I can still refer to the old documentations.

Thanks!

**Comment by matteodem** [comment]
Hi there

It's actually here https://github.com/matteodem/meteor-easy-search/tree/gh-pages/_v1docs. Not sure if there's an easy way to refer to those docs so that people actually notice it. I'll probably put it into the README.md

**Comment by CWLye** [comment]
Awesome. Thank you! 

Regards,
Chuan Wee

**Comment by matteodem** [comment]
Add the link to the v1 docs here https://github.com/matteodem/meteor-easy-search.
