### ISSUE TITLE
How to use IfSearching and IfNoResults with multiple indexes

### ISSUE THREAD

**Issue by Shelagh-Lewins** [matteodem/meteor-easy-search#378]
Can I use IfSearching and IfNoResults with multiple indexes, so I can show feedback to the user if

a) no results from any index
b) any index is still searching

**Comment by matteodem** [comment]
Yes, see `logic` parameter, http://matteodem.github.io/meteor-easy-search/docs/components/. I'll add examples for that though.

**Comment by Shelagh-Lewins** [comment]
Great, thanks! I'm afraid this is an example of the docs being vague - the page implies this is possible but doesn't explain how to do it. An example would be fantastic.

**Comment by Shelagh-Lewins** [comment]
In case it will help anybody, now that I understand how to use component methods, I've found a workaround by writing a template helper:

    no_results: function() {
      if (patternsIndex.getComponentMethods().hasNoResults() && usersIndex.getComponentMethods().hasNoResults())
        return true
    }

Then in my template:

    {{#if no_results}}
    <span class="no_results">No results found"</span>
    {{else}}
    ...results here...
    {{/if}}
