### ISSUE TITLE
How to use LoadMore with multiple indexes

### ISSUE THREAD

**Issue by Shelagh-Lewins** [matteodem/meteor-easy-search#379]
How should I use LoadMore with multiple indexes, so that there is only one button which loads more results from all indexes?

On a related topic, is there a way to limit total results returned instead of having up to (say) 5 from each for a variable total?

**Comment by matteodem** [comment]
Right now it's only possible for one index, since indexes may show different counts of documents per default, how is your view constructed and why would one load more button for different "type" of search results make sense?

It's totally accomplishable with components API though, please read through the docs carefully (Using component methods) http://matteodem.github.io/meteor-easy-search/docs/components/.

**Comment by Shelagh-Lewins** [comment]
With a single search box, I think the user expects a single interface. For example if you search in Facebook, it show different types of result like pages, people and groups, but there is only one "see more results" button at the bottom of the list. It's a better user experience.

I would want to limit total results because if there are 10 results returned from each of 3 indexes, that's 30 results in total which is too many. But if I restrict each index to 3 results then there will be too few within an index. Again, I think it's what a user expects now. However this is not as important as the single "load more",

I have read the docs, spent about 2 days looking through this so far, but unfortunately I have not been able to understand how to use the API, or what API I should use. I'd be incredibly grateful for a code example. Easy Search is clearly a very powerful package and I'm sure it all makes sense if you understand how it works, but coming to it as a noob, I am finding it confusing.

**Comment by matteodem** [comment]
Feel free to ask me _noobish_ questions right here, my focus in the next days will be to update the documentation to make things as clear as possible.

**Comment by Shelagh-Lewins** [comment]
Thanks! I've had another look and I think I've figured this one out now thanks to your help. To load another 4 results:

   patternsIndex.getComponentMethods().loadMore(4)

(where patternsIndex is whatever you named your Index when you created it)

so what I'll create a button and when you click it, it will run loadMore for each index. Before showing the button I'll need to check for each index whether there is more to load, would

    patternsIndex.getComponentMethods().hasMoreDocuments()

be the right check for that? If so I can put that in a helper to check each index.

**Comment by matteodem** [comment]
Yes, feel free to read through the source code to find out how display logic is handled there. For example the load more component: https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/lib/load-more/load-more.js
