### ISSUE TITLE
Is there a way to combine results from multiple indexes into a single list?

### ISSUE THREAD

**Issue by Shelagh-Lewins** [matteodem/meteor-easy-search#380]
Can I make a single list of results from all indexes, sorted alphabetically? Or do I have to show all of one set of results, then all of the next etc?

**Comment by matteodem** [comment]
No, this is not supported as of now, as it does not make sense (to me at least) to mix data from different collections since they are different. Create a collection that aggregates those different datasets into one document structure if you want to have all of those searchable.
