### ISSUE TITLE
selectors with a compound object

### ISSUE THREAD

**Issue by mudum** [matteodem/meteor-easy-search#383]
If i want to filter my search say by a collection's category then this works fine:

selector.category= "someCategory"

but what if it's a compound object , specifically with a meteor users' profile?

selector.profile.category = "someCategory"

It gives me undefined. Is there another way around this? basically what I want to achieve is that the search is already filtered by the time the template is rendered so certain roles can only search what's already published.

**Comment by matteodem** [comment]
It is as easy as using a mongodb selector where `selector` is the object that is used as the first argument for `collection.find` (see http://docs.meteor.com/#/full/find)

**Comment by mudum** [comment]
hmmm thank you. i really need to understand mongo. this is kinda different than sql

**Comment by matteodem** [comment]
yes it is, see https://docs.mongodb.org/manual/reference/sql-comparison/ for SQL comparison and otherwise google returns good results quite easily.

**Comment by mudum** [comment]
i have another question and since this is minor i don't want to put up a new issue.

Is there a default property for input in search or I do i really have to add it myself like so:

input = options.search.props.input;

Template.name.events({
    "input #some_input": function(event){
      SomeIndex.getComponentMethods()
        .addProps("input", $(event.target).val());
    }
  });

**Comment by matteodem** [comment]
What does _default property for input_ mean? Default value? You can simply set a `attributes` parameter as described here (that is a object with `value` specified) https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/lib/input/input.js#L94.
