### ISSUE TITLE
Documentation issue: recipe to access user data doesn't work

### ISSUE THREAD

**Issue by Shelagh-Lewins** [matteodem/meteor-easy-search#387]
In the recipe 'Accessing user data' this code fails to build:

    engine: new MongoDB({
        selector(searchDefinition, options) {
          console.log(options.search.userId); // contains the userId
        }
      })

If I replace

    new MongoDB({

with

    new EasySearch.MongoDB({

The code builds but the server shows an error:

    Exception from sub patterns/easySearch id FAGMaDTDP5DcPGeaq Error: Match error: Expected object, got undefined

What is the correct way to access userId in a selector for MongoDB?

**Comment by Shelagh-Lewins** [comment]
I've also tried this construction, it runs but options.search.userId is null:

    patternsIndex = new EasySearch.Index({
      collection: Patterns,
      fields: ['name', 'tags', 'created_by_username'],
      defaultSearchOptions: {
        limit: 6
      },
      engine: new EasySearch.MongoDB({
        selector: function (searchObject, options, aggregation) {
          let selector = this.defaultConfiguration().selector(searchObject, options, aggregation);

          selector.createdBy = options.search.userId;
          console.log("id " + options.search.userId);

          return selector;
        }
      })
    });

**Comment by matteodem** [comment]
Did you add one of the accounts packages?

**Comment by Shelagh-Lewins** [comment]
Yes, I'm using:

accounts-password
accounts-ui

**Comment by matteodem** [comment]
Did you try using `options.userId`? I think this is a documentation issue.

**Comment by Shelagh-Lewins** [comment]
I did try it but no, options.userId doesn't work. I ran this code:

    engine: new EasySearch.MongoDB({
        selector: function (searchObject, options, aggregation) {
          let selector = this.defaultConfiguration().selector(searchObject, options, aggregation);

          selector.createdBy = options.userId;
          console.log("keys " + Object.keys(options));
          console.log("id " + options.userId);

          return selector;
        }
      })

In the server console I saw:

keys search,index
id undefined

**Comment by matteodem** [comment]
It should be `options.search.userId`, it only works though if you have the accounts packages added. Are you still experiencing this problem?

**Comment by Shelagh-Lewins** [comment]
How very odd! options.search.userId now works. The exact same code that gave me null, now works.

In my app, I use minimongo as the engine so that searches only happen on the client, which solved my security issue anyway. But thank you very much for getting back to me, now I know how to run this I might take another look at server-side selectors.

**Comment by matteodem** [comment]
Perfect!
