### ISSUE TITLE
Can I search a numeric field?

### ISSUE THREAD

**Issue by Shelagh-Lewins** [matteodem/meteor-easy-search#389]
Is there a way to set up Easy Search so the user can type in a number, such as 10, and see in the results all documents with the value of a numeric field equal to 10?

I've tried this form but got no results:

postsIndex = new EasySearch.Index({
  collection: Posts,
  fields: [ 'number_of_comments'],
  defaultSearchOptions: {
    limit: 6
  },
  engine: new EasySearch.Minimongo()
});

**Comment by mbreuer23** [comment]
You could try something like this.  Basically the idea is to override the default selector which uses a regex search.

```javascript
postsIndex = new EasySearch.Index({
  collection: Posts,
  fields: [ 'number_of_comments'],
  defaultSearchOptions: {
    limit: 6
  },
  engine: new EasySearch.Minimongo({
    selector: function(searchObject, options, aggregation) {
     
      var selector = {};

      selector.number_of_comments = searchObject && searchObject.number_of_comments && parseInt(searchObject.number_of_comments.searchString,10);
      return selector;
    }
  })
});
```

**Comment by Shelagh-Lewins** [comment]
I'm afraThe line 'searchObject.number_of_comments.searchString' puzzles me, why would I expect the searchString to be a property of the returned document?

So I would need to create a new index purely for the numeric field search? I was hoping to return one list of search results finding posts by either (say) username or number of posts, whatever the user typed in. This way I'd have two different sets of search results, one by name and the other by number. But I can make this work, thank you.

A useful option would be to search for posts with **more than** or **fewer than** a particular number of comments, could I do that by replacing 'selector.number_of_comments =' with 'selector.number_of_comments >' ?

**Comment by matteodem** [comment]
EasySearch uses a simple regex search by default with `Minimongo` which works fine for string searches. Since Minimongo uses mongo selectors you need to overwrite that regex to be an exact catch or whatever you want that logic to be, see @mbreuer23's answer. 

There are a lot of examples in the _Recipes_ section and the _Core_ section http://matteodem.github.io/meteor-easy-search/docs/core/.
