### ISSUE TITLE
LoadMore

### ISSUE THREAD

**Issue by GJean** [matteodem/meteor-easy-search#390]
Hello,

It's possible to use LoadMore in JS code, not with button, it's for use search list with lazy loading ?

Thanks,
GJean

**Comment by mbreuer23** [comment]
You could try defining an event listener in your onRendered callback that fires when the user scrolls to a certain point (in this example, to the bottom of the page) ..

```javascript
$(window).scroll(function() {
   if($(window).scrollTop() + $(window).height() == $(document).height()) {
       var numToLoad= 10; // or however many you want to load
       myIndex.getComponentMethods().loadMore(numToLoad)
   }
});
```

**Comment by matteodem** [comment]
Thanks for answering, docs are here under Using component methods: http://matteodem.github.io/meteor-easy-search/docs/components/. Might add this though.
