### ISSUE TITLE
Fetch only selected fields

### ISSUE THREAD

**Issue by WayneUong** [matteodem/meteor-easy-search#391]
Is there an option to only fetch a set of pre-selected fields instead of the entire document? For performance purpose.

**Comment by matteodem** [comment]
Right now you can use `beforePublish` to only return a document that contains the fields you want to have published.

**Comment by matteodem** [comment]
This can be done by providing a `fields` param on engine level. See https://matteodem.github.io/meteor-easy-search/docs/engines/
