### ISSUE TITLE
Search by custom fields

### ISSUE THREAD

**Issue by WayneUong** [matteodem/meteor-easy-search#392]
We allow users to add custom fields to collections. Is there a feature that allows client to add fields dynamically to indexes?

**Comment by mbreuer23** [comment]
I think the way to do this is to use getComponentMethods().addProps() on the client to define what fields are going to be searched.

Then, in your selector definition, get the fields you want to search from options.search.props and define your selector accordingly.

**Comment by matteodem** [comment]
Yes, that would be the preferred way, please have a look at the docs and especially __Recipes__ for cookbook style examples.

**Comment by WayneUong** [comment]
I thought that the selector.fields are for strictly filtering, not search. Let me take a closer look.

**Comment by matteodem** [comment]
I don't understand what you mean with `selector.fields`. Please have a close look at the docs and ask if the recipes don't show enough examples.
