### ISSUE TITLE
Custom mapping with ElasticSearch

### ISSUE THREAD

**Issue by ilectrode** [matteodem/meteor-easy-search#394]
I am trying to use a custom mapping with easysearch:elasticsearch. First I set up an index like so:

``` javascript
index = new EasySearch.Index({
    collection: Books,
    fields: ['title'],
    engine: new EasySearch.ElasticSearch({
        client: {
            host: 'localhost:9200'
        }
    })
});
```

And I am trying to set up a custom mapping as is described in the docs like so:

``` javascript
index.config.elasticSearchClient.indices.putMapping({
        "index": "easysearch",
        "type": "books",
        "body": {
            "books": {
                "properties": {
                    "title": {
                        "type": "string",
                        "analyzer": "snowball"
                    }
                }
            }
        }
    });
```

However, when I do that, I get the following traceback:
`W20151212-13:21:35.732? (STDERR) Unhandled rejection Error: MergeMappingException[Merge failed with failures {[mapper [title] has different index_analyzer]}]
W20151212-13:21:35.732? (STDERR)     at respond (/Users/ilectrode/.meteor/packages/easysearch_elasticsearch/.2.0.3.1daznfj++os+web.browser+web.cordova/npm/node_modules/elasticsearch/src/lib/transport.js:256:15)
W20151212-13:21:35.733? (STDERR)     at checkRespForFailure (/Users/ilectrode/.meteor/packages/easysearch_elasticsearch/.2.0.3.1daznfj++os+web.browser+web.cordova/npm/node_modules/elasticsearch/src/lib/transport.js:219:7)
W20151212-13:21:35.733? (STDERR)     at HttpConnector.<anonymous> (/Users/ilectrode/.meteor/packages/easysearch_elasticsearch/.2.0.3.1daznfj++os+web.browser+web.cordova/npm/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
W20151212-13:21:35.733? (STDERR)     at IncomingMessage.wrapper (/Users/ilectrode/.meteor/packages/easysearch_elasticsearch/.2.0.3.1daznfj++os+web.browser+web.cordova/npm/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
W20151212-13:21:35.733? (STDERR)     at IncomingMessage.emit (events.js:117:20)
W20151212-13:21:35.734? (STDERR)     at _stream_readable.js:944:16
W20151212-13:21:35.734? (STDERR)     at process._tickCallback (node.js:448:13)`

It looks like the default mapping set up by easysearch is conflicting with my custom mappings. I have read the docs and the tests, and tried everything else I could, and I am unable to resolve my issue. I feel like the documents for the elasticsearch section are incomplete compared to the rest of the docs. 

Some documentation for setting up custom mappings would be appreciated.

**Comment by mgebundy** [comment]
Documentation would indeed be great, but from what I can see it's incredibly difficult to create a custom mapping before easysearch starts indexing everything into elasticsearch.

Many mapping configurations need to be configured before indexing begins. For example, in my case, I need to have certain fields as type `nested`, but elasticsearch won't let fields be converted to that type with data already indexed.

**Comment by matteodem** [comment]
I'll probably add a method configuration that allows to execute actions with the elasticsearch client before the documents get indexed.

**Comment by moonrockfamily** [comment]
First and foremost, thank you for all your work on Easy Search.  Solid design and easy to read and extend! 
- I like your idea of adding a 'method configuration' for the ElasticSearchClient.  
- it likely makes sense to add the elastic search indexName and indexType to the indexConfig and pass it to the ElasticSearchDataSyncer constructor; it already has the collection and elasticSearchClient
- it would be nice to also have a 'method configuration' for the 'data-syncer' and pass the default ElasticSearchDataSyncer and indexConfig object and expect an 'data-syncer' instances in retrun that have a start() method.  The start() method would observe the collection changes etc...

**Comment by steven-tib** [comment]
@ilectrode, have you found a solution to this issue ? I'm trying as well to change the mapping but cannot manage to do so. 

Maybe @matteodem has solved it in the meantime and my issue comes from somewhere else. Just wanted to get an update on your situation and maybe your help. thank you
