### ISSUE TITLE
'meteor add' adds older version of package

### ISSUE THREAD

**Issue by pyankoff** [matteodem/meteor-easy-search#395]

**Comment by matteodem** [comment]
Which package?

**Comment by pyankoff** [comment]
'easysearch:components', there is some console log when search input loads. I also had some problems with using 'else' in 'ifHasNoResults', which should have been fixed in last version, so maybe core as well. Didn't have time to look into it.

**Comment by matteodem** [comment]
Please write into this issue if it's still a problem
