### ISSUE TITLE
Get information from Client in the beforePublish function

### ISSUE THREAD

**Issue by iuraya** [matteodem/meteor-easy-search#397]
Hi,

I'm trying to show a list of products. Each of this products has a latitude and longitude values that represent its position. I would like to be able to sort the list by the distance of current user position to the products position. 

For getting the user position I use a geolocation service. Once I get lat and lng of current position I would like to use the 'beforePublish' function in order to add a distance field to the products and so be able to do a distance sorting.

Is there a way of passing the lat and lng of the user position to the 'beforePublish'?

As I haven't found a way of doing this I've tried to save in the mongo user collection his current position and accessing it in the  'beforePublish' but I get this:

"Exception in queued task: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions"

Thank you!

**Comment by matteodem** [comment]
Yes, it is possible to sort for lat / lng as you can specify the mongodb sort object with the `sort` configuration method. Also can you show me an example of your configuration + example code to show what you want to achieve in the `beforePublish` method?

**Comment by iuraya** [comment]
Hi,

Thank you for your response. I've finally resolved the problem using the geometry option of mongo in the sort configuration of the engine like this:

engine: new EasySearch.MongoDB({	
	sort: function (searchObject, options) {
		latFilter = options.search.props.latFilter;
		lonFilter = options.search.props.lonFilter;
		if (_.isString(latFilter) && !_.isEmpty(latFilter)) {
			var lat = parseFloat(latFilter);
			var lon = parseFloat(lonFilter);
			return {priority : -1, marker:{$near:{$geometry:{type: "Point",coordinates:[lon,lat]}}}}
		}
	}
})
