### ISSUE TITLE
sort on client?

### ISSUE THREAD

**Issue by mbreuer23** [matteodem/meteor-easy-search#398]
is it possible to sort results on the client?  I'm just doing a simple console.log in the engine's sort definition and it's only showing up on the server.

Basically, I'm trying to sort by a field added as part of the transform, which as I understand only happens on the client.

**Comment by matteodem** [comment]
It currently is only possible with the Minimongo engine. Does it not make sense to have this field as a "real" field of the document / is it a customer specific computed property?

**Comment by mbreuer23** [comment]
I don't think I can add it directly.  The value of the field will depend what route I'm on.  

I could possibly make it work if I had access to options.search.props in the beforePublish function (correct me if I'm wrong but it doest appear that I do currently).  That way I just pass in route info as a prop. 

My use case is that I am searching an index on Meteor.users as part of a form to invite people to an event.   I want to sort it so users who've already been invited are at the bottom. So yeah I guess I could de normalize and store all the users events in the user doc, but I don't think  that would help with sorting, since I'd still need to compute the field to sort by based on what plan I'm currently viewing

**Comment by matteodem** [comment]
Yeah. I think there needs to be some option to configure client only sorting. Maybe using the `search` method.

**Comment by matteodem** [comment]
This is now configurable with `clientSort` http://matteodem.github.io/meteor-easy-search/docs/engines/
