### ISSUE TITLE
iron:router pathFor __originalId

### ISSUE THREAD

**Issue by CharlesHumbert** [matteodem/meteor-easy-search#400]
The tag below does not seem to work as expected 

    {{pathFor 'pageRoute' doc.__originalId }}

while this tag works perfectly

    {{doc.__originalId}}

Reproduction here : http://meteorpad.com/pad/smsjBLZMQciivQ36B/Easy:search%20__originalId

It seems simple but I cannot seem to understand...

**Comment by CharlesHumbert** [comment]
The solution was just to precise the param id 

    {{pathFor 'pageRoute' _id=doc.__originalId }}

I close the issue

**Comment by mervynteo** [comment]
@CharlesHumbert  May I ask how u set up the js file to use the originalId reference? The docs arent clear on it?
