### ISSUE TITLE
Multiple FieldInputs in a table

### ISSUE THREAD

**Issue by nigelpasco** [matteodem/meteor-easy-search#401]
Hi... great package :)

I am wanting to add a second FieldInput searchbox in the same index on the same template.

Using the Leaderboard example for a case, can I replace the {{>EasySearch.Input index=index}} with two {{>EasySearch.FieldInput index=index}}, one to search field="name" and the other to search field="category".

This test case is not working for me as above.
thank you : P

**Comment by matteodem** [comment]
How did you setup your index + the field inputs?
