### ISSUE TITLE
Styling/ customizing components?

### ISSUE THREAD

**Issue by afang** [matteodem/meteor-easy-search#402]
Is there any way to edit the component so it's not just a plain text input?

**Comment by matteodem** [comment]
What would you like to edit? You can add classes with the `attributes` param and search with something different than an input by using the component methods.

**Comment by afang** [comment]
Trying to use this markup:
```
<div class="ui icon transparent large input inverted">
							<input type="text" placeholder="Search...">
							<i class="search icon"></i>
						</div>
```

**Comment by matteodem** [comment]
You can set the placeholder by using `attributes` and specify the other markup around the use of `EasySearch.Input`. Do you need an example?

**Comment by afang** [comment]
Thank Matteo that would help

**Comment by matteodem** [comment]
```html
<template name="mySearch">
  <div class="ui icon transparent large input inverted">
    {{> EasySearch.Input attributes=inputAttributes}}
    <i class="search icon"></i>
  </div>
</template>

```

```javascript
Template.mySearch.helpers({
  inputAttributes: () => { placeholder: 'Search' }
});
```
