### ISSUE TITLE
EasySearch.IfNoResults shows "No results found" while search runs

### ISSUE THREAD

**Issue by daveyshindig** [matteodem/meteor-easy-search#404]
Hi,

First of all, thank you for creating this useful search package.

One little problem I'm having: I understand that there are "no results" while the search is happening, but is there any way to prevent it from showing up as such? It's misleading to say "no results found" before the search is finished. 

I checked, but couldn't find any answers in the other issues or docs.

**Comment by rteslaru** [comment]
I'm having the same problem, not sure if you found a workaround, @daveyshindig

**Comment by matteodem** [comment]
The leaderboard example does not show the "No results found" content until the search is done, see https://github.com/matteodem/easy-search-leaderboard/blob/master/leaderboard.html. Please provide a reproduction repository if that's not the case with your project.

**Comment by matteodem** [comment]
This is fixed as of latest version `2.0.9`
