### ISSUE TITLE
Publication needs to update counts

### ISSUE THREAD

**Issue by veered** [matteodem/meteor-easy-search#407]
The search results don't properly update when a new item is added to the collection. To fix this we need to add: 

```
this.changed(collectionName, 'searchCount' + definitionString, { count: cursor.mongoCursor.count() });
```

to both the `addedAt` and `removedAt` handlers in `search-collection.js`.

**Comment by shybyte** [comment]
I've hit the same problem.

**Comment by shybyte** [comment]
The proposed fix from @veered  solved the problem for me, but I don't know if it has any unwanted side effects (e.g. performance-wise). 
Still, if it helps somehow to get this fix faster into a new version of meteor-easy-search I could prepare a pull request.

**Comment by matteodem** [comment]
I'll have a look at this today.

**Comment by matteodem** [comment]
This requires more changes as the `observe` method in the search collection is only obversing the docs that are currently displayed and not all. It would require an observe on all docs and changing the count based on that. Not sure how performant that would be though.

**Comment by matteodem** [comment]
this package might be of help https://github.com/percolatestudio/publish-counts

**Comment by veered** [comment]
My proposed fix had super serious performance impacts, so I am using a polling strategy now to update the counts. This has been working pretty well for me. I'm happy to post the code if anyone would like.

**Comment by matteodem** [comment]
sure feel free to post anything that could be of help when implementing this. PR's are also highly appreciated!

**Comment by veered** [comment]
Here is a gist: https://gist.github.com/veered/14944b93435662833f6690d951855776

The polling bit is at the end.

**Comment by matteodem** [comment]
awesome, seems like the polling approach might be a feasible approach for now. Do you already have this running / working in a fork of yours?

**Comment by veered** [comment]
I do indeed, but I have changed other things in the fork and do not recall which changes are necessary for this fix :\. I can try to take a closer look when I have more time.

**Comment by matteodem** [comment]
This is fixed in the latest easy-search veriosn
