### ISSUE TITLE
error: conflict: two packages included in easysearch:components (peerlibrary:blaze-components and templating) are both trying to handle *.html

### ISSUE THREAD

**Issue by blargity** [matteodem/meteor-easy-search#408]
Hi there,

Just upgraded to the latest versions of my indirect dependencies today and got this error message:

```
$ meteor
[[[[[ ~/project ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While building for web.browser:
   error: conflict: two packages included in easysearch:components (peerlibrary:blaze-components and templating) are both trying
   to handle *.html
   
=> Your application has errors. Waiting for file change.
```

My ```.meteor/versions``` file has the following:

```
easy:search@2.0.6
easysearch:components@2.0.6
easysearch:core@2.0.5
...
peerlibrary:assert@0.2.5
peerlibrary:base-component@0.14.0
peerlibrary:blaze-components@0.16.0
peerlibrary:computed-field@0.3.1
peerlibrary:data-lookup@0.1.0
peerlibrary:reactive-field@0.1.0
```

If you need I can create a reproduction repo but I haven't gotten around to it yet. Not sure if removing the dependency on templating would be the right thing to do here.

**Comment by chotikarn** [comment]
I have same problem and look like new update of Blaze Component (0.16.0) causes this error. 

https://github.com/peerlibrary/meteor-blaze-components/issues/111

reinstall Blaze Component with version 0.15.1 fix this.

**Comment by mitar** [comment]
In this [line](https://github.com/matteodem/meteor-easy-search/blob/f1438f5f5fbce2ef00112a63944fc3408fff5845/packages/easysearch:components/package.js#L13), `templating` should be removed. 0.16.0 integrates it.

**Comment by mitar** [comment]
I opened this [pull request](https://github.com/matteodem/meteor-easy-search/pull/409).

**Comment by Futurama56** [comment]
+1

**Comment by Futurama56** [comment]
Thanks for such a quick response!
