### ISSUE TITLE
Help needed: Exclude certain items from results

### ISSUE THREAD

**Issue by alexandersingleton** [matteodem/meteor-easy-search#410]
Hi all, 

Firstly thanks for the great package it's been a real help with my project. I've been building a job board type app and for the most part I've got the search functionality working as expected, there is a search bar and when I type results into it I get the expected output.

However, I'd like a way to exclude certain results from the search such as those that have been marked as deleted, not approved or expired. I've managed to do this in normal publications such as: 

`Posts.find({deleted : {$exists: false}, expired: {$exists: false}});`

but haven't been able to implement this with Easy-Search, is there a simple way to add this?

Many thanks, 
Alex

**Comment by mbreuer23** [comment]
You can easily do this in your engine's selector configuration

````
myIndex = new EasySearch.Index({
	collection: Posts,
	fields: ['title'],
	name: 'myIndex',
	engine: new EasySearch.MongoDB({
		selector: function(searchObject, options, aggregation) {
			var selector = this.defaultConfiguration().selector(searchObject, options, aggregation);

			selector.deleted = {$exists: false};
			selector.expired = {$exists: false};

			return selector;
		}
	})
});

**Comment by matteodem** [comment]
Thanks for answering

**Comment by alexandersingleton** [comment]
Thanks for the reply. It now works :)
