### ISSUE TITLE
[invalid-configuration]

### ISSUE THREAD

**Issue by JulianKingman** [matteodem/meteor-easy-search#411]
I'm having trouble implementing this plugin. I get the following error:
````
Error: Did not receive an index or an array of indexes: "esSourceGroups" [invalid-configuration]
````

The indexes:
````javascript
esSourceGroups = new EasySearch.Index({
    'collection': SourceGroups,
    'fields': ['title'],
    'engine': new EasySearch.Minimongo()
});
esSources = new EasySearch.Index({
    'collection': Sources,
    'fields': ['title'],
    'engine': new EasySearch.Minimongo()
});
````

The template helpers:
````javascript
Template.sideNav.onCreated(function () {
    var template = this;
    //These are special publications that remove transforms on the collection, just in case that was the problem.
    template.subscribe("searchSourceGroup");
    template.subscribe('searchSource');
});
Template.sideNav.helpers({
    esIndexes: function() {
        return [esSources, esSourceGroups];
    },
    esSources: function() {
        return esSources;
    },
    esSourceGroups: function() {
        return esSourceGroups;
    }
});
````

The template:
````html
<template name="sideNav">
        {{#if Template.subscriptionsReady}}
            <ul class="off-canvas-list" title="Link List">
                <li>
                            {{> EasySearch.Input indexes=esIndexes}}
                </li>
                <li class="{{selected}}">
                            {{#EasySearch.IfSearching indexes=esIndexes logic="OR"}}
                                <a href=""><i class="fa fa-spinner fa-spin"></i>Loading results...</a>
                            {{/EasySearch.IfSearching}}
                            {{#EasySearch.Each index="esSourceGroups"}}
                                <a href="/sourceGroup/{{_id}}" class="left">{{title}}</a>
                            {{/EasySearch.Each}}
                            {{#EasySearch.Each index="esSources"}}
                                <a href="/sourceGroup/{{parent}}/source/{{_id}}" class="left">{{title}}</a>
                            {{/EasySearch.Each}}
                </li>
            </ul>
        {{/if}}
</template>
````

Any idea what could be going wrong here?

**Comment by JulianKingman** [comment]
Hah, that was quick... here's the problem:
````html
{{#EasySearch.Each index="esSourceGroups"}}
````
Should be:
````html
{{#EasySearch.Each index=esSourceGroups}}
````
(no quotes)

**Comment by AdrianAbba** [comment]
export const Projects = new Mongo.Collection('projects');

ProjectIndex = new Index({
    collection: Projects,
    fields: ['title', 'subtitle','tags','jobs'],
    engine: new ElasticSearchEngine({
      sort:() => {
        return { createdAt: -1 }
      }
    
    })
  });

Template.landingPage.helpers({
  index: function () { return [ProjectIndex];  },
  projectIndex: function () { return ProjectIndex; },
  
});

{{> EasySearch.Input indexes=index}}</div>

          {{#EasySearch.Each index=projectIndex}}
              {{#if coverImg}}
                {{>projectCard}}
              {{else}}
                {{>projectCardCoverless}}
              {{/if}}
          {{/EasySearch.Each}}


details: undefined
error : "invalid-configuration"
errorType : "Meteor.Error"
message: "Did not receive an index or an array of indexes: "" [invalid-configuration]"
reason : "Did not receive an index or an array of indexes: """


any ideas to fix the error :/?

**Comment by matteodem** [comment]
don't provide the index as an array:

```
index: function () { return ProjectIndex;  },
```

**Comment by AdrianAbba** [comment]
changed it but getting this error now.

details : undefined
error : "no-index"
errorType :"Meteor.Error"
message: "Please provide an index for your component [no-index]"
reason :"Please provide an index for your component"
stack: "Error↵    at InputComponent.onCreated (http://localhost:3000/packages/easysearch_components.js?hash=55bcc51f18d9e621ffcbb1fa2dc9a6d7b1942c6d:87:15)↵    at InputComponent.onCreated (http://localhost:3000/packages/easysearch_components.js?

**Comment by matteodem** [comment]
please just do appropriate `console.log`s and find out the value actually is.

**Comment by AdrianAbba** [comment]
its always undefined

**Comment by matteodem** [comment]
so that means you need to import / export that index. please refer to how ES2015 works.

**Comment by AdrianAbba** [comment]
already did :) 

i forgot the export of ProjectIndex and used indexes by the input, had to change it to index.

thank you :)
