### ISSUE TITLE
Is there no hook on search completion?

### ISSUE THREAD

**Issue by daveyshindig** [matteodem/meteor-easy-search#414]
Hi,

I'm looking to run a function every time easy-search brings back the search results, but I couldn't find a hook for it anywhere in the docs. 

I couldn't figure out how to adapt issue #281, now that `getComponentInstance` has been split into the index methods `getComponentMethods` and `getComponentDict`. #281 refers to docs that no longer exist. I looked through the updated API, and read more jQuery docs and a few help threads elsewhere, but can't figure out how to do it.

There's probably an obvious solution, so I feel a little stupid for asking. I'm still pretty new to JavaScript and programming for the browser, so if someone could help me I'd be truly grateful.

**Comment by mbreuer23** [comment]
There are probably a few ways to do this.  One way that comes to mind is by referencing the getComponentDict method, specifically the 'searching' key.  This returns a reactiveDict, so you can use it in a template autorun which will rerun a function anytime the key changes

For example:

```
Template.myTemplate.onRendered(function() {
    var template = this;
   
    let dict = myIndex.getComponentDict();

    template.autorun(function() {
     // this line sets up a reactive dependency on the "searching" key
     // so this code will be re-run anytime it changes 
      let searching = dict.get("searching");

     // if we are not seearching, run the function
     // you can also refer to other dict keys (e.g. dict.get("currentCount")) to add more conditions
      if (!searching) {
        //do stuff 
      }
    });
});

**Comment by matteodem** [comment]
Is that answer sufficient? (thanks for answering @mbreuer23)

**Comment by daveyshindig** [comment]
Hi guys, 

I only just now got to try this, and @mbreuer23 did answer it more than sufficiently. My sincere thanks to you both for your help. Cheers!
