### ISSUE TITLE
EasySearch.getComponentInstance

### ISSUE THREAD

**Issue by pharaujo-git** [matteodem/meteor-easy-search#415]
Hi @matteodem, thank you very much for this awesome package.

I have problem trying to use the autosuggest following this example: 
https://github.com/matteodem/meteor-easy-search/blob/gh-pages/_v1docs/autosuggest-field.md

I got error on this line:
var instance = EasySearch.getComponentInstance(

Error: Uncaught TypeError: EasySearch.getComponentInstance is not a function

This method getComponentInstance was changed?

Thank you,
Paulo Henrique

**Comment by matteodem** [comment]
Those are the docs for v1, you might want to have a look at the current docs: http://matteodem.github.io/meteor-easy-search/getting-started/
