### ISSUE TITLE
auto-suggest does not work with multiple indexes

### ISSUE THREAD

**Issue by WayneUong** [matteodem/meteor-easy-search#418]
Here's my code:
{{> EasySearch.Autosuggest indexes=searchIndexes renderSuggestion="suggestion" }}

And here's the error:
Error: Please provide an index for your component [no-index]
    at null.<anonymous> (autosuggest.js:13)

**Comment by matteodem** [comment]
It doesn't because several data sets don't make sense in an autosuggest field. Feel free to convince me otherwise.

**Comment by WayneUong** [comment]
We are using auto suggest as the drop down for quick search results. Like
the search box you have on Facebook or LinkedIn. It's just very convenient.
Basic features like custom results UI or pressing arrow keys to navigate
are already there. Do you know of a better way?

Thanks.

**Comment by matteodem** [comment]
It would be best to have a specific search result collection that unifies all possible search results into one collection and then use `MongoDB` as your engine to search through it.

An even better approach would be to use `ElasticSearch` and create an elasticsearch index, which needs some time to setup and learn though.

**Comment by matteodem** [comment]
Feel free to write create a new issue if there are any other problems.
