### ISSUE TITLE
High CPU usage and pub-sub response times on version 2

### ISSUE THREAD

**Issue by actooalizame** [matteodem/meteor-easy-search#419]
I'm rebuilding an app on React (previously used Blaze) and updated to version 2 of this package.
I couldn't make it work without having <strong>several performance issues</strong> on a Digital Ocean 1GB droplet. 
I have a "Professors" collection that uses >6k documents.

The Kadira monitor showed a publication of your package  "professors/easySearch" taking <strong>several</strong> seconds to load.
![cap-kadira-pubs-before](https://cloud.githubusercontent.com/assets/11241403/12192547/5432e0a6-b5be-11e5-99bc-3d9da376abaa.jpg)

You can see that implemented here:  http://reprofes.meteor.com/
(search for a name like "Hugo")
At first it appears to work as expected, but after waiting some minutes without searching, it will take many seconds to display the results. <strong>This goes back to normal after hard reloading the page</strong>.
Also: The CPU usage peaked up to 100%
<hr>
Once I downgraded the package to version 1.6.4, everything works really fast, without the "professors/easySearch" publication not even appearing, and with the CPU usage never reaching the 2% mark.
![cap-kadira-pubs-after](https://cloud.githubusercontent.com/assets/11241403/12192530/1ad0a1ae-b5be-11e5-8e72-e6386bb6a2f0.jpg)

You can see that implemented here: http://webparaemprendedores.com/

Here is a screen capture of the obvious performance difference being tracked down by Kadira, before and after going back to the previous version :
![cap-kadira-easysearch](https://cloud.githubusercontent.com/assets/11241403/12192275/f237b78e-b5bb-11e5-8046-7e3f649650a7.jpg)

Please note that I'm not subscribing to any publication except for single-documents publications and your v.2 package generated pubs-subs.
I really don't know what may be causing this, but I followed along your v.2 documentation, and made it work (as you can see on the v.2 meteor.com hosted example).
<strong>Please correct these issues, as I want to use the up-to-date version of this useful package.</strong>

Thanks,

**Comment by matteodem** [comment]
Thank you for these helpful metrics. I'll have a look at those things in the next days.

**Comment by matteodem** [comment]
Please show me your EasySearch configuration together with sample docs so that I can reproduce it locally.

**Comment by actooalizame** [comment]
Sure:

I use your 'faceted search' recipe:
lib\collections\professors.jsx

    Professors = new Mongo.Collection('professors');
    ProfessorsIndex = new EasySearch.Index({
      collection: Professors,
      fields: ['name','slug'],
      //returnFields: ['name','schoolName','department'],
      defaultSearchOptions: {
      limit: 5
     },
     engine: new EasySearch.MongoDB({
       selector: function (searchObject, options, aggregation) {
         let selector = this.defaultConfiguration().selector(searchObject, options, aggregation),
              schoolName = options.search.props.schoolName;
         if (_.isString(schoolName) && !_.isEmpty(schoolName)) {
           selector.schoolName = schoolName;
         }
        }
        return selector;
      })
    });

I render this Blaze template into a React component:

client\components\search\searchProfessors.html

    <template name="searchBoxProfessors">
      <div class="form-group">
        {{> EasySearch.Input attributes=inputAttributes index=professorsIndex }}
      </div>
      {{#EasySearch.IfInputEmpty index=professorsIndex}}
	   <div class="hidden">hi</div>
        {{else}}
        {{#if professorsIndex}}
          <ul class="list-group searchResults">
          {{#EasySearch.Each index=professorsIndex }}
            <li class="list-group-item"><h4><a href="/profesor/{{__originalId}}">{{name}}</a></h4></li>
          {{/EasySearch.Each}}
          </ul>
        {{/if}}
      {{/EasySearch.IfInputEmpty}}
    </template>

I saw your V.2 example hosted on meteor.com servers working properly, with a collection of >90k documents working properly. I didn't copy your .html file of your leaderboard example, though.
So I wondered if there's something I'm missing out there.

I deleted my .meteor.com instance with the v.2 package by error.

**Comment by matteodem** [comment]
Please try it without wrapping the `{{#EasySearch.Each}}` inside the `IfInputEmpty` component. That seems to make problems sometimes. If that helps you can for now have a hack that returns a selector which does not match any documents. Otherwise if it doesn't please provide me a small reproduction repository.

**Comment by matteodem** [comment]
Please test this with the latest version, might have been something that coorellates to another issue.

**Comment by actooalizame** [comment]
Thanks for looking into this :) I've been squashed busy these days.

Going to try latest version and your indications and comment later.

Thx a lot

**Comment by matteodem** [comment]
How does it look like?

**Comment by actooalizame** [comment]
Hi, 

I ended up using version 1.5.6 of this package on a Meteor 1.3.2.4 Galaxy deployment and it's working with no issues. 
I also deployed a Meteor 1.2.1 build with ES v.1.5.6 on Digital Ocean 1gb and it works perfect even with an unfiltered search on a 20k items collection. 

Didn't tested newer versions of this package on any deployment, though. I guess I'll stick with 1.5.6, hopefully Meteor 1.3+ will continue to play nice with the older version of EasySearch. 
Can you please give me any feedback on that? 

Thanks,

**Comment by matteodem** [comment]
I'll close this story then as the leaderboard uses about 30k documents and seems to handle it very well too with v2.
