### ISSUE TITLE
Filtering the collection

### ISSUE THREAD

**Issue by mroftalp** [matteodem/meteor-easy-search#420]
I'm confused on how to filter the collection in the results. I have a UsersIndex which the collection is the default Meteor.users. But I want to only show the users that are not in the array of another collection. In a document of this collection I have field that is an array `{users: ['user_id_1', 'user_id_2']}` and anything in that array should not be included in the easy search index results. How do I achieve this? Also I have to get the _id of the document from the client that should filter the users. So right now, my work around, I have this helper:
```
userAssigned: function(userId) {
     var collectionId = Router.current().params._collectionId
     if (CollectionName.find({_id: collectionId, users: userId}) {
        return true; 
     }
}
```

then in the html
```
{{#EasySearch.Each index=usersIndex}}
    {{#unless userAssigned __originalId}}
         <li>{{username}}</i>
    {{/unless}}
{{/EasySearch.Each}}
```

if that returns true then I know that the user is assigned to it and should not be in the results.  Although this would not show that no search was found as it still returns the true count of the search. Hoping for a better solution for this. Thanks!

**Comment by mroftalp** [comment]
Also I tried the search with emails in the docs, it doesn't seem to search the email. Right now working is using emails.0.address in the fields.

**Comment by mroftalp** [comment]
Ok I now know about the email. in MongoDB there's no selectorPerField. So how do the emails search in MongoDB?

**Comment by matteodem** [comment]
What is your exact problem? Also show me examples of the documents you want to search.

**Comment by mroftalp** [comment]
Okay. I'm searching for Meteor.users. But want to filter it, the way to filter it is to check another collection. Which is for example Tasks collection. The user is assigned to it already. The field is assignedTo which is an array of userId. I don't want to show the users assigned in the search. How to do this?

**Comment by matteodem** [comment]
Show me your EasySearch configuration.

**Comment by mroftalp** [comment]
UsersIndex = new EasySearch.Index({
    collection: Meteor.users,
    fields: ['username', 'profile.firstName', 'profile.lastName', 'emails.0.address'],
    engine: new EasySearch.MongoDB(),
    permission(options) {
        return options.userId; // only allow searching when the user is logged in
    }
});

I haven't done the filter cause I really don't know how.

**Comment by matteodem** [comment]
There are quite a lot of examples in the docs, and other people that asked how to do it in other issues, please try to investigate there.
