### ISSUE TITLE
Multiple indexes - The second index on the list does not work well

### ISSUE THREAD

**Issue by Roylib** [matteodem/meteor-easy-search#423]
When implementing multiple indexes, the second index on the helper list always runs for several iterations.
It shows/hides elements very quickly for 1-5 seconds until stabilizes and stops to show results.
After these few seconds, both the fast (first) index, and the problematic one (second), show the correct results.
The indexes were implemented according to the example in the components documentation.

As I mentioned, I've noticed that if the order of the indexes dictates which one will be the unstable one:
If the order is searchIndexes: () => [indexOne, indexTwo] -> then indexTwo is unstable
If the order is searchIndexes: () => [indexTwo, indexOne] -> then indexOne is unstable

Please assist.

**Comment by matteodem** [comment]
Can you please show me your easysearch configuration and a clear description of what the current / expected behaviour should be

**Comment by Roylib** [comment]
Of course,

Expected Behavior: One search box, two different result lists from two different collections (indexes).

Current Behavior: One of the two lists expands and contracts for several seconds. It alternates very quickly between showing about 2 items to 8 items. This expansion/contractions usually lasts a few seconds until the list items stabilize to show a static result.

Insights:
- This occurs only to the index which is listed second on the "indexes" list in the template helper.
- To trigger the problem in its extreme, type the following in the search box:
a -> aa -> aaa -> aa (backspace) -> a (backspace)

At this point, the list takes about 5 seconds to stabilize.

Let me know if there's anything else that I can supply.

Code:
indexOne = new EasySearch.Index({
  'collection': collectionOne,
  'fields': ['title'],
  defaultSearchOptions: {
    limit: 10
  },
  'engine': new EasySearch.MongoDB({
    sort: function () {
      return { 'title': 1 };
    }
  })
});

indexTwo = new EasySearch.Index({
  'collection': Meteor.users,
  'fields': ['username'],
  defaultSearchOptions: {
    limit: 10
  }
});

Template.SearchIndex.helpers({
  indexes: () => [indexOne, indexTwo],
  indexOne: () => indexOne,
  indexTwo: () => indexTwo,
  inputAttributes: function () {
    return { 'class': 'easy-search-input', 'placeholder': 'Search...' };
  }
});

<template name="SearchIndex">
    {{> EasySearch.Input indexes=indexes attributes=inputAttributes }}

    <ul class="searchIndex">
        {{#EasySearch.Each index=indexOne }}
            {{> indexOneItem}}
        {{/EasySearch.Each}}
    </ul>

    <ul class="searchIndex">
        {{#EasySearch.Each index=indexTwo }}
            {{> indexTwoItem}}
        {{/EasySearch.Each}}
    </ul>

</template>

**Comment by Roylib** [comment]
Do you have any lead on this issue?
Does it replicate for you as well?

**Comment by matteodem** [comment]
Had a look at this and it has to do with a tracker dependency rerunning infinitely (input.js, L18), I'll try to fix this when I have time to.

**Comment by Roylib** [comment]
Thanks, glad to hear you've found it.
How complicated is it to fix? Expected anytime soon?

**Comment by matteodem** [comment]
I'll try to have a closer look again this weekend.

**Comment by matteodem** [comment]
Please test this issue in the latest version

**Comment by Roylib** [comment]
It works great, thanks!
