### ISSUE TITLE
High CPU usage, multiple subscriptions.

### ISSUE THREAD

**Issue by joejeet** [matteodem/meteor-easy-search#425]
I've collection which contains around 10,000 documents in it and each documents contains around 30 fields. Search looks from 5 fields. Also, in beforePublish it collects data from other collection which contains around 5k docs in it.

Current setup of search is MongoDb Core engine with setup like.

```
OpportunitiesIndex = new EasySearch.Index({
  engine: new EasySearch.MongoDB({
  beforePublish: function (action, doc) {
      doc.company = Companies.findOne({"_id": doc.companyId }, {
                fields: {
                    slug: 1,
                    name: 1,
                    coverImage: 1
                  }});

  return doc
},
transform: function(doc) {
  doc.location = doc.city;
  return doc;
},
props: {},
sort: function () {
  return [['featured', 'desc'],['createdAt', 'desc']];
},
selector: function (searchObject, options, aggregation) {
  var selector = this.defaultConfiguration().selector(searchObject, options, aggregation),
   now = moment();
  selector.expiresAt = {$gte: now._d};
  selector.hidden = false;

  var filters = options.search.props;
  if (filters.location) {
    selector.city = filters.location;
  }
  return selector;
 }
}),
 name: 'OpportunitiesIndex',
 collection: Opportunities,
 fields: [ 'name', 'companyName', 'city', 'jobFunctionId', 'employmentType'],
 defaultSearchOptions: {
   limit: 24
 }
});
```

With view page:

```
<section class="row text-center bottom-buffer">
 <div class="col-md-6 col-md-offset-3">
  {{> EasySearch.Input index=index attributes=inputAttributes }}
 </div>
</section>
{{#EasySearch.IfSearching index=index }}
  <div>Searching...</div>
  <div>{{> spinner }}</div>
{{/EasySearch.IfSearching }}
<div class="results-wrapper">
 <section class="tiles row">
  {{#EasySearch.Each index=index }} {{> listingTile }} {{/EasySearch.Each}}
 </section>
</div>
{{> EasySearch.LoadMore index=index count=12 attributes=paginationButton}}
{{#EasySearch.IfNoResults index=index }}
 <div class="padded no-results">
  No results
</div>
{{/EasySearch.IfNoResults }}
```

Normal search returns in multiple subscriptions and high CPU usage.

Following is result from Kadira for one search term enter and it return in 30 subscriptions and response time greater than 12sec.

![screen shot 2016-01-22 at 12 31 07](https://cloud.githubusercontent.com/assets/36263/12510779/423ed5ca-c104-11e5-8160-1779ec42ab14.png)

**Comment by matteodem** [comment]
Hm weird, I'll try to replicate this with the easy search leaderboard

**Comment by matteodem** [comment]
Is this problem still there? I'm not sure how performant it is to have a `findOne` for every document that is published. (in `beforePublish`)

**Comment by actooalizame** [comment]
Thanks for looking into this :) I've been squashed busy these days.

Going to try latest version and your indications and comment later. 

Thx a lot

**Comment by joejeet** [comment]
Apologies for late reply.

 Yes the problem is still there, I can still see it on Kadira, even I've removed beforePublish query now as well.

**Comment by matteodem** [comment]
can you give me a screenshot? also maybe an example doc for me to reproduce.

**Comment by joejeet** [comment]
This is the link to one of [kadira peak bar.](https://ui.kadira.io/pt/2387ceb5-cbc0-447f-8820-09aa37c2d8e2/F6u6MhuDzN27Fxqt8)

**Comment by branco91** [comment]
@joejeet  and @matteodem  I am also facing the same issues, CPU usage is very high and only with 8 documents in MongoDB.  Somehow, the pub/sub is extremely high on easySearch
![screen shot 2016-03-06 at 8 46 52 pm](https://cloud.githubusercontent.com/assets/11029783/13554201/a74ee978-e3dc-11e5-854f-ad7f928fc424.png)

**Comment by tenshis** [comment]
Is there a solution to this?

**Comment by matteodem** [comment]
Did you configure which fields are returned to the client on the engine level? http://matteodem.github.io/meteor-easy-search/docs/engines/

**Comment by tenshis** [comment]
Yes I have (it's tricky btw, I  think it belongs in the documentation). 

But the moment I change "index=oneIndex" (which works great) to "indexes=indexesArray" in my EasySearch.Input, the requests go crazy. It sends an endless loop of empty requests and responses take forever. 

As mentioned before, each one of the collections works fine individually, just not multiple at once.

**Comment by tenshis** [comment]
I think I found the source. I had the "ifInputEmpty" component in my template (pointing to either one or all collections leads to the weird behavior). As soon as I removed the component, multi collection search seems to behave as expected.

**Comment by matteodem** [comment]
very weird. do you have simple reproduction steps for this bug?

**Comment by matteodem** [comment]
Please provide a reproduction repository or simple reproduction steps so that this problem can be solved. I will re-open as soon as provided.
