### ISSUE TITLE
Search in Meteor.users collection

### ISSUE THREAD

**Issue by leolassence** [matteodem/meteor-easy-search#426]
I want to search in the Users collection

UsersIndex = new EasySearch.Index({
	collection: Meteor.users,
	fields: ['firstName'],
	engine: new EasySearch.Minimongo()
});

Thank you in advance :)

**Comment by matteodem** [comment]
Please have a closer look at the docs before creating issues http://matteodem.github.io/meteor-easy-search/docs/recipes/.

**Comment by leolassence** [comment]
yes but i don't understand it that's why i wanted to ask how to do it.

I just want t replace Collection bu Meteor.users

Thanks in advance and sorry


2016-01-25 10:30 GMT+01:00 Matteo De Micheli <notifications@github.com>:
