### ISSUE TITLE
How do I specify inputAttributes?

### ISSUE THREAD

**Issue by Henrijk** [matteodem/meteor-easy-search#427]
I have been trying to add a specific class to the input of {{EasySearch.Input index=myIndex}} and I do not quite understand how to. I've had a look on the docs and tried {{EasySearch.input index=myIndex {class: "[myclass]"} }} without success.

EDIT: I found it in the example project. They are specified in the Template.search.helpers {}.

**Comment by matteodem** [comment]
Docs wouldn't be bad for this, feel free to create a PR (docs are in the branch gh-pages)
