### ISSUE TITLE
Astronomy Classes and Easy Search

### ISSUE THREAD

**Issue by frankapimenta** [matteodem/meteor-easy-search#428]
I use astronomy package (https://github.com/jagi/meteor-astronomy).
How can I combine easy search and astronomy for easy search to provide me with a astronomy class and not a mongo db object?

**Comment by matteodem** [comment]
use example provided here https://github.com/jagi/meteor-astronomy/issues/531#issuecomment-259286530 to add docs

**Comment by matteodem** [comment]
docs added: http://matteodem.github.io/meteor-easy-search/docs/recipes/ (last section)
