### ISSUE TITLE
indexes on same collection

### ISSUE THREAD

**Issue by frankapimenta** [matteodem/meteor-easy-search#429]
I create two indexes where collection is the same ex: Players.
Second index is not recognised.

**Comment by matteodem** [comment]
Please show me your configuration code and reproduction steps / repository.

**Comment by frankapimenta** [comment]
It is in a private personal project.

TeamIndex = new EasySearch.Index({
  collection: Teams,
  fields: ['name'],
  engine: new EasySearch.MongoDB({
    sort: function () {
      return { score: -1 };
    }  }),
  defaultSearchOptions: {
    limit: 9
  }
});

GroupsIndex = new EasySearch.Index({
  collection: Teams,
  fields: ['players'],
  engine: new EasySearch.MongoDB({
    sort: function () {
      return { score: -1 };
    },
selector: function(searchObject, options, aggregation) {
      var selector = this.defaultConfiguration().selector(searchObject, options, aggregation);
      selector.manager = options.search.userId;
      return selector;
    }  
}),
  defaultSearchOptions: {
    limit: 9
  }
});

The second defined index is never defined.

Are you naming indexes in mongo db based on the collection name?
When I use another collection for the index it works.

**Comment by frankapimenta** [comment]
Do you try to replicate this? 
Are you naming indexes based on the collection name?

**Comment by matteodem** [comment]
yes, is there no error being thrown? You can define an optional `name` property if you have multiple indexes on the same collection.

**Comment by matteodem** [comment]
https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:core/lib/core/index.js#L24

**Comment by frankapimenta** [comment]
I'm really sorry I could not see it.
It works fine.
Thank you.
