### ISSUE TITLE
How do I filter based on nested properties?

### ISSUE THREAD

**Issue by Henrijk** [matteodem/meteor-easy-search#431]
I have looked on the Recipes,Component and Engine sections of the wiki and have been struggling to filter based upon nested properties.

    PsychologistsIndex = new EasySearch.Index({
	    engine: new EasySearch.MongoDB({
        selector: function (searchObject, options, aggregation) {
          let selector = this.defaultConfiguration().selector(searchObject, options, aggregation),
            languageFilter = options.search.props.profile_language;
    
          if (_.isString(languageFilter) && !_.isEmpty(languageFilter)) {
            selector.profile_language = languageFilter;
          }
    
          return selector;
        }
      }),
      collection: Meteor.users,
      fields: ['username', 'profile.firstName', 'profile.lastName', 'profile.municipality', 'profile.town'],
    });

In this case. I want to filter upon a certain language specified in profiles of Meteor.users. I have tried to change the syntax of selector.[what I want to filter] , but I do not get it to work. Please help :)

**Comment by matteodem** [comment]
At it's base it's a simple mongodb selector, so if you want to know if something works or not you can simply log what you're returning as your `selector` and try searching by that object in the Meteor shell. Please refer to the mongodb docs if you want to know the capability of selectors: https://docs.mongodb.org/manual/reference/operator/query/
