### ISSUE TITLE
Update lodash version

### ISSUE THREAD

**Issue by DimitryKislichenko** [matteodem/meteor-easy-search#432]
Hey,

I'm trying to install easy search, but unfortunately it depends on older version of lodash. Is there any chance (reason not to?) you could update it to a newer version?

```
While selecting package versions:
error: Potentially incompatible change required to top-level dependency: erasaur:meteor-lodash 3.10.1_1, was 4.0.0.
Constraints on package "erasaur:meteor-lodash":
* erasaur:meteor-lodash@3.10.0 <- easysearch:core 2.0.5
```

Thanks!

**Comment by matteodem** [comment]
The lodash dependency is updated in the latest version
