### ISSUE TITLE
Custom query data

### ISSUE THREAD

**Issue by seanmiddaugh** [matteodem/meteor-easy-search#433]
Thanks so much for creating such a useful package.

I have a search form that I'm using to filter Meteor.user data. I have most of it working expcept for one piece. I have two select menus where users can choose an age range to search from. Inside the user collection, users have a profile attribute of birthday. How can I get all users between two age ranges (eg 25 to 30) given that a profile has a birthday?

```
UsersIndex = new EasySearch.Index({
    collection: Meteor.users,
    fields: ['profile.birthday'],
    engine: new EasySearch.Minimongo({
        selector: function (searchObject, options, aggregation) {
            var selector = this.defaultConfiguration().selector(searchObject, options, aggregation);
            // ... other filters
            if (options.search.props.birthdayFilter) {
                // what should happen here?
                // selector['profile.birthday'] = ' something... '
            }   
            return selector;
        }
    })
});
```

**Comment by matteodem** [comment]
Use the [query comparison operators](https://docs.mongodb.org/manual/reference/operator/query-comparison/).

**Comment by Tzikas** [comment]
https://github.com/matteodem/meteor-easy-search/issues/152
