### ISSUE TITLE
Please, improve documentation

### ISSUE THREAD

**Issue by kemelzaidan** [matteodem/meteor-easy-search#435]
I want to know if I can pass multiple parameter to sort the index like that:
```js
engine: new EasySearch.Minimongo({
		sort: function(){
			return ['upVotes:-1', 'downVotes:-1', 'createOn:-1'];
		}
	})
```
Reversing the sort order with `-1`, doesn't seem to work.
The selector section on the documentation is hard to understand. What can it do?

As far as I can tell, the index is not a reactive collection, is it? Because I am increasing the upVotes values based on click events, and the sorting doesn't change.

**Comment by matteodem** [comment]
it re-uses the collection you provide and what you're returning are mongodb sort specifiers.

**Comment by liambluebox** [comment]
This doesn't seem to work: {a: 1, b: -1}

Might want to make that clear somewhere.

http://docs.meteor.com/#/full/sortspecifiers
