### ISSUE TITLE
Transform Null option

### ISSUE THREAD

**Issue by Pushplaybang** [matteodem/meteor-easy-search#437]
Hey Guys

We have a transform applied to the collection, which with search grinds our app to halt, and I don't seem to see a way to pass a transform option null on a particular index (we're using mongoDB as the engine).

is there a way to achieve this?  or could it be an option in the future?

Thanks.

**Comment by matteodem** [comment]
Can you show me your configuration? Also what does transform option null mean to you?

**Comment by Pushplaybang** [comment]
Hi There,

Sure so first off I have a transform applied to the collection : 

```js

Media = Mongo.collection('', {
    transform: function(doc) {
        //..
    }
});

```

within a publication you  are able to pass an option to your query that disables the transform for that query :  

```js
{
    transform: null
}
```

**Comment by matteodem** [comment]
You cannot do that right now, what can be gained by doing that?
