### ISSUE TITLE
Reset pagination to page one when query is re-run

### ISSUE THREAD

**Issue by dburles** [matteodem/meteor-easy-search#440]
If you're several pages deep into the pagination and change a prop that causes the results to be less than the current number of pages, you'll get no results! The workaround I'm currently using on the filter select boxes is:

``` js
  "change"() {
    QuestionsIndex.getComponentDict().set('currentPage', 1);
    QuestionsIndex.getComponentMethods().paginate(1);
  }
```

**Comment by matteodem** [comment]
Will have a look at this soon, might need some indication that shows that the search has re-run but not by changing the page or loading more results.

**Comment by matteodem** [comment]
to fix this do following has to be done:

* put dict logic for retrieving current page into component methods
* call `paginate` method in component methods when calling `addProp` or `removeProp`
