### ISSUE TITLE
Question about search 

### ISSUE THREAD

**Issue by Marcus-Crassus** [matteodem/meteor-easy-search#441]
Hi there!

How can I search some 'products' in particular range ? For example, there is db 'Products'. The search [_id, name] is available on the page, but I want to get only the results which have productType: id, where 'id' is available on the client (Router.current().params._type).

My aim is:
The user can search products with [_id, name] on the page, but get only result, where current productType: id is on the page (Router.current().params._type).

```javascript
DashboardSearchProducts = new EasySearch.Index({
    collection: Products,
    fields: ['name', '_id'],
    defaultSearchOptions: {
        limit: 5
    },
    engine: new EasySearch.MongoDB(),
    permission: (options) => {
        return options.userId;
    }
});
```

**Comment by matteodem** [comment]
You can use props together with a custom `selector` to achieve the result. Please have a look at the docs or other people that asked about filtering their collections.

**Comment by Tzikas** [comment]
https://github.com/matteodem/meteor-easy-search/issues/152
