### ISSUE TITLE
Pagination over multiple indexes

### ISSUE THREAD

**Issue by behrmann41** [matteodem/meteor-easy-search#443]
Is there a way to paginate over multiple collections? 

I have searching over both working, but when trying to pass in the indexes array to pagination it errors with "Did not receive an index or an array of indexes: "[object Object],[object Object]" [invalid-configuration]"

I can get two separate pagination tabs to show up for each index, but wondering if it is possible to combine.

Thanks for the help!

**Comment by matteodem** [comment]
I'd either think of changing the structure of your searchable data, as this is not something that I think should be part of easy:search as of now.
