### ISSUE TITLE
Not compatible with collection-helpers?

### ISSUE THREAD

**Issue by ivansglazunov** [matteodem/meteor-easy-search#444]
Package is not compatible with [collection-helpers](https://atmospherejs.com/dburles/collection-helpers) ? Search results as bare documents. Where to fix it?

**Comment by ivansglazunov** [comment]
But what if multiple collections? How in transform function detect collection?
```js
SubjectsIndex = new EasySearch.Index({
	collection: Meteor.users,
	fields: ['profile.name'],
	engine: new EasySearch.Minimongo({
	    transform: function(doc) {
	        return Meteor.users._transform(doc);
	    }
	})
});
```

**Comment by daveeel** [comment]
+1

**Comment by ivansglazunov** [comment]
Perhaps the solution to a template level, but it is not very nice.
```js
PostsIndex = new EasySearch.Index({
    collection: Posts, Comments,
    fields: ['body'],
    engine: new EasySearch.Minimongo({
        transform: function(doc) {
            return Posts._transform(doc);
        }
    })
});
```

**Comment by matteodem** [comment]
Yes, right now it's not compatible. I'll have that as my focus for the next version

**Comment by dladiguna** [comment]
+1

**Comment by matteodem** [comment]
You can use the helpers pacakge by doing [this](http://matteodem.github.io/meteor-easy-search/docs/recipes/).

**Comment by Tolsee** [comment]
@matteodem I am in a situation where the `transform` if runs only on the client, would not help me. Because I do not publish those things from where my helper is getting/returning data.

For example: Suppose I have two collections called `Contacts` and `Spendings`, I have registered a helper in `Contacts` named `lastSpending`, and I need to use the helper in the contact list, where I do not pub/sub `Spendings`.

**Comment by jamauro** [comment]
I'm following the `Usage with collection-helpers` example in the guide: http://matteodem.github.io/meteor-easy-search/docs/recipes/

Here's what the code in my `/lib/collections` folder looks like:

```
import { Index, MongoDBEngine } from 'meteor/easy:search'

Channels = new Mongo.Collection("channels");

Channels.helpers({
  convertedName() {
    if (this.name) {
      return this.name
    } else {
      var memberIdsWithoutCurrentUser = _.without(this.members, Meteor.userId());
      var userNamesNotIncludingCurrentUser = Meteor.users.find({_id: {$in: memberIdsWithoutCurrentUser}}).map(function(user) {
        return user.username
      });
      return userNamesNotIncludingCurrentUser.join(", ")
    }
  }
});

ChannelsIndex = new Index({
  collection: Channels,
  fields: ['convertedName'],
  engine: new MongoDBEngine({
    transform: (doc) => Channels._transform(doc)
  })
});
```

If I use something other than `convertedName` for the `fields`, all the documents are returned with `convertedName` available, but I obviously can't search by `convertedName` which is what I'm looking for.

What am I doing wrong? :)
