### ISSUE TITLE
Pagination and results for page

### ISSUE THREAD

**Issue by ChrisCinelli** [matteodem/meteor-easy-search#445]
On v2, how do you define the number of results that you want to get in each page?
I always get 10 results and I do not see a way to alter that number in `EasySearch.Input` or `EasySearch.Pagination`.

**Comment by matteodem** [comment]
You can set `defaultSearchOptions` on your index to define that: http://matteodem.github.io/meteor-easy-search/docs/api-reference/. I might add docs for that in the "Getting started" section

**Comment by ChrisCinelli** [comment]
`defaultSearchOptions : {limit: 40}` worked.
