### ISSUE TITLE
Reduce boielrplate code

### ISSUE THREAD

**Issue by ChrisCinelli** [matteodem/meteor-easy-search#446]
In v.2 I need to add EVERY time there is a search box TWO (one for the results, one for the search fielf): 
```
Template.MyItems.helpers({
  'myItems' : function(){
    return MyItemsIndex;
  }
});
```

v1 indexes had a string name and the string was the handle. 
While now I have to have the previous boilerplate do: 
`{{> EasySearch.Input index=myItems}}`

Before I would just do:
`{{> EasySearch.Input index='myItems'}}`

I am not sure why this changed. 
Can we have an optional `name` parameter that can be pass in `new EasySearch.Index({...})` so we can also use that `name` in `index=...` in the components?

**Comment by matteodem** [comment]
You can reduce that _boilerplate_  to be following:

```javascript
Template.MyItems.helpers({
  myItems : () =>  MyItemsIndex
});
```

This is done because v1 had a string based registry for all the indexes. It makes a lot more sense to just pass around the index itself and act upon that object, instead of looking up internal registries.

**Comment by ChrisCinelli** [comment]
I am not sure why it makes more sense to pass something around.
I have an app that has 20 different searches boxes. I have to add 40 functions like that. Most of the search boxes did not have helpers. 

I do not think it is a bad idea to have a registry indexed by `name` or a random UUID if it keeps things simpler for the programmer.

**Comment by matteodem** [comment]
You can easily create general helpers, services or helpers with any view technology. Blaze can register global helpers that might it make more easy for you to get the index instance easily. http://docs.meteor.com/#/full/template_registerhelper

**Comment by ChrisCinelli** [comment]
In practice I would have to implement a registry and make sure that every time I create a index, I put it in the registry
Are you open to a pull request that support the new and the old syntax?

**Comment by matteodem** [comment]
no I'm sorry, I do not want to revert to having that logic in Easy Search.
