### ISSUE TITLE
pagination does not work after autortracker addition;

### ISSUE THREAD

**Issue by marcinwal** [matteodem/meteor-easy-search#448]
I am using following script to trigger search where new value is added in my own search box:

Template.searchResults.onRendered(function(){
	Tracker.autorun(function() {
		var searchInput = Session.get('searchInput');
		console.log('running auto run with ' + searchInput);

		QuestionsIndex
			.getComponentMethods()
			.search(searchInput);

	});
});

search is working fine but my pagination and load more stopped working in template:

	<div class="col-md-1">
		{{#EasySearch.IfSearching index=questionsSearchIndex}}
			{{>spinner}}  		
		{{/EasySearch.IfSearching}}
	</div>
	<div class="col-md-2">		
		{{> EasySearch.LoadMore index=questionsSearchIndex count=3 content="Load next 3"}}
	</div>
 	<div class="col-md-4">
		{{> EasySearch.Pagination index=questionsSearchIndex maxPages=10}}
	</div>
It looks like autorun is triggered every time a single result is rendered and next page button just renders the same page; when loadmore button is pushed i am getting 
'Exception in template helper: Error: Current page is not in valid range [invalid-page]' error.

How should i use my own session's value to use for load more and pagination then?

**Comment by matteodem** [comment]
Is this still a problem in the latest version `2.0.9`?

**Comment by Tzikas** [comment]
I'm running version `2.0.9` and I'm getting the same error.

**Comment by Tzikas** [comment]
I seemed to temporarily fix it with this hack: 

		$('.pagination li').removeClass('disabled current')
		$('.pagination li:nth-child(2)')[0].className = 'page disabled current'

**Comment by Tzikas** [comment]
Nope nvm doesn't work very well.
