### ISSUE TITLE
How to sort ascending vs descending?

### ISSUE THREAD

**Issue by j20** [matteodem/meteor-easy-search#449]
Great package!

The docs show that it's possible to sort like this:

		// Client and Server
		let index = new EasySearch.Index({
		  ...
		  engine: new EasySearch.MongoDB({
		    sort: () => ['score']
		  })
		});

How would it be possible to specify ascending vs descending? (e.g. price low to high, price high to low, etc). In Mongo, we'd normally do: {price: 1} or {price: -1}

Is it possible to pass in the sort order so that the sort order can be updated dynamically? Like you how you passed in these properties:

		// index instanceof EasySearch.Index
		index.search('Peter', {
		  limit: 20
		  props: {
		    // custom data that can contains EJSON parseable data
		    minScore: 50,
		    maxScore: 100
		  }
		});

Thanks in advance!

(Using easysearch:core + React)

**Comment by matteodem** [comment]
What you specify is a function that returns a mongo sort modifier. You can use custom props and change the sort modifier based on your props or just always sort with a predefined modifier based on your function. See here http://matteodem.github.io/meteor-easy-search/docs/engines/

**Comment by j20** [comment]
Thanks!

It might be more clear to return an object in the docs, like a mongo's sort modifier. I just realized this actually works. Whereas the array made me wonder how to specify 1 vs -1. 

	engine: new EasySearch.MongoDB({
	  sort: function() {
	  	return {score: 1};
	  }
	})

**Comment by matteodem** [comment]
makes sense! I'll create a new story for that
