### ISSUE TITLE
any word in any field

### ISSUE THREAD

**Issue by frankapimenta** [matteodem/meteor-easy-search#452]
Imaging a player has a name and an age and there is a search string "ben 14"; 
the search should return players with name ben or that have 14 years old or both. 
How would I have to do it in easy search?  (matching part of search string per field)
do you have any interface for this implemented?
I could not get it in the documentation

**Comment by frankapimenta** [comment]
Should I used something like this to build the regex?
----
selectorPerField: function (field, searchString) {
    if ('emails' === field) {
      // return this selector if the email field is being searched
      return {
        name: {
          $elemMatch: {
            address: { '$regex' : '.*' + searchString + '.*', '$options' : 'i' }
          }
        }
      };
    }

    // use the default otherwise
    return this.defaultConfiguration().selectorPerField(field, searchString);
  }
----
});

**Comment by msj121** [comment]
Quick fix is to use fields:
fields: ['username','profile.firstName', 'profile.lastName','emails.0.address']

**Comment by matteodem** [comment]
Either use ElasticSearch that's more powerful than MongoDB's search features or analyze the search string and try to do some complex queries with them. The first solution is definitely the more mature approach.

**Comment by frankapimenta** [comment]
Hi thanks for the help. You have been amazing so far.

One thing came to my mind.
How could I enable the full search object to be like this?
--- > {$or: [{name: _regex}, {tags: _regex}]}

where _regex is:

 let _regex = new RegExp( _search, 'i' );

and _search is: 

"search string"

and name, tags are the fields of the collection.
