### ISSUE TITLE
this._id returning _id + weird object

### ISSUE THREAD

**Issue by sangyoo91** [matteodem/meteor-easy-search#454]
From  blaze `each` of search results, when I try to grab the id `using this._id` or  `this.data._id`, I get the following. 
```
_id: "bN7dDB5WMjSgQFMSy""{"userId":"59nNyNryNGuQWx4tf","limit":10,"skip":0,"props":{}}"
```
I'm unsure if this is correct or if its a bug in the core.

**Comment by matteodem** [comment]
It's correct, as we need to distinguish documents for different searches, if you want to access teh original documentId you can do that through  `__originalId `, see http://matteodem.github.io/meteor-easy-search/docs/recipes/
