### ISSUE TITLE
Sorting by geoloc distance

### ISSUE THREAD

**Issue by luniki** [matteodem/meteor-easy-search#456]
The documents of the collection used by my EasySearch.Index contains a geolocation field "loc": 

```
[
{ ..., loc: [57.5345, 2.3377 ] }
]
```

The EasySearch.Index must use the EasySearch.Minimongo engine. (Thus I cannot use MongoDB's geospatial "2dsphere" index.)

My template helper of the search page contains

```
Template.CoursesSearch.helpers({
    coursesIndex() {
        return CoursesIndex
    },
...
})
```

The template contains the EasySearch.Each component:

```
{{#EasySearch.Each index=coursesIndex}}
<tr class="searchRow">
    <td>{{title}}</td>
    ...
</tr>
{{/EasySearch.Each}}
```

I am using the mdg:geolocation package to get my current geolocation. Furthermore I implemented/copied an algorithm to compute the distance between two geolocations (my current position and the position of an entry in my collection).

Now I want to sort the table rows rendered by the template above using these distances.

I already saw the recipe to sort my index. But there is no example to sort by a computed field (using the Minimongo engine client-only!).

Could you please give me a hint how this could be solved?

**Comment by acomito** [comment]
- I solved this by creating a publication based soley on a $near query.

- The publication is reactive and the radius is based on a slider (in the search form)

- Then I use easy-search to search through the local collection that was published based on the $near query

This works well enough so far.
