### ISSUE TITLE
Allow limiting search based on complex queries

### ISSUE THREAD

**Issue by csillag** [matteodem/meteor-easy-search#457]
This might already be supported; if yes, then please tell me how.

Here is the use-case:
 - I want to limit the set of documents that the user can search, based on who the logged in user is.
 - Every user should be able to access his own documents, and the public documents of others.

In mongo terms, I want this query:

 ```
{ $or: [
            { public: {$eq: true} },
            { user: userName }
]}
```

I can implement filtering based on the user, following the recipe titled [Filtering with user data](http://matteodem.github.io/meteor-easy-search/docs/recipes/), but I don't see how can I add an '$or' to the condition. 

How can I do that?

Thank you for your help

**Comment by csillag** [comment]
Never mind. I ditched the library, and now I simply do the search on server side, using mongo's operator.

**Comment by matteodem** [comment]
I'm rather busy lately. Doing custom mongo queries aren't hard at all with EasySearch, just please have a closer look at the docs and it's recipes which might have given you a better clue.
