### ISSUE TITLE
.count() returns the incorrect count (compared to .fetch())

### ISSUE THREAD

**Issue by znewsham** [matteodem/meteor-easy-search#458]
I've an index that I need to filter based on a user selection, this is done manually by passing an options field to search(query, options) that is interpreted by the indexes engine.selector function.

When I provide no filter and search, I get 8 results (correct). When I add a filter, the search(query, filter).count() still is 8 (incorrect) however the search(query, filter).fetch() is empty (correct)

**Comment by matteodem** [comment]
The count represents "all" results found, what kind of filters are you providing in the search call?
