### ISSUE TITLE
Update Blocked due to Less Dependency at 2.0.0

### ISSUE THREAD

**Issue by rfines** [matteodem/meteor-easy-search#460]
I have been trying to update my meteor site using this package to 1.2 and have been unable to do so due to a locked Less constraint @1.0.11 || 2.0.0. Can you bump the Less version to the newest (2.5.1) to enable me to continue to use this package?

**Comment by matteodem** [comment]
I'll have a look at this soon, feel free to submit a PR if it's only changes in the package.js file.

**Comment by matteodem** [comment]
There is no css associated with EasySearch
