### ISSUE TITLE
Reactively changing sort

### ISSUE THREAD

**Issue by guylemon** [matteodem/meteor-easy-search#461]
Hi @matteodem thank you for all your work on this! -- This is a comment to help people trying to use a sort dropdown in their apps-- this was not explicitly spelled out in the docs.  Hopefully this will help anyone searching through the issues for this like I did.  If there is a better way to accomplish this than I did, I am glad to know!

The `sort` function on the engine config object gives us access to an `options` object. The `props` property on this object (`options.search.props`) can be modified by the client using `<index>.getComponentMethods().addProps( 'propName', value )`.

To change the sorting reactively, simply return a modified 'prop' from the options object, such as `{ date: -1 }`.  In this code, I define a prop called `sortBy`, and return its value from the sort function.  Whenever the value of `sortBy` changes, the sort order on the client will change with it ( provided that it is a valid field to sort by )

**from lib/listings.js**
```
ListingsIndex = new EasySearch.Index({
[...]
engine: new EasySearch.MongoDB({
    sort: function( searchObject, options ) {
      let sortBy = options.search.props.sortBy
      if( sortBy ) {
        return Object.keys( sortBy ).length ? sortBy : { date: -1 }
      } else {
        return { date: -1 }
      }
    }
  })
})
```

**from client/templates/search/result_list.js**
```
// .sort-option is an `<li>` element in a list
'click .sort-option': ( event, template ) => {
    const sortText = event.currentTarget.innerHTML
    //set up the parameter to pass to the sort function
    const sortParam = ( sortText === 'Most Recent' )
      ? { date: -1 }
      : ( sortText === 'Job Title')
      ? { jobTitle: 1 }
      : ( sortText === 'Organization')
      ? { organization: 1 }
      : ( sortText === 'Application Deadline')
      ? { applicationDeadline: -1 }
      : {}

    [...]

    // change the way that the listings are sorted
    ListingsIndex
      .getComponentMethods()
      .addProps( 'sortBy', sortParam )
  }
```

**Comment by matteodem** [comment]
looks good to me on a quick glance, definitely something worth putting into the docs! thanks

**Comment by mroftalp** [comment]
Thanks for this! :+1:

**Comment by matteodem** [comment]
Added an slightly changed example, thanks for the suggestion: http://matteodem.github.io/meteor-easy-search/docs/recipes/

**Comment by guylemon** [comment]
Great! Glad I could help.  Thanks again for your work on the package.
