### ISSUE TITLE
Migrating Old Code $not

### ISSUE THREAD

**Issue by msj121** [matteodem/meteor-easy-search#462]
I want to make sure I am not already a contact.

```
selector: function(searchObject, options, aggregation) {
            var selector = this.defaultConfiguration().selector(searchObject, options, aggregation);
            selector.profile = {contacts:{$elemMatch:{userId:{$ne:options.search.userId}}}};
            return selector;
        }
```

And of course the object looks like:

```
{
  _id: 456,
  username: 456,
  profile:{
     contacts:[
         {userId:123,name:'helloworld'}
     ]
  }
}

```

**Comment by matteodem** [comment]
What is the question?

**Comment by msj121** [comment]
I can't get $elemMatch to work (no errors). So that I can exclude users that already have the contact searching in their contacts list.

**Comment by matteodem** [comment]
Try to logging the selector before returning and see if you get any results if you call it in the shell (by using `meteor shell`) or somewhere on your server code.

**Comment by msj121** [comment]
Not sure if this is what you wanted, but logging the selector before it returns logs:

```
{ '$or': 
    [ { username: { '$regex': '.*.*', '$options': 'i' } },
      { 'profile.firstName': { '$regex': '.*.*', '$options': 'i' } },
      { 'profile.lastName': { '$regex': '.*.*', '$options': 'i' } },
      { 'emails.0.address': { '$regex': '.*.*', '$options': 'i' } } ],
   _id: { '$ne': 'HveCxZNykQywnAmEH' }, profile: { contacts: { '$elemMatch':{ userId: { '$ne': 'HveCxZNykQywnAmEH' } }} } }
```

**Comment by matteodem** [comment]
You can access the `Meteor.user` collection by using `meteor shell` on the server and using this selector on the server to find out if the mongodb selector works as expected.

**Comment by msj121** [comment]
Currently it returned a cursor with 0 count.

**Comment by matteodem** [comment]
So that means something with your query is wrong, try to figure out which part and adjust the `selector` method accordingly. The mongodb docs are of help here.
