### ISSUE TITLE
LoadMore option scrolling to top and re-rendering existing result

### ISSUE THREAD

**Issue by raisudeen** [matteodem/meteor-easy-search#463]
First of all, thanks alot for this awesome package. 

I tried using "LoadMore" option to load results on scroll.
But, whenever loading happens, it re-render results with existing results which scrolls to top.
Even some of the existing users reported this bug.
Can you please fix it at the earliest? or let me know if any work around with a code snippet. It would be a great help. Thanks in advance.
Some of them said that old version worked well. It would be better if you can share the exact old version.

-Raisudeen

**Comment by matteodem** [comment]
related to #374, gonna have a look soon

**Comment by matteodem** [comment]
Fixed as of latest version `2.0.9`
