### ISSUE TITLE
Unable to show "searching" while searching

### ISSUE THREAD

**Issue by ritchieng** [matteodem/meteor-easy-search#465]
Hi,

When I implemented this. It displays all my data first (with pagination).

When I'm searching, the "searching" function to show "searching..." does not show up. May I know why?

**Comment by matteodem** [comment]
Can you please try this again in the last version? Also add reproduction steps or a repository if this still shows up

**Comment by ritchieng** [comment]
@matteodem This does not work, I can't figure out the problem but it's related to this issue I just raised when I compared your documentation and your leaderboard example. 

#480
