### ISSUE TITLE
Minor issue console.log('once created');

### ISSUE THREAD

**Issue by mroftalp** [matteodem/meteor-easy-search#466]
This is just a minor issue but the latest version puts a console log "once created" on rendering the input search.

**Comment by matteodem** [comment]
I cannot find this code in any of the packages.

**Comment by mroftalp** [comment]
![screen shot 2016-03-21 at 5 53 20 pm](https://cloud.githubusercontent.com/assets/6789191/13915155/dc726ee2-ef8d-11e5-90e7-425688dc81c4.png)
Isn't this in your package?

**Comment by matteodem** [comment]
Very weird, which version are you using? https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/lib/input/input.js#L10

**Comment by mroftalp** [comment]
easy:search@2.0.5
easysearch:components@2.0.5
easysearch:core@2.0.8

**Comment by matteodem** [comment]
Please update to the latest version of all the packages (see https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/package.js#L4)
