### ISSUE TITLE
How do I merge search functions that use different inputs

### ISSUE THREAD

**Issue by mervynteo** [matteodem/meteor-easy-search#467]
Meteor-easy-search package uses a Blaze incorporated search input bar in the style below: 
` {{> EasySearch.Input index=myIndex}}`

Im also using Framework7, which also has a search tool that is in this format.
> http://framework7.io/docs/searchbar.html#.Vs7FOX19670 

So I tried to combine the 2 like this
```html
    <div class="page">
        <!-- Search Bar -->
        <form class="searchbar">
            <div class="searchbar-input">
                 <input type="search" placeholder="Search"> <!-- the input -->
                 {{> EasySearch.Input index=myIndex}} <!-- putting here doesnt work --> 
                 {{> EasySearch.Input index=myIndex type ="search"}} <!-- trying my luck, doesnt work--> 
                <a href="#" class="searchbar-clear"></a>
            </div>
            <a href="#" class="searchbar-cancel">Cancel</a>
        </form>
        
            <div class="searchbar-overlay"></div>

            <div class="page-content">
                <div class="content-block searchbar-not-found"> Nothing found </div>
                <div class="list-block list-block-search searchbar-found">
                <!-- this part clashes with easy-search's code here 
                          {{#EasySearch.IfNoResults index=myIndex}}
                              <div>No results found!</div>
                           {{/EasySearch.IfNoResults}}
                      --> 
                    <ul> <!-- search results --> </ul>
                </div>
            </div>
        </div>

```
I tried to insert the Blaze formatted easy-search bar and it [1] screws the formatting of Framework7 bar and [2] the easy-search does not work. Im trying to search by the header of the to-do item, as well as its contents. Also search results formatting clashes too.

How should I go about the implementation? Do I use both or pick one? Im looking through search through 2 collections, the posts and the messages parked under each post.

**Comment by matteodem** [comment]
How did you try to put in the search components? Please give me the same html code with the components in there.

**Comment by mervynteo** [comment]
Hi @matteodem, thanks for the reply. I included the codes above with marked with comments.

**Comment by matteodem** [comment]
I do not see where you are using `EasySearch.Each` to loop through the search results.

**Comment by mervynteo** [comment]
I left it out earlier as I did not make much changes to that part of the codes. Mixing both gave me errors so I just stuck to easy-search layout for the Each loop.

**Comment by matteodem** [comment]
Can you show me the errors

**Comment by mervynteo** [comment]
Sorry for not elaborating. Theres no errors except that is I put the handlebars search `{{> }}` input FW7's searcbar, the html gets distorted and theres no output. 

However if I use easy-search input style, everything works ok, except it throws out repeated post results. 
For example, if I have post A, there will be repeated post A for each messages under that post. However the repeated post shows NaN for numerical fields like scores. When I click on them, it throws a 404 error. This is probably a separate problem because it throws a result for each posts + a result for each comment under that post. 

Because easy-search uses a handlebar for the input search, I have difficulties trying to fit it into FW7's <input> tag input field.

**Comment by matteodem** [comment]
You can define `attributes` on your input if you need special classes, I don't really understand what the problem here is.

**Comment by mervynteo** [comment]
Hi Matt, the main issue is with merging the 2 search together. Is it possible to provide some example lines to show how to fit the easy-search handlebar `{{> input}}` into the FW7's `<input type='search' ....>` bar formatting? I hope to retain the clear search and no results notice. 

I read up on attributes but does not seem applicable. It allows for placeholder and specifying fields to search in.

**Comment by matteodem** [comment]
You can override the type by simply having attributes have a key of type and a value of `search`:

```js
Template.myTemplate.helpers({
  attributes: () => {
    return { type: 'search', ... };
  }
});
```

See source code here https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/lib/input/input.js#L55

**Comment by mervynteo** [comment]
I dont quite get the details. With the template helper above, will the below be a correct understanding? Im essentially using easy-search but with FW7 clear and cancel buttons, as well as FW7 search bar UI formatting.
``` html 
        <form class="searchbar">
            <div class="searchbar-input">
                 <!-- <input type="search" placeholder="Search">  FW7 input format, removed -->
                   {{> EasySearch.Input index=myIndex attributes=attributes}}
                <a href="#" class="searchbar-clear"></a>
            </div>
            <a href="#" class="searchbar-cancel">Cancel</a>
        </form>
```
``` javascript
Template.myTemplate.helpers({
  attributes: function () {
    return { 
       type: 'search',
       placeholder: 'search here'
    };
  }
});
```
Since `{{> EasySearch.Input index=myIndex}}` renders a <input> tag as well.

**Comment by matteodem** [comment]
the value of class should also be a string. Blaze can convert an object of string values to actual html attributes. Also the logic for clear and cancel can be implemented through component methods, please look them up in the docs.

**Comment by mervynteo** [comment]
Do you mean that for attributes, I can only define the type, placeholder and class (which is also just a name?). As for cancelling and clearing the search bar, I would have to create my own hel
pers?

**Comment by matteodem** [comment]
You would need to use the component methods, which are in the docs.

**Comment by mervynteo** [comment]
Ok Ill try to figure it out with the logging the `getComponentMethods` stuff.
