### ISSUE TITLE
Autosuggest Multiple Like in Selectize

### ISSUE THREAD

**Issue by mroftalp** [matteodem/meteor-easy-search#469]
How to make the Autosuggest maxItems:null like in selectize? Was hoping you could improve the documentation for it. I added the changeConfiguration field and put { maxItems:null } but it didn't work.

**Comment by matteodem** [comment]
As you can see here it doesn't display all items by default, https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:autosuggest/lib/autosuggest.js#L48. What exactly is your question? How to change the size of results being displayed when searching? 

Have a closer look here please http://matteodem.github.io/meteor-easy-search/docs/api-reference/
