### ISSUE TITLE
Load More Button Attribute Bug

### ISSUE THREAD

**Issue by ritchieng** [matteodem/meteor-easy-search#472]
Hi,

I followed the documentation but I'm unable to modify the load more button attribute. 

Here's the code: 

{{> EasySearch.Loadmore index=companiesIndex content="Load more" attributes={class:"btn btn-primary btn-md"} }}

There's a syntax error for attributes reported in the error log.

**Comment by matteodem** [comment]
Please have a look at meteor docs on how to pass JS objects in Blaze.

**Comment by ritchieng** [comment]
Hi @matteodem 

I tried searching but I'm unable to come up with a solution. I tried this:

`{{> EasySearch.Loadmore index=companiesIndex content="Load more" attributes=class}}
`

And 

```
Template.templateName.helpers({
    class: "btn btn-primary btn-md"
});
```

But it does not work.

**Comment by matteodem** [comment]
Try:

```
{{> EasySearch.Loadmore index=companiesIndex content="Load more" attributes=class}} 
```

```js
Template.templateName.helpers({
    attributes: function () {
      return { class: 'test' };
    } 
});
```

This should be pretty clear from the docs, or isn't it?

**Comment by ritchieng** [comment]
@matteodem Thanks for your help. I'm not adept in Meteor yet, but you're really good. Sorry for taking your time, you're really helpful though. 

The newbies out there would love this snippet of code in your docs though. Thanks again!

**Comment by matteodem** [comment]
No problem, will add a new issue regarding this code snippet

**Comment by ritchieng** [comment]
@matteodem I think the code needs some tweaking. It still does not work, it's the same button without any class loaded. Seems like I'm having an "unused property attributes" warning in my code editor (Webstorm). Any idea?

**Comment by matteodem** [comment]
Please provide a reproduction repository or have a look at others that provided examples in other issues.

**Comment by ritchieng** [comment]
@matteodem I've a repo at bitbucket, do you've an email/user where I can send to you to view?
