### ISSUE TITLE
Associated relation

### ISSUE THREAD

**Issue by frankapimenta** [matteodem/meteor-easy-search#473]
I have a collection players which I can search on by name when I list them.
I have a collection team. A team has many players. Team collection has field playersIds (array).
I would like to look for a player by name within a team (when I list the team players).

How could I configure my TeamIndex to search for players by name on collection Players only for ids in Team collection playersIds array?

**Comment by matteodem** [comment]
You could either:

* Denormalize your data and make the docs have contain all the searchable data (ElasticSearch encourages this)
* Use publish-composite package to setup the relations and the core `search` method inside a custom publication.
