### ISSUE TITLE
Exception in template helper: Error: Match error: Failed Match.OneOf or Match.Optional validation

### ISSUE THREAD

**Issue by SalahAdDin** [matteodem/meteor-easy-search#475]
Hi man, how are you?

I'm doing a website share and i'm using this package for solve twoo challenges:
a simple keywords search and a recommend system; but, i have an error: http://stackoverflow.com/questions/36278414/recommendation-system-using-meteor-easysearch

Can you help me?

**Comment by matteodem** [comment]
A lot of times there are others who already had a similar problem / use-case, have a look at the open and **closed** issues. There's also quite a lot of documentation, for example [recipes](http://matteodem.github.io/meteor-easy-search/docs/recipes/) which explain practical code.

Take a closer look at both of those resources and if that doesn't help then: 

* Create a reproduction repository *or*
* Show reproduction steps *or*
* If it's a question: explain what is unclear in 2 to 5 sentences

**Comment by SalahAdDin** [comment]
Ok friend, i put here the repository:
https://github.com/SalahAdDin/siteace

**Comment by matteodem** [comment]
Please provide me with the stacktrace of the error (will re-open if done)
