### ISSUE TITLE
ElasticSearch: not the same sort on the server and on the client

### ISSUE THREAD

**Issue by talalav** [matteodem/meteor-easy-search#478]
I have the same problem. My elasticsearch query is:
{
"query": { "match": { "title": "xxxx yyyy } },
"sort": { "_score": { "order": "desc" } }
}
The sort is not the same.
I'm using the 2.0.9 version of your package.

**Comment by matteodem** [comment]
How did you configure your EasySearch instance?

**Comment by talalav** [comment]
@TopicIndex = new EasySearch.Index(
  fields : ['title']
  collection : Topics
  limit: 20
  reactive: false
  engine: new EasySearch.ElasticSearch 
    query: (searchObject) -> {match: { title: { query: searchObject.title } }}  
    sort: (searchObject) -> { _score: { order: "desc" } }
  )

**Comment by talalav** [comment]
I can't insert indentation to my code example.

**Comment by talalav** [comment]
Hello Matteo! I wrote my settings. How do you find them? The issue is still labelled as waiting for something :)

**Comment by matteodem** [comment]
I don't really have the time now to investigate in that issue, feel free to have a closer look at the source code yourself in the mean time.

**Comment by micant** [comment]
I'm having the same issue, I'll post a solution if I find one.

**Comment by micant** [comment]
This looks like it might be the problem - https://jira.mongodb.org/browse/SERVER-14083

We got around it buy passing in a meteor sort specifier in collection.find().

**Comment by micant** [comment]
@talalav feel free to PM me if you'd like to see our workaround

**Comment by matteodem** [comment]
Yeah that's the problem. That's rather bad

**Comment by moonrockfamily** [comment]
I worked around this issue by hacking the engine.js on line 179.  https://github.com/EduShareOntario/jobCollectionService/blob/306d73e2a4a2199e2bdbb812de7c726611ff61df/packages/easysearch_elasticsearch/lib/engine.js 

from:
```javascript
        }, { limit: options.search.limit });
```
to:
```javascript
        }, { limit: options.search.limit, sort: options.search.sort || {} });
```

**Comment by matteodem** [comment]
Is this a valid fix to this bug? Feel free to create a PR if so

**Comment by talalav** [comment]
This doesn't work for me.

**Comment by moonrockfamily** [comment]
That's too bad you didn't have success with [my hack](https://github.com/EduShareOntario/jobCollectionService/commit/306d73e2a4a2199e2bdbb812de7c726611ff61df).  

Is it possible options.search.sort is undefined?

**Comment by talalav** [comment]
@TopicIndex = new EasySearch.Index(
  fields : ['title']
  collection : Topics
  limit: 20
  engine: new EasySearch.ElasticSearch 
    query: (searchObject) -> {match: { title: { query: searchObject.title, fuzziness: 2 } }}  
    sort: (searchObject) -> { _score: { order: "desc" } }
  )

**Comment by moonrockfamily** [comment]
I had another look at the hack, and it seems to be flawed as you have experienced.  On line 153 ` body.sort = this.callConfigMethod('sort', searchDefinition, options);` the result of the call to the `sort` config method is stored in `body.sort`, but then not used on line 179 when performing the Mongo collection `find`. 
```javascript
cursor = options.index.collection.find({
  $or: _.map(ids, (_id) => {
    return { _id };
  })
}, { limit: options.search.limit, sort: options.search.sort || {} });
```
 Try changing line 179 to use `body.sort` instead of `options.search.sort`:
```javascript
cursor = options.index.collection.find({
  $or: _.map(ids, (_id) => {
    return { _id };
  })
}, { limit: options.search.limit, sort: body.sort || {} });
```

**Comment by talalav** [comment]
Indicates an error in the server console: 
Error: Exception while polling query {"collectionName":"topics","selector":{"$or":[{"_id":"jZWN56vgzLhT7dZuC"},{"_id":"5Mj8DrG7kXbFNFmD4"},{"_id":"9PoE8FYKwb3BAcvoY"},{"_id":"sG6bdqX38dFv5eJTj"},{"_id":"Hmbm8LfoHuvRd73ZF"},{"_id":"A3vrFireMREqEp3aa"}]},"options":{"transform":null,"limit":10,"sort":{"_score":{"order":"desc"}}}}: bad sort specification

**Comment by moonrockfamily** [comment]
It's coming back to me now, I was down this path before... 
_score is an ElasticSearch provided value, not a property of the collection documents.  Preserving the order will require more work as I described in my [commit message](https://github.com/EduShareOntario/jobCollectionService/commit/306d73e2a4a2199e2bdbb812de7c726611ff61df).


`- todo: replace hack augmentation using the cursor 'observe' to alter the docs to have a __sortPosition attribute equal to the position the document id is within the original elasticsearch hits.hits result.`

**Comment by steven-tib** [comment]
Hi, any progress on this issue? I think I'm facing the same problem. The results are displayed randomly on the client however when testing the query/sort directly on the elastic server its correctly sorted. @moonrockfamily @talalav have you manage to sort your data properly since last November? thanks for your help

**Comment by moonrockfamily** [comment]
I didn't have a need to strictly respect the elastic search order and hence post sorting by another document attribute was sufficient. The small change I made to the engine just enabled the passing through of a sort config restricted to document attributes.  

Extending the observe callbacks to add the sort position is the solution I think would allow sorting the collection consistently with the elastic search results.

**Comment by talalav** [comment]
Hi! I switched to MongoDB text search.

23 янв 2017 г. 6:59 PM пользователь "Steven Maurin" <
notifications@github.com> написал:

**Comment by steven-tib** [comment]
Ok thanks for your replies, I'm switching also to mongodb text search for now and see when I'll reach the limits of this solution, then I might go back to Elasticsearch.

**Comment by matteodem** [comment]
I don't have a lot of time to provide a great elasticsearch solution right now, please feel free to create a PR if you want to help out. I can guide you if there's any problems.

**Comment by steven-tib** [comment]
Thank you @matteodem, on my side I will just go with mongo text search as it seems to work for what I need for my MVP, I might come back later to elasticsearch so whenever you have more time just let us know, I can help to run some tests when you update it. thanks again for this package.

**Comment by matteodem** [comment]
@steven-tib please check out if this bug is fixed with the latest elasticsearch release. I'll re-open if that's the case

**Comment by steven-tib** [comment]
@matteodem thanks for the update. I'm not yet back to elasticsearch and still using mongo text search. probably in the next month I will come back to ES. I will then let you know if this bug is still occurring.
