### ISSUE TITLE
Minimongo isSearching won't work

### ISSUE THREAD

**Issue by ritchieng** [matteodem/meteor-easy-search#480]
In the documentation you used

```
ProfilesIndex = new EasySearch.Index({
    collection: Profiles,
    fields: ['title'],
    engine: new EasySearch.Minimongo()
});
```

In the leaderboard example you used

```
ProfilesIndex = new EasySearch.Index({
    collection: Profiles,
    fields: ['title'],
    engine: new EasySearch.MongoDB()
});
```

If we were to follow the former, ifSearching would not work. The later would work if you use MongoDB. Any idea why?

**Comment by matteodem** [comment]
I just had a look again in the core library and I think this is simply because all the data is already available on the client and it loads it directly. I'll keep this open and have a closer look soon
