### ISSUE TITLE
Search over multiple collections with selector on it

### ISSUE THREAD

**Issue by raisudeen** [matteodem/meteor-easy-search#481]
Hi, I have below collections with relations to it.

School:
      |_____ SchoolID
      |_____ Name
      |_____ Status

Game:
      |_____ SchoolID
      |_____ GameID
      |_____ Name
      |_____ Status

Participants:
      |_____ SchoolID
      |_____ GameID
      |_____ StudentID
      |_____ Name
      |_____ Status

I want to show "Participants" only if "Status" of "School" and "Game" is "active".
Is it possible to filter results or create selector to achieve above criteria?
If it is not possible, kindly let me know the alternative ways to achieve it with some code example. Thanks in advance.

**Comment by matteodem** [comment]
Please check out the docs and leaderboard example, there's most certainly a solution. For example a de-normalized data structure, with Elastic Search or MongoDB, that contains all the necessary searchable / filterable data in the same collection.
