### ISSUE TITLE
Autosuggest Error: TypeError: _.get is not a function

### ISSUE THREAD

**Issue by uberism** [matteodem/meteor-easy-search#482]
It seems like the lodash or underscore get is giving me errors when trying to use autosuggest. 
Any ideas why I am getting TypeError: _.get is not a function?

**Comment by matteodem** [comment]
How did you produce that error?

**Comment by uberism** [comment]
By using {{> EasySearch.Autosuggest index=myIndex}}

Tried this in my own project and also in the leaderboard example. In the leaderboard example I replaced  EasySearch.Input with EasySearch.Autosuggest.

**Comment by joeblurton** [comment]
I also have this problem using {{> EasySearch.Autosuggest index=myIndex }}

**Comment by talalav** [comment]
Add globally _ = lodash;

**Comment by steven-tib** [comment]
Hi, I'm having the same error, and cannot manage to add `_ = lodash; ` to solve it

@joeblurton and @uberism did that solve your issue ? 
(I'm new to meteor and JS, maybe i'm just not including this code at the right place...)

Thanks a lot for your help

**Comment by joeblurton** [comment]
Interesting. I had no idea what lodash was until now. I'm just quick prototyping so I've culled the feature for now and moved on, but will return to it and update when I can.

**Comment by steven-tib** [comment]
I actually found out, was a stupid beginner error, I've added lodash (stevezhu:lodash) package and added `_ = lodash;` to my client and server and it worked. 
Also, note that if you use lodash and underscore at the same time you might have namespace conflicts. There are a bunch of discussions about this topic on meteor forums apparently.

**Comment by matteodem** [comment]
Published version `2.0.10` with a changed dependency to lodash, which is not weak anymore.
