### ISSUE TITLE
Client Side Collection Search

### ISSUE THREAD

**Issue by mroftalp** [matteodem/meteor-easy-search#483]
```
SampleCollection = new Mongo.Collection(null);

SampleCollectionIndex = new EasySearch.Index({
    collection: SampleCollection,
    fields: ['title'],
    engine: new EasySearch.Minimongo()
});
```

Sorry, I know the package can do search with client side collections #25. Just wondering why everytime I search it always has no search results? Or did I do it wrong? How to do it properly? There's no example in the docs using a client collection.

**Comment by matteodem** [comment]
Do you populate your `SampleCollection` on the client? Can you provide me with a small reproduction repository?

**Comment by mroftalp** [comment]
@matteodem just found out the problem I guess its a bad practice calling SampleCollection = new Mongo.Collection(null); everytime I visit that page again. So if clearing collection just use SampleCollection.remove({});
