### ISSUE TITLE
Getting single search box to search multiple fields

### ISSUE THREAD

**Issue by jasonnmark** [matteodem/meteor-easy-search#490]
I'm using easy search on the following schema

```
Contacts = new Mongo.Collection('contacts'),
  ContactsIndex = new EasySearch.Index({
    collection: Contacts,
    fields: ['firstName','lastName'],
    engine: new EasySearch.Minimongo()
  });
```

```
	firstName: {
	    optional: true,
	    type: String      
	},
	
	lastName: {
	    optional: true,
	    type: String
	},
```

I want to find the contact named Jason Mark. If I search on "Jason" it finds it, if I search on "Mark" it finds it, but if I search on both it doesn't. I tried making a new combined field to search on but if it doesn't stay up to date. If I update the first name then the last name becomes "undefined" and vice versa.
```
	seachOnMe: {
		type: String,
		optional: true,
	    autoValue: function() {
                return this.field("firstName").value + ' ' + this.field("lastName").value;
        }
},
```
I feel like I'm probably missing something simple... please advise.

**Comment by matteodem** [comment]
There's multiple ways how to handle this: 

* Use Elastic-Search and it's search features 
* Use a composite field that holds the full name and use that in the `fields` configuration
* Change the mongo selector by adding a [selector](http://matteodem.github.io/meteor-easy-search/docs/engines/) configuration

I'll add a task to add a recipe on what to do with composite fields, hopefully that'll be also of help.
