### ISSUE TITLE
Searching dot or "." displays all document in collection?

### ISSUE THREAD

**Issue by mroftalp** [matteodem/meteor-easy-search#491]
Searching dot or "." displays all document in collection?

**Comment by matteodem** [comment]
What is the expected behavior?

**Comment by mroftalp** [comment]
Result should return only with the strings that have the character "." within but it displays all documents. Also these are some other characters: `$ \ + ^ ? | .` Are they like illegal searches?

**Comment by matteodem** [comment]
Right now it's creating a mongodb selector out of the search string, maybe it might make sense to escape `.` and other special characters.
