### ISSUE TITLE
Using Components to Search for fields with boolean using addProps

### ISSUE THREAD

**Issue by sangyoo91** [matteodem/meteor-easy-search#492]
Is it possible to filter the results with Boolean?

for example,

```
OrdersSearchIndex.getComponentMethods().addProps('isCanceled', true)
```

I tried this but the search won't return documents with `isCanceled : true`

**Comment by matteodem** [comment]
Please have a look at the **Adding facets to you search app** section to find out how to use props, http://matteodem.github.io/meteor-easy-search/docs/recipes/.
