### ISSUE TITLE
Template code re-use: _id and _originalId

### ISSUE THREAD

**Issue by bflorea** [matteodem/meteor-easy-search#494]
In one of my projects I used the old version of EasySearch and I could use the search results as drop-in replacements for the collection documents, using the same templates to display the results. Now, that the new version uses _originalId, the templates that used to work both with search results and collection documents do not work anymore because of this change.

What is the recommended recipe for re-using the same templates to work both on collection documents and on search results?

**Comment by matteodem** [comment]
Probably using a template helper called `getId` that just checks if `_originalId` is around and uses that instead of `_id`.
