### ISSUE TITLE
Make this package frontend independent

### ISSUE THREAD

**Issue by matteodem** [matteodem/meteor-easy-search#495]
Next major version will focus on making this package easy to use with any frontend library that's wished by either using GraphQL / Apollo or the Meteor Pub / Sub system.

**Comment by ivansglazunov** [comment]
[Blaze in React](http://guide.meteor.com/react.html#blaze-in-react) is not working? I have not tried it, but when I try to report back. Does it make sense to do something if it works?

**Comment by matteodem** [comment]
Yeah sure, I just think it'd be cool to have a package like `easy-search:components-react` that provides some simple wrapped components.

**Comment by ivansglazunov** [comment]
Yes, cool. The package already in the works? Maybe I could do it in the next month.

**Comment by matteodem** [comment]
No it isn't, feel free to do so. I'll prioritize the open bugs either way

**Comment by acomito** [comment]
any update on this?

**Comment by matteodem** [comment]
No not really, for now you can use one of the packages that makes it easy to use blaze in react (https://atmospherejs.com/thereactivestack/blazetoreact)

**Comment by acomito** [comment]
That one doesn't seem to work anymore unfortunately. Is there a best alternative blaze-in-react package?

**Comment by babenzele** [comment]
While you wait for someone to get back to you about your github issue, you could try what mdg recommends in the guide:

https://guide.meteor.com/react.html#blaze-in-react

**Comment by acomito** [comment]
@babenzele I just realized I had `static-html` installed and handling my .html files instead of the blaze templating package.

**Comment by acomito** [comment]
hmm.. I also just realized that if I need to interact with the search results then things get kind of messy. For instance, if a user can click a search result to go to, say, an individual profile, then I need to use react-in-blaze to use react-router's `<Link>` OR somehow connect to react-router inside of blaze, or use blaze modals or something.

I wanted to avoid learning a new library but since I'm using redux already, I may go with this: https://treasure-data.github.io/redux-search/

**Comment by babenzele** [comment]
I've been using Griddle for some searches. It renders to a table but you can replace columns and cells with custom components. I'm using griddle-react-bootstrap with it as well for some styling. 

https://griddlegriddle.github.io/Griddle/
http://wadahiro.github.io/griddle-react-bootstrap/

**Comment by AlmogRnD** [comment]
It would be nice to support react is there any plans for this?

**Comment by matteodem** [comment]
I think in the long term the focus on this package will have to align with the apollo integration that's (hopefully) coming soon to meteor.  Easy Search might then go through some major refactoring to adjust to the graphql subscriptions / query logic. 

This would make react integration a breeze, as the apollo integration packages could be used to achieve that.

As of now I'm not sure if it's worth the effort though, as it's still a open source package which takes up a lot of private time.

**Comment by AlmogRnD** [comment]
Yea that makes sense, not sure about Apollo integration with Meteor was this already announced

**Comment by matteodem** [comment]
not yet, but MDG mentioned multiple times that graphql will come to Meteor as the new data stack in a future version.

**Comment by matteodem** [comment]
I will integrate Easy Search into a personal project of mine, which uses GraphQL on the backend. Maybe this will result into a new package and / or documentation on how to use the package with GraphQL easily to make it frontend agnostic.

**Comment by matteodem** [comment]
A quick update: I used Easy-Search in the project I mentioned previously (https://github.com/matteodem/meteor-easy-search/issues/495#issuecomment-343862935) and it pretty much works out of the box:

https://github.com/matteodem/sounds-social/blob/b0ad1471849850a6a970fb2fde8011ee40a7aa9a/code/api/imports/api/schema/SoundGraphqlSchema.js#L175

Open for suggestions on how to advance on this, but as of now I'm unclear on what could help this library be "easier" to integrate
