### ISSUE TITLE
Meteor date range filter not reactive

### ISSUE THREAD

**Issue by ramzauchenna** [matteodem/meteor-easy-search#496]
I have a simple publication line this 

```
Core.publish("DashOrderVolumes", function(startDate, endDate){
  console.log(arguments)
  let fields = {
    'issuedAt': 1
  };
  return Orders.find({issuedAt: {$gte: startDate, $lte: endDate}}, {
    fields: fields
  });
});
```
if i have just one condition it works i.e {issuedAt: {$gte: startDate}} alone and the data comes to the client but when i add the second range nothin happens unless i make a template change event.  I am wondering if this is a usual behaviour

**Comment by matteodem** [comment]
I don't see anything that's related to EasySearch in this issue.

**Comment by ramzauchenna** [comment]
Dont know what you mean by easy search but what i am trying to say is that the data is not reactive. meaning the dom is not updated

**Comment by ramzauchenna** [comment]
sorry. was on the wrong page
