### ISSUE TITLE
Integrating both autosuggest and search, and making a little complex search query

### ISSUE THREAD

**Issue by paduchurikowsik** [matteodem/meteor-easy-search#499]
Hello guys,
(i am new to meteor). 
the idea:
a simple search form with two input fields,
one take either **school name or major** and other take either **state or city**.
and search the collection based on the two inputs given by use.

the input field also shows an **autosuggestions** dropdown

i was able to implement this using **typeahead** for meteor for autosuggestions and was simply running a query on collection ( **.find($or: [{state: ....},{city: ...}])** ); 

i want to implement the same thing using easy search, but was not able to do that. 
how to i get auto suggest for both the text fields and then send that values to make the seach.

i tried using the getComponentDict() to get the search values so as to pass them to .search(), but was getting undefined. ( i may have an wrong idea)

i also went through the documentation, but was not able to understand the solution for this.

Could you please guide me with steps.
Thanks You.

**Comment by matteodem** [comment]
Please make decisions regarding you how structure your data. The [recipes](https://matteodem.github.io/meteor-easy-search/docs/recipes/) might help here.
