### ISSUE TITLE
2.0.9 Component issue

### ISSUE THREAD

**Issue by lucased** [matteodem/meteor-easy-search#501]
Hi 

Ive upgraded to Easy:Search to 2.0.9 but seem to have an issue with some of the components. In 2.0.7 i was able to use {{else}} statements in my templates like below. But now I get 'No results found'. From logging the index.getComponentDict() i can see that stopSubscription is set to true. If i remove the ifSearching and IfNoResults components everything works again.

Is there way around this?

```
{{> EasySearch.Input index=index attributes=inputAttributes}}

{{#EasySearch.IfSearching index=index}}
    <p>loading...</p>
  {{else}}
    {{#EasySearch.IfNoResults index=index}}
      <div class="no-results"><h4>No results found!</h4></div>
    {{else}}
      {{#EasySearch.Each index=index}}
        <div class="result">{{name}}</div>
      {{/EasySearch.Each}}
    {{/EasySearch.IfNoResults}}
{{/EasySearch.IfSearching}}
```

**Comment by matteodem** [comment]
Try not nesting the components, how does it look then?
