### ISSUE TITLE
Search inputs divided by spaces

### ISSUE THREAD

**Issue by jannikkeye** [matteodem/meteor-easy-search#502]
This is an amazing package. I have only one problem:

Is it possible for the search to detect spaces in the searchfield so I can search the specified fields with an array of values?

Or will I have to do that by hand?

Thank you in advance!

**Comment by matteodem** [comment]
Please have a look at the recipes http://matteodem.github.io/meteor-easy-search/docs/recipes/. You can achieve that functionality by using the `selectorPerField` configuration or using something like ElasticSearch for a more mature approach.
