### ISSUE TITLE
Make pollingInterval configurable

### ISSUE THREAD

**Issue by matteodem** [matteodem/meteor-easy-search#503]
see http://info.meteor.com/blog/tuning-meteor-mongo-livedata-for-scalability

should replace the earlier `reactive: false` configuration in `v1`, see #65

* make the count polling interval configurable, see #556
* add docs regarding performance configuration (count interval ms config + pollingInterval config)

**Comment by frankapimenta** [comment]
Any news regarding this? :)

**Comment by matteodem** [comment]
No, I'm rather busy with work right now. Feel free to submit a PR if you have time.

**Comment by matteodem** [comment]
This is now configurable on engine level http://matteodem.github.io/meteor-easy-search/docs/engines/
