### ISSUE TITLE
How To use Easy Search with Collection fs

### ISSUE THREAD

**Issue by yogesh2591** [matteodem/meteor-easy-search#504]
How to use Easy Search with Collectionfs package .

**Search.html**
`{{> EasySearch.Input index=searchindex}}
   {{#EasySearch.Each index=searchindex }}
Filename : {{metadata.name}}
{{/EasySearch.Each}}
`

**Search.js**
`Template.searchBox.helpers({
    searchindex: () => FilesIndex
});

Template.searchBox.onCreated(function(){
    var self = this;
    this.autorun(function(){
        self.subscribe('files')
    });
});`

**Collection.js**
`
Files = new FS.Collection("files", 
    {
    stores: [ new FS.Store.GridFS("files") ],

```
 filter: {
    maxSize: 64 * 1024 * 1024,

  onInvalid: function(message) {
    Meteor.isClient && alert(message);
    console.log(message);
}
```

  }

});

FilesIndex = new EasySearch.Index({
  collection : Files.files,
  fields : ['metadata.name'],
  engine : new EasySearch.MongoDB()
});
`
what changes need to be done here??

**Comment by matteodem** [comment]
What is the problem you're having?

**Comment by yogesh2591** [comment]
unable to list out the all file name.

**Comment by matteodem** [comment]
Closing as collectionFS is deprecated
