### ISSUE TITLE
only return some of the fields from collection with MongoDB engine 

### ISSUE THREAD

**Issue by DylanKojiCheslin** [matteodem/meteor-easy-search#507]
Hi I'm trying to only return the portions of the data needed from a collection. But I can't figure out how to do this in easy search.

This is a comparable Collection find. note that data is only return data for some fields, using the options fields property to limit

``` javascript
Agenda.find(
//selector
      {agendaState : {$eq:'published'},
      createdBy : {$ne: this.userId}
      },
//options
      {fields:{
          agendaState: 1 ,
          createdBy: 1 ,
          questions: 1 ,
          publishedDate: 1 ,
          requestorAvailabilities: 1
        }
      }
    );
```

here is the index I have now. it works fine other than returning all the fields

``` javascript
AnwserIndex = new EasySearch.Index({
  collection: Agenda,
  fields: ['questions.question.context'],
  name: 'AnwserIndex',
  engine: new EasySearch.MongoDB(
    {
    sort: function () {
      return {
        publishedDate: 1
      }
    },
    selector: function (searchObject, options, aggregation) {
      // retrieve the default selector
      selector = this.defaultConfiguration().selector(searchObject, options, aggregation);
     //filter
      selector.agendaState = {$eq:'published'};
      selector.createdBy = {$ne: this.userId};
    return selector;
    },
    permission: function (options) {
      return (!!Meteor.userId) // type converted to boolean
    },
    defaultSearchOptions: {
      sortBy: 'relevance'
    },
  }),
});
```

**Comment by tarunbatra** [comment]
:+1:
facing similar issue. I think there's **engine.fields** method just **engine.sort**, but not sure how to use it.
Anyone?

**Comment by matteodem** [comment]
http://matteodem.github.io/meteor-easy-search/docs/engines/ Here's the docs. Can you let me know what is unclear to you?

**Comment by tarunbatra** [comment]
@matteodem I checked the docs, but it's unclear how the return value of **fields** method in MongoDB engine configuration should look like.
![screenshot from 2016-08-17 18-14-49](https://cloud.githubusercontent.com/assets/5329230/17736674/c761ad68-64a6-11e6-9ea3-1e7b51abc1b8.png)

**Comment by matteodem** [comment]
It should be the same as here http://docs.meteor.com/api/collections.html#fieldspecifiers. does that work?

**Comment by tarunbatra** [comment]
Great! I was confused because the fields property in Index expects an array. Thanx @matteodem, I think that resolves the issue!

**Comment by matteodem** [comment]
Cool, I'll add docs to clarify that.
