### ISSUE TITLE
Aggregation using $and behaves like $or

### ISSUE THREAD

**Issue by babenzele** [matteodem/meteor-easy-search#510]
Using the `MongoTextIndex` engine, specifying `aggregation: '$and'` does not seem to change away from default `$or` search behavior. 

```
export const AssetsIndex = new EasySearch.Index({
  collection: Assets,
  fields: ['barcode', 'modelName', 'modelNumber', 'categoryName', 'manufacturerName', 'locationName'],
  defaultSearchOptions: { limit: 20 },
  engine: new EasySearch.MongoTextIndex({
    aggregation: '$and',
    sort() {
      return { createdAt: -1 };
    }
  })
});
```

**Comment by matteodem** [comment]
The docs are invalid, `aggregation` parameter is not configurable for the `TextIndex` engine. I'll change that now

**Comment by babenzele** [comment]
How does one aggregate using `MongoDB` engine? Zero results are returned when I apply `aggregation: '$and'`.
