### ISSUE TITLE
Customize Autosuggest template

### ISSUE THREAD

**Issue by RafOXxxx** [matteodem/meteor-easy-search#512]
Hi there,

could someone please give an example how to create a customized Autosuggest template.
To me it is not clear how to achieve that.
So far I copied the original template, renamed it and added the "suggestionTemplate" parameter and the name of the new template to my collection index like so:

``` javascript
CollectionIndex = new EasySearch.Index({
        collection: this.Collection,
        fields: ['name', 'city'],
        suggestionTemplate: 'MyAutogguestTemp',
        engine: new EasySearch.Minimongo({
            aggregation: '$or',
        }),
    });
```

``` html

<template name="MyAutogguestTemp">
  <div>
    <span class="autosuggest-title"><span class="name"><p>This is a test</p>{{label}}</span></span>
  </div>
</template>

```

I expected to see **"This is a test"** in front of every suggestion

**Comment by matteodem** [comment]
You need to pass the argument to the blaze template inclusion: 


```html
<div class="my-autosuggest">
  {{> EasySearch.Autosuggest index=myIndex suggestionTemplate="mySuggestions"}}
</div>
```

I'll reopen if the problem keeps persisting

**Comment by RafOXxxx** [comment]
Thanks for your help but that is exactly what I tried in the first place.
All the other parameters  work but it seems like it won't take the
"suggestionTemplate" parameter. Does the template has to be in a certain
place in the file structure?

2016-06-29 17:18 GMT+02:00 Matteo De Micheli <notifications@github.com>:

**Comment by matteodem** [comment]
Please try `renderSuggestion`, I think the docs might be wrong.
