### ISSUE TITLE
Loading pattern

### ISSUE THREAD

**Issue by frankapimenta** [matteodem/meteor-easy-search#516]
I was applying here a loading pattern to a collection indexed by easy search. 
It works fine on first render (page 1).
Now I would like to know how can I know when the component is fetching the next page and when fetching documents of the next page is finish (something like isSearching() method). 
I could not find that. 
Do you know how could it be done?

**Comment by matteodem** [comment]
Does [this](https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/component_methods.md) help?
