### ISSUE TITLE
Calling load more on index dynamically

### ISSUE THREAD

**Issue by Neobii** [matteodem/meteor-easy-search#523]
Is there a way to fire the load more event on an index without using the load more button (like if I want to implement inifiniscroll)

**Comment by matteodem** [comment]
yes, use component methods: http://matteodem.github.io/meteor-easy-search/docs/components/

see https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/lib/load-more/load-more.js#L11

**Comment by Neobii** [comment]
Thanks for your help!  In exchange I'll write some more recipes for you!

On Sat, Aug 20, 2016 at 5:48 AM, Matteo De Micheli <notifications@github.com

**Comment by matteodem** [comment]
awesome! looking forward
