### ISSUE TITLE
Possible race condition in getComponentMethods?

### ISSUE THREAD

**Issue by Neobii** [matteodem/meteor-easy-search#524]
I'm trying    
`var results = SearchIndex.getComponentMethods().getCursor().fetch();`

and this error pops up
`Exception in template helper: Error: Component with name '__default' not found [no-component]`

**Comment by Neobii** [comment]
I found out that I called `getComponentMethods` sometimes before the search input was loaded because they exist in different templates.  I was expecting to get the results as if the user hasn't searched yet whether the search input has been loaded or not.

**Comment by matteodem** [comment]
you need to put this code in to the `onRendered` or `onCreated` hook of a template.
