### ISSUE TITLE
Grounddb V2

### ISSUE THREAD

**Issue by NitroBAY** [matteodem/meteor-easy-search#527]
Ground db is a very popular package to access offline to database. I think grounddb is close as minimongo (find, findOne etc.) but I can't use it as if I use minimongo engine EasySearch complains about the fact that he expects a particular constructor. So I would need an engine with grounddb, obviously I should have create one instead of asking you that but I'm not really sure how to do it even after reading the source code of your engine.

**Comment by matteodem** [comment]
You could try creating a new engine, see source code for MongoDB engine as an example https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:core/lib/engines/mongo-db.js

**Comment by NitroBAY** [comment]
Yes I will give another try. It's not impossible, if I succeed you want me to : post the code here, create a repo, create a PR or create a package ?

**Comment by matteodem** [comment]
create a fork and a PR subsequently

**Comment by NitroBAY** [comment]
sorry I don't know how to do it. It's normal you don't make the ground engine but could you check the ground:db repo and give me tips ?

**Comment by NitroBAY** [comment]
the problem is that since V2 grounddb is not based anymore on Meteor.collection (I think), not really based on Meteor by the way as the author doesn't want to use any Meteor (but this is another issue). Whatever,
   ` check(config.collection, Meteor.Collection);`
cause the trouble it's here https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:core/lib/core/index.js#L17
Can I change the expected constructor or at least disable the checking with engines functionality ?

**Comment by NitroBAY** [comment]
So finally I added an option to change the checked constructor of the collection. I made a pull request

**Comment by matteodem** [comment]
Awesome, gonna have a look at it tomorrow

**Comment by matteodem** [comment]
Introduced `ignoreCollectionCheck` config param in `v2.1.8` https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:core/lib/core/index.js#L21.

**Comment by guillim** [comment]
I am having the exact same issue with GroundDB + EasySearch. For those who can't upgrade to newer versions of GroundDB: use Minimongo Engine. it works
