### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by muscaiu** [matteodem/meteor-easy-search#529]
Before implementing EasySearch i used to display my items sorted by createdAt like this:

```
return Items.find({}, { sort: { createdAt: -1 } })

  {{#each items}}
          {{> Item}}
  {{/each}}
```
Now, using EasySearch i have something like this
```
  {{#EasySearch.Each index=itemsIndex }}
          {{> Item}}
  {{/EasySearch.Each}}-->
```
, but the **sorting is not working anymore.** 

Is there any way i could work with EasySearch and also display my items in a desired order?

**Comment by matteodem** [comment]
You can use the `sort` configuration on engine level: http://matteodem.github.io/meteor-easy-search/docs/core/
