### ISSUE TITLE
[DOC] Minimongo supporting of transform

### ISSUE THREAD

**Issue by NitroBAY** [matteodem/meteor-easy-search#532]
Fortunately, and unlike to what the doc [states](http://matteodem.github.io/meteor-easy-search/docs/engines/), Minimongo does support transform property (I tested it). I hope I could directly make a PR to update doc but it doesn't seem open source.

**Comment by matteodem** [comment]
Good stuff, the docs which you are referring are here https://github.com/matteodem/meteor-easy-search/blob/gh-pages/docs/engines.md.

**Comment by NitroBAY** [comment]
Damn you're even more reactive than Meteor.

**Comment by NitroBAY** [comment]
So I'll PR.

**Comment by matteodem** [comment]
Haha I was just randomly having a look at another PR

(if you feel really lucky I'd gladly appreciate some help on our docs labeled tasks, maybe simple ones like https://github.com/matteodem/meteor-easy-search/issues/526 would already be of great help.)

**Comment by NitroBAY** [comment]
But I'll mess with your folder because my OS doesn't support : in folder :(

**Comment by matteodem** [comment]
The branch `gh-pages` does not have any semicolons, shouldn't break anything

**Comment by NitroBAY** [comment]
Great I'll give it a go when I could then.

**Comment by NitroBAY** [comment]
@matteodem you're right I should help on your project what you point out, every single dev who use and appreciate an open-source project should try to PR as much as possible as it's the price (more a pleasure actually) to pay when you use a free tool, and so every devs can both give and receive amelioration of code. But I really don't have much time these times. I hope I'll come back to your package when I could.

**Comment by matteodem** [comment]
Thanks a lot for your contribution 😄
