### ISSUE TITLE
Sort with Minimongo engine

### ISSUE THREAD

**Issue by muscaiu** [matteodem/meteor-easy-search#534]
Is it possible to have Search and Sort with Minimongo engine?

**Comment by matteodem** [comment]
yes, please refer to the documentation.

**Comment by muscaiu** [comment]
Arrghh i read [this](http://matteodem.github.io/meteor-easy-search/getting-started/) back and forward twice, All i found is for `engine: new EasySearch.MongoDB({})`, but nothing for `engine: new EasySearch.Minimongo()`. 
Could u hit me in the face with it? :grimacing:
