### ISSUE TITLE
Adding facets to your search app

### ISSUE THREAD

**Issue by demiantriebl** [matteodem/meteor-easy-search#537]
hi! i can search with a select like the [documentation ](http://matteodem.github.io/meteor-easy-search/docs/recipes/)
but i need to use a radio button with true or false. I have tried everything but i can't make it work

**Comment by matteodem** [comment]
What does "tried everything" mean?

**Comment by demiantriebl** [comment]
hi, i need 3 days to work. but when i decide post then i can resolve this. i use this on blaze

```
 <input type="radio" class="magiaFiltro" name="magia" value="" checked>Todos<br>
                    <input type="radio" class="magiaFiltro" name="magia" value="Magica"> Magica<br>
                    <input type="radio" class="magiaFiltro" name="magia" value="Convencional"> Convencional
```

on the .js use

```
 'change .magiaFiltro': function (e) {
        var radio = $('input:radio[name=magia]:checked').val();
        PlayersIndex.getComponentMethods()
                .addProps('magiafilter', radio);

    },
```
and in the model logic use 

`  selector: function (searchObject, options, aggregation) {
            let selector = this.defaultConfiguration().selector(searchObject, options, aggregation),
                categoryFilter = options.search.props.categoryFilter;
              
                magiafilter = options.search.props.magiafilter;
               if (!_.isEmpty(magiafilter) && magiafilter == "Magica") {
                selector.magia = true;
            }else if (_.isEmpty(magiafilter) && magiafilter == "Convencional"){
                selector.magia = false;
            }
`

thanks for all!!!

**Comment by matteodem** [comment]
Please refer to the recipes http://matteodem.github.io/meteor-easy-search/docs/recipes/
