### ISSUE TITLE
Load More button event

### ISSUE THREAD

**Issue by demiantriebl** [matteodem/meteor-easy-search#539]
```
hi! i try to put easy search with isotope, the first elements work fine, but when i click on the load more button, this  elements don't follow the isotope directives
```

   In the docs it is not specified how can put some code on the load more button event, i would like to update the isotope when this happen.

**Comment by matteodem** [comment]
Please rephrase your question to be clearer, maybe you're searching for [this](https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/component_methods.md)?
