### ISSUE TITLE
Easy Search and accentFold?

### ISSUE THREAD

**Issue by BrianJLennon** [matteodem/meteor-easy-search#541]
Hi,

Genuinely love the ease with which Easy Search works (Well done!) but have come across a stumbling block... If someone for example types in "cafe" and documents with the word "café"are not returned... how do I get around this?

Thanks in advance.

Brian

**Comment by matteodem** [comment]
Hi Brian

This can be resolved by using a mature engine like ElasticSearch for searching or doing some processing when saving your mongodb documents and when searching:

* Replace characters with accents like "é" with "e" in a separate field on your document
* Adding a `selectorPerField` configuration that applies the same logic to the `searchString` 

see "Searching user mails" here http://matteodem.github.io/meteor-easy-search/docs/recipes/

**Comment by matteodem** [comment]
Please write into here if you have any other questions related to this issue
