### ISSUE TITLE
update 2.1.0 elasticSearch and error massage

### ISSUE THREAD

**Issue by AdrianAbba** [matteodem/meteor-easy-search#550]
Hey Matteo =)

After updating everything, the Version doesnt change.
Removed the old one, tried to install it local, but im getting still 2.0.9.

And i tried to work with elasticSearch.

```
import { Meteor } from 'meteor/meteor';
import { Mongo } from 'meteor/mongo';
import { check } from 'meteor/check';
import { Match } from 'meteor/check';
import { Index } from 'meteor/easy:search';
import { ElasticSearchEngine } from 'meteor/easysearch:elasticsearch';

export const Projects = new Mongo.Collection('projects');

const projectIndex = new Index({
    collection: Projects,
    fields: ['title', 'subtitle','tags','jobs'],
    new ElasticSearchEngine({
      sort: function () {
        return { createdAt: -1 }
      },
    
    })
  });
```

getting always the Error:

`TypeError: ElasticSearchEngine is not a function.`

Any ideas :/?

**Comment by matteodem** [comment]
try executing `meteor update easysearch:elasticsearch`. Does it still not update then?

**Comment by AdrianAbba** [comment]
still 2.0.9 :/

**Comment by AdrianAbba** [comment]
local i got the folder 2.1.0 and 2.0.9 now, but in my project the Version.file still has 2.0.9

**Comment by AdrianAbba** [comment]
changed the Versions manual and its working  now  :)
