### ISSUE TITLE
Sorting by Date not working

### ISSUE THREAD

**Issue by zyonnetworks** [matteodem/meteor-easy-search#554]
Hi,

For some reason, the sort feature isn't working. Am I doing something wrong?

```
export const LeadsIndex = new Index({
  collection: Leads,
  fields: ['firstName', 'lastName', 'createdAt'],
  engine: new MongoDBEngine({
    sort: () => { createdAt: -1 }
  }),
  defaultSearchOptions: { limit: 25 }
});
```

Mongo is saving date as ISODate().

I even tried to sort by a field called 'firstName', but it didn't work either. Please advise.

**Comment by matteodem** [comment]
shouldn't `sort: () => { createdAt: -1 }` be `sort: () => ({ createdAt: -1 })`?

Looks like invalid syntax to me.

**Comment by zyonnetworks** [comment]
Perfect. That worked! It was a syntax error on my end. 

Is there a feature to refresh the search because when a new document is added, it puts it on the bottom.  It doesn't order correctly until I hit refresh.

**Comment by matteodem** [comment]
Please create a new story for the question

**Comment by guillim** [comment]
thanks @matteodem I had the exact same problem. maybe the doc is a bit confusing ? -> http://matteodem.github.io/meteor-easy-search/docs/engines/

**Comment by matteodem** [comment]
Can you explain what you think is confusing? I happily will adjust the docs (or you can create a PR in the `gh-pages` branch)

**Comment by guillim** [comment]
@matteodem yes, here is the sentence that confused me: on the first paragraph, under the title ENGINES, there is a piece of example code where is written
sort: () => { score: 1 },
And you mentioned above in this conversation that it would better be 
sort: () => ({ score: 1 }),

Am I right?

**Comment by matteodem** [comment]
oh yeah. Feel free to either create a PR fixing this in the gh-pages branch or creating a new issue
