### ISSUE TITLE
"Component with name '__default' not found [no-component]"

### ISSUE THREAD

**Issue by krishaamer** [matteodem/meteor-easy-search#555]
Hello, recently I've come across this error:

`Uncaught errorClassdetails: undefinederror: "no-component"errorType: "Meteor.Error"message: "Component with name '__default' not found [no-component]"reason: "Component with name '__default' not found"stack: "Error↵    at Index.getComponentMethods (http://localhost:3000/packages/easysearch_components.js?hash=e2a0d2f16ac649505144a6464d5a1c842de80435:626:15)↵    at HTMLDivElement.onChange (http://localhost:3000/app/app.js?hash=fa2f28e45776f190c67a98b44f1a165bcadc0865:11779:23)↵    at Object.value (http://localhost:3000/app/app.js?hash=fa2f28e45776f190c67a98b44f1a165bcadc0865:7015:35)↵    at HTMLDivElement.<anonymous> (http://localhost:3000/app/app.js?hash=fa2f28e45776f190c67a98b44f1a165bcadc0865:7103:30)↵    at Function.each (http://localhost:3000/packages/jquery.js?hash=c57b3cfa0ca9c66400d4456b6f6f1e486ee10aad:442:23)↵    at jQuery.fn.init.each (http://localhost:3000/packages/jquery.js?hash=c57b3cfa0ca9c66400d4456b6f6f1e486ee10aad:194:17)↵    at Object.selected (http://localhost:3000/app/app.js?hash=fa2f28e45776f190c67a98b44f1a165bcadc0865:7070:29)↵    at HTMLDivElement.activate (http://localhost:3000/app/app.js?hash=fa2f28e45776f190c67a98b44f1a165bcadc0865:6145:28)↵    at HTMLDivElement.selectAction (http://localhost:3000/app/app.js?hash=fa2f28e45776f190c67a98b44f1a165bcadc0865:6082:48)↵    at HTMLDivElement.click (http://localhost:3000/app/app.js?hash=fa2f28e45776f190c67a98b44f1a165bcadc0865:5799:49)"__proto__: Error`

I'm closest guess it's coming from here: 

```
Template.header.onRendered(() => {

  Tracker.autorun(() => {
    $('.ui.dropdown').dropdown({
      onChange (value) {
        TAPi18n.setLanguage(value);
        ThingsIndex.getComponentMethods().addProps('lang', TAPi18n.getLanguage());
      }
    });
  });

});
```

**Comment by matteodem** [comment]
Do you have any easy search components in the `header` template?
