### ISSUE TITLE
Are Components Reactive?

### ISSUE THREAD

**Issue by zyonnetworks** [matteodem/meteor-easy-search#558]
The data results isn't updating when using a reactive helper.  Should this update the results reactively OR do i need to add a config option OR is this not supported?

/index.js
```
Template.templateName.onRendered(function() {
    this.autorun(function() {
            reactiveIndex.set(someIndex);
    }
})
Template.templateName.helpers({
currentIndex() {
    return reactiveIndex.get();
}
});
```

/index.html
```
{{#EasySearch.Each index=currentIndex}}
    <li>{{this}}</lI>
{{/EasySearch.Each}}
```

**Comment by zyonnetworks** [comment]
i actually got this to work by making some really minor updates to BaseComponent and getCursor()

**Comment by matteodem** [comment]
What did you patch in there?

**Comment by zyonnetworks** [comment]
/packages/easysearch:components/lib/base.js
```
onCreated() {

        this.autorun(function() { // added autorun
            let index = this.getData().index,
                indexes = [index];
            ...
        } // added autorun
}
```

/packages/easysearch:components/lib/component-methods.js line 23
```
options = dict.get('searchOptions') **|| {}**, //added || {}
```

**Comment by choncj** [comment]
Is there a way to have the pagination component and pagination page reactive?
Removing Items from the Collection wont update the page correctly. Adding new items to the Collection wont update the Pagination count.

Any help would be really great!

![zeichenflache 1](https://cloud.githubusercontent.com/assets/10691778/26538819/50c04e02-4449-11e7-89c8-df28df7a1319.png)


![zeichenflache 1 kopie](https://cloud.githubusercontent.com/assets/10691778/26538826/5e2c63aa-4449-11e7-99a2-d4e4e8b770c6.png)

**Comment by matteodem** [comment]
Could you please create a new issue with reproduction steps? A reproduction repository will make it even easier to find the bug and fix it.

**Comment by choncj** [comment]
@matteodem Thank you for the fast reply. I created a new issue [#610](https://github.com/matteodem/meteor-easy-search/issues/610)
