### ISSUE TITLE
Make {{ @index }} available inside a {{ #EasySearch.Each }}

### ISSUE THREAD

**Issue by huguesbrunelle** [matteodem/meteor-easy-search#559]
Hello there,

Really cool plugin but in my recent project I use {{@index}} inside a normal {{#each}} loop but when I implemented {{ #EasySearch.Each }}, the {{@index}} make the app crash with this error :

```
Error: Unsupported directive: @index
```

Thanks for your time and this really cool package :)

**Comment by matteodem** [comment]
the fix might be as easy as adding `@index=@index` to here https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/lib/each/each.html#L3. 

I gladly accept help in form of PRs as I'm quite busy with other work right now.

**Comment by huguesbrunelle** [comment]
Wow thanks I didn't know we could make our own templating that way. I'll try this today for sure and let you know. Thanks a lot.

**Comment by huguesbrunelle** [comment]
@matteodem not sure to understand tho.
I've installed `easy:search` so `easysearch:components` should be wrap with it.
When I try to create my own `template name="EasySearch.Each"` it says that a template of that name already exist.
I never overwritten an existing template before so if you could help me once more on this it would be much appreciated.

**Comment by matteodem** [comment]
It would have to be fixed as a PR. Fixing in your app is only possible by installing the package locally.

**Comment by huguesbrunelle** [comment]
Ok got it. So I can contribute by fixing it and PR you. Didn't understand that the first time.
Ok I'll be glad to do it later today.

**Comment by matteodem** [comment]
This is published in the latest version! See https://github.com/matteodem/meteor-easy-search/commit/4e988ba92a8330821264c29e4875c8a59626a863 if you're interested in the implementation details.

**Comment by huguesbrunelle** [comment]
Just implemented it. Works perfectly!!! Thanks a lot. I'll tell another person who was looking for this on a forum... Have a great day and Holidays.

**Comment by matteodem** [comment]
You too, thank you!
