### ISSUE TITLE
Autosuggest ignores noDocumentsOnEmpty

### ISSUE THREAD

**Issue by stefanve** [matteodem/meteor-easy-search#566]
I have a simple EasySearch.Autosuggest and when I click it, it displays the result for "", so it fills the drop down. That is not very cute, I would like it that they have to type at least one character before it reacts. The  "event" argument is also ignored, so I can not force them to press enter or check for a keystroke.

Any ideas how I can go about this?

**Comment by stefanve** [comment]
By the way, the template named:
'EasySarch.Autogguest.DefaultRenderSuggestion' 
is that as intended? "sarch"? "autogguest"?

**Comment by matteodem** [comment]
That's a naming error. feel free to submit a PR for it.

**Comment by matteodem** [comment]
this is related to #417

**Comment by matteodem** [comment]
This is fixed in latest version `2.2.1` after nearly half a year 😅

**Comment by stefanve** [comment]
Great! I'm sorry, I guess I should have been more active here but I made a workaround and forgot about it :)

**Comment by matteodem** [comment]
no problem, hopefully this provides a stable solution to your workaround.
