### ISSUE TITLE
Start Searching After 3 Characters?

### ISSUE THREAD

**Issue by krishaamer** [matteodem/meteor-easy-search#568]
Hey @matteodem, the plugin is working great, thanks so much for your work! 

I was wondering is it possible to limit the search in a way that it only starts after 3 characters have been written? I can feel the search slow down with 1-2 characters because it's pulling in most of the results containing just the single letter.

You can try it out here: http://100.haam.co

Best,
Kris

**Comment by matteodem** [comment]
You can extend the input component and override the keyup input logic, see https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/lib/input/input.js#L37. Or create a PR that allows to configure this logic (might make the `event` parameter obsolete).
