### ISSUE TITLE
How do you setup the ElasticSearch addon to work with a remote server instead of localhost:9200?

### ISSUE THREAD

**Issue by webmagnets** [matteodem/meteor-easy-search#569]
I have an account with Bonsai.io for hosting ElasticSearch.

How do you configure the ElasticSearch addon to work with that?

**Comment by matteodem** [comment]
See the configuration section https://github.com/matteodem/meteor-easy-search/tree/master/packages/easysearch:elasticsearch#configuration

**Comment by webmagnets** [comment]
I read that section. I need an example. I am too much of a beginner to know what to do from just reading that section.

**Comment by matteodem** [comment]
It's the client option. This should help you https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/quick-start.html
