### ISSUE TITLE
Customize esAutosuggest input, selected values and suggestions

### ISSUE THREAD

**Issue by rico** [matteodem/meteor-easy-search#57]
First of all - thank you. I appreciate your work very much. I'm kind of new to meteor, so please excuse if this is a stupid question. 

I need to customize the `esAutosuggest` template. Is it possible? Where would I start?

**Comment by matteodem** [comment]
This is resolved in v2, as a new package using selectize called `easysearch:autosuggest`. see https://github.com/matteodem/meteor-easy-search/tree/master/packages/easysearch:autosuggest.
