### ISSUE TITLE
TypeError: MinimongoEngine is not a function

### ISSUE THREAD

**Issue by eumb** [matteodem/meteor-easy-search#570]
I am getting this error whenever I am starting the app

TypeError: MinimongoEngine is not a function

on a very basic example

import { Index,MinimongoEngine} from 'meteor/easy:search'

// On Client and Server
const Player = new Mongo.Collection('players')
const PlayersIndex = new Index({
  collection: Players,
  fields: ['name'],
  engine: new MinimongoEngine()
})

**Comment by matteodem** [comment]
Which version are you using?

**Comment by eumb** [comment]
I just installed
easy:search@2.0.5
easysearch:components@2.0.5
easysearch:core@2.0.9

and running latest meteor 1.4.2.3

**Comment by matteodem** [comment]
I just tested it with the leaderboard and it works as expected (no error).

```js
import { Index, MinimongoEngine } from 'meteor/easy:search'
```

Please provide a reproduction repo or checkout the leaderboard example.
