### ISSUE TITLE
Search is not working with elastic search engine

### ISSUE THREAD

**Issue by Nits7029** [matteodem/meteor-easy-search#572]
this is my indexCode:
```js
import { Index } from 'meteor/easy:search'
import { ElasticSearchEngine } from 'meteor/easysearch:elasticsearch'

 RoomsIndex = new Index({

 engine: new ElasticSearchEngine({
    body: (a,b,c) => {}
  }),
 collection: Rooms,
 fields:  ['roomName', 'roomType','speciality']
});
```
rooms.html template code:
```html
  {{> EasySearch.Input index=roomsIndex}}
                    <ul>
                        {{#EasySearch.Each index=roomsIndex}}
                        <li>Name of the player: {{roomName}} - {{roomType}} - {{speciality}}</li>
                        {{/EasySearch.Each}}
                    </ul>
```
rooms.js code:

this is helper code:

```js
  roomsIndex:function(){
      return RoomsIndex ;
    }
```

**Comment by matteodem** [comment]
Is elasticsearch running locally?

**Comment by Nits7029** [comment]
on page load time data shows but when i type search string in search box it is not work. it gives me all record which i have.
![capture](https://cloud.githubusercontent.com/assets/9457796/21426274/fd3f6278-c873-11e6-9a03-f2313a6910be.PNG)

**Comment by Nits7029** [comment]
yes, elasticsearch is running locally

**Comment by bompi88** [comment]
Does returning `a` inside the body function work? If the body function is defined, you'll have to return the actual ES-body which will be used by the ES-client.

**Comment by matteodem** [comment]
If this is still a problem please provide a reproduction repository or steps. Will re-open if provided
