### ISSUE TITLE
Exception in template helper: bindDataContext when using getComponentDict()

### ISSUE THREAD

**Issue by talalav** [matteodem/meteor-easy-search#574]
Hello Matteo!
I just copied code from your recipes 
```
Template.topicSearch.helpers	
   testResults: () ->
      dict = TopicIndex.getComponentDict()
      return dict.get('count')
```
and got "Exception in template helper: bindDataContext". However I I'm perfectly able to get data from this dictionary by using a console.

**Comment by matteodem** [comment]
What if you try the same without coffeescript? If that helps then I'd suggest checking out if other people had similiar problems
