### ISSUE TITLE
Autoscroll Compatibility

### ISSUE THREAD

**Issue by krishaamer** [matteodem/meteor-easy-search#581]
Hey @matteodem would it be theoretically possible to make easy-search autoscroll back to the same search result when using the back button? This would make for a smoother user experience.

Thanks,
Kris

**Comment by matteodem** [comment]
it might work if you search based on the url, or when you have some way to access what was searched last. Also might have to save the page of the search (or the search results that were loaded if it's a load more button).

Based on that you'd have to write some logic to store the last search params and use the component methods to get your desired behaviour when going back.
