### ISSUE TITLE
AutoSuggest Component ( Show Result When Select )

### ISSUE THREAD

**Issue by 1073113** [matteodem/meteor-easy-search#585]
Hi,

According to `[Auto-Suggest Not Working #453]` said `The idea of the autosuggest is that it is self contained and has no direct relation with the Each component`.

I wish to have direct relation with each component. 
Its there any way to show to results when I can click the contained data from the autosuggest component?
I mean the result page reactively response to data i selected from autosuggest component (selectize) .

Please advise , thanks

**Comment by matteodem** [comment]
What is your usecase? Is using the normal input not sufficient?

**Comment by matteodem** [comment]
Will reopen when answered

**Comment by 1073113** [comment]
Hi Matteodem, 
This is my usecase. Apologize for late late response. 
Thanks. 
![sample](https://cloud.githubusercontent.com/assets/12009185/22888584/41b600c8-f241-11e6-9ae2-370c41117074.jpg)
