### ISSUE TITLE
Example of integrating Publish Composite with Easy-Search

### ISSUE THREAD

**Issue by 1073113** [matteodem/meteor-easy-search#586]
Hi Matteodem,

Do you have any example of using EasySearch with Publish Composite?
I having trouble of getting this to work.

Besides, I have a doubts that need your kind explanation.
1) Let's say about your leaderboard app. It has no subscription in Template.OnCreated. How and where do you subscribe from publication example `Meteor.publish('test-search', function (searchTerm) { .. }) ` ? 
  1.a) Does it need to subscribe?
2)  `Meteor.publish('test-search', function (searchTerm) { .. }) ` Where does `searchTerm` argument passed from?

By the way here is my code. Kind advise whats goes wrong? it does not get Collection.Files and Meteor.users collection.
I'm looking forward to your advise. 
Thank in advance. 

```
import { CourseIndex } from '../course-index.js';
Meteor.publishComposite('App.inPublic', function appInPublic(options) {
return {
    find() {
      return CourseIndex.search(options).mongoCursor;
    },
    children: [
      {
        find(docs) {
          return Collections.files.find({ 'meta.courseId': docs._id}).cursor;
        },
      },
      {
        find(docs) {
          console.log(docs);
          return Meteor.users.find({ _id: docs.courseUserId },
            { fields: {
              'profile.name': 1,
              'profile.avatarURL': 1,
              'profile.avatarImage': 1,
              'services.facebook.id': 1,
            } });
        },
      },
    ],
  };
});
```

**Comment by 1073113** [comment]
Hi Matteodem,
I looking forward to your reply. 
Thank you.

**Comment by matteodem** [comment]
1. This has to do with the `MongoDBEngine` that's being used, please refer to the docs to get more information regarding each engine http://matteodem.github.io/meteor-easy-search/docs/engines/

2. Not really sure what you're asking for here, do you want to have info about the Meteor publish / subscribe
