### ISSUE TITLE
Adjust default elasticsearch query

### ISSUE THREAD

**Issue by matteodem** [matteodem/meteor-easy-search#587]
fuzzy like this queries don't exist anymore. a PR is gladly appreciated here, basically just have to adjust following lines here: https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:elasticsearch/lib/engine.js#L62

**Comment by AdrianAbba** [comment]
the fields parameter doesnt exist anymore too :/

"The fields parameter has been replaced by stored_fields. The stored_fields parameter will only return stored fields — it will no longer extract values from the _source."

https://www.elastic.co/guide/en/elasticsearch/reference/5.2/breaking_50_search_changes.html#_literal_fields_literal_parameter

**Comment by bompi88** [comment]
@AdrianAbba this should help if you're using ES 5.x:

```javascript
body: function (body, opts) {
  return {
    query: body.query,
    stored_fields: body.fields
  };
}
```
