### ISSUE TITLE
Elasticsearch: Modify body based on options

### ISSUE THREAD

**Issue by bompi88** [matteodem/meteor-easy-search#588]
Seems that the body function is [called](https://github.com/matteodem/meteor-easy-search/blob/c91804408c4e49ac55acd960b7314e77a91c5cd3/packages/easysearch:elasticsearch/lib/engine.js#L158) without the options parameter. Could be very useful to construct aggregations based on props set there, as I don't see EasySearch supporting aggregations yet. PR #589

**Comment by matteodem** [comment]
released in `v2.1.1`
