### ISSUE TITLE
sort by textScore when using MongoTextIndex

### ISSUE THREAD

**Issue by WayneUong** [matteodem/meteor-easy-search#592]
I remember using this feature a while ago. But I can't get it to work now. Is it removed? I can't find an example in the docs either.

**Comment by WayneUong** [comment]
I figured out after diving into the code. Would be nice to have an example (:

**Comment by matteodem** [comment]
feel free to provide a PR on the `gh-pages` branch or post an example in this issue

**Comment by huevoncito** [comment]
@WayneUong Can you please say more about how you did this?
