### ISSUE TITLE
Search fields on an object 

### ISSUE THREAD

**Issue by AlmogRnD** [matteodem/meteor-easy-search#593]
I wanted to know if it's possible to have easy search use an object for the field search. 

I have the following 
```
profileFields: {
    name: "Lucy Lloyd",
    gender: "female",
    iGenLocation: "Melbourne",
    industry: "Education",
    interests: [
      "Dog Lover",
      "Extrovert"
    ],
    role: "mentee",
    contactDays: "Weekends"
  },
```

and when I set the fields to 
```
  fields: ['profileFields']
```

It does not work but the following does work 
```
  fields: ['profileFields.name', 'profileFields.bio']
```

**Comment by matteodem** [comment]
There's multiple approaches to solve this. Either you save the data differently, provide a `selector` configuration or use ElasticSearch, see http://matteodem.github.io/meteor-easy-search/docs/recipes/
