### ISSUE TITLE
Load all data or user without the button load more

### ISSUE THREAD

**Issue by Marcelrama** [matteodem/meteor-easy-search#594]
Hello,
It is possible to load all the data in my users case without the need to give the load more button. For design issues I do not need the load my button to come out.

``{{{> EasySearch.LoadMore index=playersIndex}}``

**Comment by matteodem** [comment]
I'd suggest having a look at the component methods which expose all the functionality used by the components in a Javascript API. http://matteodem.github.io/meteor-easy-search/docs/components/
