### ISSUE TITLE
subscription using MongoDBEngine

### ISSUE THREAD

**Issue by daorren** [matteodem/meteor-easy-search#596]
> The MongoDB engine searches the specified collection directly with MongoDB on the server and uses subscriptions to retrieve reactive data                   
> -- MongoDBEngine

When I use MongoDBEngine, I'm not getting all the data from server side database

Index here only get subscription from its context template, which is the same result when I use MinimongoEngine.

So should I specify which subscription to use? But how?

```js
// indexes.js
export const MessagesIndex = new Index({
  collection: Messages,
  engine: new MongoDBEngine({
    //
  }),
  fields: ['content'],
})

// conversation.html
<template name="conversation">
  {{> messagesSearch}}
<template>

// search.html
<template name="messagesSearch">
  {{> EasySearch.Input index=MessagesIndex }}
  <ul>
    {{#EasySearch.Each index=MessagesIndex}}
      <li>Content: {{content}}</li>
    {{/EasySearch.Each}}
  </ul>

  {{> EasySearch.LoadMore index=MessagesIndex}}

  {{#EasySearch.IfNoResults index=MessagesIndex}}
    <div class="no-results">No results found!</div>
  {{/EasySearch.IfNoResults}}
</template>

// search.js
Template.messagesSearch.helpers({
  MessagesIndex: function () {
    console.log(Messages.find({}).fetch());
    console.log(MessagesIndex.search('').fetch());
    return MessagesIndex;
  },
})
```

**Comment by matteodem** [comment]
did you create the index on both the server and client? the easy search leaderboard example can also give you a hint maybe.
