### ISSUE TITLE
Allow LoadMore button HTML content

### ISSUE THREAD

**Issue by Roshdy** [matteodem/meteor-easy-search#597]
First, thanks for the great package.

That said, would you please do me a favor and modify this [file](meteor-easy-search/packages/easysearch:components/lib/load-more/load-more.html)

to be:

`<template name="EasySearch.LoadMore">
    {{#if moreDocuments}}
        <button {{attributes}}>{{html content}}</button>
    {{/if}}
</template>`

to allow html content (i.e. icons --> `<i class="fa fa-spinner"></i>`)

example:
**JS**
`Template.searchbox.helpers({
loadMoreContent: function(){
		return '<i class="fa fa-spinner"></i> <span>More...</span>';
	}
});`

**HTML**
`{{> EasySearch.LoadMore index=productsIndex attributes=loadMoreAtts content=loadMoreContent}}`

**Comment by matteodem** [comment]
Please create a PR if you want to see changes in the code.
