### ISSUE TITLE
Pagination Component and Page reactive?

### ISSUE THREAD

**Issue by choncj** [matteodem/meteor-easy-search#610]
## Component Bug Report 
Issues with Pagination & Each Components
[Demo](https://github.com/choncj/easy-search-pagination)

As asked on [#558](https://github.com/matteodem/meteor-easy-search/issues/558#issuecomment-263642959).
Is there a way to have the pagination component and pagination page reactive?

## Reproduce
1. Insert as many Collection entries until the pagination of the EasySearch Each Component is triggered 
2. Now trigger the Meteor Function remove() within the paginated Each Component 
    1. Picture 1
![zeichenflache 1](https://cloud.githubusercontent.com/assets/10691778/26556418/b85532a2-449a-11e7-8cff-a4ba67c2d805.png)

3. You should see that the sorting of the paginated Each Component is out of order
    1. Picture 2
![zeichenflache 1 kopie](https://cloud.githubusercontent.com/assets/10691778/26556419/b9a81cb4-449a-11e7-8c0a-95a0d25a287b.png)
4. Refreshing the page fixes the issue and shows the paginated Each Component in order again

## Expected

- Deleting a Collection entry within the Each Component shows the paginated Page in order

**Comment by matteodem** [comment]
Please provide reproduction steps or repository and define the problems with `expected` and `current` behaviours.

**Comment by choncj** [comment]
Really sorry for the late reply!
So i made a repository including the Meteor project that has the issue.
Im new to Github and Meteor and hope this is right :/ if not please let me know!
[choncj/easy-search-pagination](https://github.com/choncj/easy-search-pagination)

**Comment by matteodem** [comment]
Can you please provide steps to reproduce the bug?

**Comment by choncj** [comment]
@matteodem I updated the issue #610 

I've tried my best to write down the reproduction steps for the issue i have.
But i never reported a bug before so any guiding/ example would be appreciated. 

Thank you for your time.

**Comment by matteodem** [comment]
@choncj thanks! I'll check it out soon

**Comment by matteodem** [comment]
Fixed in latest version v2.2.0

**Comment by choncj** [comment]
Thank you very much!
