### ISSUE TITLE
Tips on large data set

### ISSUE THREAD

**Issue by zyonnetworks** [matteodem/meteor-easy-search#611]
I have 33 million records in a collection... Currently search results appear in about 60 seconds....  how do i get the results returned quicker?  Any tips on how to query faster for this many records?

I am using index.search('keyword string')

**Comment by matteodem** [comment]
You can add the `fields` parameter to only return a certain subset of fields on the document https://matteodem.github.io/meteor-easy-search/docs/engines/

Also check out the `selectorPerField` config which can be used to change the mongodb selector (if you use mongodb). 

The recipe for advanced search might be helpful for you too https://matteodem.github.io/meteor-easy-search/docs/recipes/

**Comment by zyonnetworks** [comment]
Thanks I'll check it out!
