### ISSUE TITLE
Filter results based on Client Startup completion

### ISSUE THREAD

**Issue by sydCPT** [matteodem/meteor-easy-search#617]
Hi There

Awesome package.  I have a very specific use case, which I am struggling to implement, and I was hoping this would be the correct platform to get some assistance.

What I need to do is wait for Client Startup to complete before creating the Index, or update the Index when the startup is complete.

Background:
I submit the users IP address to an external API to check if the user is connecting from a specific network/ISP.  When that response comes back, I want to make sure that the results for Easy-Search are filtered based on the response.  IE, the external API says the user is connecting from Cape Town, so only show Cape Town specific results.

The search is being done on both Client and Server, using the MongoDB engine, and everything works fine.  But I need a way to either wait for Startup to finish, or to update the search after startup is complete.

Any idea how this can be achieved?

Many thanks
Mike

**Comment by matteodem** [comment]
I'm not entirely sure if I understand your use-case, but it sounds like you want to delay displaying the search. You can put the whole html part into an `if` statement and then use filters to only display search results relevant to that user. The recipes have some examples on how to use filters.

**Comment by sydCPT** [comment]
Apologies for the late reply @matteodem, I managed to get it working by using your above advice.  Thanks for the assistance
