### ISSUE TITLE
$or Query in Selector

### ISSUE THREAD

**Issue by sydCPT** [matteodem/meteor-easy-search#618]
Hi There

Is there a way to write a query using $or on the selector.  When I try the below, I get back the error: MongoError: unknown operator: $or

```
const now = moment().unix()
selector['availability.to'] = {
        $or: [{
          $gte: now
        },{
          $eq: NaN
        }]
      };
```

This query works if I do it directly on Mongo, but not using Easysearch.  Is this a limitation of Easysearch or am I trying to do the query incorrectly?

Thanks

**Comment by ignacy130** [comment]
Why is it closed? Did you find a solution? It would be great if you post it! :)
