### ISSUE TITLE
Is it possible to sort by an added field

### ISSUE THREAD

**Issue by mikkelking** [matteodem/meteor-easy-search#624]
Previously on this ticket https://github.com/matteodem/meteor-easy-search/issues/363

You said that it's not possible to sort when using beforePublish on the server to add a field to the document.

I am using transform on the client, and the sort by my added field isn't working, so I'm wondering what my options are...

1. Is it possible to achieve using what is there already? (I suspect the answer is no)
2. Is it possible to somehow add the feature (I could possibly help and raise a PR with some guidance)
3. Should I create a temporary collection with the added field and then search/sort on that? 

The difficulty is that the sorting will be different for each user, so I can't really update the underlying collection to achieve this

**Comment by matteodem** [comment]
1. You could use the Minimongo search engine, but then you would have to write the publish logic yourself. (Which documents are published to the client)
2. Before submitting the PR we should have a discussion about what the main use case is and how you think it is achievable.
3. You can start de-normalizing your collection or use Elastic Search as describe in the recipes.
