### ISSUE TITLE
Get all documents from elastic search result 

### ISSUE THREAD

**Issue by lucased** [matteodem/meteor-easy-search#627]
Is there a way i can get all the documents from a elastic search results? I want to be able to export all the documents found in the search but currently only the "limit" documents are returned.

**Comment by andsnw** [comment]
anyone manage to achieve this?

**Comment by matteodem** [comment]
As the docs state you can adjust the query / body and other params quite flexibly. https://github.com/matteodem/meteor-easy-search/tree/master/packages/easysearch_elasticsearch
