### ISSUE TITLE
Problem with peerlibrary and Meteor 1.6.1

### ISSUE THREAD

**Issue by ruerob** [matteodem/meteor-easy-search#634]
Hello! :0)

When I update my project to Meteor 1.6.1 and start I get this error:

ReferenceError: ClassyTestCase is not defined
at packages/peerlibrary_computed-field.js:258:4
at packages/peerlibrary_computed-field.js:264:4
at packages/peerlibrary_computed-field.js:408:3
at /home/xx/Entwicklung/blade.report/.meteor/local/build/programs/server/boot.js:411:36
at Array.forEach (<anonymous>)
at /home/xx/Entwicklung/blade.report/.meteor/local/build/programs/server/boot.js:220:19
at /home/xx/Entwicklung/blade.report/.meteor/local/build/programs/server/boot.js:471:5
at Function.run (/home/xx/Entwicklung/blade.report/.meteor/local/build/programs/server/profile.js:510:12)
at /home/xx/Entwicklung/blade.report/.meteor/local/build/programs/server/boot.js:470:11

Can I change something about this, can you, or should I also file an issue on peerlibrary?

**Comment by matteodem** [comment]
If you remove easy-search the errors disappear? Also I don't see any error in the stack message related to easy-search.

**Comment by ruerob** [comment]
Yes, I've tried that, my app starts without easy-search! :0)

Also I've searched which one of my included packages includes peerlibrary:computed-field. And found out that you are using version 0.5.0. I hoped that you could update to 0.8.0 to solve the problem, but I think that wont work...

So I'm a bit clueless right now..

**Comment by ruerob** [comment]
Found something! :0)

https://github.com/peerlibrary/meteor-computed-field/issues/13

**Comment by m-pokrovskii** [comment]
Yes, it doesn't work with 1.6.1

**Comment by matteodem** [comment]
I'll close this issue as it doesn't seem to be connected with Easy-Search but one of it's dependencies
