### ISSUE TITLE
Collation feature of MongoDB

### ISSUE THREAD

**Issue by Tolsee** [matteodem/meteor-easy-search#636]
MongoDB has released the collation feature from 3.4 and meteor also supports it(with rawCollection). But, I cannot find a way to use collation in easy-search(Mongo Engine).

**Comment by matteodem** [comment]
This is related to #630. I'll try to add docs on how to use collation with easy-search.

**Comment by Tolsee** [comment]
@matteodem Ok, but that does not explain how to use those feature in easy-search right? If I am right then that only shows how we can use aggregation in rawCollection. I am confused.

**Comment by matteodem** [comment]
yes. the only other thing that's needed in the code example is the custom selector method.

**Comment by matteodem** [comment]
Actually I have a working example here https://github.com/matteodem/sounds-social/blob/master/code/api/imports/data/search/SoundSearchIndex.js

Not hugely performant as it does 2 queries but I think it's a doable solution for most apps
