### ISSUE TITLE
Does this still work with collection-helpers for composite fields?

### ISSUE THREAD

**Issue by jamauro** [matteodem/meteor-easy-search#641]
I'm following the Usage with collection-helpers example in the guide: http://matteodem.github.io/meteor-easy-search/docs/recipes/

Does anyone have an example of how they've gotten easy-search to work with collection-helpers? I can't seem to return any search results when searching on a composite field created with collection-helpers.

Here's what my setup looks like:

**Relevant versions**
```
Meteor 1.7.0.3

easy:search@2.2.1
easysearch:components@2.2.1
easysearch:core@2.2.0

dburles:collection-helpers@1.1.0
```
**Code in my `/lib/collections folder`**
```
import { Index, MongoDBEngine } from 'meteor/easy:search'

Channels = new Mongo.Collection("channels");

// using collection-helpers
Channels.helpers({
  convertedName() {
    if (this.name) {
      return this.name
    } else {
      var memberIdsWithoutCurrentUser = _.without(this.members, Meteor.userId());
      var userNamesNotIncludingCurrentUser = Meteor.users.find({_id: {$in: memberIdsWithoutCurrentUser}}).map(function(user) {
        return user.username
      });
      return userNamesNotIncludingCurrentUser.join(", ")
    }
  }
});

// want to search by convertedName created with collection-helpers
ChannelsIndex = new Index({
  collection: Channels,
  fields: ['convertedName'],
  engine: new MongoDBEngine({
    transform: (doc) => Channels._transform(doc)
  })
});
```

**Comment by matteodem** [comment]
It should still work. On what environment is the code run? Server and / or client?

**Comment by matteodem** [comment]
okay so now I see it. You can't search for the convertedName (see fields configured as `convertedName`), because easy-search uses a mongo selector which does a search on the mongo documents. 

I'd recommend having a denormalization process before inserting or updating a doc or some other way to have that field available in the actual document.

**Comment by jamauro** [comment]
I see. Can you help me understand how my use of `convertedName` differs from the `fullName` in the example in the docs?

![screen shot 2019-01-23 at 10 22 47 am](https://user-images.githubusercontent.com/1749828/51620955-22243900-1ef9-11e9-8ed0-441b4c33d27a.png)

**Comment by jamauro** [comment]
Got it. Thanks for your help!
