### ISSUE TITLE
Is it possible to get ifSearching directly from the index?

### ISSUE THREAD

**Issue by little-brain** [matteodem/meteor-easy-search#649]
Hi, I'm using Easy Search in a React frontend.

The search cursor is inside withTracker and looks like this:

`const cursor = MyIndex.search(searchTerm);`

Is there any way to get the ifSearching status from the index, so I can use that as a reactive property? I don't have Blaze components.

Thank you.

**Comment by frankapimenta** [comment]
@little-brain are you able to use this (without blaze)  only with react?

**Comment by matteodem** [comment]
You can use the logic as defined in the component package:

https://github.com/matteodem/meteor-easy-search/blob/fe22f092e128358610f6d0b6e40cf632fb5cd411/packages/easysearch_components/lib/if-searching/if-searching.js#L14

The `name` parameter is optional.
