### ISSUE TITLE
populating easy search input and getting search results on page render

### ISSUE THREAD

**Issue by meecect** [matteodem/meteor-easy-search#651]
When entering a new route (with flowrouter), is it possible to prepopulate the easysearch.index component with a search term and execute the results so that easysearch.each will have results to show?

In this case I am getting the search term in a url param (/search/[terms]) so i wan the page to show the search input with [terms] and the initial results below it.

I know I can get the mongoCursor from the index in a helper function...is that the way to do this?  What is the appropriate way of setting the value of the search input, short of just using $().val() ?

thanks,
Cliff

**Comment by matteodem** [comment]
Does following do the trick?

```js
index.getComponentMethods(/** name if needed **/).search('searchvalue')
```

See https://matteodem.github.io/meteor-easy-search/docs/components/ (Using component methods)
