### ISSUE TITLE
Easy-search nested fields as props

### ISSUE THREAD

**Issue by luislymon** [matteodem/meteor-easy-search#653]
I have a collection with nested properties such as: 
users.cast.eyes

How can I search over those using selector facets? 

/*This is not working, because "eyes* is a nested property/
if (options.search.props.eyes) {
  selector.eyes = options.search.props.eyes;
}

/*This is not working, I'm getting a not such property error*/
if (options.search.props.eyes) {
  selector.cast.eyes = options.search.props.eyes;
}

I appreciate any help, thanks

**Comment by matteodem** [comment]
Please provide more context, the docs should be sufficient here
