### ISSUE TITLE
How to search from the start of the searchString?

### ISSUE THREAD

**Issue by jamauro** [matteodem/meteor-easy-search#661]
This is a follow up to this older issue: https://github.com/matteodem/meteor-easy-search/issues/95

I'm using selectorPerField to search from the start of the `searchString`. It gets the job done but is there a better way to do it? 

```js
...
fields: ['symbol', 'name'],
engine: new MongoDBEngine({
    selectorPerField: function (field, searchString) {
      if (field === 'name') {
        return {
          name: { '$regex' : '^' + searchString + '.*', '$options' : 'i' }
        }
      }

      if (field === 'symbol') {
        return {
          symbol: { '$regex' : '^' + searchString + '.*', '$options' : 'i' }
        }
      }

      // use the default otherwise
      return this.defaultConfiguration().selectorPerField(field, searchString)
    }
  })
```

**Comment by matteodem** [comment]
Hi there, if you want to use MongoDB than that seems to be the preferred way to go. It's even better to use ElasticSearch, if performance is a key factor for your app. Here's the library for that: https://github.com/matteodem/meteor-easy-search/tree/master/packages/easysearch_elasticsearch

Cheers!

**Comment by jamauro** [comment]
Thanks! Will check it out.
