### ISSUE TITLE
Searching over joins

### ISSUE THREAD

**Issue by erasaur** [matteodem/meteor-easy-search#70]
It would be awesome to be able to search over joined cursors. For instance, if I search for posts, I want to get the data for each post author as well. Currently, it seems like the solution is to either create a custom search engine or set up pub/subs separately and listen to `searchingDone`, but I would love to see this functionality in the package.

**Comment by matteodem** [comment]
There's no several ways to achieve this as of v2.

* Use one of `transform` or `beforePublish` to change the doc data inside the index configuration, see http://matteodem.github.io/meteor-easy-search/docs/recipes/
* Or you can use the `mongoCursor` thats on the `EasySearch.Cursor` being returned, see http://matteodem.github.io/meteor-easy-search/docs/core/ (Searching)
