### ISSUE TITLE
Handling nested objects with Elastic-Search

### ISSUE THREAD

**Issue by matteodem** [matteodem/meteor-easy-search#79]
* Add mapping property
* Don't stringify doc values anymore
* Automapping functionality by default? (analyse first mongo doc or Collection2 schema and add mapping for it)

**Comment by soniya90** [comment]
How to add nested objects mapping properties in easysearch elastic-search?

**Comment by matteodem** [comment]
It's not possible yet I'm afraid.

**Comment by soniya90** [comment]
Please can you suggest me some other ways to achieve this with proper demo?

**Comment by soniya90** [comment]
Hello Matteo De Micheli,
  
           I am soniya agrawal and i am newby in elasticsearch. I have used easysearch tool for elasticsearch to integrate for full text search. But i m not able to create nested object mappings. I have following structure,

{
	"_id" : "oNqyoq2a92YNK39jG",
	"id" : 1,
	"fk" : {
		"idcategory" : {
			"value" : "1"
		},
		"idsubcategory" : {
			"value" : "1"
		},
		"idsource" : {
			"id_val" : "3",
			"value" : "3"
		}
	},
	"location" : {
		"country" : {
			"value" : "Iran"
		},
		"province" : {
			"value" : "Tehran"
		},
		"city" : {
			"value" : "Bandar Anzali"
		},
		"areaname" : {
			"value" : "District1"
		},
		"areacode" : {
			"value" : "1234567890"
		}
	},
	"ownerdetails" : {
		"name" : {
			"value" : "prop1"
		},
		"owneremailid" : {
			"value" : "sdsd@sdf.dsf"
		},
		"ownerphone" : {
			"value" : "45645646"
		}
	},
	"fields" : {
		"title" : {
			"value" : "prop1"
		},
		"description" : {
			"value" : "prop1"
		},
		"nbrooms" : {
			"value" : "5"
		},
		"surface" : {
			"value" : "5"
		},
		"images" : {
			"value" : null
		},
		"price" : {
			"value" : "4545"
		},
		"type" : {
			"value" : "Apartement"
		}
	},
	"approvalStatus" : "Pending",
	"crawledDate" : ISODate("2015-03-03T10:01:33.415Z"),
	"sourcetype" : "par",
	"classifiedtype" : "Public"
}

where <fields> can have any number of properties. Now how to create an index with appropriate mapping? 
I will be very thankful if you help me in this issue.

Thank you,  
 Regards Soniya Agrawal

 

----------------------------------------

**Comment by matteodem** [comment]
You can use the Node ElasticSearch client for now (see the docs).

**Comment by matteodem** [comment]
As of v2 ElasticSearch is in a separate package called `easysearch:elasticsearch`. You can update mapping through the direct access to the elasticsearch node client, see https://github.com/matteodem/meteor-easy-search/tree/master/packages/easysearch:elasticsearch
