### ISSUE TITLE
Show all results by default option

### ISSUE THREAD

**Issue by isAlmogK** [matteodem/meteor-easy-search#82]
I'm testing out the package it's working great but it doesn't show any items until I search, is it possible to have it return a set of default docs with some type of sorting?

**Comment by ransanjeev** [comment]
I am also facing the same situation. I have a text query and search returns 0 results when text query is empty. I know this is something should be dealt by the custom code, But What about adding a hook/option in createSearchIndex, which could the custom result ?
I am using the javascript api.

**Comment by matteodem** [comment]
Please have a closer look at the docs: http://matteodem.github.io/meteor-easy-search/docs/blaze-components/ (```allDocsOnEmpty``` option)

**Comment by ransanjeev** [comment]
Ya this one gets the first page result, but I am using the  js api with react. Currently I have logic to get the first page when input is of zero length.  Unless I am missing something here,but it will be nice if could be specified during index creation.

**Comment by matteodem** [comment]
Please create a new ticket for your request then.

**Comment by ransanjeev** [comment]
https://github.com/matteodem/meteor-easy-search/issues/200

**Comment by joaobarcia** [comment]
Hi Matt, this would be extremely useful. In our case we have "filter" and "sort by" options associated with easysearch. Do we have to create a new template with the same filter/sort buttons, helpers, events and methods but now associating them with the full collection display?

**Comment by matteodem** [comment]
Please create a new issue with a detailed description of your problem

**Comment by d4nyll** [comment]
For those who are reading this in 2016, `allDocsOnEmpty` is now [`noDocumentsOnEmpty`](http://matteodem.github.io/meteor-easy-search/docs/components/)

    {{> EasySearch.Input index=myIndex noDocumentsOnEmpty=false}}

**Comment by BrianJLennon** [comment]
@d4nyll thank you for that last comment! Man, that documentation is difficult to navigate. THere are so many tiny holes in it. A few tweaks would make all the difference.

**Comment by matteodem** [comment]
Feel free to create an issue regarding the problems you're having!

**Comment by BrianJLennon** [comment]
Hey Matteo, I will create an issue alright but please take on board that I am not criticizing your work - once I figured it out it was awesome. (Maybe I am missing something but) I really felt the documentation could be more up to date and comprehensive. IMO, this package is really important for Meteor going forward.

**Comment by matteodem** [comment]
It's fine, no worries. I actually wanna have the docs as good as possible so it's great that you're giving me feedback 👍
