### ISSUE TITLE
MWE for ElasticSearch

### ISSUE THREAD

**Issue by KrishnaPG** [matteodem/meteor-easy-search#94]
Is there a minimum working example for using this plugin with ElasticSearch? (Laderboard example seems to be specific to mongo-db variants)

I am having hard time trying to make this work with ElasticSearch. Repeatedly getting some 'SearchPhaseExecutionException' no matter what data source I use. May be I got the API flow completely wrong.

For example, after creating `EasySearch.createSearchIndex` it is not clear what to do, or which option/parameter of this plugin API corresponds to which part of Elastic Search query /DB.

It would be really helpful if someone could post a quick working example (preferably using some very simple sample data as below)
````
# Delete the `my_store` index
DELETE /my_store

# Index example docs
POST /my_store/products/_bulk
{"index":{"_id":1}}
{"price":10,"productID":"XHDK-A-1293-#fJ3"}
{"index":{"_id":2}}
{"price":20,"productID":"KDKE-B-9947-#kL5"}
{"index":{"_id":3}}
{"price":30,"productID":"JODL-X-1937-#pV7"}
{"index":{"_id":4}}
{"price":30,"productID":"QQPX-R-3956-#aD8"}
````

**Comment by matteodem** [comment]
Feel free to create a new ticket if there are more questions.
